// Carrot Revolt Labs · Inpainting & Outpainting Lab · stages, steps and live checklists.
// It runs on the ComfyUI Lab interface (../comfyui/app.js) and adds its own nodes and simulator (./nodes.js).
import { defaultGraph, makeNode, makeLink, connect, CHECKPOINTS } from '../comfyui/engine.js';
import { PHOTO_META, coverage, maskBox, findRecipe as find } from './nodes.js';
export const L = (en, ca, es) => ({ en, ca, es });

export const META = { key: 'carrot-revolt-comfy-inpaint:', title: 'Inpainting Lab', label: 'GENERATIVE IMAGE / COMFYUI · 02' };

/* ── Graph helpers ── */
const N = (g, type) => g.nodes.filter(n => n.type === type && n.mode === 0);
const into = (g, id, input) => g.links.find(l => l.to === id && l.input === input);
const from = (g, id, input) => { const l = into(g, id, input); return l ? g.nodes.find(n => n.id === l.from) : null; };
const goal = (text, test, optional = false) => ({ text, test, optional });
const add = (g, ...nodes) => { g.nodes.push(...nodes); return g; };
const wire = (g, list) => { for (const l of list) connect(g, makeLink(...l)); return g; };
const set = (g, id, k, v) => { g.nodes.find(n => n.id === id).widgets[k] = v; return g; };
const move = (g, id, x, y) => { const n = g.nodes.find(n => n.id === id); n.x = x; n.y = y; return g; };
const drop = (g, id) => { g.nodes = g.nodes.filter(n => n.id !== id); g.links = g.links.filter(l => l.from !== id && l.to !== id); return g; };
const hist = c => c.history.filter(h => h.method !== undefined || h.kind);
const INPAINT_CKPT = 'dreamshaper_8Inpainting.safetensors', BASE_CKPT = 'dreamshaper_8.safetensors';

/* ── Ready-made masks (strokes in 0–1 coordinates, like the Mask Editor saves them) ── */
const rows = (x0, x1, ys, r) => ys.map(y => ({ p: [[x0, y], [x1, y]], r }));
const MASKS = {
  cat: rows(.35, .68, [.49, .58, .67, .76, .84], .06),
  person: [{ p: [[.6, .5], [.6, .89]], r: .055 }, { p: [[.65, .5], [.65, .89]], r: .055 }],
  lighthouse: [{ p: [[.17, .47], [.17, .68]], r: .045 }],
};
const BOXES = { ...Object.fromEntries(Object.entries(PHOTO_META).map(([k, m]) => [k, m.box])), lighthouse: [.12, .44, .22, .71] };
const imgNode = g => N(g, 'LoadImage')[0];
const maskOf = n => n ? { kind: 'mask', strokes: n.widgets.mask || [], invert: !!n.widgets.mask_invert, w: 512, h: 512 } : null;
const coverOf = (g, box) => { const n = imgNode(g); return n ? coverage(maskOf(n), box) : { cover: 0, area: 0 }; };

/* ── Starters and solutions ── */
const G = {
  maskPreview: (mask = null) => {
    const g = { nodes: [makeNode('LoadImage', 40, 160, { image: 'garden_cat.png', ...(mask ? { mask } : {}) }, 'img'), makeNode('MaskToImage', 440, 250, {}, 'm2i'), makeNode('PreviewImage', 760, 160, {}, 'preview')], links: [], groups: [] };
    return wire(g, [['img', 1, 'm2i', 'mask'], ['m2i', 0, 'preview', 'images']]);
  },
  maskGrow: () => { const g = G.maskPreview(MASKS.cat); add(g, makeNode('GrowMaskWithBlur', 440, 160, { expand: 12, blur_radius: 8 }, 'grow')); move(g, 'm2i', 800, 250); move(g, 'preview', 1110, 160); return wire(g, [['img', 1, 'grow', 'mask'], ['grow', 0, 'm2i', 'mask']]); },
  // Text-to-image graph turned into an inpainting graph: the empty latent goes, a photo with a mask comes in.
  inpaint: ({ method = 'vaeinpaint', image = 'garden_cat.png', mask = MASKS.cat, text = 'a blue robot in a landscape, detailed', neg = 'text, watermark', denoise = 1, ckpt = BASE_CKPT } = {}) => {
    const g = drop(defaultGraph(), 'latent');
    set(set(set(set(g, 'pos', 'text', text), 'neg', 'text', neg), 'sampler', 'denoise', denoise), 'sampler', 'control_after_generate', 'fixed');
    set(g, 'ckpt', 'ckpt_name', ckpt); move(g, 'ckpt', 26, 330);
    add(g, makeNode('LoadImage', 26, 560, { image, ...(mask ? { mask } : {}) }, 'img'));
    if (method === 'vaeinpaint') { add(g, makeNode('VAEEncodeForInpaint', 450, 620, {}, 'enc')); wire(g, [['img', 0, 'enc', 'pixels'], ['ckpt', 2, 'enc', 'vae'], ['img', 1, 'enc', 'mask'], ['enc', 0, 'sampler', 'latent_image']]); }
    if (method === 'noisemask') { add(g, makeNode('VAEEncode', 450, 600, {}, 'enc'), makeNode('SetLatentNoiseMask', 450, 720, {}, 'nm')); wire(g, [['img', 0, 'enc', 'pixels'], ['ckpt', 2, 'enc', 'vae'], ['enc', 0, 'nm', 'samples'], ['img', 1, 'nm', 'mask'], ['nm', 0, 'sampler', 'latent_image']]); }
    if (method === 'imc') {
      add(g, makeNode('InpaintModelConditioning', 450, 600, {}, 'imc')); move(g, 'sampler', 900, 186); move(g, 'decode', 1250, 188); move(g, 'save', 1490, 189);
      wire(g, [['pos', 0, 'imc', 'positive'], ['neg', 0, 'imc', 'negative'], ['ckpt', 2, 'imc', 'vae'], ['img', 0, 'imc', 'pixels'], ['img', 1, 'imc', 'mask'], ['imc', 0, 'sampler', 'positive'], ['imc', 1, 'sampler', 'negative'], ['imc', 2, 'sampler', 'latent_image']]);
    }
    return g;
  },
  softMask: (diff = false) => {
    const g = G.inpaint({ method: 'imc', ckpt: INPAINT_CKPT });
    add(g, makeNode('GrowMaskWithBlur', 450, 820, { expand: 8, blur_radius: 16 }, 'grow')); wire(g, [['img', 1, 'grow', 'mask'], ['grow', 0, 'imc', 'mask']]);
    if (diff) { add(g, makeNode('DifferentialDiffusion', 450, 40, {}, 'dd')); wire(g, [['ckpt', 0, 'dd', 'model'], ['dd', 0, 'sampler', 'model']]); }
    return g;
  },
  composite: () => {
    const g = G.inpaint({ method: 'imc', ckpt: INPAINT_CKPT });
    add(g, makeNode('ImageCompositeMasked', 1490, 360, {}, 'comp')); move(g, 'save', 1840, 189);
    return wire(g, [['img', 0, 'comp', 'destination'], ['decode', 0, 'comp', 'source'], ['img', 1, 'comp', 'mask'], ['comp', 0, 'save', 'images']]);
  },
  small: () => G.inpaint({ method: 'imc', image: 'beach_person.png', mask: MASKS.lighthouse, text: 'a red lighthouse, beach, detailed', ckpt: INPAINT_CKPT }),
  stitch: () => {
    const g = G.small(); add(g, makeNode('InpaintCrop', 450, 820, {}, 'crop'), makeNode('InpaintStitch', 1250, 330, {}, 'stitch'));
    return wire(g, [['img', 0, 'crop', 'image'], ['img', 1, 'crop', 'mask'], ['crop', 1, 'imc', 'pixels'], ['crop', 2, 'imc', 'mask'], ['crop', 0, 'stitch', 'stitcher'], ['decode', 0, 'stitch', 'inpainted_image'], ['stitch', 0, 'save', 'images']]);
  },
  outpaint: ({ right = 0, feathering = 40, ckpt = INPAINT_CKPT, text = 'snow, winter landscape, detailed' } = {}) => {
    const g = G.inpaint({ method: 'vaeinpaint', image: 'snow_cabin.png', mask: null, text, ckpt });
    add(g, makeNode('ImagePadForOutpaint', 26, 950, { right, feathering }, 'pad'));
    return wire(g, [['img', 0, 'pad', 'image'], ['pad', 0, 'enc', 'pixels'], ['pad', 1, 'enc', 'mask']]);
  },
  cleanStart: () => G.inpaint({ method: 'imc', image: 'beach_person.png', mask: null, text: 'beach, sea, sunset, detailed', neg: 'person, text, watermark', ckpt: INPAINT_CKPT }),
  clean: () => { const g = G.cleanStart(); set(g, 'img', 'mask', MASKS.person); add(g, makeNode('GrowMask', 450, 820, { expand: 10 }, 'grow')); return wire(g, [['img', 1, 'grow', 'mask'], ['grow', 0, 'imc', 'mask']]); },
  cleanFinal: () => { const g = G.clean(); add(g, makeNode('GrowMaskWithBlur', 900, 820, { expand: 4, blur_radius: 6 }, 'soft'), makeNode('ImageCompositeMasked', 1490, 360, {}, 'comp')); move(g, 'save', 1840, 189); return wire(g, [['grow', 0, 'soft', 'mask'], ['img', 0, 'comp', 'destination'], ['decode', 0, 'comp', 'source'], ['soft', 0, 'comp', 'mask'], ['comp', 0, 'save', 'images']]); },
};

/* ── What every run leaves in the history (read by the checklists) ── */
function chain(m) {
  let grow = 0, blur = 0, pad = null, v = m, full = m;
  for (let guard = 0; v && guard < 20; guard++) {
    if (v.kind === 'grow') { grow += v.px || 0; blur = Math.max(blur, v.blur || 0); v = v.of; }
    else if (v.kind === 'invert') v = v.of;
    else if (v.kind === 'cropmask') { full = v.st.mask; v = v.st.mask; }
    else { if (v.kind === 'padmask') pad = v; break; }
  }
  return { grow, blur, pad, full };
}
const photoName = v => { while (v && !v.name) v = v.of || v.st?.image || v.dest; return v?.name || null; };
export function historyExtra(recipe) {
  const inp = recipe.latent?.inpaint; if (!inp) return { method: null };
  const c = chain(inp.mask), photo = photoName(recipe.latent.source), box = BOXES[photo];
  const negs = new Set(recipe.neg.prompt.subjects.map(s => s.value)), subject = recipe.pos.prompt.subjects.map(s => s.value).find(s => !negs.has(s)) || null;
  const cov = box ? coverage(c.full, box) : { cover: 0, area: 0 }, light = photo === 'beach_person.png' ? coverage(c.full, BOXES.lighthouse).cover : 0;
  const mb = c.pad ? null : maskBox(c.full);
  return { method: inp.method, inpaintModel: !!CHECKPOINTS[recipe.model.ckpt]?.inpaint, diffdiff: recipe.model.diffdiff || 0, noiseMask: inp.noiseMask ?? null, grow: c.grow + (inp.grow || 0), nodeGrow: c.grow, blur: c.blur, pad: c.pad ? c.pad.pad.l + c.pad.pad.t + c.pad.pad.r + c.pad.pad.b : 0, feather: c.pad?.feather ?? null, photo, subject, cover: cov.cover, area: cov.area, lightCover: light, maskSize: mb ? Math.max(mb[2] - mb[0], mb[3] - mb[1]) : 1, cropped: recipe.latent.source?.kind === 'crop', composite: false, stitch: false };
}
export function outputExtra(img) {
  if (img.kind === 'composite') { const c = img.mask ? chain(img.mask) : null; return { composite: true, compMasked: !!img.mask, compGrow: c?.grow ?? 0, compBlur: c?.blur ?? 0, compDest: img.dest?.kind === 'photo' }; }
  if (img.kind === 'stitch') return { stitch: true };
  return {};
}
export const findRecipe = find;

/* ── Shared tests ── */
const ran = (c, f) => hist(c).some(f);
const noSubject = h => !h.subject;

export const UI = {
  headline: L('Paint over it, <span>keep the rest.</span>', 'Pinta-hi a sobre, <span>conserva la resta.</span>', 'Pinta encima, <span>conserva el resto.</span>'),
  lead: L('Change one part of a picture and leave the rest untouched. Paint masks, compare the four inpainting routes of ComfyUI (and when each one is the right one), sew the result back without seams, work on small details at full resolution, extend a picture beyond its edges and make clean plates. Same interface and shortcuts as ComfyUI.', 'Canvia una part d’una imatge i deixa la resta intacta. Pinta màscares, compara les quatre vies d’inpainting de ComfyUI (i quan toca cadascuna), cus el resultat sense costures, treballa detalls petits a resolució completa, allarga una imatge més enllà de les vores i fes cleanplates. La mateixa interfície i dreceres que ComfyUI.', 'Cambia una parte de una imagen y deja el resto intacto. Pinta máscaras, compara las cuatro vías de inpainting de ComfyUI (y cuándo toca cada una), cose el resultado sin costuras, trabaja detalles pequeños a resolución completa, alarga una imagen más allá de sus bordes y haz cleanplates. La misma interfaz y atajos que ComfyUI.'),
};

const ROUTES = (h, rows, foot) => `<table class="c-cmp"><tr><th></th><th>${h[0]}</th><th>${h[1]}</th></tr>${rows.map(r => `<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</table><p>${foot}</p>`;
UI.loraVsCn = L('Which inpainting route?', 'Quina via d’inpainting?', '¿Qué vía de inpainting?');
UI.loraVsCnBody = L(
  ROUTES(['Use', 'Denoise'], [['<b>VAE Encode (for Inpainting)</b>', 'something new, with an inpainting model', '1'], ['<b>Set Latent Noise Mask</b>', 'recolour, retouch, keep the shape', '0.4–0.75'], ['<b>InpaintModelConditioning</b>', 'the default: best with an inpainting model', '1 (or less)'], ['<b>+ Differential Diffusion</b>', 'soft masks, invisible joins', 'any']], 'Always finish with ImageCompositeMasked (or Inpaint Stitch) over the original.'),
  ROUTES(['Per a', 'Denoise'], [['<b>VAE Encode (for Inpainting)</b>', 'una cosa nova, amb un model d’inpainting', '1'], ['<b>Set Latent Noise Mask</b>', 'canviar el color, retocar, mantenir la forma', '0.4–0.75'], ['<b>InpaintModelConditioning</b>', 'la via per defecte: millor amb un model d’inpainting', '1 (o menys)'], ['<b>+ Differential Diffusion</b>', 'màscares suaus, unions invisibles', 'qualsevol']], 'Acaba sempre amb ImageCompositeMasked (o Inpaint Stitch) sobre l’original.'),
  ROUTES(['Para', 'Denoise'], [['<b>VAE Encode (for Inpainting)</b>', 'algo nuevo, con un modelo de inpainting', '1'], ['<b>Set Latent Noise Mask</b>', 'cambiar el color, retocar, mantener la forma', '0.4–0.75'], ['<b>InpaintModelConditioning</b>', 'la vía por defecto: mejor con un modelo de inpainting', '1 (o menos)'], ['<b>+ Differential Diffusion</b>', 'máscaras suaves, uniones invisibles', 'cualquiera']], 'Acaba siempre con ImageCompositeMasked (o Inpaint Stitch) sobre el original.'));
UI.type_STITCHER = L('where a crop came from, to paste it back', 'd’on ve un retall, per tornar-lo a enganxar', 'de dónde viene un recorte, para volver a pegarlo');

export const DOCS = {
  GrowMask: { short: L('Grows (or shrinks) a mask by some pixels.', 'Fa créixer (o encongir) una màscara uns píxels.', 'Hace crecer (o encoger) una máscara unos píxeles.'), long: L('A mask painted tight to an object leaves its outline behind. Growing it a few pixels lets the new pixels cover the old edge. Negative values shrink it.', 'Una màscara pintada just a la vora d’un objecte en deixa el contorn. Fer-la créixer uns píxels permet que els píxels nous tapin la vora vella. Els valors negatius l’encongeixen.', 'Una máscara pintada justo al borde de un objeto deja su contorno. Hacerla crecer unos píxeles permite que los píxeles nuevos tapen el borde viejo. Los valores negativos la encogen.'), widgets: { expand: L('pixels to grow (negative = shrink)', 'píxels per créixer (negatiu = encongir)', 'píxeles para crecer (negativo = encoger)'), tapered_corners: L('round the corners while growing', 'arrodoneix les cantonades en créixer', 'redondea las esquinas al crecer') } },
  GrowMaskWithBlur: { short: L('Grows and blurs a mask in one node.', 'Fa créixer i difumina una màscara en un sol node.', 'Hace crecer y difumina una máscara en un solo nodo.'), long: L('From a popular custom node pack (KJNodes). The blur gives the mask a soft border: values between 0 and 1 that mean “change this a little”. Only useful if something reads them: Differential Diffusion or a masked composite.', 'D’un paquet de custom nodes molt fet servir (KJNodes). El blur dona a la màscara una vora suau: valors entre 0 i 1 que volen dir “canvia això una mica”. Només serveix si algú els llegeix: Differential Diffusion o una composició amb màscara.', 'De un paquete de custom nodes muy usado (KJNodes). El blur da a la máscara un borde suave: valores entre 0 y 1 que significan “cambia esto un poco”. Solo sirve si alguien los lee: Differential Diffusion o una composición con máscara.'), widgets: { expand: L('pixels to grow', 'píxels per créixer', 'píxeles para crecer'), blur_radius: L('softness of the border', 'suavitat de la vora', 'suavidad del borde') } },
  InvertMask: { short: L('White becomes black and black becomes white.', 'El blanc passa a negre i el negre a blanc.', 'El blanco pasa a negro y el negro a blanco.'), long: L('Inverts the mask: protect the object and change everything else (a new background), or the other way round.', 'Inverteix la màscara: protegeix l’objecte i canvia tota la resta (un fons nou), o al revés.', 'Invierte la máscara: protege el objeto y cambia todo lo demás (un fondo nuevo), o al revés.') },
  MaskToImage: { short: L('Shows a mask as a black and white image.', 'Mostra una màscara com una imatge en blanc i negre.', 'Muestra una máscara como una imagen en blanco y negro.'), long: L('A MASK cannot go into Preview Image. Convert it to IMAGE to see exactly what the sampler will receive: white = change, black = keep.', 'Una MASK no pot anar a Preview Image. Converteix-la en IMAGE per veure exactament què rebrà el sampler: blanc = canviar, negre = conservar.', 'Una MASK no puede ir a Preview Image. Conviértela en IMAGE para ver exactamente qué recibirá el sampler: blanco = cambiar, negro = conservar.') },
  VAEEncodeForInpaint: { short: L('Encodes the image and erases the masked area.', 'Codifica la imatge i esborra la zona emmascarada.', 'Codifica la imagen y borra la zona enmascarada.'), long: L('The masked area is filled with neutral grey before encoding, so the sampler has nothing to start from there: use denoise 1, or you get grey mush. Made for inpainting checkpoints; with a normal model the border shows.', 'La zona emmascarada s’omple de gris neutre abans de codificar, i el sampler no hi té res de què partir: fes servir denoise 1, o sortirà una pasta grisa. Pensat per a checkpoints d’inpainting; amb un model normal la vora es nota.', 'La zona enmascarada se rellena de gris neutro antes de codificar, y el sampler no tiene nada de qué partir: usa denoise 1, o saldrá una pasta gris. Pensado para checkpoints de inpainting; con un modelo normal el borde se nota.'), widgets: { grow_mask_by: L('pixels added around the mask to hide the seam', 'píxels afegits al voltant de la màscara per amagar la costura', 'píxeles añadidos alrededor de la máscara para esconder la costura') } },
  SetLatentNoiseMask: { short: L('Limits the sampling to the masked area.', 'Limita el mostreig a la zona emmascarada.', 'Limita el muestreo a la zona enmascarada.'), long: L('Img2img inside a mask: the latent keeps the original pixels and the sampler only adds noise where the mask is white. With a low denoise the shape survives: perfect to recolour or retouch.', 'Img2img dins d’una màscara: el latent conserva els píxels originals i el sampler només afegeix soroll on la màscara és blanca. Amb un denoise baix la forma sobreviu: perfecte per canviar el color o retocar.', 'Img2img dentro de una máscara: el latente conserva los píxeles originales y el sampler solo añade ruido donde la máscara es blanca. Con un denoise bajo la forma sobrevive: perfecto para cambiar el color o retocar.') },
  InpaintModelConditioning: { short: L('Gives the model the image and the mask.', 'Dona al model la imatge i la màscara.', 'Da al modelo la imagen y la máscara.'), long: L('Adds the original pixels and the mask to the conditioning and returns the latent too. The model sees what surrounds the hole, so colours and light match. It is the best route with an inpainting checkpoint, and it also works with normal models.', 'Afegeix els píxels originals i la màscara al conditioning i també torna el latent. El model veu què envolta el forat, i els colors i la llum lliguen. És la millor via amb un checkpoint d’inpainting, i també funciona amb models normals.', 'Añade los píxeles originales y la máscara al conditioning y también devuelve el latente. El modelo ve qué rodea el agujero, y los colores y la luz encajan. Es la mejor vía con un checkpoint de inpainting, y también funciona con modelos normales.'), widgets: { noise_mask: L('true: only the masked area is sampled; false: the whole picture is redrawn', 'true: només es mostreja la zona emmascarada; false: es redibuixa tota la imatge', 'true: solo se muestrea la zona enmascarada; false: se redibuja toda la imagen') } },
  DifferentialDiffusion: { short: L('Reads a soft mask as “how much to change”.', 'Llegeix una màscara suau com a “quant cal canviar”.', 'Lee una máscara suave como “cuánto cambiar”.'), long: L('Without it, the sampler treats every mask as on or off, at latent resolution (8 × 8 pixel blocks). With it, grey values change the picture partially, so a blurred mask gives an invisible transition. It patches the MODEL: put it between the loader and the KSampler.', 'Sense ell, el sampler tracta qualsevol màscara com a sí o no, a resolució latent (blocs de 8 × 8 píxels). Amb ell, els grisos canvien la imatge parcialment, i una màscara difuminada dona una transició invisible. Modifica el MODEL: posa’l entre el loader i el KSampler.', 'Sin él, el sampler trata cualquier máscara como sí o no, a resolución latente (bloques de 8 × 8 píxeles). Con él, los grises cambian la imagen parcialmente, y una máscara difuminada da una transición invisible. Modifica el MODEL: ponlo entre el loader y el KSampler.'), widgets: { strength: L('how much of the soft mask is respected', 'quant es respecta la màscara suau', 'cuánto se respeta la máscara suave') } },
  ImagePadForOutpaint: { short: L('Adds empty space around an image, with its mask.', 'Afegeix espai buit al voltant d’una imatge, amb la seva màscara.', 'Añade espacio vacío alrededor de una imagen, con su máscara.'), long: L('Makes the canvas bigger and returns the mask of the new area. Feathering makes the mask fade into the original a few pixels, so the join is soft.', 'Fa el llenç més gran i torna la màscara de la zona nova. El feathering fa que la màscara s’endinsi uns píxels a l’original, i la unió queda suau.', 'Hace el lienzo más grande y devuelve la máscara de la zona nueva. El feathering hace que la máscara entre unos píxeles en el original, y la unión queda suave.'), widgets: { left: L('pixels added on the left', 'píxels afegits a l’esquerra', 'píxeles añadidos a la izquierda'), right: L('pixels added on the right', 'píxels afegits a la dreta', 'píxeles añadidos a la derecha'), feathering: L('soft border inside the original', 'vora suau dins l’original', 'borde suave dentro del original') } },
  ImageCompositeMasked: { short: L('Pastes one image over another through a mask.', 'Enganxa una imatge sobre una altra a través d’una màscara.', 'Pega una imagen sobre otra a través de una máscara.'), long: L('The finishing step of every pro inpaint: destination = the original, source = the inpainted result, mask = where to paste. Every pixel outside the mask is the original again, without the small loss of going through the VAE.', 'El pas final de tot inpaint professional: destination = l’original, source = el resultat, mask = on s’enganxa. Cada píxel fora de la màscara torna a ser l’original, sense la petita pèrdua de passar pel VAE.', 'El paso final de todo inpaint profesional: destination = el original, source = el resultado, mask = dónde se pega. Cada píxel fuera de la máscara vuelve a ser el original, sin la pequeña pérdida de pasar por el VAE.'), widgets: { x: L('horizontal offset of the source', 'desplaçament horitzontal de la font', 'desplazamiento horizontal de la fuente'), y: L('vertical offset of the source', 'desplaçament vertical de la font', 'desplazamiento vertical de la fuente'), resize_source: L('scale the source to the destination', 'escala la font a la destinació', 'escala la fuente al destino') } },
  InpaintCrop: { short: L('Crops around the mask and scales it up.', 'Retalla al voltant de la màscara i l’amplia.', 'Recorta alrededor de la máscara y la amplía.'), long: L('Custom node (Inpaint Crop and Stitch). A small mask on a big picture has very few latent pixels. This node crops the masked area with some context and scales it to the size the model likes, so a small detail is painted at full resolution.', 'Custom node (Inpaint Crop and Stitch). Una màscara petita en una imatge gran té molt pocs píxels latents. Aquest node retalla la zona amb una mica de context i l’escala a la mida que agrada al model, i un detall petit es pinta a resolució completa.', 'Custom node (Inpaint Crop and Stitch). Una máscara pequeña en una imagen grande tiene muy pocos píxeles latentes. Este nodo recorta la zona con algo de contexto y la escala al tamaño que le gusta al modelo, y un detalle pequeño se pinta a resolución completa.'), widgets: { context_expand_factor: L('how much context around the mask (1.5 = 50% more)', 'quant context al voltant de la màscara (1.5 = 50% més)', 'cuánto contexto alrededor de la máscara (1.5 = 50% más)'), output_target_size: L('size of the crop sent to the sampler', 'mida del retall que va al sampler', 'tamaño del recorte que va al sampler') } },
  InpaintStitch: { short: L('Puts the crop back in the original picture.', 'Torna a posar el retall a la imatge original.', 'Vuelve a poner el recorte en la imagen original.'), long: L('Scales the inpainted crop back down and pastes it in place through the mask. The STITCHER wire carries where the crop came from.', 'Torna a escalar el retall i l’enganxa al seu lloc a través de la màscara. El cable STITCHER porta d’on venia el retall.', 'Vuelve a escalar el recorte y lo pega en su sitio a través de la máscara. El cable STITCHER lleva de dónde venía el recorte.') },
};

export const STAGES = [
  {
    id: 'masks', name: L('Masks', 'Màscares', 'Máscaras'), sub: L('Paint · preview · grow', 'Pinta · previsualitza · fes créixer', 'Pinta · previsualiza · haz crecer'),
    steps: [
      {
        title: L('Paint your first mask', 'Pinta la primera màscara', 'Pinta tu primera máscara'),
        task: L('Open the Mask Editor on the photo of the cat, paint over the whole cat and preview the mask.', 'Obre el Mask Editor a la foto del gat, pinta tot el gat i previsualitza la màscara.', 'Abre el Mask Editor en la foto del gato, pinta todo el gato y previsualiza la máscara.'),
        concept: L('<b>Inpainting</b> = redraw only one part of a picture. The part is chosen with a <b>mask</b>: a black and white image the size of the photo, where white means “change this” and black “keep this”. Load Image has two outputs for this reason: IMAGE (the pixels) and MASK (green). A good mask covers the whole object, with a small margin, and nothing else.', '<b>Inpainting</b> = redibuixar només una part d’una imatge. La part es tria amb una <b>màscara</b>: una imatge en blanc i negre de la mida de la foto, on blanc vol dir “canvia això” i negre “conserva això”. Per això Load Image té dues sortides: IMAGE (els píxels) i MASK (verda). Una bona màscara cobreix tot l’objecte, amb un petit marge, i res més.', '<b>Inpainting</b> = redibujar solo una parte de una imagen. La parte se elige con una <b>máscara</b>: una imagen en blanco y negro del tamaño de la foto, donde blanco significa “cambia esto” y negro “conserva esto”. Por eso Load Image tiene dos salidas: IMAGE (los píxeles) y MASK (verde). Una buena máscara cubre todo el objeto, con un pequeño margen, y nada más.'),
        how: [L('Click the photo in Load Image (or right-click the node › <b>Open in MaskEditor</b>).', 'Clica la foto a Load Image (o clic dret al node › <b>Open in MaskEditor</b>).', 'Haz clic en la foto de Load Image (o clic derecho en el nodo › <b>Open in MaskEditor</b>).'), L('Paint over the cat with a thick brush, then <b>Save</b>.', 'Pinta el gat amb un pinzell gruixut i després <b>Save</b>.', 'Pinta el gato con un pincel grueso y luego <b>Save</b>.'), L('<kbd>Ctrl Enter</kbd>: Convert Mask to Image shows the mask in Preview Image.', '<kbd>Ctrl Enter</kbd>: Convert Mask to Image mostra la màscara a Preview Image.', '<kbd>Ctrl Enter</kbd>: Convert Mask to Image muestra la máscara en Preview Image.')],
        note: L('In ComfyUI the painted mask is saved inside the image file (as transparency), in the input/clipspace folder.', 'A ComfyUI la màscara pintada es desa dins el fitxer de la imatge (com a transparència), a la carpeta input/clipspace.', 'En ComfyUI la máscara pintada se guarda dentro del archivo de la imagen (como transparencia), en la carpeta input/clipspace.'),
        starter: () => G.maskPreview(), solution: () => G.maskPreview(MASKS.cat),
        goals: [goal(L('Painted a mask in the Mask Editor', 'Has pintat una màscara al Mask Editor', 'Has pintado una máscara en el Mask Editor'), (g, c) => c.flags.maskPainted || (imgNode(g)?.widgets.mask || []).length > 0), goal(L('The mask covers most of the cat', 'La màscara cobreix gairebé tot el gat', 'La máscara cubre casi todo el gato'), g => coverOf(g, BOXES['garden_cat.png']).cover >= .7), goal(L('…and not half of the picture', '…i no mitja imatge', '…y no media imagen'), g => { const c = coverOf(g, BOXES['garden_cat.png']); return c.cover >= .7 && c.area < .32; }), goal(L('Previewed the mask', 'Has previsualitzat la màscara', 'Has previsualizado la máscara'), (g, c) => c.history.some(h => h.kind === 'maskimg'))],
      },
      {
        title: L('Grow it and soften it', 'Fes-la créixer i suavitza-la', 'Hazla crecer y suavízala'),
        task: L('Put a Grow Mask With Blur between the mask and the preview: expand at least 6 px and blur at least 4.', 'Posa un Grow Mask With Blur entre la màscara i la previsualització: expand com a mínim 6 px i blur com a mínim 4.', 'Pon un Grow Mask With Blur entre la máscara y la previsualización: expand al menos 6 px y blur al menos 4.'),
        concept: L('A mask that follows the outline exactly leaves a halo: the edge pixels of the old object stay. <b>Grow</b> pushes the border out a few pixels so the new pixels cover them. <b>Blur</b> turns the hard border into a gradient (grey = change a little), the base of an invisible join. Almost every inpainting workflow has a grow step.', 'Una màscara que segueix exactament el contorn deixa un halo: els píxels de la vora de l’objecte vell es queden. <b>Grow</b> empeny la vora uns píxels enfora perquè els píxels nous els tapin. <b>Blur</b> converteix la vora dura en un degradat (gris = canvia una mica), la base d’una unió invisible. Gairebé tots els workflows d’inpainting tenen un pas de grow.', 'Una máscara que sigue exactamente el contorno deja un halo: los píxeles del borde del objeto viejo se quedan. <b>Grow</b> empuja el borde unos píxeles hacia fuera para que los píxeles nuevos los tapen. <b>Blur</b> convierte el borde duro en un degradado (gris = cambia un poco), la base de una unión invisible. Casi todos los workflows de inpainting tienen un paso de grow.'),
        how: [L('Drag a wire from the green <b>MASK</b> of Load Image, drop it on the canvas and search <b>grow mask with blur</b>.', 'Arrossega un cable des de la <b>MASK</b> verda de Load Image, deixa’l anar al llenç i cerca <b>grow mask with blur</b>.', 'Arrastra un cable desde la <b>MASK</b> verde de Load Image, suéltalo en el lienzo y busca <b>grow mask with blur</b>.'), L('Connect its <b>mask</b> output to Convert Mask to Image (it replaces the old wire).', 'Connecta la sortida <b>mask</b> a Convert Mask to Image (substitueix el cable vell).', 'Conecta su salida <b>mask</b> a Convert Mask to Image (sustituye el cable viejo).'), L('Set <b>expand</b> 12 and <b>blur_radius</b> 8 and run.', 'Posa <b>expand</b> 12 i <b>blur_radius</b> 8 i executa.', 'Pon <b>expand</b> 12 y <b>blur_radius</b> 8 y ejecuta.')],
        note: L('Grow Mask With Blur comes from a custom node pack (the badge on its title says which). The core alternative is Grow Mask + a blur node.', 'Grow Mask With Blur ve d’un paquet de custom nodes (l’etiqueta del títol diu quin). L’alternativa del nucli és Grow Mask + un node de blur.', 'Grow Mask With Blur viene de un paquete de custom nodes (la etiqueta del título dice cuál). La alternativa del núcleo es Grow Mask + un nodo de blur.'),
        starter: () => G.maskPreview(MASKS.cat), solution: G.maskGrow,
        goals: [goal(L('Grow Mask With Blur gets the mask', 'Grow Mask With Blur rep la màscara', 'Grow Mask With Blur recibe la máscara'), g => N(g, 'GrowMaskWithBlur').some(n => from(g, n.id, 'mask')?.type === 'LoadImage')), goal(L('expand ≥ 6', 'expand ≥ 6', 'expand ≥ 6'), g => N(g, 'GrowMaskWithBlur').some(n => n.widgets.expand >= 6)), goal(L('blur_radius ≥ 4', 'blur_radius ≥ 4', 'blur_radius ≥ 4'), g => N(g, 'GrowMaskWithBlur').some(n => n.widgets.blur_radius >= 4)), goal(L('Previewed the grown mask', 'Has previsualitzat la màscara crescuda', 'Has previsualizado la máscara crecida'), (g, c) => c.history.some(h => h.kind === 'maskimg' && h.graph?.nodes.some(n => n.type === 'GrowMaskWithBlur' && n.mode === 0 && n.widgets.expand >= 6)))],
      },
    ],
  },
  {
    id: 'methods', name: L('Four routes', 'Quatre vies', 'Cuatro vías'), sub: L('Which inpaint, when', 'Quin inpaint, quan', 'Qué inpaint, cuándo'),
    steps: [
      {
        title: L('VAE Encode (for Inpainting)', 'VAE Encode (for Inpainting)', 'VAE Encode (for Inpainting)'),
        task: L('Replace the cat with a robot at denoise 1. Then lower denoise to 0.6 and run again.', 'Substitueix el gat per un robot amb denoise 1. Després baixa el denoise a 0.6 i torna a executar.', 'Sustituye el gato por un robot con denoise 1. Luego baja el denoise a 0.6 y vuelve a ejecutar.'),
        concept: L('The first route. <b>VAE Encode (for Inpainting)</b> fills the masked area with grey and encodes it: there is nothing left of the cat for the sampler to start from. That is good to put something completely new, but it needs <b>denoise 1</b>: with less, the grey stays. And with a normal checkpoint the border of the mask shows, because the model does not know that it has to blend with the surroundings.', 'La primera via. <b>VAE Encode (for Inpainting)</b> omple la zona emmascarada de gris i la codifica: no queda res del gat per on començar. Va bé per posar-hi una cosa totalment nova, però necessita <b>denoise 1</b>: amb menys, el gris es queda. I amb un checkpoint normal la vora de la màscara es nota, perquè el model no sap que s’ha de fondre amb el que l’envolta.', 'La primera vía. <b>VAE Encode (for Inpainting)</b> rellena la zona enmascarada de gris y la codifica: no queda nada del gato por donde empezar. Va bien para poner algo totalmente nuevo, pero necesita <b>denoise 1</b>: con menos, el gris se queda. Y con un checkpoint normal el borde de la máscara se nota, porque el modelo no sabe que tiene que fundirse con lo que lo rodea.'),
        how: [L('The mask is already painted. Run with <kbd>Ctrl Enter</kbd>.', 'La màscara ja està pintada. Executa amb <kbd>Ctrl Enter</kbd>.', 'La máscara ya está pintada. Ejecuta con <kbd>Ctrl Enter</kbd>.'), L('Look at the border of the robot area: can you see the seam?', 'Mira la vora de la zona del robot: veus la costura?', 'Mira el borde de la zona del robot: ¿ves la costura?'), L('Set the KSampler <b>denoise</b> to 0.6 and run again: grey mush.', 'Posa el <b>denoise</b> del KSampler a 0.6 i torna a executar: pasta grisa.', 'Pon el <b>denoise</b> del KSampler a 0.6 y vuelve a ejecutar: pasta gris.')],
        note: L('grow_mask_by (6 by default) grows the mask inside this node, to hide part of the seam.', 'grow_mask_by (6 per defecte) fa créixer la màscara dins el mateix node, per amagar part de la costura.', 'grow_mask_by (6 por defecto) hace crecer la máscara dentro del propio nodo, para esconder parte de la costura.'),
        starter: () => G.inpaint(), solution: () => set(G.inpaint(), 'sampler', 'denoise', .6),
        goals: [goal(L('A robot where the cat was (denoise 1)', 'Un robot on hi havia el gat (denoise 1)', 'Un robot donde estaba el gato (denoise 1)'), (g, c) => ran(c, h => h.method === 'vaeinpaint' && h.subject === 'robot' && h.denoise >= .95 && h.cover >= .6)), goal(L('Ran it again with denoise ≤ 0.7', 'L’has tornat a executar amb denoise ≤ 0.7', 'Lo has vuelto a ejecutar con denoise ≤ 0.7'), (g, c) => ran(c, h => h.method === 'vaeinpaint' && h.denoise <= .7))],
      },
      {
        title: L('Set Latent Noise Mask', 'Set Latent Noise Mask', 'Set Latent Noise Mask'),
        task: L('Make the cat black without changing its pose: Set Latent Noise Mask with a denoise between 0.4 and 0.75.', 'Fes el gat negre sense canviar-ne la postura: Set Latent Noise Mask amb un denoise entre 0.4 i 0.75.', 'Haz el gato negro sin cambiar su postura: Set Latent Noise Mask con un denoise entre 0.4 y 0.75.'),
        concept: L('The second route is <b>img2img inside a mask</b>. VAE Encode keeps the original pixels in the latent and <b>Set Latent Noise Mask</b> tells the KSampler to add noise only where the mask is white. Now denoise means what it meant in img2img: low = small changes that keep shape and pose. It is the route to recolour, retouch or change a material.', 'La segona via és <b>img2img dins una màscara</b>. VAE Encode conserva els píxels originals al latent i <b>Set Latent Noise Mask</b> diu al KSampler que només afegeixi soroll on la màscara és blanca. Ara denoise vol dir el mateix que a img2img: baix = canvis petits que mantenen la forma i la postura. És la via per canviar un color, retocar o canviar un material.', 'La segunda vía es <b>img2img dentro de una máscara</b>. VAE Encode conserva los píxeles originales en el latente y <b>Set Latent Noise Mask</b> dice al KSampler que solo añada ruido donde la máscara es blanca. Ahora denoise significa lo mismo que en img2img: bajo = cambios pequeños que mantienen la forma y la postura. Es la vía para cambiar un color, retocar o cambiar un material.'),
        how: [L('The prompt already says <b>a black cat</b>. Run at denoise 0.55.', 'El prompt ja diu <b>a black cat</b>. Executa amb denoise 0.55.', 'El prompt ya dice <b>a black cat</b>. Ejecuta con denoise 0.55.'), L('Too little change? Try 0.7. Try 1.0 too: the cat is drawn again from scratch, in another pose.', 'Massa poc canvi? Prova 0.7. Prova també 1.0: el gat es dibuixa de nou, en una altra postura.', '¿Demasiado poco cambio? Prueba 0.7. Prueba también 1.0: el gato se dibuja de nuevo, en otra postura.')],
        note: L('Rule of thumb: change something new → denoise 1; change what is there → denoise 0.4–0.75.', 'Regla pràctica: posar una cosa nova → denoise 1; canviar el que hi ha → denoise 0.4–0.75.', 'Regla práctica: poner algo nuevo → denoise 1; cambiar lo que hay → denoise 0.4–0.75.'),
        starter: () => G.inpaint({ method: 'noisemask', text: 'a black cat in a landscape, detailed', denoise: .55 }), solution: () => G.inpaint({ method: 'noisemask', text: 'a black cat in a landscape, detailed', denoise: .65 }),
        goals: [goal(L('Ran with Set Latent Noise Mask', 'Executat amb Set Latent Noise Mask', 'Ejecutado con Set Latent Noise Mask'), (g, c) => ran(c, h => h.method === 'noisemask')), goal(L('Still a cat, now with a colour in the prompt', 'Encara un gat, ara amb un color al prompt', 'Todavía un gato, ahora con un color en el prompt'), (g, c) => ran(c, h => h.method === 'noisemask' && h.subject === 'cat' && h.pos?.colors?.length > 0)), goal(L('Denoise between 0.4 and 0.75', 'Denoise entre 0.4 i 0.75', 'Denoise entre 0.4 y 0.75'), (g, c) => ran(c, h => h.method === 'noisemask' && h.denoise >= .4 && h.denoise <= .75)), goal(L('Compared with denoise 1', 'Comparat amb denoise 1', 'Comparado con denoise 1'), (g, c) => ran(c, h => h.method === 'noisemask' && h.denoise >= .95), true)],
      },
      {
        title: L('InpaintModelConditioning + an inpainting model', 'InpaintModelConditioning + un model d’inpainting', 'InpaintModelConditioning + un modelo de inpainting'),
        task: L('Run this graph once with the normal model, then switch to dreamshaper_8Inpainting and run it again.', 'Executa aquest graf un cop amb el model normal, després canvia a dreamshaper_8Inpainting i torna’l a executar.', 'Ejecuta este grafo una vez con el modelo normal, luego cambia a dreamshaper_8Inpainting y vuelve a ejecutarlo.'),
        concept: L('The third route. <b>InpaintModelConditioning</b> sends the model the original picture and the mask as part of the conditioning, so the model sees what is around the hole. <b>Inpainting checkpoints</b> are trained exactly for this (they have extra input channels for image and mask): the colours and the light of the new area match the old ones and the seam disappears. Look for “inpainting” in the file name.', 'La tercera via. <b>InpaintModelConditioning</b> envia al model la imatge original i la màscara dins el conditioning, i el model veu què hi ha al voltant del forat. Els <b>checkpoints d’inpainting</b> estan entrenats exactament per a això (tenen canals d’entrada extra per a imatge i màscara): els colors i la llum de la zona nova lliguen amb els vells i la costura desapareix. Busca “inpainting” al nom del fitxer.', 'La tercera vía. <b>InpaintModelConditioning</b> envía al modelo la imagen original y la máscara dentro del conditioning, y el modelo ve qué hay alrededor del agujero. Los <b>checkpoints de inpainting</b> están entrenados exactamente para esto (tienen canales de entrada extra para imagen y máscara): los colores y la luz de la zona nueva encajan con los viejos y la costura desaparece. Busca “inpainting” en el nombre del archivo.'),
        how: [L('Run as it is (dreamshaper_8): note the border.', 'Executa tal com està (dreamshaper_8): fixa’t en la vora.', 'Ejecuta tal cual (dreamshaper_8): fíjate en el borde.'), L('In Load Checkpoint choose <b>dreamshaper_8Inpainting.safetensors</b> and run again with the same seed.', 'A Load Checkpoint tria <b>dreamshaper_8Inpainting.safetensors</b> i torna a executar amb el mateix seed.', 'En Load Checkpoint elige <b>dreamshaper_8Inpainting.safetensors</b> y vuelve a ejecutar con el mismo seed.'), L('Look at the wiring: the conditioning <i>and</i> the latent come from the same node.', 'Mira el cablejat: el conditioning <i>i</i> el latent surten del mateix node.', 'Mira el cableado: el conditioning <i>y</i> el latente salen del mismo nodo.')],
        note: L('noise_mask = true samples only the masked area. With false, the whole picture is redrawn (useful to harmonise everything at a low denoise).', 'noise_mask = true mostreja només la zona emmascarada. Amb false, es redibuixa tota la imatge (útil per harmonitzar-ho tot amb un denoise baix).', 'noise_mask = true muestrea solo la zona enmascarada. Con false, se redibuja toda la imagen (útil para armonizarlo todo con un denoise bajo).'),
        starter: () => G.inpaint({ method: 'imc' }), solution: () => G.inpaint({ method: 'imc', ckpt: INPAINT_CKPT }),
        goals: [goal(L('Ran with InpaintModelConditioning', 'Executat amb InpaintModelConditioning', 'Ejecutado con InpaintModelConditioning'), (g, c) => ran(c, h => h.method === 'imc')), goal(L('…with the normal model', '…amb el model normal', '…con el modelo normal'), (g, c) => ran(c, h => h.method === 'imc' && !h.inpaintModel), true), goal(L('…and with the inpainting model, denoise 1', '…i amb el model d’inpainting, denoise 1', '…y con el modelo de inpainting, denoise 1'), (g, c) => ran(c, h => h.method === 'imc' && h.inpaintModel && h.denoise >= .95))],
      },
      {
        title: L('Differential Diffusion', 'Differential Diffusion', 'Differential Diffusion'),
        task: L('Run with the soft mask and look at the border. Then put Differential Diffusion between Load Checkpoint and the KSampler and run again.', 'Executa amb la màscara suau i mira la vora. Després posa Differential Diffusion entre Load Checkpoint i el KSampler i torna a executar.', 'Ejecuta con la máscara suave y mira el borde. Luego pon Differential Diffusion entre Load Checkpoint y el KSampler y vuelve a ejecutar.'),
        concept: L('The latent is 8 times smaller than the picture, so the sampler sees the mask in 8 × 8 pixel blocks, and as yes/no: a nice soft mask becomes a <b>staircase</b>. <b>Differential Diffusion</b> patches the model so it reads the grey values as “how much to change”, pixel by pixel. It is the fourth piece, and it combines with the other routes: soft mask + Differential Diffusion = joins you cannot see.', 'El latent és 8 vegades més petit que la imatge, i el sampler veu la màscara en blocs de 8 × 8 píxels, i com a sí/no: una màscara suau i bonica es converteix en una <b>escala</b>. <b>Differential Diffusion</b> modifica el model perquè llegeixi els grisos com a “quant cal canviar”, píxel a píxel. És la quarta peça, i es combina amb les altres vies: màscara suau + Differential Diffusion = unions que no es veuen.', 'El latente es 8 veces más pequeño que la imagen, y el sampler ve la máscara en bloques de 8 × 8 píxeles, y como sí/no: una máscara suave y bonita se convierte en una <b>escalera</b>. <b>Differential Diffusion</b> modifica el modelo para que lea los grises como “cuánto cambiar”, píxel a píxel. Es la cuarta pieza, y se combina con las otras vías: máscara suave + Differential Diffusion = uniones que no se ven.'),
        how: [L('Run once. Zoom into the result (click it in the Queue): blocky border.', 'Executa una vegada. Amplia el resultat (clica’l a la Queue): vora a blocs.', 'Ejecuta una vez. Amplía el resultado (haz clic en la Queue): borde a bloques.'), L('Search <b>differential diffusion</b>. MODEL of Load Checkpoint → Differential Diffusion → model of the KSampler.', 'Cerca <b>differential diffusion</b>. MODEL de Load Checkpoint → Differential Diffusion → model del KSampler.', 'Busca <b>differential diffusion</b>. MODEL de Load Checkpoint → Differential Diffusion → model del KSampler.'), L('Run again (same seed) and compare.', 'Torna a executar (mateix seed) i compara.', 'Vuelve a ejecutar (mismo seed) y compara.')],
        note: L('If you use LoRAs, Differential Diffusion goes after them: Checkpoint → LoRA → Differential Diffusion → KSampler.', 'Si fas servir LoRAs, Differential Diffusion va després: Checkpoint → LoRA → Differential Diffusion → KSampler.', 'Si usas LoRAs, Differential Diffusion va después: Checkpoint → LoRA → Differential Diffusion → KSampler.'),
        starter: () => G.softMask(false), solution: () => G.softMask(true),
        goals: [goal(L('Ran a soft mask without it', 'Has executat una màscara suau sense', 'Has ejecutado una máscara suave sin él'), (g, c) => ran(c, h => h.method && h.blur >= 4 && !h.diffdiff)), goal(L('Differential Diffusion feeds the KSampler', 'Differential Diffusion alimenta el KSampler', 'Differential Diffusion alimenta el KSampler'), g => N(g, 'KSampler').some(s => from(g, s.id, 'model')?.type === 'DifferentialDiffusion')), goal(L('Ran a soft mask with it', 'Has executat una màscara suau amb ell', 'Has ejecutado una máscara suave con él'), (g, c) => ran(c, h => h.method && h.blur >= 4 && h.diffdiff > 0))],
      },
    ],
  },
  {
    id: 'finish', name: L('Pro finish', 'Acabat pro', 'Acabado pro'), sub: L('Composite · crop & stitch', 'Composició · crop & stitch', 'Composición · crop & stitch'),
    steps: [
      {
        title: L('Paste it back on the original', 'Enganxa-ho sobre l’original', 'Pégalo sobre el original'),
        task: L('Add an ImageCompositeMasked: original as destination, the decoded result as source, the mask as mask, and save that.', 'Afegeix un ImageCompositeMasked: l’original com a destination, el resultat descodificat com a source, la màscara com a mask, i desa això.', 'Añade un ImageCompositeMasked: el original como destination, el resultado decodificado como source, la máscara como mask, y guarda eso.'),
        concept: L('Even when only the mask is sampled, the <b>whole picture</b> goes through the VAE twice (encode and decode). The VAE compresses: outside the mask everything comes back a little softer and duller. After 3 or 4 rounds of retouching you can see it. The fix is simple: paste the result on the original through the mask. Outside it, the pixels are the original ones again. Pros always end with this node.', 'Encara que només es mostregi la màscara, <b>tota la imatge</b> passa dues vegades pel VAE (encode i decode). El VAE comprimeix: fora de la màscara tot torna una mica més tou i apagat. Després de 3 o 4 retocs es nota. La solució és simple: enganxar el resultat sobre l’original a través de la màscara. Fora, els píxels tornen a ser els originals. Els professionals sempre acaben amb aquest node.', 'Aunque solo se muestree la máscara, <b>toda la imagen</b> pasa dos veces por el VAE (encode y decode). El VAE comprime: fuera de la máscara todo vuelve un poco más blando y apagado. Después de 3 o 4 retoques se nota. La solución es simple: pegar el resultado sobre el original a través de la máscara. Fuera, los píxeles vuelven a ser los originales. Los profesionales siempre acaban con este nodo.'),
        how: [L('Search <b>ImageCompositeMasked</b>.', 'Cerca <b>ImageCompositeMasked</b>.', 'Busca <b>ImageCompositeMasked</b>.'), L('IMAGE of Load Image → <b>destination</b>; IMAGE of VAE Decode → <b>source</b>; MASK of Load Image → <b>mask</b>.', 'IMAGE de Load Image → <b>destination</b>; IMAGE de VAE Decode → <b>source</b>; MASK de Load Image → <b>mask</b>.', 'IMAGE de Load Image → <b>destination</b>; IMAGE de VAE Decode → <b>source</b>; MASK de Load Image → <b>mask</b>.'), L('Its IMAGE → Save Image. Run.', 'La seva IMAGE → Save Image. Executa.', 'Su IMAGE → Save Image. Ejecuta.')],
        note: L('If the paste line shows, use a grown and slightly blurred mask for the composite (not the original tight one).', 'Si es nota la línia de l’enganxat, fes servir per a la composició una màscara crescuda i una mica difuminada (no l’original justa).', 'Si se nota la línea del pegado, usa para la composición una máscara crecida y un poco difuminada (no la original justa).'),
        starter: () => G.inpaint({ method: 'imc', ckpt: INPAINT_CKPT }), solution: G.composite,
        goals: [goal(L('An ImageCompositeMasked with destination, source and mask', 'Un ImageCompositeMasked amb destination, source i mask', 'Un ImageCompositeMasked con destination, source y mask'), g => N(g, 'ImageCompositeMasked').some(n => from(g, n.id, 'destination')?.type === 'LoadImage' && from(g, n.id, 'source')?.type === 'VAEDecode' && into(g, n.id, 'mask'))), goal(L('Saved the composite', 'Has desat la composició', 'Has guardado la composición'), (g, c) => ran(c, h => h.composite && h.compMasked && h.compDest))],
      },
      {
        title: L('Small details: crop and stitch', 'Detalls petits: crop and stitch', 'Detalles pequeños: crop and stitch'),
        task: L('Turn the small lighthouse red. Run once as it is, then add Inpaint Crop and Inpaint Stitch and run again.', 'Fes vermell el far petit. Executa una vegada tal com està, després afegeix Inpaint Crop i Inpaint Stitch i torna a executar.', 'Haz rojo el faro pequeño. Ejecuta una vez tal cual, luego añade Inpaint Crop e Inpaint Stitch y vuelve a ejecutar.'),
        concept: L('A small mask on a big picture is a handful of latent pixels: the model paints the detail with very little room and it comes out soft. <b>Crop and stitch</b> crops the area around the mask (with some context), scales it up to the size the model likes, inpaints it at full resolution and pastes it back. The same idea is behind face and hand detailers.', 'Una màscara petita en una imatge gran són quatre píxels latents: el model pinta el detall amb molt poc espai i surt tou. <b>Crop and stitch</b> retalla la zona del voltant de la màscara (amb una mica de context), l’amplia a la mida que agrada al model, la pinta a resolució completa i la torna a enganxar. La mateixa idea hi ha darrere dels detailers de cares i mans.', 'Una máscara pequeña en una imagen grande son cuatro píxeles latentes: el modelo pinta el detalle con muy poco espacio y sale blando. <b>Crop and stitch</b> recorta la zona alrededor de la máscara (con algo de contexto), la amplía al tamaño que le gusta al modelo, la pinta a resolución completa y la vuelve a pegar. La misma idea está detrás de los detailers de caras y manos.'),
        how: [L('Run: the lighthouse is red but blurry.', 'Executa: el far és vermell però borrós.', 'Ejecuta: el faro es rojo pero borroso.'), L('Add <b>✂️ Inpaint Crop</b>: image and mask from Load Image. Its <b>cropped_image</b> and <b>cropped_mask</b> go to InpaintModelConditioning.', 'Afegeix <b>✂️ Inpaint Crop</b>: image i mask de Load Image. El seu <b>cropped_image</b> i <b>cropped_mask</b> van a InpaintModelConditioning.', 'Añade <b>✂️ Inpaint Crop</b>: image y mask de Load Image. Su <b>cropped_image</b> y <b>cropped_mask</b> van a InpaintModelConditioning.'), L('Add <b>✂️ Inpaint Stitch</b>: stitcher from Inpaint Crop, inpainted_image from VAE Decode, and its image → Save Image.', 'Afegeix <b>✂️ Inpaint Stitch</b>: stitcher d’Inpaint Crop, inpainted_image de VAE Decode, i la seva image → Save Image.', 'Añade <b>✂️ Inpaint Stitch</b>: stitcher de Inpaint Crop, inpainted_image de VAE Decode, y su image → Save Image.')],
        note: L('Install the pack with ComfyUI Manager (search “crop and stitch”). Stitch already pastes through the mask, so no composite is needed after it.', 'Instal·la el paquet amb ComfyUI Manager (cerca “crop and stitch”). Stitch ja enganxa a través de la màscara: no cal cap composició després.', 'Instala el paquete con ComfyUI Manager (busca “crop and stitch”). Stitch ya pega a través de la máscara: no hace falta ninguna composición después.'),
        starter: G.small, solution: G.stitch,
        goals: [goal(L('Ran the small mask without cropping', 'Has executat la màscara petita sense retallar', 'Has ejecutado la máscara pequeña sin recortar'), (g, c) => ran(c, h => h.method && h.lightCover > .5 && !h.cropped), true), goal(L('The sampler gets the cropped image', 'El sampler rep la imatge retallada', 'El sampler recibe la imagen recortada'), g => N(g, 'InpaintCrop').length > 0 && g.links.some(l => l.from === N(g, 'InpaintCrop')[0].id && l.out === 1)), goal(L('Saved a stitched result with a lighthouse', 'Has desat un resultat cosit amb un far', 'Has guardado un resultado cosido con un faro'), (g, c) => ran(c, h => h.stitch && h.cropped && h.subject === 'lighthouse'))],
      },
    ],
  },
  {
    id: 'outpaint', name: L('Outpainting', 'Outpainting', 'Outpainting'), sub: L('Beyond the frame', 'Més enllà del marc', 'Más allá del marco'),
    steps: [
      {
        title: L('Make the picture wider', 'Fes la imatge més ampla', 'Haz la imagen más ancha'),
        task: L('Add 256 px on the right of the cabin with Pad Image for Outpainting and run.', 'Afegeix 256 px a la dreta de la cabana amb Pad Image for Outpainting i executa.', 'Añade 256 px a la derecha de la cabaña con Pad Image for Outpainting y ejecuta.'),
        concept: L('<b>Outpainting</b> is inpainting outside the picture. <b>Pad Image for Outpainting</b> makes the canvas bigger and returns two things: the bigger image (with an empty area) and a mask that is white exactly there. From then on it is an inpaint: VAE Encode (for Inpainting) and denoise 1, ideally with an inpainting checkpoint. Extend in steps of 128–256 px: the model needs enough picture to know what to continue.', 'L’<b>outpainting</b> és inpainting fora de la imatge. <b>Pad Image for Outpainting</b> fa el llenç més gran i torna dues coses: la imatge més gran (amb una zona buida) i una màscara que és blanca justament allà. A partir d’aquí és un inpaint: VAE Encode (for Inpainting) i denoise 1, millor amb un checkpoint d’inpainting. Allarga de 128 en 128 o de 256 en 256 px: el model necessita prou imatge per saber què ha de continuar.', 'El <b>outpainting</b> es inpainting fuera de la imagen. <b>Pad Image for Outpainting</b> hace el lienzo más grande y devuelve dos cosas: la imagen más grande (con una zona vacía) y una máscara que es blanca justo allí. A partir de aquí es un inpaint: VAE Encode (for Inpainting) y denoise 1, mejor con un checkpoint de inpainting. Alarga de 128 en 128 o de 256 en 256 px: el modelo necesita suficiente imagen para saber qué tiene que continuar.'),
        how: [L('Run once with right = 0: nothing changes, the mask is empty.', 'Executa una vegada amb right = 0: no canvia res, la màscara és buida.', 'Ejecuta una vez con right = 0: no cambia nada, la máscara está vacía.'), L('Set <b>right</b> to 256 in Pad Image for Outpainting.', 'Posa <b>right</b> a 256 a Pad Image for Outpainting.', 'Pon <b>right</b> a 256 en Pad Image for Outpainting.'), L('Run: 768 × 512, with new snow on the right.', 'Executa: 768 × 512, amb neu nova a la dreta.', 'Ejecuta: 768 × 512, con nieve nueva a la derecha.')],
        note: L('The new size counts for the model too: SD 1.5 is happy up to about 768 px on the long side. Further than that, extend in several passes.', 'La mida nova també compta per al model: SD 1.5 va bé fins a uns 768 px pel costat llarg. Per anar més lluny, allarga en diverses passades.', 'El tamaño nuevo también cuenta para el modelo: SD 1.5 va bien hasta unos 768 px por el lado largo. Para ir más lejos, alarga en varias pasadas.'),
        starter: () => G.outpaint(), solution: () => G.outpaint({ right: 256 }),
        goals: [goal(L('Pad Image for Outpainting feeds pixels and mask', 'Pad Image for Outpainting alimenta pixels i mask', 'Pad Image for Outpainting alimenta pixels y mask'), g => N(g, 'ImagePadForOutpaint').some(p => g.links.filter(l => l.from === p.id).length >= 2)), goal(L('At least 128 px added', 'Com a mínim 128 px afegits', 'Al menos 128 px añadidos'), g => N(g, 'ImagePadForOutpaint').some(p => p.widgets.left + p.widgets.right + p.widgets.top + p.widgets.bottom >= 128)), goal(L('Ran a wider picture', 'Has executat una imatge més ampla', 'Has ejecutado una imagen más ancha'), (g, c) => ran(c, h => h.pad >= 128 && h.w > 512))],
      },
      {
        title: L('Two outpainting traps', 'Dues trampes de l’outpainting', 'Dos trampas del outpainting'),
        task: L('This graph has both traps. Run it, then fix it: no subject in the prompt, feathering ≥ 32 and the inpainting checkpoint.', 'Aquest graf té les dues trampes. Executa’l i arregla’l: cap subjecte al prompt, feathering ≥ 32 i el checkpoint d’inpainting.', 'Este grafo tiene las dos trampas. Ejecútalo y arréglalo: ningún sujeto en el prompt, feathering ≥ 32 y el checkpoint de inpainting.'),
        concept: L('Trap 1: <b>the prompt describes the whole picture</b>. If it says “a cabin”, the model paints a second cabin in the new area: the prompt is what goes <i>inside the mask</i>. For outpainting describe only the surroundings (snow, trees, sky). Trap 2: <b>feathering 0</b>. A hard border between the old and the new area with a normal model gives a visible line. A feather of 32–64 px lets the new area start a little inside the old one.', 'Trampa 1: <b>el prompt descriu tota la imatge</b>. Si diu “a cabin”, el model pinta una segona cabana a la zona nova: el prompt és el que va <i>dins la màscara</i>. Per a l’outpainting descriu només l’entorn (neu, arbres, cel). Trampa 2: <b>feathering 0</b>. Una vora dura entre la zona vella i la nova amb un model normal fa una línia visible. Un feather de 32–64 px deixa que la zona nova comenci una mica dins la vella.', 'Trampa 1: <b>el prompt describe toda la imagen</b>. Si dice “a cabin”, el modelo pinta una segunda cabaña en la zona nueva: el prompt es lo que va <i>dentro de la máscara</i>. Para el outpainting describe solo el entorno (nieve, árboles, cielo). Trampa 2: <b>feathering 0</b>. Un borde duro entre la zona vieja y la nueva con un modelo normal hace una línea visible. Un feather de 32–64 px deja que la zona nueva empiece un poco dentro de la vieja.'),
        how: [L('Run as it is: a second cabin and a line.', 'Executa tal com està: una segona cabana i una línia.', 'Ejecuta tal cual: una segunda cabaña y una línea.'), L('Prompt: <b>snow, winter landscape, detailed</b>. Feathering 40. Checkpoint dreamshaper_8Inpainting.', 'Prompt: <b>snow, winter landscape, detailed</b>. Feathering 40. Checkpoint dreamshaper_8Inpainting.', 'Prompt: <b>snow, winter landscape, detailed</b>. Feathering 40. Checkpoint dreamshaper_8Inpainting.'), L('Run again.', 'Torna a executar.', 'Vuelve a ejecutar.')],
        note: L('The same applies to every inpaint: describe what goes in the mask, not the whole picture.', 'Val per a tot inpaint: descriu el que va dins la màscara, no tota la imatge.', 'Vale para todo inpaint: describe lo que va dentro de la máscara, no toda la imagen.'),
        starter: () => G.outpaint({ right: 256, feathering: 0, ckpt: BASE_CKPT, text: 'a cabin in the snow, detailed' }), solution: () => G.outpaint({ right: 256 }),
        goals: [goal(L('Saw the traps', 'Has vist les trampes', 'Has visto las trampas'), (g, c) => ran(c, h => h.pad > 0 && (h.subject || h.feather < 16)), true), goal(L('No subject in the prompt', 'Cap subjecte al prompt', 'Ningún sujeto en el prompt'), (g, c) => ran(c, h => h.pad > 0 && noSubject(h))), goal(L('Feathering ≥ 32', 'Feathering ≥ 32', 'Feathering ≥ 32'), (g, c) => ran(c, h => h.pad > 0 && h.feather >= 32)), goal(L('All three together, with the inpainting model', 'Les tres coses alhora, amb el model d’inpainting', 'Las tres cosas a la vez, con el modelo de inpainting'), (g, c) => ran(c, h => h.pad > 0 && noSubject(h) && h.feather >= 32 && h.inpaintModel))],
      },
    ],
  },
  {
    id: 'cleanplate', name: L('Clean plates', 'Cleanplates', 'Cleanplates'), sub: L('Remove, fill, deliver', 'Treu, omple, entrega', 'Quita, rellena, entrega'),
    steps: [
      {
        title: L('Remove the person', 'Treu la persona', 'Quita la persona'),
        task: L('Paint a mask over the person on the beach, grow it 6 px or more and run: an empty beach.', 'Pinta una màscara sobre la persona de la platja, fes-la créixer 6 px o més i executa: una platja buida.', 'Pinta una máscara sobre la persona de la playa, hazla crecer 6 px o más y ejecuta: una playa vacía.'),
        concept: L('A <b>clean plate</b> is the background without the subject: for compositing, for VFX, for moving the subject somewhere else. It is an inpaint where the prompt asks for <i>nothing</i>: only the surroundings, and the subject in the negative. The model fills the hole by continuing the sea, the sand and the sky. The mask must be generous: any pixel of the person left out (the shadow too!) the model will try to turn into another person.', 'Un <b>cleanplate</b> és el fons sense el subjecte: per compondre, per a VFX, per moure el subjecte a un altre lloc. És un inpaint on el prompt no demana <i>res</i>: només l’entorn, i el subjecte al negatiu. El model omple el forat continuant el mar, la sorra i el cel. La màscara ha de ser generosa: qualsevol píxel de la persona que quedi fora (l’ombra també!) el model intentarà convertir-lo en una altra persona.', 'Un <b>cleanplate</b> es el fondo sin el sujeto: para componer, para VFX, para mover el sujeto a otro sitio. Es un inpaint donde el prompt no pide <i>nada</i>: solo el entorno, y el sujeto en el negativo. El modelo rellena el agujero continuando el mar, la arena y el cielo. La máscara tiene que ser generosa: cualquier píxel de la persona que quede fuera (¡la sombra también!) el modelo intentará convertirlo en otra persona.'),
        how: [L('Open the Mask Editor and paint the whole person, with a margin.', 'Obre el Mask Editor i pinta tota la persona, amb marge.', 'Abre el Mask Editor y pinta toda la persona, con margen.'), L('Add a <b>Grow Mask</b> (expand 10) between Load Image and InpaintModelConditioning.', 'Afegeix un <b>Grow Mask</b> (expand 10) entre Load Image i InpaintModelConditioning.', 'Añade un <b>Grow Mask</b> (expand 10) entre Load Image e InpaintModelConditioning.'), L('Check the prompts: positive without a subject, negative with <b>person</b>. Run.', 'Revisa els prompts: positiu sense subjecte, negatiu amb <b>person</b>. Executa.', 'Revisa los prompts: positivo sin sujeto, negativo con <b>person</b>. Ejecuta.')],
        note: L('Big objects are harder: the model invents more. For a really big area, run twice: first remove, then a second pass at denoise 0.5 to add texture.', 'Els objectes grans costen més: el model s’inventa més coses. Per a una zona molt gran, fes dues passades: primer treure, després una segona a denoise 0.5 per donar textura.', 'Los objetos grandes cuestan más: el modelo se inventa más cosas. Para una zona muy grande, haz dos pasadas: primero quitar, luego una segunda a denoise 0.5 para dar textura.'),
        starter: G.cleanStart, solution: G.clean,
        goals: [goal(L('The mask covers the person', 'La màscara cobreix la persona', 'La máscara cubre la persona'), g => coverOf(g, BOXES['beach_person.png']).cover >= .8), goal(L('The mask is grown ≥ 6 px', 'La màscara ha crescut ≥ 6 px', 'La máscara ha crecido ≥ 6 px'), g => [...N(g, 'GrowMask'), ...N(g, 'GrowMaskWithBlur')].some(n => n.widgets.expand >= 6)), goal(L('An empty beach: no subject, denoise 1', 'Una platja buida: cap subjecte, denoise 1', 'Una playa vacía: ningún sujeto, denoise 1'), (g, c) => ran(c, h => h.photo === 'beach_person.png' && h.cover >= .8 && h.nodeGrow >= 6 && noSubject(h) && h.denoise >= .95))],
      },
      {
        title: L('Deliver the clean plate', 'Entrega el cleanplate', 'Entrega el cleanplate'),
        task: L('Finish it like a pro: a softened mask and ImageCompositeMasked over the original, then save.', 'Acaba-ho com un professional: una màscara suavitzada i ImageCompositeMasked sobre l’original, i desa.', 'Acábalo como un profesional: una máscara suavizada e ImageCompositeMasked sobre el original, y guarda.'),
        concept: L('Everything together. The grown mask decides <b>what is redrawn</b>; a second, slightly softer mask decides <b>how it is pasted</b> on the untouched original. The result: a background without the person, with every pixel outside the mask exactly as it was. This is the workflow you will repeat again and again.', 'Tot junt. La màscara crescuda decideix <b>què es redibuixa</b>; una segona màscara, una mica més suau, decideix <b>com s’enganxa</b> sobre l’original intacte. El resultat: un fons sense la persona, amb cada píxel de fora de la màscara exactament com era. Aquest és el workflow que repetiràs una vegada i una altra.', 'Todo junto. La máscara crecida decide <b>qué se redibuja</b>; una segunda máscara, un poco más suave, decide <b>cómo se pega</b> sobre el original intacto. El resultado: un fondo sin la persona, con cada píxel de fuera de la máscara exactamente como era. Este es el workflow que repetirás una y otra vez.'),
        how: [L('Add a <b>Grow Mask With Blur</b> (expand 4, blur 6) fed by the Grow Mask.', 'Afegeix un <b>Grow Mask With Blur</b> (expand 4, blur 6) alimentat pel Grow Mask.', 'Añade un <b>Grow Mask With Blur</b> (expand 4, blur 6) alimentado por el Grow Mask.'), L('<b>ImageCompositeMasked</b>: destination = Load Image, source = VAE Decode, mask = the soft mask.', '<b>ImageCompositeMasked</b>: destination = Load Image, source = VAE Decode, mask = la màscara suau.', '<b>ImageCompositeMasked</b>: destination = Load Image, source = VAE Decode, mask = la máscara suave.'), L('Into Save Image, and run.', 'A Save Image, i executa.', 'A Save Image, y ejecuta.')],
        note: L('Save the workflow (<kbd>Ctrl S</kbd>): with a new photo and a new mask it is ready to use again.', 'Desa el workflow (<kbd>Ctrl S</kbd>): amb una foto i una màscara noves ja el pots tornar a fer servir.', 'Guarda el workflow (<kbd>Ctrl S</kbd>): con una foto y una máscara nuevas ya lo puedes volver a usar.'),
        starter: G.clean, solution: G.cleanFinal,
        goals: [goal(L('The composite mask is grown and blurred', 'La màscara de la composició ha crescut i és suau', 'La máscara de la composición ha crecido y es suave'), (g, c) => ran(c, h => h.composite && h.compGrow >= 6 && h.compBlur > 0)), goal(L('A clean plate saved over the original', 'Un cleanplate desat sobre l’original', 'Un cleanplate guardado sobre el original'), (g, c) => ran(c, h => h.composite && h.compDest && h.photo === 'beach_person.png' && noSubject(h) && h.cover >= .8)), goal(L('Saved the workflow', 'Has desat el workflow', 'Has guardado el workflow'), (g, c) => c.flags.saved, true)],
      },
    ],
  },
];

export const TEMPLATES = [
  { id: 'inpaint-model', name: L('Inpaint (inpainting model)', 'Inpaint (model d’inpainting)', 'Inpaint (modelo de inpainting)'), make: G.composite },
  { id: 'inpaint-noise', name: L('Retouch (Set Latent Noise Mask)', 'Retoc (Set Latent Noise Mask)', 'Retoque (Set Latent Noise Mask)'), make: () => G.inpaint({ method: 'noisemask', text: 'a black cat in a landscape, detailed', denoise: .65 }) },
  { id: 'crop-stitch', name: L('Inpaint Crop and Stitch', 'Inpaint Crop and Stitch', 'Inpaint Crop and Stitch'), make: G.stitch },
  { id: 'outpaint', name: L('Outpainting', 'Outpainting', 'Outpainting'), make: () => G.outpaint({ right: 256 }) },
  { id: 'cleanplate', name: L('Clean plate', 'Cleanplate', 'Cleanplate'), make: G.cleanFinal },
];
export { G as GRAPHS, MASKS };
