// Carrot Revolt Labs · Upscale & Detail Lab · stages, steps and live checklists.
// It runs on the ComfyUI Lab interface (../comfyui/app.js) and adds its own nodes and detail simulator (./nodes.js).
import { defaultGraph, makeNode, makeLink, connect } from '../comfyui/engine.js';
import { summary, findRecipe as find, UPSCALERS } from './nodes.js';
export const L = (en, ca, es) => ({ en, ca, es });

export const META = { key: 'carrot-revolt-comfy-upscale:', title: 'Upscale & Detail Lab', label: 'GENERATIVE IMAGE / COMFYUI · 03' };

/* ── Graph helpers ── */
const N = (g, type) => g.nodes.filter(n => n.type === type && n.mode === 0);
const into = (g, id, input) => g.links.find(l => l.to === id && l.input === input);
const from = (g, id, input) => { const l = into(g, id, input); return l ? g.nodes.find(n => n.id === l.from) : null; };
const goal = (text, test, optional = false) => ({ text, test, optional });
const add = (g, ...nodes) => { g.nodes.push(...nodes); return g; };
const wire = (g, list) => { for (const l of list) connect(g, makeLink(...l)); return g; };
const set = (g, id, k, v) => { g.nodes.find(n => n.id === id).widgets[k] = v; return g; };
const move = (g, id, x, y) => { const n = g.nodes.find(n => n.id === id); n.x = x; n.y = y; return g; };
const out = c => c.history.filter(h => h.outW);
const ran = (c, f) => out(c).some(f);
const PROMPT = 'a woman on the beach, sunset, detailed', WIDE = 'a woman on the beach, wide shot, sunset, detailed';
const sampler2 = (id, x, y, denoise) => makeNode('KSampler', x, y, { denoise, control_after_generate: 'fixed' }, id);

/* ── Starters and solutions ── */
const G = {
  base: (text = PROMPT, size = 512) => { const g = defaultGraph(); set(g, 'pos', 'text', text); set(g, 'neg', 'text', 'blurry, text, watermark'); set(g, 'sampler', 'control_after_generate', 'fixed'); set(g, 'latent', 'width', size); set(g, 'latent', 'height', size); return g; },
  // Decode → [nodes] → Save, in a row after VAE Decode.
  chain: (g, nodes, start = 'decode') => { let prev = start, x = 1460; for (const n of nodes) { n.x = x; n.y = n.y || 186; add(g, n); wire(g, [[prev, 0, n.id, 'image']]); prev = n.id; x += 330; } move(g, 'save', x, 189); wire(g, [[prev, 0, 'save', 'images']]); return g; },
  scaleBy: (method = 'lanczos', f = 4) => G.chain(G.base(), [makeNode('ImageScaleBy', 0, 0, { upscale_method: method, scale_by: f }, 'up')]),
  model: (name = '4x-UltraSharp.pth') => { const g = G.chain(G.base(), [makeNode('ImageUpscaleWithModel', 0, 0, {}, 'ups')]); add(g, makeNode('UpscaleModelLoader', 1209, 330, { model_name: name }, 'uml')); return wire(g, [['uml', 0, 'ups', 'upscale_model']]); },
  modelHalf: () => { const g = G.chain(G.base(), [makeNode('ImageUpscaleWithModel', 0, 0, {}, 'ups'), makeNode('ImageScaleBy', 0, 0, { upscale_method: 'lanczos', scale_by: .5 }, 'down')]); add(g, makeNode('UpscaleModelLoader', 1209, 330, {}, 'uml')); return wire(g, [['uml', 0, 'ups', 'upscale_model']]); },
  latentRaw: (f = 2) => { const g = G.base(); add(g, makeNode('LatentUpscaleBy', 1209, 400, { scale_by: f }, 'lup')); move(g, 'decode', 1560, 188); move(g, 'save', 1800, 189); return wire(g, [['sampler', 0, 'lup', 'samples'], ['lup', 0, 'decode', 'samples']]); },
  hires: (d = .5, f = 2) => { const g = G.latentRaw(f); add(g, sampler2('s2', 1560, 186, d)); move(g, 'decode', 1920, 188); move(g, 'save', 2160, 189); return wire(g, [['ckpt', 0, 's2', 'model'], ['pos', 0, 's2', 'positive'], ['neg', 0, 's2', 'negative'], ['lup', 0, 's2', 'latent_image'], ['s2', 0, 'decode', 'samples']]); },
  pixelHires: (d = .35) => {
    const g = G.base(); add(g, makeNode('UpscaleModelLoader', 1209, 330, {}, 'uml'), makeNode('ImageUpscaleWithModel', 1460, 186, {}, 'ups'), makeNode('ImageScaleBy', 1460, 330, { upscale_method: 'lanczos', scale_by: .5 }, 'down'), makeNode('VAEEncode', 1790, 330, {}, 'enc'), sampler2('s2', 2040, 186, d), makeNode('VAEDecode', 2400, 188, {}, 'dec2'));
    move(g, 'save', 2650, 189);
    return wire(g, [['uml', 0, 'ups', 'upscale_model'], ['decode', 0, 'ups', 'image'], ['ups', 0, 'down', 'image'], ['down', 0, 'enc', 'pixels'], ['ckpt', 2, 'enc', 'vae'], ['ckpt', 0, 's2', 'model'], ['pos', 0, 's2', 'positive'], ['neg', 0, 's2', 'negative'], ['enc', 0, 's2', 'latent_image'], ['s2', 0, 'dec2', 'samples'], ['ckpt', 2, 'dec2', 'vae'], ['dec2', 0, 'save', 'images']]);
  },
  usdu: (w = {}, src = G.base()) => {
    const g = src, img = g.nodes.some(n => n.id === 'dec2') ? 'dec2' : g.nodes.some(n => n.id === 'fd') ? 'fd' : 'decode', x = Math.max(...g.nodes.map(n => n.x)) + 20;
    g.links = g.links.filter(l => l.to !== 'save');
    if (!g.nodes.some(n => n.id === 'uml')) add(g, makeNode('UpscaleModelLoader', x - 300, 560, {}, 'uml'));
    add(g, makeNode('UltimateSDUpscale', x, 120, { upscale_by: 4, denoise: .3, ...w }, 'usdu')); move(g, 'save', x + 380, 189);
    return wire(g, [[img, 0, 'usdu', 'image'], ['ckpt', 0, 'usdu', 'model'], ['pos', 0, 'usdu', 'positive'], ['neg', 0, 'usdu', 'negative'], ['ckpt', 2, 'usdu', 'vae'], ['uml', 0, 'usdu', 'upscale_model'], ['usdu', 0, 'save', 'images']]);
  },
  usduTile: (d = .5) => {
    const g = G.usdu({ denoise: d }); add(g, makeNode('ControlNetLoader', 1209, 760, { control_net_name: 'control_v11f1e_sd15_tile.pth' }, 'cnl'), makeNode('ControlNetApplyAdvanced', 1460, 620, { strength: .8 }, 'cn'));
    return wire(g, [['pos', 0, 'cn', 'positive'], ['neg', 0, 'cn', 'negative'], ['cnl', 0, 'cn', 'control_net'], ['decode', 0, 'cn', 'image'], ['cn', 0, 'usdu', 'positive'], ['cn', 1, 'usdu', 'negative']]);
  },
  detailer: (w = {}, src = G.base(WIDE)) => {
    const g = src, img = g.nodes.some(n => n.id === 's2') ? 'decode' : 'decode';
    g.links = g.links.filter(l => l.to !== 'save'); const x = Math.max(...g.nodes.filter(n => n.id !== 'save').map(n => n.x)) + 350;
    add(g, makeNode('UltralyticsDetectorProvider', x - 330, 560, {}, 'det'), makeNode('FaceDetailer', x, 120, { denoise: .45, ...w }, 'fd')); move(g, 'save', x + 380, 189);
    return wire(g, [[img, 0, 'fd', 'image'], ['ckpt', 0, 'fd', 'model'], ['ckpt', 1, 'fd', 'clip'], ['ckpt', 2, 'fd', 'vae'], ['pos', 0, 'fd', 'positive'], ['neg', 0, 'fd', 'negative'], ['det', 0, 'fd', 'bbox_detector'], ['fd', 0, 'save', 'images']]);
  },
  full: () => G.usdu({ denoise: .3 }, G.detailer({}, G.hires(.5))),
  fullStart: () => G.hires(.5),
};

/* ── History: what the checklists read ── */
export const findRecipe = find;
export function outputExtra(img) { const s = summary(img); return { ...s, w: s.outW, h: s.outH }; }
const pct = v => `${Math.round(v * 100)}%`;
export function resultExtra(h) {
  if (!h.outW) return '';
  const row = (k, v) => `<dt>${k}</dt><dd>${v}</dd>`;
  const edge = { clean: 'clean', soft: 'soft (blurred)', blocky: 'blocky (latent / nearest)', sharp: 'sharp but flat', waxy: 'smooth, waxy' }[h.edge] || h.edge;
  return `<dl class="q-dl">${row('real detail', pct(h.detail))}${row('texture', pct(h.tex))}${row('edges', edge)}${h.faceQ !== null ? row('face', `${pct(h.faceQ)} · ${h.facePx}px`) : ''}${h.dup > 1 ? row('copies', h.dup) : ''}${h.ghosts ? row('tile ghosts', h.ghosts) : ''}${h.seams ? row('tile seams', pct(h.seams)) : ''}${h.detected !== null && h.detailer ? row('faces found', h.detected) : ''}</dl>`;
}
const passIn = (h, lo, hi) => h.passes.some(p => p.d >= lo && p.d <= hi && p.W > 512);

export const UI = {
  headline: L('From 512 pixels <span>to 4K, with detail.</span>', 'De 512 píxels <span>a 4K, amb detall.</span>', 'De 512 píxeles <span>a 4K, con detalle.</span>'),
  lead: L('Models draw well only at their own size. Here you learn how to get big pictures that hold up at 100%: resize vs upscale models, the hires fix with a second pass and its denoise window, tiled upscaling without seams or ghosts, ControlNet Tile, face detailers and a full pipeline to 4K. Every result shows a 100% crop, so you can see the difference.', 'Els models només dibuixen bé a la seva mida. Aquí aprens a fer imatges grans que aguantin al 100%: redimensionar vs models d’upscale, el hires fix amb segona passada i la seva finestra de denoise, l’upscale per tiles sense costures ni fantasmes, la ControlNet Tile, els detailers de cares i un pipeline complet fins a 4K. Cada resultat mostra un retall al 100%, perquè vegis la diferència.', 'Los modelos solo dibujan bien a su tamaño. Aquí aprendes a hacer imágenes grandes que aguanten al 100%: redimensionar vs modelos de upscale, el hires fix con segunda pasada y su ventana de denoise, el upscale por tiles sin costuras ni fantasmas, la ControlNet Tile, los detailers de caras y un pipeline completo hasta 4K. Cada resultado muestra un recorte al 100%, para que veas la diferencia.'),
  loraVsCn: L('Which upscale?', 'Quin upscale?', '¿Qué upscale?'),
  type_UPSCALE_MODEL: L('an upscale network (ESRGAN family)', 'una xarxa d’upscale (família ESRGAN)', 'una red de upscale (familia ESRGAN)'),
  type_BBOX_DETECTOR: L('finds boxes around faces, hands…', 'troba requadres al voltant de cares, mans…', 'encuentra recuadros alrededor de caras, manos…'),
  type_SEGM_DETECTOR: L('finds the exact shape of what it detects', 'troba la forma exacta del que detecta', 'encuentra la forma exacta de lo que detecta'),
  type_SAM_MODEL: L('Segment Anything, to refine masks', 'Segment Anything, per afinar màscares', 'Segment Anything, para afinar máscaras'),
};
const T3 = (h, rows, foot) => `<table class="c-cmp"><tr><th></th><th>${h[0]}</th><th>${h[1]}</th></tr>${rows.map(r => `<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</table><p>${foot}</p>`;
UI.loraVsCnBody = L(
  T3(['Gives', 'Use it for'], [['<b>Upscale Image (By)</b>', 'more pixels, no detail', 'small changes, final fit'], ['<b>Upscale model</b>', 'sharp edges, flat texture', 'the first step of every upscale'], ['<b>Hires fix</b> (2nd pass)', 'real detail, up to ~2× native', 'the base picture'], ['<b>Ultimate SD Upscale</b>', 'detail by tiles, any size', '2K, 4K and more'], ['<b>FaceDetailer</b>', 'faces drawn at full size', 'faces too small in the picture']], 'Pixels are not detail: only a sampler adds detail.'),
  T3(['Dona', 'Per a'], [['<b>Upscale Image (By)</b>', 'més píxels, cap detall', 'canvis petits, ajust final'], ['<b>Model d’upscale</b>', 'vores nítides, textura plana', 'el primer pas de tot upscale'], ['<b>Hires fix</b> (2a passada)', 'detall real, fins a ~2× la mida nativa', 'la imatge base'], ['<b>Ultimate SD Upscale</b>', 'detall per tiles, qualsevol mida', '2K, 4K i més'], ['<b>FaceDetailer</b>', 'cares dibuixades a mida completa', 'cares massa petites a la imatge']], 'Píxels no és detall: només un sampler afegeix detall.'),
  T3(['Da', 'Para'], [['<b>Upscale Image (By)</b>', 'más píxeles, ningún detalle', 'cambios pequeños, ajuste final'], ['<b>Modelo de upscale</b>', 'bordes nítidos, textura plana', 'el primer paso de todo upscale'], ['<b>Hires fix</b> (2a pasada)', 'detalle real, hasta ~2× el tamaño nativo', 'la imagen base'], ['<b>Ultimate SD Upscale</b>', 'detalle por tiles, cualquier tamaño', '2K, 4K y más'], ['<b>FaceDetailer</b>', 'caras dibujadas a tamaño completo', 'caras demasiado pequeñas en la imagen']], 'Píxeles no es detalle: solo un sampler añade detalle.'));

export const DOCS = {
  UpscaleModelLoader: { short: L('Loads an upscale network.', 'Carrega una xarxa d’upscale.', 'Carga una red de upscale.'), long: L('Files in models/upscale_models (ESRGAN family: 4x-UltraSharp, RealESRGAN…). Each one multiplies the size by a fixed factor (×2, ×4) and has its own character: sharper, smoother, better for photos or for drawings.', 'Fitxers de models/upscale_models (família ESRGAN: 4x-UltraSharp, RealESRGAN…). Cadascun multiplica la mida per un factor fix (×2, ×4) i té el seu caràcter: més nítid, més suau, millor per a fotos o per a dibuix.', 'Archivos de models/upscale_models (familia ESRGAN: 4x-UltraSharp, RealESRGAN…). Cada uno multiplica el tamaño por un factor fijo (×2, ×4) y tiene su carácter: más nítido, más suave, mejor para fotos o para dibujo.'), widgets: { model_name: L('the file; the ×2 / ×4 is in the name', 'el fitxer; el ×2 / ×4 és al nom', 'el archivo; el ×2 / ×4 está en el nombre') } },
  ImageUpscaleWithModel: { short: L('Upscales pixels with a network.', 'Amplia píxels amb una xarxa.', 'Amplía píxeles con una red.'), long: L('Much better than resizing: it rebuilds sharp edges. But it has never seen your prompt and does not invent new texture: at 100% things look clean and a bit plastic. It is the first half of a good upscale; the second half is a sampler.', 'Molt millor que redimensionar: reconstrueix vores nítides. Però no ha vist mai el teu prompt i no inventa textura nova: al 100% tot es veu net i una mica de plàstic. És la primera meitat d’un bon upscale; l’altra meitat és un sampler.', 'Mucho mejor que redimensionar: reconstruye bordes nítidos. Pero no ha visto nunca tu prompt y no inventa textura nueva: al 100% todo se ve limpio y un poco de plástico. Es la primera mitad de un buen upscale; la otra mitad es un sampler.') },
  ImageScale: { short: L('Resizes to an exact size.', 'Redimensiona a una mida exacta.', 'Redimensiona a un tamaño exacto.'), long: L('Plain interpolation: no new detail. Useful to fit an exact size at the end.', 'Interpolació simple: cap detall nou. Útil per ajustar una mida exacta al final.', 'Interpolación simple: ningún detalle nuevo. Útil para ajustar un tamaño exacto al final.'), widgets: { upscale_method: L('nearest-exact = blocks; lanczos = the softest good one', 'nearest-exact = blocs; lanczos = el més suau i bo', 'nearest-exact = bloques; lanczos = el más suave y bueno') } },
  ImageScaleBy: { short: L('Resizes by a factor.', 'Redimensiona per un factor.', 'Redimensiona por un factor.'), long: L('Interpolation only: ×4 gives 16 times more pixels and exactly the same detail, blurred. Great for going <i>down</i> (0.5 after a ×4 model) or for a final fit.', 'Només interpolació: ×4 dona 16 vegades més píxels i exactament el mateix detall, borrós. Perfecte per <i>baixar</i> (0.5 després d’un model ×4) o per a un ajust final.', 'Solo interpolación: ×4 da 16 veces más píxeles y exactamente el mismo detalle, borroso. Perfecto para <i>bajar</i> (0.5 después de un modelo ×4) o para un ajuste final.'), widgets: { upscale_method: L('lanczos or bicubic for photos', 'lanczos o bicubic per a fotos', 'lanczos o bicubic para fotos'), scale_by: L('the factor (0.5 = half)', 'el factor (0.5 = la meitat)', 'el factor (0.5 = la mitad)') } },
  LatentUpscale: { short: L('Resizes the latent to an exact size.', 'Redimensiona el latent a una mida exacta.', 'Redimensiona el latente a un tamaño exacto.'), long: L('The latent is 8× smaller than the picture: resizing it makes blocks. It only works followed by a KSampler with enough denoise.', 'El latent és 8× més petit que la imatge: redimensionar-lo fa blocs. Només funciona seguit d’un KSampler amb prou denoise.', 'El latente es 8× más pequeño que la imagen: redimensionarlo hace bloques. Solo funciona seguido de un KSampler con suficiente denoise.') },
  LatentUpscaleBy: { short: L('Resizes the latent by a factor (hires fix).', 'Redimensiona el latent per un factor (hires fix).', 'Redimensiona el latente por un factor (hires fix).'), long: L('The classic hires fix: generate small, upscale the latent, and sample again at the new size. Decoded directly it is a mess of blocks; the second KSampler (denoise 0.5–0.6) redraws it with real detail.', 'El hires fix clàssic: genera petit, amplia el latent i torna a mostrejar a la mida nova. Descodificat directament és un desastre de blocs; el segon KSampler (denoise 0.5–0.6) el redibuixa amb detall real.', 'El hires fix clásico: genera pequeño, amplía el latente y vuelve a muestrear al tamaño nuevo. Decodificado directamente es un desastre de bloques; el segundo KSampler (denoise 0.5–0.6) lo redibuja con detalle real.'), widgets: { scale_by: L('1.5–2 is the usual range', 'l’habitual és 1.5–2', 'lo habitual es 1.5–2') } },
  VAEDecodeTiled: { short: L('VAE Decode in tiles, for big pictures.', 'VAE Decode per tiles, per a imatges grans.', 'VAE Decode por tiles, para imágenes grandes.'), long: L('Decodes the latent piece by piece, so big pictures fit in memory. The normal VAE Decode falls back to tiles when it runs out of memory, but slower and with a warning.', 'Descodifica el latent tros a tros, i les imatges grans caben a la memòria. El VAE Decode normal passa a tiles quan es queda sense memòria, però més lent i amb un avís.', 'Decodifica el latente trozo a trozo, y las imágenes grandes caben en memoria. El VAE Decode normal pasa a tiles cuando se queda sin memoria, pero más lento y con un aviso.') },
  UltimateSDUpscale: { short: L('Upscale model + a sampler, tile by tile.', 'Model d’upscale + un sampler, tile a tile.', 'Modelo de upscale + un sampler, tile a tile.'), long: L('Custom node. It upscales with the model, cuts the big picture in tiles of the model’s size and samples each one at low denoise. Memory stays low whatever the final size. Each tile only sees its piece and the prompt: with too much denoise, the prompt’s subject appears in every tile.', 'Custom node. Amplia amb el model, talla la imatge gran en tiles de la mida del model i mostreja cadascun amb denoise baix. La memòria es manté baixa sigui quina sigui la mida final. Cada tile només veu el seu tros i el prompt: amb massa denoise, el subjecte del prompt apareix a cada tile.', 'Custom node. Amplía con el modelo, corta la imagen grande en tiles del tamaño del modelo y muestrea cada uno con denoise bajo. La memoria se mantiene baja sea cual sea el tamaño final. Cada tile solo ve su trozo y el prompt: con demasiado denoise, el sujeto del prompt aparece en cada tile.'), widgets: { upscale_by: L('final size = input × this', 'mida final = entrada × això', 'tamaño final = entrada × esto'), denoise: L('0.2–0.35 without ControlNet Tile', '0.2–0.35 sense ControlNet Tile', '0.2–0.35 sin ControlNet Tile'), mask_blur: L('soft border between tiles', 'vora suau entre tiles', 'borde suave entre tiles'), tile_padding: L('context around each tile', 'context al voltant de cada tile', 'contexto alrededor de cada tile'), seam_fix_mode: L('an extra pass over the joins', 'una passada extra sobre les unions', 'una pasada extra sobre las uniones') } },
  UltralyticsDetectorProvider: { short: L('Loads a YOLO detector (faces, hands, people).', 'Carrega un detector YOLO (cares, mans, persones).', 'Carga un detector YOLO (caras, manos, personas).'), long: L('Impact Pack. bbox models find boxes, segm models find shapes. face_yolov8 for faces, hand_yolov8 for hands.', 'Impact Pack. Els models bbox troben requadres, els segm troben formes. face_yolov8 per a cares, hand_yolov8 per a mans.', 'Impact Pack. Los modelos bbox encuentran recuadros, los segm encuentran formas. face_yolov8 para caras, hand_yolov8 para manos.') },
  FaceDetailer: { short: L('Finds faces and redraws them at full size.', 'Troba cares i les redibuixa a mida completa.', 'Encuentra caras y las redibuja a tamaño completo.'), long: L('Impact Pack. Detect → crop around each face → scale the crop to guide_size → inpaint it → paste it back. A face of 30 pixels gets the model’s full attention. The same idea as crop and stitch, automatic.', 'Impact Pack. Detecta → retalla al voltant de cada cara → escala el retall a guide_size → hi fa inpaint → el torna a enganxar. Una cara de 30 píxels rep tota l’atenció del model. La mateixa idea que el crop and stitch, automàtica.', 'Impact Pack. Detecta → recorta alrededor de cada cara → escala el recorte a guide_size → le hace inpaint → lo vuelve a pegar. Una cara de 30 píxeles recibe toda la atención del modelo. La misma idea que el crop and stitch, automática.'), widgets: { guide_size: L('the size the face is redrawn at', 'la mida a què es redibuixa la cara', 'el tamaño al que se redibuja la cara'), denoise: L('0.35–0.5: fixes without changing who it is', '0.35–0.5: arregla sense canviar qui és', '0.35–0.5: arregla sin cambiar quién es'), bbox_threshold: L('minimum confidence; lower it if small faces are missed', 'confiança mínima; baixa-la si no troba cares petites', 'confianza mínima; bájala si no encuentra caras pequeñas'), bbox_crop_factor: L('context around the face (3 = 3× the box)', 'context al voltant de la cara (3 = 3× el requadre)', 'contexto alrededor de la cara (3 = 3× el recuadro)'), feather: L('soft border of the pasted face', 'vora suau de la cara enganxada', 'borde suave de la cara pegada'), drop_size: L('ignore faces smaller than this (px)', 'ignora cares més petites que això (px)', 'ignora caras más pequeñas que esto (px)') } },
};

export const STAGES = [
  {
    id: 'size', name: L('Size', 'Mida', 'Tamaño'), sub: L('Native size · resize', 'Mida nativa · redimensionar', 'Tamaño nativo · redimensionar'),
    steps: [
      {
        title: L('The model’s size and the 100% view', 'La mida del model i la vista al 100%', 'El tamaño del modelo y la vista al 100%'),
        task: L('Generate at 512 × 512, then at 1024 × 1024. Open both results from the Queue and compare.', 'Genera a 512 × 512 i després a 1024 × 1024. Obre els dos resultats des de la Queue i compara.', 'Genera a 512 × 512 y luego a 1024 × 1024. Abre los dos resultados desde la Queue y compara.'),
        concept: L('Every model was trained at one size: SD 1.5 at 512, SDXL and Flux around 1024. Ask for much more and it composes the picture as several 512 pictures glued together: <b>two people, two horizons</b>. That is why big pictures are made in steps. In this lab every result has a yellow frame and a <b>100% crop</b> in the corner: real pixels, the way you see them in a print or zoomed in. Learn to judge there, not on the thumbnail.', 'Cada model es va entrenar a una mida: SD 1.5 a 512, SDXL i Flux al voltant de 1024. Si en demanes molt més, compon la imatge com si fossin diverses imatges de 512 enganxades: <b>dues persones, dos horitzons</b>. Per això les imatges grans es fan per passos. En aquest lab cada resultat té un marc groc i un <b>retall al 100%</b> a la cantonada: píxels reals, com els veuràs imprès o amb zoom. Aprèn a jutjar allà, no a la miniatura.', 'Cada modelo se entrenó a un tamaño: SD 1.5 a 512, SDXL y Flux alrededor de 1024. Si pides mucho más, compone la imagen como varias imágenes de 512 pegadas: <b>dos personas, dos horizontes</b>. Por eso las imágenes grandes se hacen por pasos. En este lab cada resultado tiene un marco amarillo y un <b>recorte al 100%</b> en la esquina: píxeles reales, como los verás impresos o con zoom. Aprende a juzgar allí, no en la miniatura.'),
        how: [L('Run at 512 × 512 (<kbd>Ctrl Enter</kbd>).', 'Executa a 512 × 512 (<kbd>Ctrl Enter</kbd>).', 'Ejecuta a 512 × 512 (<kbd>Ctrl Enter</kbd>).'), L('Set Empty Latent Image to 1024 × 1024 and run again.', 'Posa Empty Latent Image a 1024 × 1024 i torna a executar.', 'Pon Empty Latent Image a 1024 × 1024 y vuelve a ejecutar.'), L('<kbd>Q</kbd> › click a result: size, real detail and the face quality, measured.', '<kbd>Q</kbd> › clica un resultat: mida, detall real i qualitat de la cara, mesurats.', '<kbd>Q</kbd> › haz clic en un resultado: tamaño, detalle real y calidad de la cara, medidos.')],
        note: L('The face at 512 is only about 60 pixels tall: the model does what it can. Keep it in mind for the last stage.', 'La cara a 512 només fa uns 60 píxels d’alçada: el model fa el que pot. Tingues-ho present per a l’última etapa.', 'La cara a 512 solo mide unos 60 píxeles de alto: el modelo hace lo que puede. Tenlo presente para la última etapa.'),
        starter: () => G.base(), solution: () => G.base(PROMPT, 1024),
        goals: [goal(L('A 512 × 512 picture', 'Una imatge de 512 × 512', 'Una imagen de 512 × 512'), (g, c) => ran(c, h => h.outW === 512 && h.ops.length === 1)), goal(L('A 1024 × 1024 picture straight away: count the people', 'Una imatge de 1024 × 1024 directa: compta les persones', 'Una imagen de 1024 × 1024 directa: cuenta las personas'), (g, c) => ran(c, h => h.outW >= 1024 && h.ops.length === 1 && h.dup >= 2)), goal(L('Opened a result', 'Has obert un resultat', 'Has abierto un resultado'), (g, c) => c.flags.resultOpened)],
      },
      {
        title: L('Resizing is not upscaling', 'Redimensionar no és fer upscale', 'Redimensionar no es hacer upscale'),
        task: L('Put an Upscale Image By (lanczos, ×4) between VAE Decode and Save Image. Run and look at the 100% crop.', 'Posa un Upscale Image By (lanczos, ×4) entre VAE Decode i Save Image. Executa i mira el retall al 100%.', 'Pon un Upscale Image By (lanczos, ×4) entre VAE Decode y Save Image. Ejecuta y mira el recorte al 100%.'),
        concept: L('A 2048 × 2048 file is not a 2048 picture. Resizing (bilinear, bicubic, lanczos) <b>spreads the same pixels</b> over a bigger area: the 100% crop is blurry. With nearest-exact you get visible squares. The number that matters is not the size of the file but the <b>real detail</b>: how much of the picture was actually drawn at that size.', 'Un fitxer de 2048 × 2048 no és una imatge de 2048. Redimensionar (bilinear, bicubic, lanczos) <b>escampa els mateixos píxels</b> en una àrea més gran: el retall al 100% és borrós. Amb nearest-exact surten quadrets. El que compta no és la mida del fitxer sinó el <b>detall real</b>: quanta imatge s’ha dibuixat de veritat a aquella mida.', 'Un archivo de 2048 × 2048 no es una imagen de 2048. Redimensionar (bilinear, bicubic, lanczos) <b>esparce los mismos píxeles</b> en un área más grande: el recorte al 100% es borroso. Con nearest-exact salen cuadraditos. Lo que cuenta no es el tamaño del archivo sino el <b>detalle real</b>: cuánta imagen se ha dibujado de verdad a ese tamaño.'),
        how: [L('Drag from the IMAGE of VAE Decode, drop on the canvas and search <b>upscale image by</b>.', 'Arrossega des de la IMAGE de VAE Decode, deixa-la al llenç i cerca <b>upscale image by</b>.', 'Arrastra desde la IMAGE de VAE Decode, suéltala en el lienzo y busca <b>upscale image by</b>.'), L('upscale_method <b>lanczos</b>, scale_by <b>4</b>. Its IMAGE → Save Image.', 'upscale_method <b>lanczos</b>, scale_by <b>4</b>. La seva IMAGE → Save Image.', 'upscale_method <b>lanczos</b>, scale_by <b>4</b>. Su IMAGE → Save Image.'), L('Run and open the result: real detail 25%.', 'Executa i obre el resultat: detall real 25%.', 'Ejecuta y abre el resultado: detalle real 25%.')],
        note: L('Try nearest-exact too: the classic pixel-art look.', 'Prova també nearest-exact: l’aspecte clàssic de pixel art.', 'Prueba también nearest-exact: el aspecto clásico de pixel art.'),
        starter: () => G.base(), solution: () => G.scaleBy(),
        goals: [goal(L('Upscale Image By feeds Save Image', 'Upscale Image By alimenta Save Image', 'Upscale Image By alimenta Save Image'), g => N(g, 'SaveImage').some(s => from(g, s.id, 'images')?.type === 'ImageScaleBy')), goal(L('A 2048 px file from a 512 picture', 'Un fitxer de 2048 px a partir d’una imatge de 512', 'Un archivo de 2048 px a partir de una imagen de 512'), (g, c) => ran(c, h => h.outW >= 2048 && h.scaled.length && !h.modelUp)), goal(L('Opened it: how much real detail?', 'L’has obert: quant detall real té?', 'Lo has abierto: ¿cuánto detalle real tiene?'), (g, c) => c.flags.resultOpened)],
      },
    ],
  },
  {
    id: 'models', name: L('Upscale models', 'Models d’upscale', 'Modelos de upscale'), sub: L('ESRGAN · ×4 then ×0.5', 'ESRGAN · ×4 i ×0.5', 'ESRGAN · ×4 y ×0.5'),
    steps: [
      {
        title: L('Upscale with a model', 'Upscale amb un model', 'Upscale con un modelo'),
        task: L('Replace the resize with Load Upscale Model + Upscale Image (using Model) and compare the 100% crops.', 'Substitueix el redimensionat per Load Upscale Model + Upscale Image (using Model) i compara els retalls al 100%.', 'Sustituye el redimensionado por Load Upscale Model + Upscale Image (using Model) y compara los recortes al 100%.'),
        concept: L('Upscale models (ESRGAN and family) are small networks trained to turn small pictures into big ones. They rebuild <b>clean, sharp edges</b>, which resizing cannot. What they cannot do is invent the texture a sampler would draw: skin, sand, fabric look <b>smooth and a bit plastic</b> at 100%. Each model has a style: 4x-UltraSharp is crisp, RealESRGAN is softer and waxy.', 'Els models d’upscale (ESRGAN i família) són xarxes petites entrenades per convertir imatges petites en grans. Reconstrueixen <b>vores netes i nítides</b>, cosa que el redimensionat no pot fer. El que no poden fer és inventar la textura que dibuixaria un sampler: pell, sorra i roba es veuen <b>llises i una mica de plàstic</b> al 100%. Cada model té el seu estil: 4x-UltraSharp és nítid, RealESRGAN és més suau i encerat.', 'Los modelos de upscale (ESRGAN y familia) son redes pequeñas entrenadas para convertir imágenes pequeñas en grandes. Reconstruyen <b>bordes limpios y nítidos</b>, cosa que el redimensionado no puede hacer. Lo que no pueden hacer es inventar la textura que dibujaría un sampler: piel, arena y ropa se ven <b>lisas y un poco de plástico</b> al 100%. Cada modelo tiene su estilo: 4x-UltraSharp es nítido, RealESRGAN es más suave y encerado.'),
        how: [L('Run once as it is (lanczos ×4) to have something to compare.', 'Executa una vegada tal com està (lanczos ×4) per tenir amb què comparar.', 'Ejecuta una vez tal cual (lanczos ×4) para tener con qué comparar.'), L('Add <b>Load Upscale Model</b> (4x-UltraSharp) and <b>Upscale Image (using Model)</b>: VAE Decode → image, the loader → upscale_model, its IMAGE → Save Image.', 'Afegeix <b>Load Upscale Model</b> (4x-UltraSharp) i <b>Upscale Image (using Model)</b>: VAE Decode → image, el loader → upscale_model, la seva IMAGE → Save Image.', 'Añade <b>Load Upscale Model</b> (4x-UltraSharp) y <b>Upscale Image (using Model)</b>: VAE Decode → image, el loader → upscale_model, su IMAGE → Save Image.'), L('Run, then try RealESRGAN_x4plus.', 'Executa i després prova RealESRGAN_x4plus.', 'Ejecuta y luego prueba RealESRGAN_x4plus.')],
        note: L('Upscale models go in models/upscale_models. ComfyUI Manager › Model Manager can download the usual ones.', 'Els models d’upscale van a models/upscale_models. ComfyUI Manager › Model Manager pot descarregar els habituals.', 'Los modelos de upscale van en models/upscale_models. ComfyUI Manager › Model Manager puede descargar los habituales.'),
        starter: () => G.scaleBy(), solution: () => G.model(),
        goals: [goal(L('Compared with a plain resize', 'Comparat amb un redimensionat', 'Comparado con un redimensionado'), (g, c) => ran(c, h => h.scaled.length && !h.modelUp), true), goal(L('Upscale Image (using Model) gets its model', 'Upscale Image (using Model) rep el seu model', 'Upscale Image (using Model) recibe su modelo'), g => N(g, 'ImageUpscaleWithModel').some(n => from(g, n.id, 'upscale_model')?.type === 'UpscaleModelLoader')), goal(L('Saved a model upscale ×4', 'Has desat un upscale amb model ×4', 'Has guardado un upscale con modelo ×4'), (g, c) => ran(c, h => h.modelUp && h.outW >= 2048 && h.edge === 'sharp')), goal(L('Tried the RealESRGAN look', 'Has provat l’estil de RealESRGAN', 'Has probado el estilo de RealESRGAN'), (g, c) => ran(c, h => h.modelUp && h.edge === 'waxy'), true)],
      },
      {
        title: L('×4 with the model, then down to ×2', '×4 amb el model, i després baixa a ×2', '×4 con el modelo, y luego baja a ×2'),
        task: L('Get a 1024 × 1024 picture: model ×4 (2048), then Upscale Image By 0.5.', 'Aconsegueix una imatge de 1024 × 1024: model ×4 (2048) i després Upscale Image By 0.5.', 'Consigue una imagen de 1024 × 1024: modelo ×4 (2048) y luego Upscale Image By 0.5.'),
        concept: L('Most good upscale models are ×4, but you often want ×2 or ×1.5. The trick: upscale ×4 with the model and then <b>resize down</b> to the size you want. Going down never loses quality, and it also hides the slightly artificial look of the model: at 1024 the result is cleaner than the model’s 2048.', 'La majoria de bons models d’upscale són ×4, però sovint vols ×2 o ×1.5. El truc: amplia ×4 amb el model i després <b>redimensiona cap avall</b> a la mida que vols. Baixar mai perd qualitat, i a més amaga l’aspecte una mica artificial del model: a 1024 el resultat és més net que els 2048 del model.', 'La mayoría de buenos modelos de upscale son ×4, pero a menudo quieres ×2 o ×1.5. El truco: amplía ×4 con el modelo y luego <b>redimensiona hacia abajo</b> al tamaño que quieres. Bajar nunca pierde calidad, y además esconde el aspecto un poco artificial del modelo: a 1024 el resultado es más limpio que los 2048 del modelo.'),
        how: [L('After Upscale Image (using Model), add <b>Upscale Image By</b> with scale_by <b>0.5</b> (lanczos).', 'Després d’Upscale Image (using Model), afegeix <b>Upscale Image By</b> amb scale_by <b>0.5</b> (lanczos).', 'Después de Upscale Image (using Model), añade <b>Upscale Image By</b> con scale_by <b>0.5</b> (lanczos).'), L('Its IMAGE → Save Image. Run: 1024 × 1024.', 'La seva IMAGE → Save Image. Executa: 1024 × 1024.', 'Su IMAGE → Save Image. Ejecuta: 1024 × 1024.')],
        note: L('Upscale Image (exact width and height) does the same when you need a precise size, like 1920 × 1080.', 'Upscale Image (amplada i alçada exactes) fa el mateix quan necessites una mida precisa, com 1920 × 1080.', 'Upscale Image (ancho y alto exactos) hace lo mismo cuando necesitas un tamaño preciso, como 1920 × 1080.'),
        starter: () => G.model(), solution: G.modelHalf,
        goals: [goal(L('Model first, then a resize down', 'Primer el model, després un redimensionat cap avall', 'Primero el modelo, luego un redimensionado hacia abajo'), g => N(g, 'ImageScaleBy').some(n => from(g, n.id, 'image')?.type === 'ImageUpscaleWithModel' && n.widgets.scale_by < 1)), goal(L('Saved 1024 × 1024', 'Has desat 1024 × 1024', 'Has guardado 1024 × 1024'), (g, c) => ran(c, h => h.modelUp && h.outW === 1024 && h.outH === 1024))],
      },
    ],
  },
  {
    id: 'hires', name: L('Hires fix', 'Hires fix', 'Hires fix'), sub: L('A second pass adds detail', 'Una segona passada afegeix detall', 'Una segunda pasada añade detalle'),
    steps: [
      {
        title: L('Latent upscale + a second KSampler', 'Upscale latent + un segon KSampler', 'Upscale latente + un segundo KSampler'),
        task: L('Run this graph (latent upscaled and decoded straight away). Then add a second KSampler at denoise 0.5 between Upscale Latent By and VAE Decode.', 'Executa aquest graf (latent ampliat i descodificat directament). Després afegeix un segon KSampler amb denoise 0.5 entre Upscale Latent By i VAE Decode.', 'Ejecuta este grafo (latente ampliado y decodificado directamente). Luego añade un segundo KSampler con denoise 0.5 entre Upscale Latent By y VAE Decode.'),
        concept: L('Only a sampler adds detail. The <b>hires fix</b> uses that: generate at the model’s size (composition right), make the picture bigger, and run a <b>second KSampler</b> with denoise 0.4–0.6 at the big size. The composition comes from the first pass; the detail, from the second. Upscaling the latent is the quickest way, but an upscaled latent is pure blocks: it needs that second pass, with at least ~0.5 denoise.', 'Només un sampler afegeix detall. El <b>hires fix</b> ho aprofita: genera a la mida del model (composició bona), fes la imatge més gran i passa-hi un <b>segon KSampler</b> amb denoise 0.4–0.6 a la mida gran. La composició ve de la primera passada; el detall, de la segona. Ampliar el latent és la manera més ràpida, però un latent ampliat són blocs purs: necessita aquesta segona passada, amb com a mínim ~0.5 de denoise.', 'Solo un sampler añade detalle. El <b>hires fix</b> lo aprovecha: genera al tamaño del modelo (composición buena), haz la imagen más grande y pasa un <b>segundo KSampler</b> con denoise 0.4–0.6 al tamaño grande. La composición viene de la primera pasada; el detalle, de la segunda. Ampliar el latente es la forma más rápida, pero un latente ampliado son bloques puros: necesita esa segunda pasada, con al menos ~0.5 de denoise.'),
        how: [L('Run: the 100% crop is made of blocks.', 'Executa: el retall al 100% són blocs.', 'Ejecuta: el recorte al 100% son bloques.'), L('Select the KSampler and <kbd>Ctrl C</kbd> / <kbd>Ctrl Shift V</kbd>: a copy that keeps its input wires.', 'Selecciona el KSampler i <kbd>Ctrl C</kbd> / <kbd>Ctrl Shift V</kbd>: una còpia que conserva els cables d’entrada.', 'Selecciona el KSampler y <kbd>Ctrl C</kbd> / <kbd>Ctrl Shift V</kbd>: una copia que conserva los cables de entrada.'), L('Connect Upscale Latent By → its latent_image, its LATENT → VAE Decode. Denoise <b>0.5</b>. Run.', 'Connecta Upscale Latent By → el seu latent_image, el seu LATENT → VAE Decode. Denoise <b>0.5</b>. Executa.', 'Conecta Upscale Latent By → su latent_image, su LATENT → VAE Decode. Denoise <b>0.5</b>. Ejecuta.')],
        note: L('In other interfaces this is a checkbox called “Hires. fix”. In ComfyUI you see what it really is: two samplers.', 'En altres interfícies és una casella que es diu “Hires. fix”. A ComfyUI veus què és de veritat: dos samplers.', 'En otras interfaces es una casilla llamada “Hires. fix”. En ComfyUI ves lo que es de verdad: dos samplers.'),
        starter: () => G.latentRaw(), solution: () => G.hires(.5),
        goals: [goal(L('Saw an upscaled latent decoded without a second pass', 'Has vist un latent ampliat descodificat sense segona passada', 'Has visto un latente ampliado decodificado sin segunda pasada'), (g, c) => ran(c, h => h.latentUp && !h.passes.length)), goal(L('A second KSampler gets the upscaled latent', 'Un segon KSampler rep el latent ampliat', 'Un segundo KSampler recibe el latente ampliado'), g => N(g, 'KSampler').some(s => from(g, s.id, 'latent_image')?.type === 'LatentUpscaleBy')), goal(L('A clean 1024 picture with one person', 'Una imatge neta de 1024 amb una sola persona', 'Una imagen limpia de 1024 con una sola persona'), (g, c) => ran(c, h => h.latentUp && passIn(h, .4, .65) && h.edge === 'clean' && h.dup === 1))],
      },
      {
        title: L('The denoise window', 'La finestra del denoise', 'La ventana del denoise'),
        task: L('Run the second KSampler at denoise 0.3, then at 0.8, then find the right value again (0.45–0.6).', 'Executa el segon KSampler amb denoise 0.3, després 0.8, i torna a trobar el valor bo (0.45–0.6).', 'Ejecuta el segundo KSampler con denoise 0.3, luego 0.8, y vuelve a encontrar el valor bueno (0.45–0.6).'),
        concept: L('The second pass has a narrow window. <b>Too low</b>: the sampler cannot clean the blocks of the latent (a pixel upscale tolerates lower values, next step). <b>Too high</b>: it forgets the first picture and composes again at 1024, which is above the model’s size: <b>the extra people come back</b>. In between, it keeps the composition and redraws the detail. The window moves with the factor: ×1.5 tolerates more denoise than ×2.', 'La segona passada té una finestra estreta. <b>Massa baix</b>: el sampler no pot netejar els blocs del latent (un upscale de píxels tolera valors més baixos, pas següent). <b>Massa alt</b>: oblida la primera imatge i torna a compondre a 1024, que és més que la mida del model: <b>tornen les persones extra</b>. Al mig, conserva la composició i redibuixa el detall. La finestra es mou amb el factor: ×1.5 tolera més denoise que ×2.', 'La segunda pasada tiene una ventana estrecha. <b>Demasiado bajo</b>: el sampler no puede limpiar los bloques del latente (un upscale de píxeles tolera valores más bajos, paso siguiente). <b>Demasiado alto</b>: olvida la primera imagen y vuelve a componer a 1024, que es más que el tamaño del modelo: <b>vuelven las personas extra</b>. En medio, conserva la composición y redibuja el detalle. La ventana se mueve con el factor: ×1.5 tolera más denoise que ×2.'),
        how: [L('Second KSampler › denoise <b>0.3</b>, run: blocks are still there.', 'Segon KSampler › denoise <b>0.3</b>, executa: encara hi ha blocs.', 'Segundo KSampler › denoise <b>0.3</b>, ejecuta: todavía hay bloques.'), L('Denoise <b>0.8</b>, run: count the people.', 'Denoise <b>0.8</b>, executa: compta les persones.', 'Denoise <b>0.8</b>, ejecuta: cuenta las personas.'), L('Back to <b>0.5</b> or so.', 'Torna a <b>0.5</b> més o menys.', 'Vuelve a <b>0.5</b> más o menos.')],
        note: L('Use a fixed seed in both KSamplers while you compare, or every run is a different picture.', 'Fes servir un seed fix als dos KSamplers mentre compares, o cada execució serà una imatge diferent.', 'Usa un seed fijo en los dos KSamplers mientras comparas, o cada ejecución será una imagen distinta.'),
        starter: () => G.hires(.5), solution: () => G.hires(.55),
        goals: [goal(L('Denoise ≤ 0.3: blocks left', 'Denoise ≤ 0.3: queden blocs', 'Denoise ≤ 0.3: quedan bloques'), (g, c) => ran(c, h => h.latentUp && h.passes.some(p => p.d <= .3) && h.edge === 'blocky')), goal(L('Denoise ≥ 0.75: extra people', 'Denoise ≥ 0.75: persones de més', 'Denoise ≥ 0.75: personas de más'), (g, c) => ran(c, h => h.latentUp && h.passes.some(p => p.d >= .75) && h.dup >= 2)), goal(L('In the window: clean and one person', 'Dins la finestra: net i una sola persona', 'Dentro de la ventana: limpio y una sola persona'), (g, c) => ran(c, h => h.latentUp && passIn(h, .45, .62) && h.edge === 'clean' && h.dup === 1))],
      },
      {
        title: L('Hires fix in pixels', 'Hires fix en píxels', 'Hires fix en píxeles'),
        task: L('Build the pixel route: model ×4 → ×0.5 → VAE Encode → KSampler (denoise 0.35) → VAE Decode → Save.', 'Construeix la via de píxels: model ×4 → ×0.5 → VAE Encode → KSampler (denoise 0.35) → VAE Decode → Save.', 'Construye la vía de píxeles: modelo ×4 → ×0.5 → VAE Encode → KSampler (denoise 0.35) → VAE Decode → Save.'),
        concept: L('The second route upscales the <b>decoded picture</b> with an upscale model and encodes it again. It costs a decode and an encode more, but the second sampler starts from clean, sharp shapes instead of blocks: it needs less denoise (0.25–0.45), so it changes the picture less and keeps faces and details more faithful. Most professional workflows use this route.', 'La segona via amplia la <b>imatge descodificada</b> amb un model d’upscale i la torna a codificar. Costa un decode i un encode més, però el segon sampler parteix de formes netes i nítides en lloc de blocs: necessita menys denoise (0.25–0.45), i per tant canvia menys la imatge i és més fidel a cares i detalls. La majoria de workflows professionals fan servir aquesta via.', 'La segunda vía amplía la <b>imagen decodificada</b> con un modelo de upscale y la vuelve a codificar. Cuesta un decode y un encode más, pero el segundo sampler parte de formas limpias y nítidas en lugar de bloques: necesita menos denoise (0.25–0.45), y por tanto cambia menos la imagen y es más fiel a caras y detalles. La mayoría de workflows profesionales usan esta vía.'),
        how: [L('From the 512 VAE Decode: Upscale Image (using Model) → Upscale Image By 0.5.', 'Des del VAE Decode de 512: Upscale Image (using Model) → Upscale Image By 0.5.', 'Desde el VAE Decode de 512: Upscale Image (using Model) → Upscale Image By 0.5.'), L('<b>VAE Encode</b> (vae from Load Checkpoint) → latent_image of a second <b>KSampler</b> (denoise 0.35, same model and prompts).', '<b>VAE Encode</b> (vae de Load Checkpoint) → latent_image d’un segon <b>KSampler</b> (denoise 0.35, mateix model i prompts).', '<b>VAE Encode</b> (vae de Load Checkpoint) → latent_image de un segundo <b>KSampler</b> (denoise 0.35, mismo modelo y prompts).'), L('A second <b>VAE Decode</b> → Save Image. Run.', 'Un segon <b>VAE Decode</b> → Save Image. Executa.', 'Un segundo <b>VAE Decode</b> → Save Image. Ejecuta.')],
        note: L('Compare the face in the 100% crop with the latent route: same size, more faithful.', 'Compara la cara del retall al 100% amb la via latent: mateixa mida, més fidel.', 'Compara la cara del recorte al 100% con la vía latente: mismo tamaño, más fiel.'),
        starter: () => G.base(), solution: () => G.pixelHires(),
        goals: [goal(L('The second KSampler starts from a model upscale', 'El segon KSampler parteix d’un upscale amb model', 'El segundo KSampler parte de un upscale con modelo'), (g, c) => ran(c, h => h.modelUp && h.passes.length > 0 && h.ops.indexOf('model') < h.ops.indexOf('pass'))), goal(L('Denoise between 0.25 and 0.45', 'Denoise entre 0.25 i 0.45', 'Denoise entre 0.25 y 0.45'), (g, c) => ran(c, h => h.modelUp && passIn(h, .25, .45))), goal(L('Clean, detailed and one person', 'Net, amb detall i una sola persona', 'Limpio, con detalle y una sola persona'), (g, c) => ran(c, h => h.modelUp && passIn(h, .25, .45) && h.dup === 1 && h.tex >= .5 && h.edge !== 'blocky'))],
      },
    ],
  },
  {
    id: 'tiles', name: L('Tiled to 4K', 'Per tiles fins a 4K', 'Por tiles hasta 4K'), sub: L('Memory · seams · ghosts', 'Memòria · costures · fantasmes', 'Memoria · costuras · fantasmas'),
    steps: [
      {
        title: L('Out of memory', 'Sense memòria', 'Sin memoria'),
        task: L('Run this hires fix ×4 (2048 × 2048): it fails. Then make the 2048 picture with Ultimate SD Upscale instead.', 'Executa aquest hires fix ×4 (2048 × 2048): falla. Després fes la imatge de 2048 amb Ultimate SD Upscale.', 'Ejecuta este hires fix ×4 (2048 × 2048): falla. Luego haz la imagen de 2048 con Ultimate SD Upscale.'),
        concept: L('A KSampler holds the whole latent in the GPU at once, and memory grows faster than the size. The lab simulates an 8 GB card: around 1500 × 1500 is the limit. The answer is <b>tiles</b>: <b>Ultimate SD Upscale</b> (a custom node) upscales with a model, cuts the picture in 512 × 512 tiles and samples them one by one at low denoise. The size of the picture no longer matters, only the size of a tile.', 'Un KSampler té tot el latent a la GPU alhora, i la memòria creix més de pressa que la mida. El lab simula una targeta de 8 GB: el límit és d’uns 1500 × 1500. La resposta són els <b>tiles</b>: <b>Ultimate SD Upscale</b> (un custom node) amplia amb un model, talla la imatge en tiles de 512 × 512 i els mostreja un a un amb denoise baix. La mida de la imatge ja no importa, només la d’un tile.', 'Un KSampler tiene todo el latente en la GPU a la vez, y la memoria crece más deprisa que el tamaño. El lab simula una tarjeta de 8 GB: el límite es de unos 1500 × 1500. La respuesta son los <b>tiles</b>: <b>Ultimate SD Upscale</b> (un custom node) amplía con un modelo, corta la imagen en tiles de 512 × 512 y los muestrea uno a uno con denoise bajo. El tamaño de la imagen ya no importa, solo el de un tile.'),
        how: [L('Run: <b>torch.OutOfMemoryError</b>.', 'Executa: <b>torch.OutOfMemoryError</b>.', 'Ejecuta: <b>torch.OutOfMemoryError</b>.'), L('Add <b>Ultimate SD Upscale</b>: image from the first VAE Decode, model, positive, negative, vae, and a Load Upscale Model. upscale_by <b>4</b>, denoise <b>0.3</b>.', 'Afegeix <b>Ultimate SD Upscale</b>: image del primer VAE Decode, model, positive, negative, vae i un Load Upscale Model. upscale_by <b>4</b>, denoise <b>0.3</b>.', 'Añade <b>Ultimate SD Upscale</b>: image del primer VAE Decode, model, positive, negative, vae y un Load Upscale Model. upscale_by <b>4</b>, denoise <b>0.3</b>.'), L('Its IMAGE → Save Image (delete or bypass the failing branch). Run.', 'La seva IMAGE → Save Image (esborra o fes bypass de la branca que falla). Executa.', 'Su IMAGE → Save Image (borra o haz bypass de la rama que falla). Ejecuta.')],
        note: L('Install it with ComfyUI Manager: search “Ultimate SD Upscale”. In the log you see one sampling per tile: 16 tiles for 2048 × 2048.', 'Instal·la’l amb ComfyUI Manager: cerca “Ultimate SD Upscale”. Al log veuràs un mostreig per tile: 16 tiles per a 2048 × 2048.', 'Instálalo con ComfyUI Manager: busca “Ultimate SD Upscale”. En el log verás un muestreo por tile: 16 tiles para 2048 × 2048.'),
        starter: () => G.hires(.5, 4), solution: () => G.usdu(),
        goals: [goal(L('Saw the out of memory error', 'Has vist l’error de memòria', 'Has visto el error de memoria'), (g, c) => c.flags.rt_oom), goal(L('Ultimate SD Upscale has its six inputs', 'Ultimate SD Upscale té les sis entrades', 'Ultimate SD Upscale tiene sus seis entradas'), g => N(g, 'UltimateSDUpscale').some(n => ['image', 'model', 'positive', 'negative', 'vae', 'upscale_model'].every(i => into(g, n.id, i)))), goal(L('Saved a 2048 px picture made in tiles', 'Has desat una imatge de 2048 px feta per tiles', 'Has guardado una imagen de 2048 px hecha por tiles'), (g, c) => ran(c, h => h.usdu && h.outW >= 2048 && h.usdu.tiles > 1))],
      },
      {
        title: L('No seams, no ghosts', 'Sense costures ni fantasmes', 'Sin costuras ni fantasmas'),
        task: L('This Ultimate SD Upscale has ghosts and seams. Run it, then fix it: denoise ≤ 0.35, mask_blur ≥ 4 and tile_padding ≥ 16.', 'Aquest Ultimate SD Upscale té fantasmes i costures. Executa’l i arregla’l: denoise ≤ 0.35, mask_blur ≥ 4 i tile_padding ≥ 16.', 'Este Ultimate SD Upscale tiene fantasmas y costuras. Ejecútalo y arréglalo: denoise ≤ 0.35, mask_blur ≥ 4 y tile_padding ≥ 16.'),
        concept: L('The two classic tile problems. <b>Ghosts</b>: each tile is sampled with the whole prompt (“a woman on the beach”) but only sees its piece of sky or sand; with too much denoise, it draws a small woman in it. <b>Seams</b>: tiles sampled separately do not match at the edges. mask_blur blends each tile into its neighbours and tile_padding gives it context around; seam_fix_mode adds a pass over the joins.', 'Els dos problemes clàssics dels tiles. <b>Fantasmes</b>: cada tile es mostreja amb tot el prompt (“a woman on the beach”) però només veu el seu tros de cel o de sorra; amb massa denoise, hi dibuixa una dona petita. <b>Costures</b>: els tiles mostrejats per separat no lliguen a les vores. mask_blur fon cada tile amb els veïns i tile_padding li dona context al voltant; seam_fix_mode afegeix una passada sobre les unions.', 'Los dos problemas clásicos de los tiles. <b>Fantasmas</b>: cada tile se muestrea con todo el prompt (“a woman on the beach”) pero solo ve su trozo de cielo o de arena; con demasiado denoise, dibuja una mujer pequeña en él. <b>Costuras</b>: los tiles muestreados por separado no encajan en los bordes. mask_blur funde cada tile con sus vecinos y tile_padding le da contexto alrededor; seam_fix_mode añade una pasada sobre las uniones.'),
        how: [L('Run: look for the small people and the grid.', 'Executa: busca les persones petites i la quadrícula.', 'Ejecuta: busca las personas pequeñas y la cuadrícula.'), L('denoise <b>0.3</b>, mask_blur <b>8</b>, tile_padding <b>32</b> (the defaults).', 'denoise <b>0.3</b>, mask_blur <b>8</b>, tile_padding <b>32</b> (els valors per defecte).', 'denoise <b>0.3</b>, mask_blur <b>8</b>, tile_padding <b>32</b> (los valores por defecto).'), L('Run again.', 'Torna a executar.', 'Vuelve a ejecutar.')],
        note: L('Another fix for ghosts: a prompt for the tiles without the subject (“detailed, sharp, high quality”). Here you keep the full prompt and control it with denoise.', 'Una altra solució per als fantasmes: un prompt per als tiles sense el subjecte (“detailed, sharp, high quality”). Aquí mantens el prompt complet i ho controles amb el denoise.', 'Otra solución para los fantasmas: un prompt para los tiles sin el sujeto (“detailed, sharp, high quality”). Aquí mantienes el prompt completo y lo controlas con el denoise.'),
        starter: () => G.usdu({ denoise: .6, mask_blur: 0, tile_padding: 0 }), solution: () => G.usdu(),
        goals: [goal(L('Saw ghosts and seams', 'Has vist fantasmes i costures', 'Has visto fantasmas y costuras'), (g, c) => ran(c, h => h.usdu && (h.ghosts > 0 || h.seams > .3)), true), goal(L('No ghosts', 'Cap fantasma', 'Ningún fantasma'), (g, c) => ran(c, h => h.usdu && h.ghosts === 0 && h.usdu.d >= .15)), goal(L('No seams', 'Cap costura', 'Ninguna costura'), (g, c) => ran(c, h => h.usdu && h.ghosts === 0 && h.seams < .2 && h.usdu.d >= .15))],
      },
      {
        title: L('ControlNet Tile: more denoise, same picture', 'ControlNet Tile: més denoise, mateixa imatge', 'ControlNet Tile: más denoise, misma imagen'),
        task: L('Add a ControlNet Tile to the conditioning of Ultimate SD Upscale and run at denoise 0.5 without ghosts.', 'Afegeix una ControlNet Tile al conditioning d’Ultimate SD Upscale i executa amb denoise 0.5 sense fantasmes.', 'Añade una ControlNet Tile al conditioning de Ultimate SD Upscale y ejecuta con denoise 0.5 sin fantasmas.'),
        concept: L('Low denoise keeps the picture but adds little detail. <b>ControlNet Tile</b> is trained to keep each tile faithful to the picture underneath: with it you can use 0.5–0.7 denoise, much more new texture, and the tiles still do not invent people. It is the standard partner of tiled upscaling.', 'Un denoise baix conserva la imatge però afegeix poc detall. La <b>ControlNet Tile</b> està entrenada per mantenir cada tile fidel a la imatge de sota: amb ella pots fer servir 0.5–0.7 de denoise, molta més textura nova, i els tiles igualment no s’inventen persones. És la parella habitual de l’upscale per tiles.', 'Un denoise bajo conserva la imagen pero añade poco detalle. La <b>ControlNet Tile</b> está entrenada para mantener cada tile fiel a la imagen de debajo: con ella puedes usar 0.5–0.7 de denoise, mucha más textura nueva, y los tiles igualmente no se inventan personas. Es la pareja habitual del upscale por tiles.'),
        how: [L('<b>Load ControlNet Model</b>: control_v11f1e_sd15_tile.pth.', '<b>Load ControlNet Model</b>: control_v11f1e_sd15_tile.pth.', '<b>Load ControlNet Model</b>: control_v11f1e_sd15_tile.pth.'), L('<b>Apply ControlNet</b>: prompts in, image = the 512 picture, strength 0.8. Its positive and negative → Ultimate SD Upscale.', '<b>Apply ControlNet</b>: entren els prompts, image = la imatge de 512, strength 0.8. El seu positive i negative → Ultimate SD Upscale.', '<b>Apply ControlNet</b>: entran los prompts, image = la imagen de 512, strength 0.8. Su positive y negative → Ultimate SD Upscale.'), L('denoise <b>0.5</b>, run.', 'denoise <b>0.5</b>, executa.', 'denoise <b>0.5</b>, ejecuta.')],
        note: L('The tile model is only for SD 1.5. SDXL and Flux have their own tile ControlNets (or union models with a tile mode).', 'El model tile és només per a SD 1.5. SDXL i Flux tenen les seves ControlNets tile (o models union amb mode tile).', 'El modelo tile es solo para SD 1.5. SDXL y Flux tienen sus ControlNets tile (o modelos union con modo tile).'),
        starter: () => G.usdu(), solution: () => G.usduTile(.5),
        goals: [goal(L('Ultimate SD Upscale gets a ControlNet Tile', 'Ultimate SD Upscale rep una ControlNet Tile', 'Ultimate SD Upscale recibe una ControlNet Tile'), (g, c) => ran(c, h => h.usdu?.ctl)), goal(L('Denoise ≥ 0.45 without ghosts', 'Denoise ≥ 0.45 sense fantasmes', 'Denoise ≥ 0.45 sin fantasmas'), (g, c) => ran(c, h => h.usdu?.ctl && h.usdu.d >= .45 && h.ghosts === 0 && h.seams < .2)), goal(L('More texture than at 0.3', 'Més textura que a 0.3', 'Más textura que a 0.3'), (g, c) => ran(c, h => h.usdu?.ctl && h.usdu.d >= .45 && h.tex >= .8))],
      },
    ],
  },
  {
    id: 'detail', name: L('Detailers', 'Detailers', 'Detailers'), sub: L('Faces · the 4K pipeline', 'Cares · el pipeline a 4K', 'Caras · el pipeline a 4K'),
    steps: [
      {
        title: L('Small faces', 'Cares petites', 'Caras pequeñas'),
        task: L('Run the wide shot and look at the face at 100%. Then add an UltralyticsDetectorProvider (face) and a FaceDetailer before Save Image.', 'Executa el pla general i mira la cara al 100%. Després afegeix un UltralyticsDetectorProvider (face) i un FaceDetailer abans de Save Image.', 'Ejecuta el plano general y mira la cara al 100%. Luego añade un UltralyticsDetectorProvider (face) y un FaceDetailer antes de Save Image.'),
        concept: L('In a wide shot a face is 25–30 pixels: the model cannot draw eyes and a mouth with so little room, and they melt. A <b>detailer</b> fixes this automatically: a detector finds the faces, each one is cropped with some context, scaled up to <b>guide_size</b> (512), inpainted at that size and pasted back. It is crop and stitch with automatic masks.', 'En un pla general una cara fa 25–30 píxels: el model no pot dibuixar ulls i boca amb tan poc espai, i es fonen. Un <b>detailer</b> ho arregla automàticament: un detector troba les cares, cadascuna es retalla amb una mica de context, s’escala a <b>guide_size</b> (512), s’hi fa inpaint a aquella mida i es torna a enganxar. És el crop and stitch amb màscares automàtiques.', 'En un plano general una cara mide 25–30 píxeles: el modelo no puede dibujar ojos y boca con tan poco espacio, y se funden. Un <b>detailer</b> lo arregla automáticamente: un detector encuentra las caras, cada una se recorta con algo de contexto, se escala a <b>guide_size</b> (512), se le hace inpaint a ese tamaño y se vuelve a pegar. Es el crop and stitch con máscaras automáticas.'),
        how: [L('Run and look at the 100% crop.', 'Executa i mira el retall al 100%.', 'Ejecuta y mira el recorte al 100%.'), L('Add <b>UltralyticsDetectorProvider</b> (bbox/face_yolov8m.pt) and <b>FaceDetailer</b>: image from VAE Decode, model, clip, vae, positive, negative, and BBOX_DETECTOR → bbox_detector.', 'Afegeix <b>UltralyticsDetectorProvider</b> (bbox/face_yolov8m.pt) i <b>FaceDetailer</b>: image de VAE Decode, model, clip, vae, positive, negative, i BBOX_DETECTOR → bbox_detector.', 'Añade <b>UltralyticsDetectorProvider</b> (bbox/face_yolov8m.pt) y <b>FaceDetailer</b>: image de VAE Decode, model, clip, vae, positive, negative, y BBOX_DETECTOR → bbox_detector.'), L('Its <b>image</b> → Save Image. Run.', 'La seva <b>image</b> → Save Image. Executa.', 'Su <b>image</b> → Save Image. Ejecuta.')],
        note: L('FaceDetailer is in the Impact Pack (install with ComfyUI Manager). cropped_refined shows the face it redrew.', 'FaceDetailer és a l’Impact Pack (instal·la’l amb ComfyUI Manager). cropped_refined mostra la cara que ha redibuixat.', 'FaceDetailer está en el Impact Pack (instálalo con ComfyUI Manager). cropped_refined muestra la cara que ha redibujado.'),
        starter: () => G.base(WIDE), solution: () => G.detailer(),
        goals: [goal(L('Saw the small face melt', 'Has vist com es fon la cara petita', 'Has visto cómo se funde la cara pequeña'), (g, c) => ran(c, h => h.wide && !h.detailer && h.faceQ !== null && h.faceQ < .4), true), goal(L('FaceDetailer gets a face detector', 'FaceDetailer rep un detector de cares', 'FaceDetailer recibe un detector de caras'), g => N(g, 'FaceDetailer').some(n => from(g, n.id, 'bbox_detector')?.widgets.model_name?.includes('face'))), goal(L('A face found and redrawn', 'Una cara trobada i redibuixada', 'Una cara encontrada y redibujada'), (g, c) => ran(c, h => h.detailer && h.detected > 0 && h.faceQ >= .75))],
      },
      {
        title: L('Detailer settings', 'Paràmetres del detailer', 'Parámetros del detailer'),
        task: L('Try a denoise of 0.8 and a bbox_threshold of 0.8, see what happens, and go back to good values.', 'Prova un denoise de 0.8 i un bbox_threshold de 0.8, mira què passa i torna a valors bons.', 'Prueba un denoise de 0.8 y un bbox_threshold de 0.8, mira qué pasa y vuelve a valores buenos.'),
        concept: L('Two settings decide everything. <b>denoise</b>: 0.35–0.5 fixes the face and keeps the person; 0.7 or more draws <i>another</i> face (different hair, eyes, age). <b>bbox_threshold</b>: the detector’s minimum confidence. Small, side or blurred faces get low scores: with a high threshold nothing is found and nothing changes, without any error. If a detailer “does nothing”, lower the threshold first.', 'Dos paràmetres ho decideixen tot. <b>denoise</b>: 0.35–0.5 arregla la cara i conserva la persona; 0.7 o més dibuixa <i>una altra</i> cara (cabell, ulls, edat diferents). <b>bbox_threshold</b>: la confiança mínima del detector. Les cares petites, de perfil o borroses tenen puntuacions baixes: amb un llindar alt no es troba res i no canvia res, sense cap error. Si un detailer “no fa res”, primer baixa el llindar.', 'Dos parámetros lo deciden todo. <b>denoise</b>: 0.35–0.5 arregla la cara y conserva la persona; 0.7 o más dibuja <i>otra</i> cara (pelo, ojos, edad distintos). <b>bbox_threshold</b>: la confianza mínima del detector. Las caras pequeñas, de perfil o borrosas tienen puntuaciones bajas: con un umbral alto no se encuentra nada y no cambia nada, sin ningún error. Si un detailer “no hace nada”, primero baja el umbral.'),
        how: [L('FaceDetailer › denoise <b>0.8</b>, run: who is that?', 'FaceDetailer › denoise <b>0.8</b>, executa: qui és aquesta?', 'FaceDetailer › denoise <b>0.8</b>, ejecuta: ¿quién es esa?'), L('denoise 0.45, bbox_threshold <b>0.8</b>, run: “faces found: 0”.', 'denoise 0.45, bbox_threshold <b>0.8</b>, executa: “faces found: 0”.', 'denoise 0.45, bbox_threshold <b>0.8</b>, ejecuta: “faces found: 0”.'), L('Back to threshold 0.5 and denoise 0.35–0.5.', 'Torna a threshold 0.5 i denoise 0.35–0.5.', 'Vuelve a threshold 0.5 y denoise 0.35–0.5.')],
        note: L('For hands use hand_yolov8 in a second detailer. Hands are harder: expect to need more than one try.', 'Per a les mans fes servir hand_yolov8 en un segon detailer. Les mans costen més: compta amb més d’un intent.', 'Para las manos usa hand_yolov8 en un segundo detailer. Las manos cuestan más: cuenta con más de un intento.'),
        starter: () => G.detailer(), solution: () => G.detailer({ denoise: .4 }),
        goals: [goal(L('Denoise ≥ 0.7: another person', 'Denoise ≥ 0.7: una altra persona', 'Denoise ≥ 0.7: otra persona'), (g, c) => ran(c, h => h.detailer && h.detailer.d >= .7 && h.faceVar > 0)), goal(L('Threshold too high: nothing found', 'Llindar massa alt: no troba res', 'Umbral demasiado alto: no encuentra nada'), (g, c) => ran(c, h => h.detailer && h.detected === 0)), goal(L('Good values: found, fixed, same person', 'Valors bons: la troba, l’arregla i és la mateixa persona', 'Valores buenos: la encuentra, la arregla y es la misma persona'), (g, c) => ran(c, h => h.detailer && h.detected > 0 && h.detailer.d >= .3 && h.detailer.d <= .55 && h.faceQ >= .75 && !h.faceVar))],
      },
      {
        title: L('The full pipeline to 4K', 'El pipeline complet fins a 4K', 'El pipeline completo hasta 4K'),
        task: L('From this hires fix (1024), add a FaceDetailer and then Ultimate SD Upscale ×4: save a picture at least 3840 px wide, clean at 100%.', 'A partir d’aquest hires fix (1024), afegeix un FaceDetailer i després Ultimate SD Upscale ×4: desa una imatge d’almenys 3840 px d’amplada, neta al 100%.', 'A partir de este hires fix (1024), añade un FaceDetailer y luego Ultimate SD Upscale ×4: guarda una imagen de al menos 3840 px de ancho, limpia al 100%.'),
        concept: L('Everything in order, the way a real 4K workflow is built: <b>1)</b> generate at the model’s size (composition); <b>2)</b> hires fix ×2 (detail at 1024); <b>3)</b> detailer (faces at their best while they are still small enough to fix cheaply); <b>4)</b> tiled upscale ×4 with low denoise (texture at 4096). Each step does one job. The order matters: the detailer works better before the big upscale, and the upscale keeps what the detailer fixed.', 'Tot en ordre, com es construeix un workflow 4K de veritat: <b>1)</b> genera a la mida del model (composició); <b>2)</b> hires fix ×2 (detall a 1024); <b>3)</b> detailer (cares al màxim mentre encara són prou petites per arreglar-les barat); <b>4)</b> upscale per tiles ×4 amb denoise baix (textura a 4096). Cada pas fa una feina. L’ordre importa: el detailer funciona millor abans de l’upscale gran, i l’upscale conserva el que el detailer ha arreglat.', 'Todo en orden, como se construye un workflow 4K de verdad: <b>1)</b> genera al tamaño del modelo (composición); <b>2)</b> hires fix ×2 (detalle a 1024); <b>3)</b> detailer (caras al máximo mientras aún son lo bastante pequeñas para arreglarlas barato); <b>4)</b> upscale por tiles ×4 con denoise bajo (textura a 4096). Cada paso hace un trabajo. El orden importa: el detailer funciona mejor antes del upscale grande, y el upscale conserva lo que el detailer ha arreglado.'),
        how: [L('VAE Decode (1024) → <b>FaceDetailer</b> (with its detector).', 'VAE Decode (1024) → <b>FaceDetailer</b> (amb el seu detector).', 'VAE Decode (1024) → <b>FaceDetailer</b> (con su detector).'), L('FaceDetailer image → <b>Ultimate SD Upscale</b> ×4, denoise 0.3 (or 0.5 with ControlNet Tile).', 'image de FaceDetailer → <b>Ultimate SD Upscale</b> ×4, denoise 0.3 (o 0.5 amb ControlNet Tile).', 'image de FaceDetailer → <b>Ultimate SD Upscale</b> ×4, denoise 0.3 (o 0.5 con ControlNet Tile).'), L('→ Save Image. Run and open it: 4096 × 4096.', '→ Save Image. Executa i obre-la: 4096 × 4096.', '→ Save Image. Ejecuta y ábrela: 4096 × 4096.')],
        note: L('Save it as a workflow (<kbd>Ctrl S</kbd>): it is your 4K template. For a 16:9 picture, start at 768 × 432 (or 1344 × 768 with SDXL).', 'Desa’l com a workflow (<kbd>Ctrl S</kbd>): és la teva plantilla 4K. Per a una imatge 16:9, comença a 768 × 432 (o 1344 × 768 amb SDXL).', 'Guárdalo como workflow (<kbd>Ctrl S</kbd>): es tu plantilla 4K. Para una imagen 16:9, empieza a 768 × 432 (o 1344 × 768 con SDXL).'),
        starter: G.fullStart, solution: G.full,
        goals: [goal(L('Hires fix, then detailer, then tiles', 'Hires fix, després detailer, després tiles', 'Hires fix, luego detailer, luego tiles'), (g, c) => ran(c, h => h.passes.length > 0 && h.ops.indexOf('pass') < h.ops.indexOf('detailer') && h.ops.indexOf('detailer') < h.ops.indexOf('usdu'))), goal(L('At least 3840 px wide', 'Com a mínim 3840 px d’amplada', 'Al menos 3840 px de ancho'), (g, c) => ran(c, h => h.outW >= 3840 && h.usdu)), goal(L('Clean at 100%: one person, a good face, no ghosts or seams', 'Net al 100%: una persona, bona cara, sense fantasmes ni costures', 'Limpio al 100%: una persona, buena cara, sin fantasmas ni costuras'), (g, c) => ran(c, h => h.outW >= 3840 && h.dup === 1 && h.faceQ >= .75 && !h.faceVar && h.ghosts === 0 && h.seams < .2 && h.edge !== 'blocky')), goal(L('Saved the workflow', 'Has desat el workflow', 'Has guardado el workflow'), (g, c) => c.flags.saved, true)],
      },
    ],
  },
];

export const TEMPLATES = [
  { id: 'hires-latent', name: L('Hires fix (latent)', 'Hires fix (latent)', 'Hires fix (latente)'), make: () => G.hires(.55) },
  { id: 'hires-pixel', name: L('Hires fix (upscale model)', 'Hires fix (model d’upscale)', 'Hires fix (modelo de upscale)'), make: () => G.pixelHires() },
  { id: 'usdu', name: L('Ultimate SD Upscale + ControlNet Tile', 'Ultimate SD Upscale + ControlNet Tile', 'Ultimate SD Upscale + ControlNet Tile'), make: () => G.usduTile(.5) },
  { id: 'detailer', name: L('FaceDetailer', 'FaceDetailer', 'FaceDetailer'), make: () => G.detailer({ denoise: .4 }) },
  { id: '4k', name: L('4K pipeline', 'Pipeline 4K', 'Pipeline 4K'), make: G.full },
];
export { G as GRAPHS, UPSCALERS };
