// Carrot Revolt Labs · Sampling & Prompting Lab · stages, steps and live checklists.
// It runs on the ComfyUI Lab interface (../comfyui/app.js) and adds its own nodes and simulator (./nodes.js).
import { defaultGraph, makeNode, makeLink, connect } from '../comfyui/engine.js';
import { historyExtra as hx } from './nodes.js';
export const L = (en, ca, es) => ({ en, ca, es });

export const META = { key: 'carrot-revolt-comfy-sampling:', title: 'Sampling & Prompting Lab', label: 'GENERATIVE IMAGE / COMFYUI · 06' };
export const historyExtra = hx;

/* ── Graph helpers ── */
const N = (g, type) => g.nodes.filter(n => n.type === type && n.mode === 0);
const from = (g, id, input) => { const l = g.links.find(x => x.to === id && x.input === input); return l ? g.nodes.find(n => n.id === l.from) : null; };
const goal = (text, test, optional = false) => ({ text, test, optional });
const add = (g, ...nodes) => { g.nodes.push(...nodes); return g; };
const wire = (g, list) => { for (const l of list) connect(g, makeLink(...l)); return g; };
const set = (g, id, k, v) => { g.nodes.find(n => n.id === id).widgets[k] = v; return g; };
const move = (g, id, x, y) => { const n = g.nodes.find(n => n.id === id); n.x = x; n.y = y; return g; };
const drop = (g, id) => { g.nodes = g.nodes.filter(n => n.id !== id); g.links = g.links.filter(l => l.from !== id && l.to !== id); return g; };
const runs = c => c.history.filter(h => h.layoutKey);
const ran = (c, f) => runs(c).some(f);
const SEED = 156680208700286;
const LONG = 'masterpiece, best quality, highly detailed, sharp focus, soft light, golden hour, beautiful colours, cinematic composition, depth of field, film grain, rich textures, natural light, professional photography, award winning, intricate details, warm tones, gentle shadows, wide angle, high resolution, crisp, clean, elegant, calm mood, atmospheric, vivid, balanced, harmonious, artstation, trending, 8k, ultra detailed, realistic, fine art, painterly, smooth gradients, studio quality, a cat sitting in a landscape';

/* ── Starters and solutions ── */
const G = {
  base: (text = 'a cat sitting in a landscape, detailed', neg = 'text, watermark', w = {}) => { const g = defaultGraph(); set(g, 'pos', 'text', text); set(g, 'neg', 'text', neg); set(g, 'sampler', 'control_after_generate', 'fixed'); for (const [k, v] of Object.entries(w)) set(g, 'sampler', k, v); return g; },
  adv: ({ leftover = 'enable', addNoise = 'disable', start2 = 20, model2 = 'anything_v5.safetensors' } = {}) => {
    const g = drop(G.base('a cat sitting in a landscape, detailed'), 'sampler'); move(g, 'decode', 1620, 188); move(g, 'save', 1860, 189);
    const common = { noise_seed: SEED, steps: 30, cfg: 7, sampler_name: 'dpmpp_2m', scheduler: 'karras' };
    add(g, makeNode('KSamplerAdvanced', 863, 186, { ...common, end_at_step: 20, return_with_leftover_noise: leftover }, 'a1'), makeNode('KSamplerAdvanced', 1240, 186, { ...common, add_noise: addNoise, start_at_step: start2 }, 'a2'), makeNode('CheckpointLoaderSimple', 26, 700, { ckpt_name: model2 }, 'ckpt2'));
    return wire(g, [['ckpt', 0, 'a1', 'model'], ['pos', 0, 'a1', 'positive'], ['neg', 0, 'a1', 'negative'], ['latent', 0, 'a1', 'latent_image'], ['ckpt2', 0, 'a2', 'model'], ['pos', 0, 'a2', 'positive'], ['neg', 0, 'a2', 'negative'], ['a1', 0, 'a2', 'latent_image'], ['a2', 0, 'decode', 'samples']]);
  },
  sched: (split = .35) => {
    const g = G.base('a lighthouse on the beach, sunset'); move(g, 'sampler', 1240, 186); move(g, 'decode', 1600, 188); move(g, 'save', 1850, 189);
    add(g, makeNode('CLIPTextEncode', 413, -260, { text: 'red, watercolor, detailed' }, 'p2'), makeNode('ConditioningSetTimestepRange', 863, -80, { start: 0, end: split }, 't1'), makeNode('ConditioningSetTimestepRange', 863, -260, { start: split, end: 1 }, 't2'), makeNode('ConditioningCombine', 863, 60, {}, 'cc'));
    return wire(g, [['ckpt', 1, 'p2', 'clip'], ['pos', 0, 't1', 'conditioning'], ['p2', 0, 't2', 'conditioning'], ['t1', 0, 'cc', 'conditioning_1'], ['t2', 0, 'cc', 'conditioning_2'], ['cc', 0, 'sampler', 'positive']]);
  },
};

export const UI = {
  headline: L('The same graph, <span>better choices.</span>', 'El mateix graf, <span>millors decisions.</span>', 'El mismo grafo, <span>mejores decisiones.</span>'),
  lead: L('What the KSampler’s menus really change, and how to write prompts that work: models that are not installed, negative embeddings, samplers that converge and samplers that never settle, schedulers and how many steps are enough, two samplers sharing the steps, prompts that act only at the start or the end, weights, dynamic prompts, long prompts, and how to find and keep a good seed.', 'Què canvien de veritat els menús del KSampler, i com escriure prompts que funcionin: models que no tens instal·lats, embeddings negatius, samplers que convergeixen i samplers que no s’aturen mai, schedulers i quants steps calen, dos samplers que es reparteixen els steps, prompts que només actuen al principi o al final, pesos, prompts dinàmics, prompts llargs, i com trobar i conservar un bon seed.', 'Qué cambian de verdad los menús del KSampler, y cómo escribir prompts que funcionen: modelos que no tienes instalados, embeddings negativos, samplers que convergen y samplers que nunca se paran, schedulers y cuántos steps hacen falta, dos samplers que se reparten los steps, prompts que solo actúan al principio o al final, pesos, prompts dinámicos, prompts largos, y cómo encontrar y conservar un buen seed.'),
  loraVsCn: L('Which sampler?', 'Quin sampler?', '¿Qué sampler?'),
};
const T3 = (h, rows, foot) => `<table class="c-cmp"><tr><th></th><th>${h[0]}</th><th>${h[1]}</th></tr>${rows.map(r => `<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</table><p>${foot}</p>`;
UI.loraVsCnBody = L(
  T3(['Steps', 'Note'], [['<b>euler</b>', '20–30', 'simple, reliable'], ['<b>dpmpp_2m</b> + karras', '20–25', 'the usual default'], ['<b>euler_ancestral</b>, *_sde', '25–40', 'never settles: each step count is another picture'], ['<b>lcm</b>', '4–8', 'only with LCM models or LoRAs']], 'Ancestral and SDE samplers add new noise every step: more variety, less control.'),
  T3(['Steps', 'Nota'], [['<b>euler</b>', '20–30', 'simple, fiable'], ['<b>dpmpp_2m</b> + karras', '20–25', 'l’opció per defecte habitual'], ['<b>euler_ancestral</b>, *_sde', '25–40', 'no s’atura mai: cada nombre de steps és una altra imatge'], ['<b>lcm</b>', '4–8', 'només amb models o LoRAs LCM']], 'Els samplers ancestrals i SDE afegeixen soroll nou a cada step: més varietat, menys control.'),
  T3(['Steps', 'Nota'], [['<b>euler</b>', '20–30', 'simple, fiable'], ['<b>dpmpp_2m</b> + karras', '20–25', 'la opción por defecto habitual'], ['<b>euler_ancestral</b>, *_sde', '25–40', 'nunca se para: cada número de steps es otra imagen'], ['<b>lcm</b>', '4–8', 'solo con modelos o LoRAs LCM']], 'Los samplers ancestrales y SDE añaden ruido nuevo en cada step: más variedad, menos control.'));

export const DOCS = {
  KSamplerAdvanced: { short: L('A KSampler that can run only part of the steps.', 'Un KSampler que pot fer només una part dels steps.', 'Un KSampler que puede hacer solo una parte de los steps.'), long: L('start_at_step / end_at_step choose the slice of the schedule. To chain two: the first returns with leftover noise, the second does not add noise and starts where the first ended.', 'start_at_step / end_at_step trien el tram del calendari. Per encadenar-ne dos: el primer torna amb soroll sobrant, el segon no afegeix soroll i comença on va acabar el primer.', 'start_at_step / end_at_step eligen el tramo del calendario. Para encadenar dos: el primero devuelve con ruido sobrante, el segundo no añade ruido y empieza donde acabó el primero.'), widgets: { add_noise: L('disable when it continues another sampler', 'disable quan continua un altre sampler', 'disable cuando continúa otro sampler'), return_with_leftover_noise: L('enable when another sampler continues', 'enable quan un altre sampler continua', 'enable cuando otro sampler continúa'), start_at_step: L('first step it runs', 'primer step que fa', 'primer step que hace'), end_at_step: L('step where it stops (10000 = to the end)', 'step on s’atura (10000 = fins al final)', 'step donde se para (10000 = hasta el final)') } },
  ConditioningSetTimestepRange: { short: L('Makes a prompt act only during part of the steps.', 'Fa que un prompt actuï només durant una part dels steps.', 'Hace que un prompt actúe solo durante una parte de los steps.'), long: L('0 is the first step and 1 the last. Early steps decide shapes and layout, late steps colours, textures and style. Combine two ranges to compose with one prompt and finish with another.', '0 és el primer step i 1 l’últim. Els primers steps decideixen formes i composició, els últims colors, textures i estil. Combina dos trams per compondre amb un prompt i acabar amb un altre.', '0 es el primer step y 1 el último. Los primeros steps deciden formas y composición, los últimos colores, texturas y estilo. Combina dos tramos para componer con un prompt y acabar con otro.') },
  ConditioningCombine: { short: L('Joins two conditionings.', 'Uneix dos conditionings.', 'Une dos conditionings.'), long: L('Both are applied, each in its own range or area.', 'S’apliquen tots dos, cadascun en el seu tram o àrea.', 'Se aplican los dos, cada uno en su tramo o área.') },
};

export const STAGES = [
  {
    id: 'files', name: L('Files', 'Fitxers', 'Archivos'), sub: L('Missing models · embeddings', 'Models que falten · embeddings', 'Modelos que faltan · embeddings'),
    steps: [
      {
        title: L('A workflow from another computer', 'Un workflow d’un altre ordinador', 'Un workflow de otro ordenador'),
        task: L('This workflow was shared by someone with other models. Run it, read the error and fix it with a checkpoint you have.', 'Aquest workflow l’ha compartit algú amb altres models. Executa’l, llegeix l’error i arregla’l amb un checkpoint que tinguis.', 'Este workflow lo ha compartido alguien con otros modelos. Ejecútalo, lee el error y arréglalo con un checkpoint que tengas.'),
        concept: L('A workflow stores the <b>names</b> of the files it uses, not the files. Open someone else’s workflow and the model names point to files you do not have: ComfyUI refuses to run with <b>“Value not in list”</b>, naming the widget and the missing value. Fix it by choosing a file you have, or download the same one into the right folder: models/checkpoints, models/loras, models/vae, models/embeddings, models/controlnet, models/upscale_models…', 'Un workflow guarda els <b>noms</b> dels fitxers que fa servir, no els fitxers. Obre el workflow d’una altra persona i els noms dels models apunten a fitxers que no tens: ComfyUI es nega a executar amb <b>“Value not in list”</b>, amb el nom del widget i el valor que falta. Arregla-ho triant un fitxer que tinguis, o descarrega el mateix a la carpeta bona: models/checkpoints, models/loras, models/vae, models/embeddings, models/controlnet, models/upscale_models…', 'Un workflow guarda los <b>nombres</b> de los archivos que usa, no los archivos. Abre el workflow de otra persona y los nombres de los modelos apuntan a archivos que no tienes: ComfyUI se niega a ejecutar con <b>“Value not in list”</b>, con el nombre del widget y el valor que falta. Arréglalo eligiendo un archivo que tengas, o descarga el mismo en la carpeta correcta: models/checkpoints, models/loras, models/vae, models/embeddings, models/controlnet, models/upscale_models…'),
        how: [L('Run: “Value not in list: ckpt_name”.', 'Executa: “Value not in list: ckpt_name”.', 'Ejecuta: “Value not in list: ckpt_name”.'), L('Click the ckpt_name of Load Checkpoint and choose <b>dreamshaper_8</b>.', 'Clica el ckpt_name de Load Checkpoint i tria <b>dreamshaper_8</b>.', 'Haz clic en el ckpt_name de Load Checkpoint y elige <b>dreamshaper_8</b>.'), L('Run.', 'Executa.', 'Ejecuta.')],
        note: L('Missing custom nodes appear red when loading a workflow; ComfyUI Manager › “Install Missing Custom Nodes” installs them. Restart ComfyUI after installing.', 'Els custom nodes que falten surten en vermell en carregar un workflow; ComfyUI Manager › “Install Missing Custom Nodes” els instal·la. Reinicia ComfyUI després d’instal·lar.', 'Los custom nodes que faltan salen en rojo al cargar un workflow; ComfyUI Manager › “Install Missing Custom Nodes” los instala. Reinicia ComfyUI después de instalar.'),
        starter: () => set(G.base(), 'ckpt', 'ckpt_name', 'realisticVision_v51.safetensors'), solution: () => G.base(),
        goals: [goal(L('Read the validation error', 'Has llegit l’error de validació', 'Has leído el error de validación'), (g, c) => c.flags.errorSeen), goal(L('A checkpoint you have', 'Un checkpoint que tens', 'Un checkpoint que tienes'), g => N(g, 'CheckpointLoaderSimple').every(n => n.widgets.ckpt_name !== 'realisticVision_v51.safetensors')), goal(L('Generated', 'Has generat', 'Has generado'), (g, c) => runs(c).length > 0)],
      },
      {
        title: L('Negative embeddings', 'Embeddings negatius', 'Embeddings negativos'),
        task: L('The negative prompt calls an embedding you do not have. Read the log, then use embedding:easynegative.', 'El prompt negatiu crida un embedding que no tens. Llegeix el log i després fes servir embedding:easynegative.', 'El prompt negativo llama a un embedding que no tienes. Lee el log y luego usa embedding:easynegative.'),
        concept: L('An <b>embedding</b> (textual inversion) is a tiny file that teaches the text encoder one new “word”. Negative embeddings like EasyNegative pack a long list of “bad quality” concepts into one word: write <b>embedding:easynegative</b> in the negative prompt. They live in models/embeddings and must match the model family. A missing one is not an error: ComfyUI ignores it with a warning in the log, which is easy to miss.', 'Un <b>embedding</b> (textual inversion) és un fitxer petit que ensenya una “paraula” nova al text encoder. Els embeddings negatius com EasyNegative empaqueten una llista llarga de conceptes de “mala qualitat” en una sola paraula: escriu <b>embedding:easynegative</b> al prompt negatiu. Van a models/embeddings i han de coincidir amb la família del model. Si en falta un no és un error: ComfyUI l’ignora amb un avís al log, que és fàcil de no veure.', 'Un <b>embedding</b> (textual inversion) es un archivo pequeño que enseña una “palabra” nueva al text encoder. Los embeddings negativos como EasyNegative empaquetan una lista larga de conceptos de “mala calidad” en una sola palabra: escribe <b>embedding:easynegative</b> en el prompt negativo. Van en models/embeddings y deben coincidir con la familia del modelo. Si falta uno no es un error: ComfyUI lo ignora con un aviso en el log, que es fácil de no ver.'),
        how: [L('Run and open the log: “embedding:badhands does not exist, ignoring”.', 'Executa i mira el log: “embedding:badhands does not exist, ignoring”.', 'Ejecuta y mira el log: “embedding:badhands does not exist, ignoring”.'), L('Negative: <b>embedding:easynegative, text, watermark</b>.', 'Negatiu: <b>embedding:easynegative, text, watermark</b>.', 'Negativo: <b>embedding:easynegative, text, watermark</b>.'), L('Run and compare.', 'Executa i compara.', 'Ejecuta y compara.')],
        note: L('Embeddings also work in the positive prompt (a style, a character), with weights like a word: (embedding:name:0.8).', 'Els embeddings també funcionen al prompt positiu (un estil, un personatge), amb pesos com una paraula: (embedding:name:0.8).', 'Los embeddings también funcionan en el prompt positivo (un estilo, un personaje), con pesos como una palabra: (embedding:name:0.8).'),
        starter: () => G.base(undefined, 'embedding:badhands, text, watermark'), solution: () => G.base(undefined, 'embedding:easynegative, text, watermark'),
        goals: [goal(L('Saw a missing embedding ignored', 'Has vist com s’ignora un embedding que falta', 'Has visto cómo se ignora un embedding que falta'), (g, c) => ran(c, h => h.embMissing)), goal(L('A run with easynegative', 'Una execució amb easynegative', 'Una ejecución con easynegative'), (g, c) => ran(c, h => h.embOk && !h.embMissing))],
      },
    ],
  },
  {
    id: 'samplers', name: L('Samplers', 'Samplers', 'Samplers'), sub: L('Converge · schedulers · steps', 'Convergir · schedulers · steps', 'Converger · schedulers · steps'),
    steps: [
      {
        title: L('Samplers that settle and samplers that do not', 'Samplers que s’aturen i samplers que no', 'Samplers que se paran y samplers que no'),
        task: L('With the same seed, run euler_ancestral at 20 and at 30 steps, then dpmpp_2m at 20 and at 30. Compare each pair.', 'Amb el mateix seed, executa euler_ancestral a 20 i a 30 steps, i després dpmpp_2m a 20 i a 30. Compara cada parella.', 'Con el mismo seed, ejecuta euler_ancestral a 20 y a 30 steps, y luego dpmpp_2m a 20 y a 30. Compara cada pareja.'),
        concept: L('Most samplers <b>converge</b>: more steps refine the same picture (euler, dpmpp_2m, heun, uni_pc…). <b>Ancestral</b> samplers (the ones with “a” or “ancestral”) and the <b>SDE</b> ones add a bit of fresh noise every step: they never settle, so changing the number of steps gives <b>another picture</b> even with the same seed. Use them for variety and texture; use a converging one when you want to fine-tune a picture you like.', 'La majoria de samplers <b>convergeixen</b>: més steps refinen la mateixa imatge (euler, dpmpp_2m, heun, uni_pc…). Els samplers <b>ancestrals</b> (els que tenen “a” o “ancestral”) i els <b>SDE</b> afegeixen una mica de soroll nou a cada step: no s’aturen mai, i canviar el nombre de steps dona <b>una altra imatge</b> fins i tot amb el mateix seed. Fes-los servir per a varietat i textura; fes servir un que convergeixi quan vulguis afinar una imatge que t’agrada.', 'La mayoría de samplers <b>convergen</b>: más steps refinan la misma imagen (euler, dpmpp_2m, heun, uni_pc…). Los samplers <b>ancestrales</b> (los que tienen “a” o “ancestral”) y los <b>SDE</b> añaden un poco de ruido nuevo en cada step: no se paran nunca, y cambiar el número de steps da <b>otra imagen</b> incluso con el mismo seed. Úsalos para variedad y textura; usa uno que converja cuando quieras afinar una imagen que te gusta.'),
        how: [L('sampler_name <b>euler_ancestral</b>: run at 20 steps, then at 30.', 'sampler_name <b>euler_ancestral</b>: executa a 20 steps i després a 30.', 'sampler_name <b>euler_ancestral</b>: ejecuta a 20 steps y luego a 30.'), L('sampler_name <b>dpmpp_2m</b>: run at 20, then at 30.', 'sampler_name <b>dpmpp_2m</b>: executa a 20 i després a 30.', 'sampler_name <b>dpmpp_2m</b>: ejecuta a 20 y luego a 30.'), L('Compare in the Queue.', 'Compara a la Queue.', 'Compara en la Queue.')],
        note: L('The seed stays fixed here (control_after_generate: fixed). With randomize, every run is another picture anyway.', 'El seed es queda fix (control_after_generate: fixed). Amb randomize, cada execució és una altra imatge igualment.', 'El seed se queda fijo (control_after_generate: fixed). Con randomize, cada ejecución es otra imagen igualmente.'),
        starter: () => G.base(undefined, undefined, { sampler_name: 'euler_ancestral', steps: 20 }), solution: () => G.base(undefined, undefined, { sampler_name: 'dpmpp_2m', steps: 30 }),
        goals: [goal(L('Ancestral: another picture with more steps', 'Ancestral: una altra imatge amb més steps', 'Ancestral: otra imagen con más steps'), (g, c) => { const a = runs(c).filter(h => h.ancestral); return a.some(x => a.some(y => x.seed === y.seed && x.steps !== y.steps && x.layoutKey !== y.layoutKey)); }), goal(L('Converging: the same picture, refined', 'Convergent: la mateixa imatge, més acabada', 'Convergente: la misma imagen, más acabada'), (g, c) => { const a = runs(c).filter(h => !h.ancestral && !h.stage); return a.some(x => a.some(y => x.seed === y.seed && x.steps !== y.steps && x.layoutKey === y.layoutKey)); })],
      },
      {
        title: L('Schedulers and how many steps', 'Schedulers i quants steps', 'Schedulers y cuántos steps'),
        task: L('Run dpmpp_2m at 10 steps with the normal scheduler, then with karras. Then try 60 steps and compare with 25.', 'Executa dpmpp_2m a 10 steps amb el scheduler normal, i després amb karras. Després prova 60 steps i compara amb 25.', 'Ejecuta dpmpp_2m a 10 steps con el scheduler normal, y luego con karras. Luego prueba 60 steps y compara con 25.'),
        concept: L('The <b>scheduler</b> decides how much noise is removed at each step. <b>karras</b> (and exponential) remove less at the end, spending more steps on details: at few steps it finishes cleaner than normal. And more steps is not always better: a converging sampler is practically done at 20–30; at 60 the picture is the same and takes twice as long. Find the point where it stops improving and stay there.', 'El <b>scheduler</b> decideix quant soroll es treu a cada step. <b>karras</b> (i exponential) en treuen menys al final, i dediquen més steps als detalls: amb pocs steps acaba més net que normal. I més steps no sempre és millor: un sampler que convergeix pràcticament ha acabat a 20–30; a 60 la imatge és la mateixa i triga el doble. Troba el punt on deixa de millorar i queda-t’hi.', 'El <b>scheduler</b> decide cuánto ruido se quita en cada step. <b>karras</b> (y exponential) quitan menos al final, y dedican más steps a los detalles: con pocos steps acaba más limpio que normal. Y más steps no siempre es mejor: un sampler que converge prácticamente ha acabado a 20–30; a 60 la imagen es la misma y tarda el doble. Encuentra el punto donde deja de mejorar y quédate ahí.'),
        how: [L('steps <b>10</b>, scheduler <b>normal</b>: run.', 'steps <b>10</b>, scheduler <b>normal</b>: executa.', 'steps <b>10</b>, scheduler <b>normal</b>: ejecuta.'), L('scheduler <b>karras</b>: run.', 'scheduler <b>karras</b>: executa.', 'scheduler <b>karras</b>: ejecuta.'), L('Optional: steps 25 and 60, compare.', 'Opcional: steps 25 i 60, compara.', 'Opcional: steps 25 y 60, compara.')],
        note: L('simple and beta are the usual schedulers for Flux and SD3; karras for SD 1.5 and SDXL.', 'simple i beta són els schedulers habituals per a Flux i SD3; karras per a SD 1.5 i SDXL.', 'simple y beta son los schedulers habituales para Flux y SD3; karras para SD 1.5 y SDXL.'),
        starter: () => G.base(undefined, undefined, { sampler_name: 'dpmpp_2m', steps: 10 }), solution: () => G.base(undefined, undefined, { sampler_name: 'dpmpp_2m', steps: 10, scheduler: 'karras' }),
        goals: [goal(L('normal at 10 steps: not finished', 'normal a 10 steps: no acabat', 'normal a 10 steps: no acabado'), (g, c) => ran(c, h => h.scheduler === 'normal' && h.steps <= 10 && h.quality < .9)), goal(L('karras at 10 steps: cleaner', 'karras a 10 steps: més net', 'karras a 10 steps: más limpio'), (g, c) => ran(c, h => h.scheduler === 'karras' && h.steps <= 10 && h.quality >= .9)), goal(L('60 steps look like 25', '60 steps es veuen com 25', '60 steps se ven como 25'), (g, c) => { const a = runs(c).filter(h => !h.ancestral); return a.some(x => x.steps >= 50 && a.some(y => y.steps >= 20 && y.steps <= 30 && y.layoutKey === x.layoutKey)); }, true)],
      },
    ],
  },
  {
    id: 'stages', name: L('Two stages', 'Dues etapes', 'Dos etapas'), sub: L('KSampler Advanced · prompt timing', 'KSampler Advanced · prompts per trams', 'KSampler Advanced · prompts por tramos'),
    steps: [
      {
        title: L('Two samplers share the steps', 'Dos samplers es reparteixen els steps', 'Dos samplers se reparten los steps'),
        task: L('Two KSampler (Advanced): the first composes with dreamshaper (steps 0–20 of 30), the second finishes with anything_v5 (20–30). Two settings are wrong: fix them.', 'Dos KSampler (Advanced): el primer compon amb dreamshaper (steps 0–20 de 30), el segon acaba amb anything_v5 (20–30). Hi ha dos paràmetres malament: arregla’ls.', 'Dos KSampler (Advanced): el primero compone con dreamshaper (steps 0–20 de 30), el segundo acaba con anything_v5 (20–30). Hay dos parámetros mal: arréglalos.'),
        concept: L('<b>KSampler (Advanced)</b> can run a slice of the schedule. Chaining two lets one model <b>compose</b> and another <b>finish</b> (a realistic model and an illustration model, SDXL base and refiner…). The rules: the first sampler <b>return_with_leftover_noise: enable</b> (it hands over a half-finished latent), and the second <b>add_noise: disable</b> (it continues that noise instead of adding new) with <b>start_at_step</b> equal to the first one’s <b>end_at_step</b>. Get one wrong and the result is noisy or the second model does nothing.', '<b>KSampler (Advanced)</b> pot fer un tram del calendari. Encadenar-ne dos permet que un model <b>compongui</b> i un altre <b>acabi</b> (un model realista i un d’il·lustració, SDXL base i refiner…). Les regles: el primer sampler <b>return_with_leftover_noise: enable</b> (passa un latent a mig fer), i el segon <b>add_noise: disable</b> (continua aquell soroll en lloc d’afegir-ne de nou) amb <b>start_at_step</b> igual a l’<b>end_at_step</b> del primer. Si en falla una, el resultat té soroll o el segon model no fa res.', '<b>KSampler (Advanced)</b> puede hacer un tramo del calendario. Encadenar dos permite que un modelo <b>componga</b> y otro <b>acabe</b> (un modelo realista y uno de ilustración, SDXL base y refiner…). Las reglas: el primer sampler <b>return_with_leftover_noise: enable</b> (pasa un latente a medio hacer), y el segundo <b>add_noise: disable</b> (continúa ese ruido en lugar de añadir uno nuevo) con <b>start_at_step</b> igual al <b>end_at_step</b> del primero. Si falla una, el resultado tiene ruido o el segundo modelo no hace nada.'),
        how: [L('Run as it is: noisy.', 'Executa tal com està: amb soroll.', 'Ejecuta tal cual: con ruido.'), L('First sampler: return_with_leftover_noise <b>enable</b>. Second: add_noise <b>disable</b>, start_at_step <b>20</b>.', 'Primer sampler: return_with_leftover_noise <b>enable</b>. Segon: add_noise <b>disable</b>, start_at_step <b>20</b>.', 'Primer sampler: return_with_leftover_noise <b>enable</b>. Segundo: add_noise <b>disable</b>, start_at_step <b>20</b>.'), L('Run: the composition of the first model, the finish of the second.', 'Executa: la composició del primer model, l’acabat del segon.', 'Ejecuta: la composición del primer modelo, el acabado del segundo.')],
        note: L('Both samplers must have the same total steps, and both models the same family (both SD 1.5 here).', 'Els dos samplers han de tenir els mateixos steps totals, i els dos models la mateixa família (tots dos SD 1.5 aquí).', 'Los dos samplers deben tener los mismos steps totales, y los dos modelos la misma familia (los dos SD 1.5 aquí).'),
        starter: () => G.adv({ leftover: 'disable', addNoise: 'enable' }), solution: () => G.adv(),
        goals: [goal(L('Saw a broken hand-over', 'Has vist un relleu mal fet', 'Has visto un relevo mal hecho'), (g, c) => ran(c, h => h.stage?.chained && !h.stage.ok)), goal(L('A clean hand-over between two models', 'Un relleu net entre dos models', 'Un relevo limpio entre dos modelos'), (g, c) => ran(c, h => h.stage?.chained && h.stage.ok && h.stage.twoModels && h.stage.look === 'anime'))],
      },
      {
        title: L('Prompts on a timetable', 'Prompts amb horari', 'Prompts con horario'),
        task: L('Make the first prompt act on steps 0–0.35 (the lighthouse) and the second on 0.35–1 (red, watercolor), with ConditioningSetTimestepRange, and combine them.', 'Fes que el primer prompt actuï als steps 0–0.35 (el far) i el segon a 0.35–1 (red, watercolor), amb ConditioningSetTimestepRange, i combina’ls.', 'Haz que el primer prompt actúe en los steps 0–0.35 (el faro) y el segundo en 0.35–1 (red, watercolor), con ConditioningSetTimestepRange, y combínalos.'),
        concept: L('The early steps of sampling decide the big shapes and the layout; the late steps the colours, the textures and the style. <b>ConditioningSetTimestepRange</b> limits a prompt to a part of the steps (0 = start, 1 = end). One prompt composes, another finishes: useful to keep a composition while changing the look, or to stop a style word from changing the shapes.', 'Els primers steps del mostreig decideixen les formes grans i la composició; els últims els colors, les textures i l’estil. <b>ConditioningSetTimestepRange</b> limita un prompt a una part dels steps (0 = inici, 1 = final). Un prompt compon, l’altre acaba: útil per mantenir una composició i canviar-ne l’aspecte, o perquè una paraula d’estil no canviï les formes.', 'Los primeros steps del muestreo deciden las formas grandes y la composición; los últimos los colores, las texturas y el estilo. <b>ConditioningSetTimestepRange</b> limita un prompt a una parte de los steps (0 = inicio, 1 = final). Un prompt compone, el otro acaba: útil para mantener una composición y cambiar su aspecto, o para que una palabra de estilo no cambie las formas.'),
        how: [L('Positive (lighthouse) → <b>ConditioningSetTimestepRange</b> start 0, end 0.35.', 'Positiu (far) → <b>ConditioningSetTimestepRange</b> start 0, end 0.35.', 'Positivo (faro) → <b>ConditioningSetTimestepRange</b> start 0, end 0.35.'), L('A second CLIP Text Encode “red, watercolor, detailed” → another range, start 0.35, end 1.', 'Un segon CLIP Text Encode “red, watercolor, detailed” → un altre tram, start 0.35, end 1.', 'Un segundo CLIP Text Encode “red, watercolor, detailed” → otro tramo, start 0.35, end 1.'), L('<b>Conditioning (Combine)</b> → positive of the KSampler. Run.', '<b>Conditioning (Combine)</b> → positive del KSampler. Executa.', '<b>Conditioning (Combine)</b> → positive del KSampler. Ejecuta.')],
        note: L('Leave no gaps: the two ranges must cover 0 to 1 between them, or some steps sample with no prompt.', 'No deixis forats: els dos trams han de cobrir de 0 a 1 entre tots dos, o alguns steps mostregen sense prompt.', 'No dejes huecos: los dos tramos deben cubrir de 0 a 1 entre los dos, o algunos steps muestrean sin prompt.'),
        starter: () => G.base('a lighthouse on the beach, sunset'), solution: () => G.sched(),
        goals: [goal(L('Two ranges that cover 0 to 1', 'Dos trams que cobreixen de 0 a 1', 'Dos tramos que cubren de 0 a 1'), (g, c) => ran(c, h => h.schedule?.covers)), goal(L('The split early (0.2–0.6)', 'El canvi aviat (0.2–0.6)', 'El cambio pronto (0.2–0.6)'), (g, c) => ran(c, h => h.schedule?.covers && h.schedule.split >= .2 && h.schedule.split <= .6)), goal(L('Shape from one prompt, look from the other', 'La forma d’un prompt, l’aspecte de l’altre', 'La forma de un prompt, el aspecto del otro'), (g, c) => ran(c, h => h.schedule?.earlySubject === 'lighthouse' && (h.schedule.lateStyle || h.schedule.lateColor)))],
      },
    ],
  },
  {
    id: 'prompting', name: L('Prompting', 'Prompts', 'Prompts'), sub: L('Weights · dynamic · length', 'Pesos · dinàmics · llargada', 'Pesos · dinámicos · longitud'),
    steps: [
      {
        title: L('Weights', 'Pesos', 'Pesos'),
        task: L('Give watercolor more weight with (watercolor:1.4). Then try 2.0 and see it break. Settle at 1.5 or less.', 'Dona més pes a watercolor amb (watercolor:1.4). Després prova 2.0 i mira com es trenca. Queda’t a 1.5 o menys.', 'Da más peso a watercolor con (watercolor:1.4). Luego prueba 2.0 y mira cómo se rompe. Quédate en 1.5 o menos.'),
        concept: L('<b>(word:1.3)</b> multiplies the importance of a word; <b>(word)</b> is 1.1, and values below 1 soften it. In ComfyUI select the word and press <kbd>Ctrl ↑</kbd> / <kbd>Ctrl ↓</kbd> to change it in steps of 0.05. Weights are strong medicine: above about 1.6 the conditioning is pushed out of what the model knows and the picture breaks into bands and burned colours. If a word needs 1.8, the problem is usually elsewhere (a word that fights it, a LoRA, the CFG).', '<b>(paraula:1.3)</b> multiplica la importància d’una paraula; <b>(paraula)</b> és 1.1, i els valors per sota d’1 la suavitzen. A ComfyUI selecciona la paraula i prem <kbd>Ctrl ↑</kbd> / <kbd>Ctrl ↓</kbd> per canviar-la de 0.05 en 0.05. Els pesos són medicina forta: per sobre d’uns 1.6 el conditioning surt del que el model coneix i la imatge es trenca en bandes i colors cremats. Si una paraula necessita 1.8, el problema sol ser en una altra banda (una paraula que hi lluita en contra, una LoRA, el CFG).', '<b>(palabra:1.3)</b> multiplica la importancia de una palabra; <b>(palabra)</b> es 1.1, y los valores por debajo de 1 la suavizan. En ComfyUI selecciona la palabra y pulsa <kbd>Ctrl ↑</kbd> / <kbd>Ctrl ↓</kbd> para cambiarla de 0.05 en 0.05. Los pesos son medicina fuerte: por encima de unos 1.6 el conditioning sale de lo que el modelo conoce y la imagen se rompe en bandas y colores quemados. Si una palabra necesita 1.8, el problema suele estar en otro sitio (una palabra que lucha en contra, una LoRA, el CFG).'),
        how: [L('Prompt: <b>a cat sitting in a landscape, (watercolor:1.4)</b>. Run.', 'Prompt: <b>a cat sitting in a landscape, (watercolor:1.4)</b>. Executa.', 'Prompt: <b>a cat sitting in a landscape, (watercolor:1.4)</b>. Ejecuta.'), L('Change it to <b>2.0</b>, run.', 'Canvia-ho a <b>2.0</b>, executa.', 'Cámbialo a <b>2.0</b>, ejecuta.'), L('Back to 1.3–1.5.', 'Torna a 1.3–1.5.', 'Vuelve a 1.3–1.5.')],
        note: L('With Flux (T5) weights do much less: describe instead (“painted in a loose watercolor style”).', 'Amb Flux (T5) els pesos fan molt menys: descriu (“painted in a loose watercolor style”).', 'Con Flux (T5) los pesos hacen mucho menos: describe (“painted in a loose watercolor style”).'),
        starter: () => G.base('a cat sitting in a landscape, watercolor'), solution: () => G.base('a cat sitting in a landscape, (watercolor:1.4)'),
        goals: [goal(L('A weight between 1.2 and 1.6', 'Un pes entre 1.2 i 1.6', 'Un peso entre 1.2 y 1.6'), (g, c) => ran(c, h => h.maxWeight >= 1.2 && h.maxWeight < 1.7)), goal(L('Saw a weight of 1.8 or more break it', 'Has vist com un pes d’1.8 o més la trenca', 'Has visto cómo un peso de 1.8 o más la rompe'), (g, c) => ran(c, h => h.broken))],
      },
      {
        title: L('Dynamic prompts', 'Prompts dinàmics', 'Prompts dinámicos'),
        task: L('Write a {red|blue|green} cat in the {snow|desert|forest} and run it several times (or set the Run count to 4).', 'Escriu a {red|blue|green} cat in the {snow|desert|forest} i executa-ho unes quantes vegades (o posa el comptador de Run a 4).', 'Escribe a {red|blue|green} cat in the {snow|desert|forest} y ejecútalo varias veces (o pon el contador de Run a 4).'),
        concept: L('The ComfyUI interface understands <b>{a|b|c}</b> in any text: every time you queue, it picks one option and sends that text. Write a template once and get variations without touching the graph: colours, places, lighting, outfits. The text you see keeps the braces; the image metadata stores the version that was actually used.', 'La interfície de ComfyUI entén <b>{a|b|c}</b> en qualsevol text: cada vegada que poses a la cua, tria una opció i envia aquell text. Escriu una plantilla una vegada i tindràs variacions sense tocar el graf: colors, llocs, llums, roba. El text que veus conserva les claus; les metadades de la imatge guarden la versió que s’ha fet servir de veritat.', 'La interfaz de ComfyUI entiende <b>{a|b|c}</b> en cualquier texto: cada vez que pones en la cola, elige una opción y envía ese texto. Escribe una plantilla una vez y tendrás variaciones sin tocar el grafo: colores, lugares, luces, ropa. El texto que ves conserva las llaves; los metadatos de la imagen guardan la versión que se ha usado de verdad.'),
        how: [L('Positive: <b>a {red|blue|green} cat in the {snow|desert|forest}, detailed</b>.', 'Positiu: <b>a {red|blue|green} cat in the {snow|desert|forest}, detailed</b>.', 'Positivo: <b>a {red|blue|green} cat in the {snow|desert|forest}, detailed</b>.'), L('The number next to Run is the batch count: set it to <b>4</b> and press Run.', 'El número al costat de Run és el batch count: posa-hi <b>4</b> i prem Run.', 'El número junto a Run es el batch count: pon <b>4</b> y pulsa Run.'), L('Open the Queue: each picture used a different text.', 'Obre la Queue: cada imatge ha fet servir un text diferent.', 'Abre la Queue: cada imagen ha usado un texto distinto.')],
        note: L('For big lists (hundreds of options in files) there are wildcard custom nodes; the braces cover most needs.', 'Per a llistes grans (centenars d’opcions en fitxers) hi ha custom nodes de wildcards; les claus cobreixen la majoria de necessitats.', 'Para listas grandes (cientos de opciones en archivos) hay custom nodes de wildcards; las llaves cubren la mayoría de necesidades.'),
        starter: () => G.base(), solution: () => G.base('a {red|blue|green} cat in the {snow|desert|forest}, detailed'),
        goals: [goal(L('A prompt with {options}', 'Un prompt amb {opcions}', 'Un prompt con {opciones}'), g => N(g, 'CLIPTextEncode').some(n => /\{[^{}]*\|[^{}]*\}/.test(n.widgets.text))), goal(L('Three different versions generated', 'Tres versions diferents generades', 'Tres versiones distintas generadas'), (g, c) => new Set(runs(c).filter(h => h.dynamic).map(h => h.resolved)).size >= 3)],
      },
      {
        title: L('Long prompts', 'Prompts llargs', 'Prompts largos'),
        task: L('This prompt has a long list of quality words and the cat at the very end. Run it, then move “a cat sitting in a landscape” to the start.', 'Aquest prompt té una llista llarga de paraules de qualitat i el gat al final de tot. Executa’l, i després mou “a cat sitting in a landscape” al principi.', 'Este prompt tiene una lista larga de palabras de calidad y el gato al final del todo. Ejecútalo, y luego mueve “a cat sitting in a landscape” al principio.'),
        concept: L('CLIP reads <b>75 tokens</b> at a time (a token is a word or a piece of one). ComfyUI splits longer prompts into chunks and joins them, so nothing is lost, but the later chunks weigh less and the words at the start lead. Put the subject first, then the setting, then the style; and drop the long “masterpiece, best quality, 8k…” lists, which mostly push the important words out of the first chunk.', 'CLIP llegeix <b>75 tokens</b> cada vegada (un token és una paraula o un tros de paraula). ComfyUI divideix els prompts més llargs en trossos i els uneix, de manera que no es perd res, però els trossos del final pesen menys i les paraules del principi manen. Posa primer el subjecte, després l’escenari, després l’estil; i treu les llistes llargues de “masterpiece, best quality, 8k…”, que sobretot empenyen les paraules importants fora del primer tros.', 'CLIP lee <b>75 tokens</b> cada vez (un token es una palabra o un trozo de palabra). ComfyUI divide los prompts más largos en trozos y los une, de modo que no se pierde nada, pero los trozos del final pesan menos y las palabras del principio mandan. Pon primero el sujeto, luego el escenario, luego el estilo; y quita las listas largas de “masterpiece, best quality, 8k…”, que sobre todo empujan las palabras importantes fuera del primer trozo.'),
        how: [L('Run: a small, faded cat.', 'Executa: un gat petit i esvaït.', 'Ejecuta: un gato pequeño y desvaído.'), L('Cut <b>a cat sitting in a landscape</b> from the end and paste it at the start.', 'Talla <b>a cat sitting in a landscape</b> del final i enganxa-ho al principi.', 'Corta <b>a cat sitting in a landscape</b> del final y pégalo al principio.'), L('Run again (and delete some of the quality words).', 'Torna a executar (i esborra algunes paraules de qualitat).', 'Vuelve a ejecutar (y borra algunas palabras de calidad).')],
        note: L('Flux and other T5 models read up to 256–512 tokens: there, long descriptive prompts work well.', 'Flux i altres models amb T5 llegeixen fins a 256–512 tokens: allà els prompts llargs i descriptius funcionen bé.', 'Flux y otros modelos con T5 leen hasta 256–512 tokens: allí los prompts largos y descriptivos funcionan bien.'),
        starter: () => G.base(LONG), solution: () => G.base('a cat sitting in a landscape, soft light, golden hour, detailed'),
        goals: [goal(L('Saw a subject lost after 75 tokens', 'Has vist un subjecte perdut després de 75 tokens', 'Has visto un sujeto perdido después de 75 tokens'), (g, c) => ran(c, h => h.late)), goal(L('The subject in the first words', 'El subjecte a les primeres paraules', 'El sujeto en las primeras palabras'), (g, c) => ran(c, h => h.subjectToken >= 0 && h.subjectToken <= 10))],
      },
    ],
  },
  {
    id: 'seeds', name: L('Seeds', 'Seeds', 'Seeds'), sub: L('Explore · keep', 'Explora · conserva', 'Explora · conserva'),
    steps: [
      {
        title: L('Explore seeds in a row', 'Explora seeds seguits', 'Explora seeds seguidos'),
        task: L('Set control_after_generate to increment and Run 4 times in one go (Run count 4).', 'Posa control_after_generate a increment i fes Run 4 vegades de cop (comptador de Run a 4).', 'Pon control_after_generate en increment y haz Run 4 veces de golpe (contador de Run a 4).'),
        concept: L('The seed decides the composition. To explore, change only the seed: <b>increment</b> gives seed, seed + 1, seed + 2… so you can find any of them again later (randomize gives numbers you cannot guess). With the <b>Run count</b> next to the Run button you queue several prompts at once. Explore with few steps and a fast sampler; finish the good one with all the steps.', 'El seed decideix la composició. Per explorar, canvia només el seed: <b>increment</b> dona seed, seed + 1, seed + 2… i després pots tornar a trobar qualsevol d’ells (randomize dona números que no pots endevinar). Amb el <b>comptador de Run</b> al costat del botó Run poses diversos prompts a la cua alhora. Explora amb pocs steps i un sampler ràpid; acaba la bona amb tots els steps.', 'El seed decide la composición. Para explorar, cambia solo el seed: <b>increment</b> da seed, seed + 1, seed + 2… y luego puedes volver a encontrar cualquiera de ellos (randomize da números que no puedes adivinar). Con el <b>contador de Run</b> junto al botón Run pones varios prompts en la cola a la vez. Explora con pocos steps y un sampler rápido; acaba la buena con todos los steps.'),
        how: [L('KSampler › control_after_generate <b>increment</b>.', 'KSampler › control_after_generate <b>increment</b>.', 'KSampler › control_after_generate <b>increment</b>.'), L('Run count (next to Run) <b>4</b>, then Run.', 'Comptador de Run (al costat de Run) <b>4</b>, i Run.', 'Contador de Run (junto a Run) <b>4</b>, y Run.'), L('<kbd>Q</kbd>: four seeds in a row.', '<kbd>Q</kbd>: quatre seeds seguits.', '<kbd>Q</kbd>: cuatro seeds seguidos.')],
        note: L('batch_size in Empty Latent Image makes several pictures in one run (faster on a big GPU), all from the same seed.', 'batch_size a Empty Latent Image fa diverses imatges en una execució (més ràpid en una GPU gran), totes del mateix seed.', 'batch_size en Empty Latent Image hace varias imágenes en una ejecución (más rápido en una GPU grande), todas del mismo seed.'),
        starter: () => G.base(), solution: () => set(G.base(), 'sampler', 'control_after_generate', 'increment'),
        goals: [goal(L('control_after_generate: increment', 'control_after_generate: increment', 'control_after_generate: increment'), g => N(g, 'KSampler').some(n => n.widgets.control_after_generate === 'increment')), goal(L('Three or more seeds in a row', 'Tres seeds o més seguits', 'Tres seeds o más seguidos'), (g, c) => { const s = [...new Set(runs(c).map(h => Number(h.seed)))].sort((a, b) => a - b); let best = 1, cur = 1; for (let i = 1; i < s.length; i++) { cur = s[i] === s[i - 1] + 1 ? cur + 1 : 1; best = Math.max(best, cur); } return best >= 3; })],
      },
      {
        title: L('Keep the good one', 'Conserva la bona', 'Conserva la buena'),
        task: L('Pick your favourite picture in the Queue, load its workflow, and make a small change (one word, or the CFG) keeping its seed.', 'Tria la teva imatge preferida a la Queue, carrega’n el workflow i fes-hi un petit canvi (una paraula, o el CFG) conservant-ne el seed.', 'Elige tu imagen preferida en la Queue, carga su workflow y hazle un pequeño cambio (una palabra, o el CFG) conservando su seed.'),
        concept: L('Every picture carries its workflow, seed included. Load it, set control_after_generate to <b>fixed</b>, and you can change one thing at a time while the composition stays: a colour word, the CFG, the steps, a LoRA. This is how a picture is refined in ComfyUI: explore wide with seeds, then fix the seed and work in small steps.', 'Cada imatge porta el seu workflow, seed inclòs. Carrega’l, posa control_after_generate a <b>fixed</b>, i pots canviar una cosa cada vegada mentre la composició es manté: una paraula de color, el CFG, els steps, una LoRA. Així es refina una imatge a ComfyUI: explora ample amb els seeds, i després fixa el seed i treballa a passos petits.', 'Cada imagen lleva su workflow, seed incluido. Cárgalo, pon control_after_generate en <b>fixed</b>, y puedes cambiar una cosa cada vez mientras la composición se mantiene: una palabra de color, el CFG, los steps, una LoRA. Así se refina una imagen en ComfyUI: explora a lo ancho con los seeds, y luego fija el seed y trabaja a pasos pequeños.'),
        how: [L('<kbd>Q</kbd> › click a picture › <b>Load Workflow</b>.', '<kbd>Q</kbd> › clica una imatge › <b>Load Workflow</b>.', '<kbd>Q</kbd> › haz clic en una imagen › <b>Load Workflow</b>.'), L('control_after_generate <b>fixed</b>. Change one word of the prompt.', 'control_after_generate <b>fixed</b>. Canvia una paraula del prompt.', 'control_after_generate <b>fixed</b>. Cambia una palabra del prompt.'), L('Run: same composition, the change you asked for.', 'Executa: mateixa composició, el canvi que has demanat.', 'Ejecuta: misma composición, el cambio que has pedido.')],
        note: L('Write down the seeds you like (or save the PNGs): a seed is only useful with the same model, size and sampler.', 'Apunta els seeds que t’agradin (o desa els PNG): un seed només serveix amb el mateix model, mida i sampler.', 'Apunta los seeds que te gusten (o guarda los PNG): un seed solo sirve con el mismo modelo, tamaño y sampler.'),
        starter: () => set(G.base(), 'sampler', 'control_after_generate', 'increment'), solution: () => G.base('a black cat sitting in a landscape, detailed'),
        goals: [goal(L('Loaded a workflow from a picture', 'Has carregat un workflow d’una imatge', 'Has cargado un workflow de una imagen'), (g, c) => c.flags.loadedFromImage), goal(L('Same seed, different prompt', 'Mateix seed, prompt diferent', 'Mismo seed, prompt distinto'), (g, c) => runs(c).some(x => runs(c).some(y => x !== y && x.seed === y.seed && x.posText !== y.posText)))],
      },
    ],
  },
];

export const TEMPLATES = [
  { id: 'two-stage', name: L('Two-stage KSampler (Advanced)', 'KSampler (Advanced) en dues etapes', 'KSampler (Advanced) en dos etapas'), make: () => G.adv() },
  { id: 'timestep', name: L('Prompt timing', 'Prompts per trams', 'Prompts por tramos'), make: () => G.sched() },
  { id: 'dynamic', name: L('Dynamic prompt', 'Prompt dinàmic', 'Prompt dinámico'), make: () => G.base('a {red|blue|green} cat in the {snow|desert|forest}, detailed') },
  { id: 'default', name: L('Text to image (default)', 'Text a imatge (per defecte)', 'Texto a imagen (por defecto)'), make: () => G.base() },
];
export { G as GRAPHS };
