// Carrot Revolt Labs · Workflow Lab · stages, steps and live checklists.
// It runs on the ComfyUI Lab interface (../comfyui/app.js) and adds its own nodes (./nodes.js).
import { defaultGraph, makeNode, makeLink, connect, makeSubgraph, isSubgraphNode, SUBGRAPH } from '../comfyui/engine.js';
import { NEW_CKPT, outputExtra as ox } from './nodes.js';
export const L = (en, ca, es) => ({ en, ca, es });

export const META = { key: 'carrot-revolt-comfy-workflow:', title: 'Workflow Lab', label: 'GENERATIVE IMAGE / COMFYUI · 09' };
export const outputExtra = ox;
export function resultExtra(h) { return h.xy ? `<p class="vid-cap">${h.xy.cells} pictures · x: ${h.xy.xAxis} (${h.xy.xs.join(', ')})${h.xy.yAxis !== 'none' ? ` · y: ${h.xy.yAxis} (${h.xy.ys.join(', ')})` : ''}</p>` : ''; }

/* ── The Manager: packs and models this lab knows ── */
export const PACKS = [
  { id: 'xy-plot', title: 'XY Plot', author: 'community', nodes: ['XYPlotSampler'], desc: L('Grids of pictures that change one or two settings: cfg × steps, samplers × schedulers, seeds…', 'Graelles d’imatges que canvien un o dos paràmetres: cfg × steps, samplers × schedulers, seeds…', 'Rejillas de imágenes que cambian uno o dos parámetros: cfg × steps, samplers × schedulers, seeds…') },
  { id: 'rembg', title: 'rembg (background removal)', author: 'community', nodes: ['ImageRemoveBackground'], desc: L('Cuts the subject out of its background.', 'Retalla el subjecte del fons.', 'Recorta el sujeto del fondo.') },
  { id: 'Impact Pack', title: 'Impact Pack', author: 'community', nodes: ['FaceDetailer', 'UltralyticsDetectorProvider'], desc: L('Detectors and detailers for faces and hands.', 'Detectors i detailers per a cares i mans.', 'Detectores y detailers para caras y manos.') },
  { id: 'UltimateSDUpscale', title: 'Ultimate SD Upscale', author: 'community', nodes: ['UltimateSDUpscale'], desc: L('Upscaling in tiles with a sampler.', 'Upscale per tiles amb un sampler.', 'Upscale por tiles con un sampler.') },
];
export const MODELS = [
  { file: NEW_CKPT, dir: 'checkpoints', size: '6.6 GB', desc: L('SDXL checkpoint tuned for photographs. The workflow you received uses it.', 'Checkpoint SDXL afinat per a fotografies. El workflow que has rebut el fa servir.', 'Checkpoint SDXL afinado para fotografías. El workflow que has recibido lo usa.') },
  { file: '4x-UltraSharp.pth', dir: 'upscale_models', size: '67 MB', desc: L('An upscale model (see the Upscale & Detail Lab).', 'Un model d’upscale (mira el Upscale & Detail Lab).', 'Un modelo de upscale (mira el Upscale & Detail Lab).') },
];

/* ── Graph helpers ── */
const N = (g, type) => g.nodes.filter(n => n.type === type && n.mode === 0);
const goal = (text, test, optional = false) => ({ text, test, optional });
const add = (g, ...nodes) => { g.nodes.push(...nodes); return g; };
const wire = (g, list) => { for (const l of list) connect(g, makeLink(...l)); return g; };
const set = (g, id, k, v) => { g.nodes.find(n => n.id === id).widgets[k] = v; return g; };
const move = (g, id, x, y) => { const n = g.nodes.find(n => n.id === id); n.x = x; n.y = y; return g; };
const drop = (g, id) => { g.nodes = g.nodes.filter(n => n.id !== id); g.links = g.links.filter(l => l.from !== id && l.to !== id); return g; };
const fromOf = (g, id, input) => { const l = g.links.find(x => x.to === id && x.input === input); return l ? g.nodes.find(n => n.id === l.from) : null; };
// How many nodes of a type take this widget from a primitive.
const drivenBy = (g, prim, type, widget) => g.nodes.filter(n => n.type === type && n.mode === 0 && fromOf(g, n.id, widget)?.type === prim).length;
const xys = c => c.history.filter(h => h.xy);
const PROMPT = 'a red lighthouse on a beach at sunset, detailed';
const SG_SAMPLER = 'sgSampler';

const G = {
  base: (text = PROMPT) => { const g = defaultGraph(); set(g, 'pos', 'text', text); set(g, 'neg', 'text', 'blurry, low quality, watermark'); set(g, 'sampler', 'control_after_generate', 'fixed'); return g; },
  // A workflow shared by someone else: it uses the XY Plot custom nodes.
  xy: ({ x = 'cfg', xv = '4, 7, 10', y = 'none', yv = '' } = {}) => {
    const g = drop(drop(G.base(), 'sampler'), 'decode'); move(g, 'save', 1300, 189);
    add(g, makeNode('XYPlotSampler', 863, 120, { control_after_generate: 'fixed', x_axis: x, x_values: xv, y_axis: y, y_values: yv }, 'xy'));
    return wire(g, [['ckpt', 0, 'xy', 'model'], ['pos', 0, 'xy', 'positive'], ['neg', 0, 'xy', 'negative'], ['latent', 0, 'xy', 'latent_image'], ['ckpt', 2, 'xy', 'vae'], ['xy', 0, 'save', 'images']]);
  },
  photoreal: () => { const g = G.base('a cat sitting in a forest, detailed'); set(g, 'ckpt', 'ckpt_name', NEW_CKPT); set(g, 'latent', 'width', 1024); set(g, 'latent', 'height', 1024); set(g, 'sampler', 'cfg', 6); return g; },
  // A wide layout: the VAE has a long way to go.
  wide: (reroute = false) => {
    const g = G.base(); move(g, 'ckpt', 26, 700); move(g, 'decode', 1700, 188); move(g, 'save', 1960, 189);
    g.links = g.links.filter(l => !(l.to === 'decode' && l.input === 'vae'));
    if (reroute) { add(g, makeNode('Reroute', 1580, 420, {}, 'rr')); wire(g, [['ckpt', 2, 'rr', 'input'], ['rr', 0, 'decode', 'vae']]); }
    return g;
  },
  // Two samplers that should share a seed, to compare them fairly.
  twoSamplers: (shared = false) => {
    const g = G.base(); set(g, 'sampler', 'control_after_generate', 'randomize'); set(g, 'sampler', 'seed', 1234); move(g, 'latent', 473, 640);
    add(g, makeNode('KSampler', 863, 560, { seed: 98765, control_after_generate: 'randomize', sampler_name: 'dpmpp_2m', scheduler: 'karras' }, 's2'), makeNode('VAEDecode', 1209, 560, {}, 'd2'), makeNode('SaveImage', 1451, 560, { filename_prefix: 'dpmpp_2m' }, 'save2'));
    set(g, 'save', 'filename_prefix', 'euler');
    wire(g, [['ckpt', 0, 's2', 'model'], ['pos', 0, 's2', 'positive'], ['neg', 0, 's2', 'negative'], ['latent', 0, 's2', 'latent_image'], ['s2', 0, 'd2', 'samples'], ['ckpt', 2, 'd2', 'vae'], ['d2', 0, 'save2', 'images']]);
    if (shared) { add(g, makeNode('PrimitiveInt', 470, 40, { value: 42, control_after_generate: 'increment' }, 'seed')); wire(g, [['seed', 0, 'sampler', 'seed'], ['seed', 0, 's2', 'seed']]); }
    return g;
  },
  // Two models, two prompt boxes that should say the same thing.
  twoModels: (shared = false) => {
    const g = G.base('a cat sitting in the snow, detailed'); set(g, 'neg', 'text', 'blurry, low quality');
    add(g, makeNode('CheckpointLoaderSimple', 26, 980, { ckpt_name: 'sd_xl_base_1.0.safetensors' }, 'ckpt2'), makeNode('CLIPTextEncode', 415, 900, { text: 'a cat sitting in a forest, detailed' }, 'pos2'), makeNode('CLIPTextEncode', 415, 1100, { text: 'blurry, low quality' }, 'neg2'), makeNode('EmptyLatentImage', 473, 1300, { width: 1024, height: 1024 }, 'latent2'),
      makeNode('KSampler', 863, 900, { control_after_generate: 'fixed', cfg: 7 }, 's2'), makeNode('VAEDecode', 1209, 900, {}, 'd2'), makeNode('SaveImage', 1451, 900, { filename_prefix: 'sdxl' }, 'save2'));
    set(g, 'save', 'filename_prefix', 'sd15');
    wire(g, [['ckpt2', 1, 'pos2', 'clip'], ['ckpt2', 1, 'neg2', 'clip'], ['ckpt2', 0, 's2', 'model'], ['pos2', 0, 's2', 'positive'], ['neg2', 0, 's2', 'negative'], ['latent2', 0, 's2', 'latent_image'], ['s2', 0, 'd2', 'samples'], ['ckpt2', 2, 'd2', 'vae'], ['d2', 0, 'save2', 'images']]);
    if (shared) { add(g, makeNode('PrimitiveStringMultiline', -60, 560, { value: 'a cat sitting in a forest, detailed' }, 'text')); wire(g, [['text', 0, 'pos', 'text'], ['text', 0, 'pos2', 'text']]); }
    return g;
  },
  subgraph: () => { const g = G.base(); makeSubgraph(g, ['sampler', 'decode'], { sid: SG_SAMPLER, nid: 'sg1', name: 'Sampler' }); return g; },
  // One subgraph definition, used twice: two prompts through the same sampler settings.
  sgTwice: ({ sampler = 'euler', scheduler = 'normal' } = {}) => {
    const g = G.base('a cat sitting in a landscape, detailed'); set(g, 'sampler', 'sampler_name', sampler); set(g, 'sampler', 'scheduler', scheduler);
    makeSubgraph(g, ['sampler', 'decode'], { sid: SG_SAMPLER, nid: 'sg1', name: 'Sampler' });
    add(g, makeNode('CLIPTextEncode', 415, 760, { text: PROMPT }, 'pos2'), { id: 'sg2', type: SUBGRAPH + SG_SAMPLER, x: 1000, y: 700, mode: 0, widgets: {}, title: null, collapsed: false }, makeNode('SaveImage', 1451, 700, { filename_prefix: 'lighthouse' }, 'save2'));
    set(g, 'save', 'filename_prefix', 'cat');
    return wire(g, [['ckpt', 1, 'pos2', 'clip'], ['ckpt', 0, 'sg2', 'model'], ['pos2', 0, 'sg2', 'positive'], ['neg', 0, 'sg2', 'negative'], ['latent', 0, 'sg2', 'latent_image'], ['ckpt', 2, 'sg2', 'vae'], ['sg2', 0, 'save2', 'images']]);
  },
};

export const UI = {
  headline: L('Workflows that travel, <span>graphs that stay readable.</span>', 'Workflows que viatgen, <span>grafs que es poden llegir.</span>', 'Workflows que viajan, <span>grafos que se pueden leer.</span>'),
  lead: L('Everything around the nodes: opening a workflow from someone else and installing what it needs with the Manager, missing models, reroutes, Int and String nodes that drive several widgets at once, subgraphs that pack a block of nodes into one, and XY grids to compare settings side by side.', 'Tot el que envolta els nodes: obrir el workflow d’una altra persona i instal·lar el que necessita amb el Manager, models que falten, reroutes, nodes Int i String que governen diversos widgets alhora, subgraphs que empaqueten un bloc de nodes en un de sol, i graelles XY per comparar paràmetres un al costat de l’altre.', 'Todo lo que rodea a los nodos: abrir el workflow de otra persona e instalar lo que necesita con el Manager, modelos que faltan, reroutes, nodos Int y String que gobiernan varios widgets a la vez, subgraphs que empaquetan un bloque de nodos en uno solo, y rejillas XY para comparar parámetros uno al lado del otro.'),
  loraVsCn: L('Tidy graph, reusable graph', 'Graf endreçat, graf reutilitzable', 'Grafo ordenado, grafo reutilizable'),
  type_INT: L('a whole number (seed, steps…)', 'un nombre enter (seed, steps…)', 'un número entero (seed, steps…)'), type_FLOAT: L('a decimal number (cfg, denoise…)', 'un nombre decimal (cfg, denoise…)', 'un número decimal (cfg, denoise…)'), type_STRING: L('text (a prompt, a file name…)', 'text (un prompt, un nom de fitxer…)', 'texto (un prompt, un nombre de archivo…)'), 'type_*': L('anything: a reroute takes the type it receives', 'qualsevol cosa: un reroute pren el tipus que rep', 'cualquier cosa: un reroute toma el tipo que recibe'),
};
const T3 = (h, rows, foot) => `<table class="c-cmp"><tr><th></th><th>${h[0]}</th><th>${h[1]}</th></tr>${rows.map(r => `<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</table><p>${foot}</p>`;
UI.loraVsCnBody = L(
  T3(['What', 'When'], [['<b>Group</b>', 'a coloured frame', 'to label a part'], ['<b>Reroute</b>', 'a dot on a link', 'long or crossing links'], ['<b>Primitive</b>', 'one value, many widgets', 'shared seed or prompt'], ['<b>Subgraph</b>', 'nodes packed into one', 'a block you reuse']], 'Groups and reroutes only change how the graph looks; primitives and subgraphs change how you work with it.'),
  T3(['Què', 'Quan'], [['<b>Grup</b>', 'un marc de color', 'per posar nom a una part'], ['<b>Reroute</b>', 'un punt en un enllaç', 'enllaços llargs o que es creuen'], ['<b>Primitiva</b>', 'un valor, molts widgets', 'seed o prompt compartit'], ['<b>Subgraph</b>', 'nodes empaquetats en un', 'un bloc que reutilitzes']], 'Els grups i els reroutes només canvien com es veu el graf; les primitives i els subgraphs canvien com hi treballes.'),
  T3(['Qué', 'Cuándo'], [['<b>Grupo</b>', 'un marco de color', 'para poner nombre a una parte'], ['<b>Reroute</b>', 'un punto en un enlace', 'enlaces largos o que se cruzan'], ['<b>Primitiva</b>', 'un valor, muchos widgets', 'seed o prompt compartido'], ['<b>Subgraph</b>', 'nodos empaquetados en uno', 'un bloque que reutilizas']], 'Los grupos y los reroutes solo cambian cómo se ve el grafo; las primitivas y los subgraphs cambian cómo trabajas con él.'));

export const DOCS = {
  Reroute: { short: L('A dot that carries a link of any type.', 'Un punt que porta un enllaç de qualsevol tipus.', 'Un punto que lleva un enlace de cualquier tipo.'), long: L('Use it to route long links around the graph. It takes the type of what you connect to it. Right-click a link’s middle dot › Add Reroute.', 'Serveix per portar enllaços llargs pel graf. Pren el tipus del que hi connectes. Clic dret al punt del mig d’un enllaç › Add Reroute.', 'Sirve para llevar enlaces largos por el grafo. Toma el tipo de lo que le conectas. Clic derecho en el punto central de un enlace › Add Reroute.') },
  PrimitiveInt: { short: L('A whole number you can link to INT widgets.', 'Un nombre enter que pots enllaçar a widgets INT.', 'Un número entero que puedes enlazar a widgets INT.'), long: L('Drag its INT output onto the socket of a widget (it appears when you hover over the node): the widget shows the link and takes this value. One Int can drive the seed of several samplers; its control_after_generate changes it for every run.', 'Arrossega la seva sortida INT al socket d’un widget (apareix quan passes per sobre del node): el widget mostra l’enllaç i pren aquest valor. Un Int pot governar el seed de diversos samplers; el seu control_after_generate el canvia a cada execució.', 'Arrastra su salida INT al socket de un widget (aparece al pasar por encima del nodo): el widget muestra el enlace y toma este valor. Un Int puede gobernar el seed de varios samplers; su control_after_generate lo cambia en cada ejecución.') },
  PrimitiveFloat: { short: L('A decimal number for FLOAT widgets.', 'Un nombre decimal per a widgets FLOAT.', 'Un número decimal para widgets FLOAT.') },
  PrimitiveString: { short: L('One line of text for STRING widgets.', 'Una línia de text per a widgets STRING.', 'Una línea de texto para widgets STRING.') },
  PrimitiveStringMultiline: { short: L('A text box you can link to several prompts.', 'Una caixa de text que pots enllaçar a diversos prompts.', 'Una caja de texto que puedes enlazar a varios prompts.'), long: L('Link its STRING output to the text socket of CLIP Text Encode nodes: write the prompt once, use it everywhere.', 'Enllaça la seva sortida STRING al socket text dels CLIP Text Encode: escriu el prompt una vegada, fes-lo servir a tot arreu.', 'Enlaza su salida STRING al socket text de los CLIP Text Encode: escribe el prompt una vez, úsalo en todas partes.') },
  XYPlotSampler: { short: L('A KSampler that makes a grid of variations.', 'Un KSampler que fa una graella de variacions.', 'Un KSampler que hace una rejilla de variaciones.'), long: L('Custom node (xy-plot). x_axis and y_axis choose which settings change; x_values and y_values list the values, separated by commas. Every cell is a full generation: a 4 × 3 grid takes twelve times as long.', 'Custom node (xy-plot). x_axis i y_axis trien quins paràmetres canvien; x_values i y_values en llisten els valors, separats per comes. Cada cel·la és una generació sencera: una graella de 4 × 3 triga dotze vegades més.', 'Custom node (xy-plot). x_axis e y_axis eligen qué parámetros cambian; x_values e y_values listan los valores, separados por comas. Cada celda es una generación entera: una rejilla de 4 × 3 tarda doce veces más.') },
};

export const STAGES = [
  {
    id: 'shared', name: L('Shared workflows', 'Workflows compartits', 'Workflows compartidos'), sub: L('Manager · missing nodes · models', 'Manager · nodes que falten · models', 'Manager · nodos que faltan · modelos'),
    steps: [
      {
        title: L('Missing custom nodes', 'Custom nodes que falten', 'Custom nodes que faltan'),
        task: L('Someone sent you this workflow. One node is red: it comes from a custom node pack you do not have. Install it with the Manager, restart and run.', 'Algú t’ha passat aquest workflow. Hi ha un node vermell: és d’un paquet de custom nodes que no tens. Instal·la’l amb el Manager, reinicia i executa.', 'Alguien te ha pasado este workflow. Hay un nodo rojo: es de un paquete de custom nodes que no tienes. Instálalo con el Manager, reinicia y ejecuta.'),
        concept: L('A workflow is a list of nodes by <b>class name</b>. If a node comes from a <b>custom node pack</b> that is not installed, ComfyUI cannot build it: it shows it in red and warns you when the workflow opens. The <b>Manager</b> reads the missing class names and finds the packs that provide them (<i>Install Missing Custom Nodes</i>). New nodes are Python code that loads when ComfyUI starts, so you have to <b>restart</b>. Custom nodes run on your computer with your permissions: install packs you trust.', 'Un workflow és una llista de nodes pel seu <b>nom de classe</b>. Si un node ve d’un <b>paquet de custom nodes</b> que no està instal·lat, ComfyUI no el pot construir: el mostra en vermell i t’avisa quan obres el workflow. El <b>Manager</b> llegeix els noms de classe que falten i troba els paquets que els tenen (<i>Install Missing Custom Nodes</i>). Els nodes nous són codi Python que es carrega quan arrenca ComfyUI, per això cal <b>reiniciar</b>. Els custom nodes s’executen al teu ordinador amb els teus permisos: instal·la paquets de confiança.', 'Un workflow es una lista de nodos por su <b>nombre de clase</b>. Si un nodo viene de un <b>paquete de custom nodes</b> que no está instalado, ComfyUI no lo puede construir: lo muestra en rojo y te avisa al abrir el workflow. El <b>Manager</b> lee los nombres de clase que faltan y encuentra los paquetes que los tienen (<i>Install Missing Custom Nodes</i>). Los nodos nuevos son código Python que se carga al arrancar ComfyUI, por eso hay que <b>reiniciar</b>. Los custom nodes se ejecutan en tu ordenador con tus permisos: instala paquetes de confianza.'),
        how: [L('Read the warning and close it. Run: “node type not found”.', 'Llegeix l’avís i tanca’l. Executa: “node type not found”.', 'Lee el aviso y ciérralo. Ejecuta: “node type not found”.'), L('<b>Manager</b> (top bar) › <b>Install Missing Custom Nodes</b> › Install.', '<b>Manager</b> (barra de dalt) › <b>Install Missing Custom Nodes</b> › Install.', '<b>Manager</b> (barra de arriba) › <b>Install Missing Custom Nodes</b> › Install.'), L('<b>Restart</b>. The node is no longer red: run.', '<b>Restart</b>. El node ja no és vermell: executa.', '<b>Restart</b>. El nodo ya no es rojo: ejecuta.')],
        note: L('The Manager is installed with ComfyUI Desktop and the portable version; in a manual install it is a custom node itself. The Node Library also lists the nodes of every installed pack, with a 🦊 badge.', 'El Manager ve instal·lat amb ComfyUI Desktop i la versió portable; en una instal·lació manual és un custom node més. La Node Library també llista els nodes de cada paquet instal·lat, amb una etiqueta 🦊.', 'El Manager viene instalado con ComfyUI Desktop y la versión portable; en una instalación manual es un custom node más. La Node Library también lista los nodos de cada paquete instalado, con una etiqueta 🦊.'),
        missing: ['xy-plot'],
        starter: () => G.xy(), solution: () => G.xy(),
        goals: [goal(L('Opened the Manager', 'Has obert el Manager', 'Has abierto el Manager'), (g, c) => c.flags.managerOpen), goal(L('Installed the pack and restarted', 'Has instal·lat el paquet i reiniciat', 'Has instalado el paquete y reiniciado'), (g, c) => c.flags['ready_xy-plot']), goal(L('The shared workflow runs', 'El workflow compartit funciona', 'El workflow compartido funciona'), (g, c) => xys(c).length > 0)],
      },
      {
        title: L('Missing models', 'Models que falten', 'Modelos que faltan'),
        task: L('This workflow uses a checkpoint you do not have. Run it, read the error, download the model with the Model Manager and run it again.', 'Aquest workflow fa servir un checkpoint que no tens. Executa’l, llegeix l’error, descarrega el model amb el Model Manager i torna a executar.', 'Este workflow usa un checkpoint que no tienes. Ejecútalo, lee el error, descarga el modelo con el Model Manager y vuelve a ejecutar.'),
        concept: L('A workflow stores the <b>file names</b> of its models, not the models. If the file is not in the right folder (<code>models/checkpoints</code>, <code>models/loras</code>…), the widget value is not in the list and the run stops with <i>Value not in list</i>. Download it to that folder (the Model Manager, or the link that comes with the workflow) and refresh the lists with <b>R</b>. If you cannot get it, pick a similar model you have: same family (SD 1.5, SDXL, Flux) and the same size.', 'Un workflow guarda els <b>noms de fitxer</b> dels seus models, no els models. Si el fitxer no és a la carpeta bona (<code>models/checkpoints</code>, <code>models/loras</code>…), el valor del widget no és a la llista i l’execució s’atura amb <i>Value not in list</i>. Descarrega’l a aquella carpeta (el Model Manager, o l’enllaç que ve amb el workflow) i actualitza les llistes amb <b>R</b>. Si no el pots aconseguir, tria’n un de semblant que tinguis: la mateixa família (SD 1.5, SDXL, Flux) i la mateixa mida.', 'Un workflow guarda los <b>nombres de archivo</b> de sus modelos, no los modelos. Si el archivo no está en la carpeta correcta (<code>models/checkpoints</code>, <code>models/loras</code>…), el valor del widget no está en la lista y la ejecución se para con <i>Value not in list</i>. Descárgalo en esa carpeta (el Model Manager, o el enlace que viene con el workflow) y actualiza las listas con <b>R</b>. Si no lo puedes conseguir, elige uno parecido que tengas: la misma familia (SD 1.5, SDXL, Flux) y el mismo tamaño.'),
        how: [L('Run: <i>Value not in list: ckpt_name</i>.', 'Executa: <i>Value not in list: ckpt_name</i>.', 'Ejecuta: <i>Value not in list: ckpt_name</i>.'), L('<b>Manager › Model Manager</b> › Download <b>photoreal_xl_v2</b>.', '<b>Manager › Model Manager</b> › Download <b>photoreal_xl_v2</b>.', '<b>Manager › Model Manager</b> › Download <b>photoreal_xl_v2</b>.'), L('Run again.', 'Torna a executar.', 'Vuelve a ejecutar.')],
        note: L('Big models live outside ComfyUI too: extra_model_paths.yaml lets several programs share one models folder.', 'Els models grans també poden viure fora de ComfyUI: extra_model_paths.yaml permet que diversos programes comparteixin una carpeta de models.', 'Los modelos grandes también pueden vivir fuera de ComfyUI: extra_model_paths.yaml permite que varios programas compartan una carpeta de modelos.'),
        missingModels: [NEW_CKPT],
        starter: G.photoreal, solution: G.photoreal,
        goals: [goal(L('Saw “Value not in list”', 'Has vist “Value not in list”', 'Has visto “Value not in list”'), (g, c) => c.flags.errorSeen), goal(L('Downloaded the model', 'Has descarregat el model', 'Has descargado el modelo'), (g, c) => c.flags[`dl_${NEW_CKPT}`]), goal(L('Ran with the workflow’s own model', 'Has executat amb el model del workflow', 'Has ejecutado con el modelo del workflow'), (g, c) => c.history.some(h => h.ckpt === NEW_CKPT))],
      },
    ],
  },
  {
    id: 'wiring', name: L('Tidy wiring', 'Cablejat endreçat', 'Cableado ordenado'), sub: L('Reroutes · Int · String', 'Reroutes · Int · String', 'Reroutes · Int · String'),
    steps: [
      {
        title: L('Reroutes', 'Reroutes', 'Reroutes'),
        task: L('The VAE Decode has no VAE, and the checkpoint is far away. Bring the VAE through a Reroute placed near the decoder, then run.', 'El VAE Decode no té VAE, i el checkpoint és lluny. Porta el VAE a través d’un Reroute posat a prop del descodificador, i executa.', 'El VAE Decode no tiene VAE, y el checkpoint está lejos. Lleva el VAE a través de un Reroute puesto cerca del decodificador, y ejecuta.'),
        concept: L('A <b>Reroute</b> is a dot that a link passes through. It does nothing to the data: it takes whatever type you connect and passes it on. Use it to send long links around nodes instead of across them, or to make one output easy to reach from several places. A clean graph is one you can read a month later.', 'Un <b>Reroute</b> és un punt per on passa un enllaç. No fa res a les dades: pren el tipus que hi connectes i el passa. Serveix per fer passar els enllaços llargs pel voltant dels nodes en lloc de travessar-los, o per tenir una sortida a mà des de diversos llocs. Un graf net és un graf que pots llegir d’aquí a un mes.', 'Un <b>Reroute</b> es un punto por donde pasa un enlace. No hace nada a los datos: toma el tipo que le conectas y lo pasa. Sirve para que los enlaces largos rodeen los nodos en lugar de atravesarlos, o para tener una salida a mano desde varios sitios. Un grafo limpio es un grafo que puedes leer dentro de un mes.'),
        how: [L('Double-click the canvas near VAE Decode, search <b>Reroute</b>.', 'Doble clic al canvas a prop del VAE Decode, cerca <b>Reroute</b>.', 'Doble clic en el canvas cerca del VAE Decode, busca <b>Reroute</b>.'), L('Load Checkpoint › VAE → the Reroute; the Reroute → vae of VAE Decode.', 'Load Checkpoint › VAE → el Reroute; el Reroute → vae del VAE Decode.', 'Load Checkpoint › VAE → el Reroute; el Reroute → vae del VAE Decode.'), L('Run.', 'Executa.', 'Ejecuta.')],
        note: L('On an existing link, click its middle dot › <b>Add Reroute</b>. Links can also be hidden with the link button at the bottom right.', 'En un enllaç que ja existeix, clica el punt del mig › <b>Add Reroute</b>. Els enllaços també es poden amagar amb el botó d’enllaç de baix a la dreta.', 'En un enlace que ya existe, haz clic en el punto central › <b>Add Reroute</b>. Los enlaces también se pueden ocultar con el botón de enlace de abajo a la derecha.'),
        starterFails: true, starter: () => G.wide(), solution: () => G.wide(true),
        goals: [goal(L('The VAE reaches VAE Decode through a Reroute', 'El VAE arriba al VAE Decode a través d’un Reroute', 'El VAE llega al VAE Decode a través de un Reroute'), g => N(g, 'VAEDecode').some(d => fromOf(g, d.id, 'vae')?.type === 'Reroute')), goal(L('The workflow runs', 'El workflow funciona', 'El workflow funciona'), (g, c) => c.history.some(h => h.graph?.nodes?.some(n => n.type === 'Reroute')))],
      },
      {
        title: L('One seed, two samplers', 'Un seed, dos samplers', 'Un seed, dos samplers'),
        task: L('Two samplers compare euler and dpmpp_2m, but each has its own random seed, so the comparison is not fair. Drive both seeds from one Int node and run twice.', 'Dos samplers comparen euler i dpmpp_2m, però cadascun té el seu seed aleatori, i la comparació no és justa. Governa els dos seeds des d’un node Int i executa dues vegades.', 'Dos samplers comparan euler y dpmpp_2m, pero cada uno tiene su seed aleatorio, y la comparación no es justa. Gobierna los dos seeds desde un nodo Int y ejecuta dos veces.'),
        concept: L('Every widget has an input socket: hover over a node and a dot appears next to each widget. Link a <b>primitive</b> (Int, Float, String) to it and the widget takes its value from the link. One <b>Int</b> linked to the seed of both samplers keeps them equal, and its own <i>control_after_generate</i> (increment) gives a new shared seed on every run. Now the only difference between the two pictures is the sampler.', 'Cada widget té un socket d’entrada: passa per sobre d’un node i surt un punt al costat de cada widget. Enllaça-hi una <b>primitiva</b> (Int, Float, String) i el widget pren el valor de l’enllaç. Un <b>Int</b> enllaçat al seed dels dos samplers els manté iguals, i el seu propi <i>control_after_generate</i> (increment) dona un seed nou i compartit a cada execució. Ara l’única diferència entre les dues imatges és el sampler.', 'Cada widget tiene un socket de entrada: pasa por encima de un nodo y sale un punto al lado de cada widget. Enlaza una <b>primitiva</b> (Int, Float, String) y el widget toma el valor del enlace. Un <b>Int</b> enlazado al seed de los dos samplers los mantiene iguales, y su propio <i>control_after_generate</i> (increment) da un seed nuevo y compartido en cada ejecución. Ahora la única diferencia entre las dos imágenes es el sampler.'),
        how: [L('Add an <b>Int</b> node (utils › primitive). control_after_generate: <b>increment</b>.', 'Afegeix un node <b>Int</b> (utils › primitive). control_after_generate: <b>increment</b>.', 'Añade un nodo <b>Int</b> (utils › primitive). control_after_generate: <b>increment</b>.'), L('Drag its INT onto the <b>seed</b> socket of each KSampler (hover the node to see it).', 'Arrossega el seu INT al socket <b>seed</b> de cada KSampler (passa per sobre del node per veure’l).', 'Arrastra su INT al socket <b>seed</b> de cada KSampler (pasa por encima del nodo para verlo).'), L('Run twice and compare each pair in the Queue.', 'Executa dues vegades i compara cada parella a la Queue.', 'Ejecuta dos veces y compara cada pareja en la Queue.')],
        note: L('Older workflows do this with “Convert widget to input” and a Primitive node; current ComfyUI shows a socket on every widget.', 'Els workflows antics ho fan amb “Convert widget to input” i un node Primitive; el ComfyUI actual mostra un socket a cada widget.', 'Los workflows antiguos lo hacen con “Convert widget to input” y un nodo Primitive; el ComfyUI actual muestra un socket en cada widget.'),
        starter: () => G.twoSamplers(), solution: () => G.twoSamplers(true),
        goals: [goal(L('One Int drives the seed of both KSamplers', 'Un Int governa el seed dels dos KSamplers', 'Un Int gobierna el seed de los dos KSamplers'), g => drivenBy(g, 'PrimitiveInt', 'KSampler', 'seed') >= 2), goal(L('A fair pair: same seed, two samplers', 'Una parella justa: mateix seed, dos samplers', 'Una pareja justa: mismo seed, dos samplers'), (g, c) => pairs(c).length >= 1), goal(L('Two runs, two shared seeds', 'Dues execucions, dos seeds compartits', 'Dos ejecuciones, dos seeds compartidos'), (g, c) => new Set(pairs(c)).size >= 2)],
      },
      {
        title: L('One prompt, two models', 'Un prompt, dos models', 'Un prompt, dos modelos'),
        task: L('This graph compares an SD 1.5 and an SDXL checkpoint, but the two prompt boxes already say different things. Write the prompt once in a String (Multiline) node and link it to both.', 'Aquest graf compara un checkpoint SD 1.5 i un SDXL, però les dues caixes de prompt ja diuen coses diferents. Escriu el prompt una sola vegada en un node String (Multiline) i enllaça’l a totes dues.', 'Este grafo compara un checkpoint SD 1.5 y uno SDXL, pero las dos cajas de prompt ya dicen cosas distintas. Escribe el prompt una sola vez en un nodo String (Multiline) y enlázalo a las dos.'),
        concept: L('Each checkpoint needs its own CLIP Text Encode, because each model has its own text encoder. The <b>text</b> itself can come from one place: a <b>String (Multiline)</b> linked to the text socket of both encoders. Change it once and both models get it. The same idea works for the negative prompt, the file name prefix or any setting you repeat.', 'Cada checkpoint necessita el seu CLIP Text Encode, perquè cada model té el seu text encoder. El <b>text</b>, en canvi, pot venir d’un sol lloc: un <b>String (Multiline)</b> enllaçat al socket text dels dos encoders. El canvies una vegada i el reben tots dos models. La mateixa idea serveix per al prompt negatiu, el prefix del nom de fitxer o qualsevol paràmetre que repeteixis.', 'Cada checkpoint necesita su CLIP Text Encode, porque cada modelo tiene su text encoder. El <b>texto</b>, en cambio, puede venir de un solo sitio: un <b>String (Multiline)</b> enlazado al socket text de los dos encoders. Lo cambias una vez y lo reciben los dos modelos. La misma idea sirve para el prompt negativo, el prefijo del nombre de archivo o cualquier parámetro que repitas.'),
        how: [L('Add <b>String (Multiline)</b> and write the prompt.', 'Afegeix <b>String (Multiline)</b> i escriu el prompt.', 'Añade <b>String (Multiline)</b> y escribe el prompt.'), L('Its STRING → the <b>text</b> socket of both positive CLIP Text Encode nodes.', 'El seu STRING → el socket <b>text</b> dels dos CLIP Text Encode positius.', 'Su STRING → el socket <b>text</b> de los dos CLIP Text Encode positivos.'), L('Run.', 'Executa.', 'Ejecuta.')],
        note: L('A linked text box shows “⟵ link”: to edit the prompt, edit the String node.', 'Una caixa de text enllaçada mostra “⟵ link”: per editar el prompt, edita el node String.', 'Una caja de texto enlazada muestra “⟵ link”: para editar el prompt, edita el nodo String.'),
        starter: () => G.twoModels(), solution: () => G.twoModels(true),
        goals: [goal(L('One String drives both prompts', 'Un String governa els dos prompts', 'Un String gobierna los dos prompts'), g => g.nodes.filter(n => n.type === 'CLIPTextEncode' && ['PrimitiveString', 'PrimitiveStringMultiline'].includes(fromOf(g, n.id, 'text')?.type)).length >= 2), goal(L('Both models drew the same prompt', 'Els dos models han dibuixat el mateix prompt', 'Los dos modelos han dibujado el mismo prompt'), (g, c) => c.history.some(a => c.history.some(b => a !== b && a.ckpt !== b.ckpt && a.posText === b.posText && a.arch !== b.arch)))],
      },
    ],
  },
  {
    id: 'subgraphs', name: L('Subgraphs', 'Subgraphs', 'Subgraphs'), sub: L('Pack · open · reuse', 'Empaquetar · obrir · reutilitzar', 'Empaquetar · abrir · reutilizar'),
    steps: [
      {
        title: L('Make a subgraph', 'Fes un subgraph', 'Haz un subgraph'),
        task: L('Pack the KSampler and the VAE Decode into one subgraph node and run.', 'Empaqueta el KSampler i el VAE Decode en un sol node subgraph i executa.', 'Empaqueta el KSampler y el VAE Decode en un solo nodo subgraph y ejecuta.'),
        concept: L('A <b>subgraph</b> is a node that contains a graph. Select some nodes and <b>Convert to Subgraph</b>: they move inside, and every link that crossed the edge becomes an input or output of the new node. The workflow runs exactly the same, but reads as a few big blocks instead of dozens of nodes. Double-click it (or ⧉) to open it; the bar at the top takes you back.', 'Un <b>subgraph</b> és un node que conté un graf. Selecciona uns quants nodes i <b>Convert to Subgraph</b>: passen a dins, i cada enllaç que travessava la vora es converteix en una entrada o una sortida del node nou. El workflow funciona exactament igual, però es llegeix com uns quants blocs grans en lloc de dotzenes de nodes. Fes-hi doble clic (o ⧉) per obrir-lo; la barra de dalt et torna enrere.', 'Un <b>subgraph</b> es un nodo que contiene un grafo. Selecciona unos cuantos nodos y <b>Convert to Subgraph</b>: pasan dentro, y cada enlace que cruzaba el borde se convierte en una entrada o una salida del nodo nuevo. El workflow funciona exactamente igual, pero se lee como unos cuantos bloques grandes en lugar de docenas de nodos. Haz doble clic (o ⧉) para abrirlo; la barra de arriba te devuelve.'),
        how: [L('Ctrl-click KSampler and VAE Decode (or Ctrl-drag a box).', 'Ctrl-clic al KSampler i al VAE Decode (o Ctrl-arrossega un requadre).', 'Ctrl-clic en el KSampler y el VAE Decode (o Ctrl-arrastra un recuadro).'), L('Right-click › <b>Convert to Subgraph</b>. Double-click its title to rename it “Sampler”.', 'Clic dret › <b>Convert to Subgraph</b>. Doble clic al títol per dir-li “Sampler”.', 'Clic derecho › <b>Convert to Subgraph</b>. Doble clic en el título para llamarlo “Sampler”.'), L('Open it, look inside, exit, and run.', 'Obre’l, mira-hi dins, surt i executa.', 'Ábrelo, mira dentro, sal y ejecuta.')],
        note: L('Unpack Subgraph puts the nodes back. Subgraphs can be saved and shared like any workflow, and nested inside other subgraphs (this lab keeps one level).', 'Unpack Subgraph torna a treure els nodes. Els subgraphs es poden desar i compartir com qualsevol workflow, i posar dins d’altres subgraphs (aquest lab es queda en un nivell).', 'Unpack Subgraph vuelve a sacar los nodos. Los subgraphs se pueden guardar y compartir como cualquier workflow, y poner dentro de otros subgraphs (este lab se queda en un nivel).'),
        starter: () => G.base(), solution: G.subgraph,
        goals: [goal(L('A subgraph with the KSampler inside', 'Un subgraph amb el KSampler a dins', 'Un subgraph con el KSampler dentro'), g => g.nodes.some(n => isSubgraphNode(n) && g.subgraphs?.[n.type.slice(SUBGRAPH.length)]?.nodes.some(m => m.type === 'KSampler'))), goal(L('Opened it', 'L’has obert', 'Lo has abierto'), (g, c) => c.flags.enteredSubgraph, true), goal(L('It runs as before', 'Funciona igual que abans', 'Funciona igual que antes'), (g, c) => c.history.some(h => h.graph?.nodes?.some(isSubgraphNode)))],
      },
      {
        title: L('Edit once, change everywhere', 'Edita una vegada, canvia a tot arreu', 'Edita una vez, cambia en todas partes'),
        task: L('Both pictures go through the same “Sampler” subgraph. Open it, set sampler_name dpmpp_2m and scheduler karras, exit and run: both pictures change.', 'Les dues imatges passen pel mateix subgraph “Sampler”. Obre’l, posa sampler_name dpmpp_2m i scheduler karras, surt i executa: canvien totes dues imatges.', 'Las dos imágenes pasan por el mismo subgraph “Sampler”. Ábrelo, pon sampler_name dpmpp_2m y scheduler karras, sal y ejecuta: cambian las dos imágenes.'),
        concept: L('Two nodes made from the same subgraph share <b>one definition</b>. Change a setting inside and every copy uses it on the next run, like a function in code. That is the difference with copy-paste: pasted nodes are independent, and fixing one leaves the others behind. Build a block once (your sampler, your upscale, your detailer), reuse it everywhere, and fix it in one place.', 'Dos nodes fets del mateix subgraph comparteixen <b>una sola definició</b>. Canvia un paràmetre a dins i totes les còpies el fan servir a la propera execució, com una funció en programació. Aquesta és la diferència amb copiar i enganxar: els nodes enganxats són independents, i arreglar-ne un deixa els altres enrere. Construeix un bloc una vegada (el teu sampler, el teu upscale, el teu detailer), reutilitza’l a tot arreu i arregla’l en un sol lloc.', 'Dos nodos hechos del mismo subgraph comparten <b>una sola definición</b>. Cambia un parámetro dentro y todas las copias lo usan en la siguiente ejecución, como una función en programación. Esa es la diferencia con copiar y pegar: los nodos pegados son independientes, y arreglar uno deja los otros atrás. Construye un bloque una vez (tu sampler, tu upscale, tu detailer), reutilízalo en todas partes y arréglalo en un solo sitio.'),
        how: [L('Double-click either “Sampler” node.', 'Doble clic a qualsevol dels nodes “Sampler”.', 'Doble clic en cualquiera de los nodos “Sampler”.'), L('Inside: KSampler › sampler_name <b>dpmpp_2m</b>, scheduler <b>karras</b>.', 'A dins: KSampler › sampler_name <b>dpmpp_2m</b>, scheduler <b>karras</b>.', 'Dentro: KSampler › sampler_name <b>dpmpp_2m</b>, scheduler <b>karras</b>.'), L('<b>Exit subgraph</b> and run.', '<b>Surt del subgraph</b> i executa.', '<b>Sal del subgraph</b> y ejecuta.')],
        note: L('Settings you change often can be promoted to the subgraph node as widgets, so you do not have to open it.', 'Els paràmetres que canvies sovint es poden promoure al node subgraph com a widgets, per no haver-lo d’obrir.', 'Los parámetros que cambias a menudo se pueden promover al nodo subgraph como widgets, para no tener que abrirlo.'),
        starter: () => G.sgTwice(), solution: () => G.sgTwice({ sampler: 'dpmpp_2m', scheduler: 'karras' }),
        goals: [goal(L('Opened the subgraph', 'Has obert el subgraph', 'Has abierto el subgraph'), (g, c) => c.flags.enteredSubgraph), goal(L('Both pictures use dpmpp_2m karras', 'Les dues imatges fan servir dpmpp_2m karras', 'Las dos imágenes usan dpmpp_2m karras'), (g, c) => { const ok = c.history.filter(h => h.sampler === 'dpmpp_2m' && h.scheduler === 'karras'); return ok.some(a => ok.some(b => a.posText !== b.posText)); })],
      },
    ],
  },
  {
    id: 'compare', name: L('Compare', 'Comparar', 'Comparar'), sub: L('XY grids', 'Graelles XY', 'Rejillas XY'),
    steps: [
      {
        title: L('An XY grid', 'Una graella XY', 'Una rejilla XY'),
        task: L('Replace the KSampler with XY Plot (KSampler): cfg on the X axis (3, 6, 9, 12) and sampler_name on the Y axis (euler, dpmpp_2m). Run.', 'Substitueix el KSampler per XY Plot (KSampler): cfg a l’eix X (3, 6, 9, 12) i sampler_name a l’eix Y (euler, dpmpp_2m). Executa.', 'Sustituye el KSampler por XY Plot (KSampler): cfg en el eje X (3, 6, 9, 12) y sampler_name en el eje Y (euler, dpmpp_2m). Ejecuta.'),
        concept: L('Changing one setting, running, changing it again and remembering what you saw is slow and unreliable. An <b>XY grid</b> runs every combination of two lists of values with everything else fixed, and lays the pictures out with labels. You see at a glance where cfg starts to burn, how many steps are enough, which sampler suits the model. It costs time: every cell is a full generation.', 'Canviar un paràmetre, executar, tornar-lo a canviar i recordar què has vist és lent i poc fiable. Una <b>graella XY</b> executa totes les combinacions de dues llistes de valors amb tota la resta fixa, i posa les imatges en ordre amb etiquetes. D’un cop d’ull veus on comença a cremar el cfg, quants steps són prou, quin sampler va bé amb el model. Costa temps: cada cel·la és una generació sencera.', 'Cambiar un parámetro, ejecutar, volverlo a cambiar y recordar lo que has visto es lento y poco fiable. Una <b>rejilla XY</b> ejecuta todas las combinaciones de dos listas de valores con todo lo demás fijo, y coloca las imágenes en orden con etiquetas. De un vistazo ves dónde empieza a quemar el cfg, cuántos steps son suficientes, qué sampler va bien con el modelo. Cuesta tiempo: cada celda es una generación entera.'),
        how: [L('Add <b>XY Plot (KSampler)</b>; connect model, positive, negative, latent_image, vae, and its IMAGE → Save Image. Delete KSampler and VAE Decode.', 'Afegeix <b>XY Plot (KSampler)</b>; connecta model, positive, negative, latent_image, vae, i el seu IMAGE → Save Image. Esborra el KSampler i el VAE Decode.', 'Añade <b>XY Plot (KSampler)</b>; conecta model, positive, negative, latent_image, vae, y su IMAGE → Save Image. Borra el KSampler y el VAE Decode.'), L('x_axis <b>cfg</b>, x_values <b>3, 6, 9, 12</b>; y_axis <b>sampler_name</b>, y_values <b>euler, dpmpp_2m</b>.', 'x_axis <b>cfg</b>, x_values <b>3, 6, 9, 12</b>; y_axis <b>sampler_name</b>, y_values <b>euler, dpmpp_2m</b>.', 'x_axis <b>cfg</b>, x_values <b>3, 6, 9, 12</b>; y_axis <b>sampler_name</b>, y_values <b>euler, dpmpp_2m</b>.'), L('Run and open the grid in the Queue.', 'Executa i obre la graella a la Queue.', 'Ejecuta y abre la rejilla en la Queue.')],
        note: L('Without custom nodes you can compare with a fixed seed, several KSamplers and a primitive per setting, as in the Tidy wiring stage.', 'Sense custom nodes pots comparar amb un seed fix, diversos KSamplers i una primitiva per paràmetre, com a l’etapa de cablejat endreçat.', 'Sin custom nodes puedes comparar con un seed fijo, varios KSamplers y una primitiva por parámetro, como en la etapa de cableado ordenado.'),
        starter: () => G.base(), solution: () => G.xy({ xv: '3, 6, 9, 12', y: 'sampler_name', yv: 'euler, dpmpp_2m' }),
        goals: [goal(L('A grid of at least three values', 'Una graella d’almenys tres valors', 'Una rejilla de al menos tres valores'), (g, c) => xys(c).some(h => h.xy.xs.length >= 3)), goal(L('Two axes: a second setting on Y', 'Dos eixos: un segon paràmetre a la Y', 'Dos ejes: un segundo parámetro en la Y'), (g, c) => xys(c).some(h => h.xy.yAxis !== 'none' && h.xy.ys.length >= 2 && h.xy.xs.length >= 2))],
      },
      {
        title: L('The setting or the seed?', 'El paràmetre o el seed?', '¿El parámetro o el seed?'),
        task: L('One seed can flatter a setting. Put seeds on the Y axis (three of them) and keep cfg on X: does the best cfg win with every seed?', 'Un seed pot afavorir un paràmetre. Posa seeds a l’eix Y (tres) i mantén el cfg a la X: el millor cfg guanya amb tots els seeds?', 'Un seed puede favorecer un parámetro. Pon seeds en el eje Y (tres) y mantén el cfg en la X: ¿el mejor cfg gana con todos los seeds?'),
        concept: L('A grid with one seed tells you what happened to <b>that</b> picture. With the seed on the other axis, each row is a different starting noise: a setting that looks best in every row is a real choice; one that wins only in one row was luck. Pick the value that holds up, then go back to a single KSampler with it.', 'Una graella amb un sol seed et diu què ha passat amb <b>aquella</b> imatge. Amb el seed a l’altre eix, cada fila és un soroll inicial diferent: un paràmetre que surt millor a totes les files és una tria de debò; un que només guanya en una fila era sort. Tria el valor que aguanta i torna a un sol KSampler amb ell.', 'Una rejilla con un solo seed te dice qué ha pasado con <b>esa</b> imagen. Con el seed en el otro eje, cada fila es un ruido inicial distinto: un parámetro que sale mejor en todas las filas es una elección de verdad; uno que solo gana en una fila era suerte. Elige el valor que aguanta y vuelve a un solo KSampler con él.'),
        how: [L('y_axis <b>seed</b>, y_values <b>1, 2, 3</b>.', 'y_axis <b>seed</b>, y_values <b>1, 2, 3</b>.', 'y_axis <b>seed</b>, y_values <b>1, 2, 3</b>.'), L('Run and read the grid row by row.', 'Executa i llegeix la graella fila per fila.', 'Ejecuta y lee la rejilla fila por fila.')],
        note: L('Typing a value that is not in the list (for example “eulr”) stops the grid with an error: the names must be exact.', 'Si escrius un valor que no és a la llista (per exemple “eulr”), la graella s’atura amb un error: els noms han de ser exactes.', 'Si escribes un valor que no está en la lista (por ejemplo “eulr”), la rejilla se para con un error: los nombres tienen que ser exactos.'),
        starter: () => G.xy({ xv: '3, 6, 9, 12' }), solution: () => G.xy({ xv: '3, 6, 9, 12', y: 'seed', yv: '1, 2, 3' }),
        goals: [goal(L('Seeds on one axis, a setting on the other', 'Seeds en un eix, un paràmetre a l’altre', 'Seeds en un eje, un parámetro en el otro'), (g, c) => xys(c).some(h => (h.xy.yAxis === 'seed' && h.xy.ys.length >= 3 && h.xy.xAxis !== 'seed') || (h.xy.xAxis === 'seed' && h.xy.xs.length >= 3 && h.xy.yAxis !== 'none' && h.xy.yAxis !== 'seed')))],
      },
    ],
  },
];
// Pairs of pictures with the same seed and different samplers: the seeds they share.
function pairs(c) { const out = []; for (const a of c.history) for (const b of c.history) if (a !== b && a.seed === b.seed && a.sampler !== b.sampler && typeof a.seed === 'number') out.push(a.seed); return out; }

export const TEMPLATES = [
  { id: 'xy', name: L('XY grid (cfg × sampler)', 'Graella XY (cfg × sampler)', 'Rejilla XY (cfg × sampler)'), make: () => G.xy({ xv: '3, 6, 9, 12', y: 'sampler_name', yv: 'euler, dpmpp_2m' }) },
  { id: 'seed', name: L('Two samplers, one seed', 'Dos samplers, un seed', 'Dos samplers, un seed'), make: () => G.twoSamplers(true) },
  { id: 'prompt', name: L('Two models, one prompt', 'Dos models, un prompt', 'Dos modelos, un prompt'), make: () => G.twoModels(true) },
  { id: 'sg', name: L('One subgraph, used twice', 'Un subgraph, fet servir dues vegades', 'Un subgraph, usado dos veces'), make: () => G.sgTwice() },
];
export { G as GRAPHS };
void move; void drop;
