// Carrot Revolt Labs · Control & Injection Lab · stages, steps and live checklists.
// It runs on the ComfyUI Lab interface (../comfyui/app.js) and adds its own nodes and simulator (./nodes.js).
import { defaultGraph, makeNode, makeLink, connect } from '../comfyui/engine.js';
import { historyExtra as hx } from './nodes.js';
export const L = (en, ca, es) => ({ en, ca, es });

export const META = { key: 'carrot-revolt-comfy-control:', title: 'Control & Injection Lab', label: 'GENERATIVE IMAGE / COMFYUI · 05' };
export const historyExtra = hx;

/* ── Graph helpers ── */
const N = (g, type) => g.nodes.filter(n => n.type === type && n.mode === 0);
const into = (g, id, input) => g.links.find(l => l.to === id && l.input === input);
const from = (g, id, input) => { const l = into(g, id, input); return l ? g.nodes.find(n => n.id === l.from) : null; };
const goal = (text, test, optional = false) => ({ text, test, optional });
const add = (g, ...nodes) => { g.nodes.push(...nodes); return g; };
const wire = (g, list) => { for (const l of list) connect(g, makeLink(...l)); return g; };
const set = (g, id, k, v) => { g.nodes.find(n => n.id === id).widgets[k] = v; return g; };
const move = (g, id, x, y) => { const n = g.nodes.find(n => n.id === id); n.x = x; n.y = y; return g; };
const shift = g => { move(g, 'sampler', 1240, 186); move(g, 'decode', 1600, 188); move(g, 'save', 1850, 189); return g; };
const runs = c => c.history.filter(h => h.controls);
const ran = (c, f) => runs(c).some(f);
const cols = (start, end, x0, x1, r = .07) => { const out = []; for (let x = x0; x <= x1 + 1e-6; x += r * 1.4) out.push({ p: [[x, start], [x, end]], r }); return out; };
const LEFT = cols(0, 1, .03, .47), RIGHT_COL = cols(.25, .95, .7, .86, .06);
const PRE = { pose: 'DWPreprocessor', depth: 'DepthAnythingV2Preprocessor', lineart: 'LineArtPreprocessor' };
const NET = { pose: 'control_v11p_sd15_openpose.pth', depth: 'control_v11f1p_sd15_depth.pth', lineart: 'control_v11p_sd15_lineart.pth', canny: 'control_v11p_sd15_canny.pth' };
const DRESS = 'a woman in a red dress at the beach, sunset, detailed';

/* ── Starters and solutions ── */
const G = {
  base: (text = DRESS) => { const g = defaultGraph(); set(g, 'pos', 'text', text); set(g, 'neg', 'text', 'blurry, text, watermark'); set(g, 'sampler', 'control_after_generate', 'fixed'); return g; },
  maps: () => { const g = { nodes: [makeNode('LoadImage', 26, 160, { image: 'pose_jump.png' }, 'img'), makeNode('DWPreprocessor', 420, 120, {}, 'pose'), makeNode('PreviewImage', 760, 120, {}, 'pv1'), makeNode('DepthAnythingV2Preprocessor', 420, 430, {}, 'depth'), makeNode('PreviewImage', 760, 430, {}, 'pv2')], links: [], groups: [] }; return wire(g, [['img', 0, 'pose', 'image'], ['pose', 0, 'pv1', 'images'], ['img', 0, 'depth', 'image'], ['depth', 0, 'pv2', 'images']]); },
  mapsStart: () => { const g = G.maps(); g.nodes = g.nodes.filter(n => n.id === 'img' || n.id === 'pv1'); g.links = []; return wire(g, [['img', 0, 'pv1', 'images']]); },
  cn: ({ map = 'pose', net = NET.pose, strength = 1, photo = 'pose_jump.png', text = DRESS, end = 1 } = {}) => {
    const g = shift(G.base(text));
    add(g, makeNode('LoadImage', 26, 760, { image: photo }, 'img'), makeNode(PRE[map], 420, 800, {}, 'pre'), makeNode('ControlNetLoader', 420, 1040, { control_net_name: net }, 'cnl'), makeNode('ControlNetApplyAdvanced', 860, 620, { strength, end_percent: end }, 'apply'));
    return wire(g, [['img', 0, 'pre', 'image'], ['pos', 0, 'apply', 'positive'], ['neg', 0, 'apply', 'negative'], ['cnl', 0, 'apply', 'control_net'], ['pre', 0, 'apply', 'image'], ['apply', 0, 'sampler', 'positive'], ['apply', 1, 'sampler', 'negative']]);
  },
  multi: (s1 = .75, s2 = .6) => {
    const g = G.cn({ strength: s1, text: 'a woman in a red dress next to a lighthouse, beach, sunset, detailed' });
    add(g, makeNode('LoadImage', 26, 1180, { image: 'ref_watercolor.png' }, 'img2'), makeNode('DepthAnythingV2Preprocessor', 420, 1240, {}, 'pre2'), makeNode('ControlNetLoader', 420, 1480, { control_net_name: NET.depth }, 'cnl2'), makeNode('ControlNetApplyAdvanced', 860, 940, { strength: s2 }, 'apply2'));
    return wire(g, [['img2', 0, 'pre2', 'image'], ['apply', 0, 'apply2', 'positive'], ['apply', 1, 'apply2', 'negative'], ['cnl2', 0, 'apply2', 'control_net'], ['pre2', 0, 'apply2', 'image'], ['apply2', 0, 'sampler', 'positive'], ['apply2', 1, 'sampler', 'negative']]);
  },
  regions: () => {
    const g = G.base('a landscape, detailed'); move(g, 'sampler', 1560, 186); move(g, 'decode', 1920, 188); move(g, 'save', 2170, 189);
    add(g, makeNode('CLIPTextEncode', 415, -460, { text: 'a red cat' }, 'pl'), makeNode('CLIPTextEncode', 415, -240, { text: 'a blue robot' }, 'pr'), makeNode('ConditioningSetAreaPercentage', 860, -460, { width: .5, x: 0 }, 'al'), makeNode('ConditioningSetAreaPercentage', 860, -220, { width: .5, x: .5 }, 'ar'), makeNode('ConditioningCombine', 1220, -330, {}, 'c1'), makeNode('ConditioningCombine', 1220, 30, {}, 'c2'));
    return wire(g, [['ckpt', 1, 'pl', 'clip'], ['ckpt', 1, 'pr', 'clip'], ['pl', 0, 'al', 'conditioning'], ['pr', 0, 'ar', 'conditioning'], ['al', 0, 'c1', 'conditioning_1'], ['ar', 0, 'c1', 'conditioning_2'], ['pos', 0, 'c2', 'conditioning_1'], ['c1', 0, 'c2', 'conditioning_2'], ['c2', 0, 'sampler', 'positive']]);
  },
  maskStart: () => { const g = shift(G.base('a beach with a white lighthouse, sunset, detailed')); add(g, makeNode('LoadImage', 26, 760, { image: 'mask_canvas.png', mask: RIGHT_COL }, 'mimg')); return g; },
  maskRegion: () => {
    const g = G.maskStart(); set(g, 'pos', 'text', 'a beach, sunset, detailed');
    add(g, makeNode('CLIPTextEncode', 415, -300, { text: 'a white lighthouse' }, 'pl'), makeNode('ConditioningSetMask', 860, -300, {}, 'sm'), makeNode('ConditioningCombine', 860, -80, {}, 'cc'));
    return wire(g, [['ckpt', 1, 'pl', 'clip'], ['pl', 0, 'sm', 'conditioning'], ['mimg', 1, 'sm', 'mask'], ['pos', 0, 'cc', 'conditioning_1'], ['sm', 0, 'cc', 'conditioning_2'], ['cc', 0, 'sampler', 'positive']]);
  },
  ipa: ({ type = 'linear', weight = .8, ref = 'ref_watercolor.png', text = 'a cat in a landscape, detailed', preset = 'PLUS (high strength)' } = {}) => {
    const g = shift(G.base(text));
    add(g, makeNode('LoadImage', 26, 760, { image: ref }, 'ref'), makeNode('IPAdapterUnifiedLoader', 420, -230, { preset }, 'ipl'), makeNode('IPAdapterAdvanced', 860, -260, { weight, weight_type: type }, 'ipa'));
    return wire(g, [['ckpt', 0, 'ipl', 'model'], ['ipl', 0, 'ipa', 'model'], ['ipl', 1, 'ipa', 'ipadapter'], ['ref', 0, 'ipa', 'image'], ['ipa', 0, 'sampler', 'model']]);
  },
  faceid: ({ weight = .85, ref = 'portrait_anna.png', text = 'a woman walking on the beach, sunset, detailed', plain = false } = {}) => {
    if (plain) return G.ipa({ ref, text, weight, preset: 'PLUS (high strength)' });
    const g = shift(G.base(text));
    add(g, makeNode('LoadImage', 26, 760, { image: ref }, 'ref'), makeNode('IPAdapterUnifiedLoaderFaceID', 420, -260, {}, 'ipl'), makeNode('IPAdapterFaceID', 860, -330, { weight }, 'fid'));
    return wire(g, [['ckpt', 0, 'ipl', 'model'], ['ipl', 0, 'fid', 'model'], ['ipl', 1, 'fid', 'ipadapter'], ['ref', 0, 'fid', 'image'], ['fid', 0, 'sampler', 'model']]);
  },
  twoStart: () => { const g = G.regions(); set(g, 'pos', 'text', 'a beach, sunset, detailed'); set(g, 'pl', 'text', 'a woman'); set(g, 'pr', 'text', 'a man'); return g; },
  two: () => {
    const g = G.twoStart();
    add(g, makeNode('IPAdapterUnifiedLoaderFaceID', 420, 660, {}, 'ipl'), makeNode('LoadImage', 26, 1000, { image: 'portrait_anna.png' }, 'refA'), makeNode('LoadImage', 26, 1420, { image: 'portrait_leo.png' }, 'refB'), makeNode('LoadImage', 420, 1000, { image: 'mask_canvas.png', mask: LEFT }, 'mimg'), makeNode('InvertMask', 800, 1300, {}, 'inv'), makeNode('IPAdapterFaceID', 860, 620, { weight: .85 }, 'fidA'), makeNode('IPAdapterFaceID', 1220, 620, { weight: .85 }, 'fidB'));
    return wire(g, [['ckpt', 0, 'ipl', 'model'], ['ipl', 0, 'fidA', 'model'], ['ipl', 1, 'fidA', 'ipadapter'], ['refA', 0, 'fidA', 'image'], ['mimg', 1, 'fidA', 'attn_mask'], ['fidA', 0, 'fidB', 'model'], ['ipl', 1, 'fidB', 'ipadapter'], ['refB', 0, 'fidB', 'image'], ['mimg', 1, 'inv', 'mask'], ['inv', 0, 'fidB', 'attn_mask'], ['fidB', 0, 'sampler', 'model']]);
  },
  finalStart: () => G.cn({ text: 'a woman in a dress dancing on the beach, sunset, detailed', strength: .85 }),
  final: () => {
    const g = G.finalStart(); move(g, 'sampler', 1600, 186); move(g, 'decode', 1960, 188); move(g, 'save', 2210, 189);
    add(g, makeNode('LoadImage', 26, 1180, { image: 'portrait_anna.png' }, 'ref'), makeNode('IPAdapterUnifiedLoaderFaceID', 420, -300, {}, 'ipl'), makeNode('IPAdapterFaceID', 860, -360, { weight: .85 }, 'fid'), makeNode('LoadImage', 26, 1600, { image: 'ref_watercolor.png' }, 'sref'), makeNode('IPAdapterUnifiedLoader', 1240, -360, {}, 'ipl2'), makeNode('IPAdapterAdvanced', 1240, -120, { weight: .8, weight_type: 'style transfer' }, 'ipa'));
    return wire(g, [['ckpt', 0, 'ipl', 'model'], ['ipl', 0, 'fid', 'model'], ['ipl', 1, 'fid', 'ipadapter'], ['ref', 0, 'fid', 'image'], ['fid', 0, 'ipl2', 'model'], ['ipl2', 0, 'ipa', 'model'], ['ipl2', 1, 'ipa', 'ipadapter'], ['sref', 0, 'ipa', 'image'], ['ipa', 0, 'sampler', 'model']]);
  },
};

export const UI = {
  headline: L('Not only words: <span>steer with pictures.</span>', 'No només paraules: <span>guia amb imatges.</span>', 'No solo palabras: <span>guía con imágenes.</span>'),
  lead: L('A prompt describes; these tools decide. Turn photos into control maps and stack ControlNets, put each thing in its place with regional prompts, borrow the style or the layout of a picture with IPAdapter, keep a face across pictures and give two people two different faces with attention masks. All of it in a ComfyUI-style workspace, with the real nodes.', 'Un prompt descriu; aquestes eines decideixen. Converteix fotos en mapes de control i apila ControlNets, posa cada cosa al seu lloc amb prompts regionals, agafa l’estil o la composició d’una imatge amb IPAdapter, mantén una cara entre imatges i dona dues cares diferents a dues persones amb màscares d’atenció. Tot en un espai com el de ComfyUI, amb els nodes reals.', 'Un prompt describe; estas herramientas deciden. Convierte fotos en mapas de control y apila ControlNets, pon cada cosa en su sitio con prompts regionales, toma el estilo o la composición de una imagen con IPAdapter, mantén una cara entre imágenes y da dos caras distintas a dos personas con máscaras de atención. Todo en un espacio como el de ComfyUI, con los nodos reales.'),
  loraVsCn: L('Which tool?', 'Quina eina?', '¿Qué herramienta?'),
  type_IPADAPTER: L('an image adapter: injects a picture into the model', 'un adaptador d’imatge: injecta una imatge al model', 'un adaptador de imagen: inyecta una imagen en el modelo'),
};
const T3 = (h, rows, foot) => `<table class="c-cmp"><tr><th></th><th>${h[0]}</th><th>${h[1]}</th></tr>${rows.map(r => `<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</table><p>${foot}</p>`;
UI.loraVsCnBody = L(
  T3(['Controls', 'Goes on'], [['<b>ControlNet</b>', 'shape, pose, depth', 'CONDITIONING'], ['<b>Regions</b>', 'what goes where', 'CONDITIONING'], ['<b>IPAdapter</b>', 'style, layout, content of a picture', 'MODEL'], ['<b>FaceID</b>', 'a face', 'MODEL'], ['<b>LoRA</b>', 'a trained style or concept', 'MODEL + CLIP']], 'They combine: ControlNet for the shape, IPAdapter for the look, the prompt for the rest.'),
  T3(['Controla', 'Va a'], [['<b>ControlNet</b>', 'forma, postura, profunditat', 'CONDITIONING'], ['<b>Regions</b>', 'què va on', 'CONDITIONING'], ['<b>IPAdapter</b>', 'estil, composició, contingut d’una imatge', 'MODEL'], ['<b>FaceID</b>', 'una cara', 'MODEL'], ['<b>LoRA</b>', 'un estil o concepte entrenat', 'MODEL + CLIP']], 'Es combinen: ControlNet per a la forma, IPAdapter per a l’aspecte, el prompt per a la resta.'),
  T3(['Controla', 'Va a'], [['<b>ControlNet</b>', 'forma, postura, profundidad', 'CONDITIONING'], ['<b>Regiones</b>', 'qué va dónde', 'CONDITIONING'], ['<b>IPAdapter</b>', 'estilo, composición, contenido de una imagen', 'MODEL'], ['<b>FaceID</b>', 'una cara', 'MODEL'], ['<b>LoRA</b>', 'un estilo o concepto entrenado', 'MODEL + CLIP']], 'Se combinan: ControlNet para la forma, IPAdapter para el aspecto, el prompt para el resto.'));

export const DOCS = {
  DWPreprocessor: { short: L('Finds the pose of people: an OpenPose skeleton.', 'Troba la postura de les persones: un esquelet OpenPose.', 'Encuentra la postura de las personas: un esqueleto OpenPose.'), long: L('Custom node pack controlnet_aux. Body, hands and face keypoints drawn as coloured bones on black. A picture without people gives an empty map.', 'Paquet de custom nodes controlnet_aux. Punts del cos, les mans i la cara dibuixats com a ossos de colors sobre negre. Una imatge sense persones dona un mapa buit.', 'Paquete de custom nodes controlnet_aux. Puntos del cuerpo, las manos y la cara dibujados como huesos de colores sobre negro. Una imagen sin personas da un mapa vacío.') },
  DepthAnythingV2Preprocessor: { short: L('Estimates depth: near is white, far is black.', 'Estima la profunditat: a prop és blanc, lluny és negre.', 'Estima la profundidad: cerca es blanco, lejos es negro.'), long: L('Keeps the volumes and the layout of a scene without its details or colours. Good to keep a composition while changing everything else.', 'Conserva els volums i la disposició d’una escena sense els detalls ni els colors. Va bé per mantenir una composició i canviar-ho tot.', 'Conserva los volúmenes y la disposición de una escena sin los detalles ni los colores. Va bien para mantener una composición y cambiarlo todo.') },
  LineArtPreprocessor: { short: L('Extracts drawing lines.', 'Extreu línies de dibuix.', 'Extrae líneas de dibujo.'), long: L('Softer and more “drawn” than Canny. Use it with the lineart ControlNet (Canny models accept it a bit too).', 'Més suau i més “dibuixat” que Canny. Fes-lo servir amb la ControlNet lineart (els models Canny també l’accepten una mica).', 'Más suave y más “dibujado” que Canny. Úsalo con la ControlNet lineart (los modelos Canny también lo aceptan un poco).') },
  ConditioningSetAreaPercentage: { short: L('Limits a prompt to a rectangle.', 'Limita un prompt a un rectangle.', 'Limita un prompt a un rectángulo.'), long: L('x, y, width and height as fractions of the picture. Combine several areas with Conditioning (Combine) and add a global prompt for the background.', 'x, y, amplada i alçada com a fraccions de la imatge. Combina diverses àrees amb Conditioning (Combine) i afegeix-hi un prompt global per al fons.', 'x, y, ancho y alto como fracciones de la imagen. Combina varias áreas con Conditioning (Combine) y añade un prompt global para el fondo.') },
  ConditioningSetMask: { short: L('Limits a prompt to a mask.', 'Limita un prompt a una màscara.', 'Limita un prompt a una máscara.'), long: L('Like Set Area, with any shape: paint where the prompt applies. mask bounds samples only the box of the mask, at more resolution.', 'Com Set Area, amb qualsevol forma: pinta on s’aplica el prompt. mask bounds mostreja només el requadre de la màscara, amb més resolució.', 'Como Set Area, con cualquier forma: pinta dónde se aplica el prompt. mask bounds muestrea solo el recuadro de la máscara, con más resolución.') },
  ConditioningCombine: { short: L('Joins two conditionings.', 'Uneix dos conditionings.', 'Une dos conditionings.'), long: L('Both are applied at once: each region with its prompt, plus the global one.', 'S’apliquen tots dos alhora: cada regió amb el seu prompt, més el global.', 'Se aplican los dos a la vez: cada región con su prompt, más el global.') },
  IPAdapterUnifiedLoader: { short: L('Loads an IPAdapter and its image encoder.', 'Carrega un IPAdapter i el seu encoder d’imatge.', 'Carga un IPAdapter y su encoder de imagen.'), long: L('Custom node pack IPAdapter plus. The preset picks the model: PLUS is the strong general one; PLUS FACE is for portraits.', 'Paquet de custom nodes IPAdapter plus. El preset tria el model: PLUS és el general fort; PLUS FACE és per a retrats.', 'Paquete de custom nodes IPAdapter plus. El preset elige el modelo: PLUS es el general fuerte; PLUS FACE es para retratos.') },
  IPAdapterAdvanced: { short: L('Injects a reference picture into the model.', 'Injecta una imatge de referència al model.', 'Inyecta una imagen de referencia en el modelo.'), long: L('The picture works like a prompt made of pixels. weight_type decides what is taken: linear takes everything (style and content), style transfer only the style, composition only the layout.', 'La imatge funciona com un prompt fet de píxels. weight_type decideix què se n’agafa: linear ho agafa tot (estil i contingut), style transfer només l’estil, composition només la composició.', 'La imagen funciona como un prompt hecho de píxeles. weight_type decide qué se toma: linear lo toma todo (estilo y contenido), style transfer solo el estilo, composition solo la composición.'), widgets: { weight: L('0.5–0.9 usually; more overpowers the prompt', '0.5–0.9 normalment; més domina el prompt', '0.5–0.9 normalmente; más domina el prompt'), weight_type: L('what to take from the picture', 'què s’agafa de la imatge', 'qué se toma de la imagen'), attn_mask: L('where in the picture it applies', 'on s’aplica a la imatge', 'dónde se aplica en la imagen') } },
  IPAdapterUnifiedLoaderFaceID: { short: L('Loads a FaceID adapter (and its LoRA).', 'Carrega un adaptador FaceID (i la seva LoRA).', 'Carga un adaptador FaceID (y su LoRA).'), long: L('FaceID reads a face with a face-recognition network (InsightFace), not as a picture: it keeps who the person is, not the photo.', 'FaceID llegeix una cara amb una xarxa de reconeixement facial (InsightFace), no com una imatge: conserva qui és la persona, no la foto.', 'FaceID lee una cara con una red de reconocimiento facial (InsightFace), no como una imagen: conserva quién es la persona, no la foto.') },
  IPAdapterFaceID: { short: L('Keeps the identity of a face.', 'Conserva la identitat d’una cara.', 'Conserva la identidad de una cara.'), long: L('The face of the reference on whoever the prompt describes, in any scene. Too much weight copies the reference photo itself.', 'La cara de la referència a qui descrigui el prompt, en qualsevol escena. Massa pes copia la mateixa foto de referència.', 'La cara de la referencia en quien describa el prompt, en cualquier escena. Demasiado peso copia la propia foto de referencia.') },
};

export const STAGES = [
  {
    id: 'control', name: L('ControlNet', 'ControlNet', 'ControlNet'), sub: L('Maps · matching · stacking', 'Mapes · encaix · apilar', 'Mapas · encaje · apilar'),
    steps: [
      {
        title: L('From a photo to a control map', 'D’una foto a un mapa de control', 'De una foto a un mapa de control'),
        task: L('Turn the photo into a pose map (DWPose) and a depth map (Depth Anything) and preview both.', 'Converteix la foto en un mapa de postura (DWPose) i un de profunditat (Depth Anything) i previsualitza’ls.', 'Convierte la foto en un mapa de postura (DWPose) y uno de profundidad (Depth Anything) y previsualízalos.'),
        concept: L('A ControlNet does not read photos: it reads <b>maps</b>. A <b>preprocessor</b> turns a photo into the map a ControlNet was trained on: a pose skeleton (OpenPose / DWPose), a depth map (near = white), lines (Canny, Lineart)… Each map keeps something different: the pose keeps only where arms and legs are, the depth keeps volumes and layout, the lines keep the outlines.', 'Una ControlNet no llegeix fotos: llegeix <b>mapes</b>. Un <b>preprocessador</b> converteix una foto en el mapa amb què es va entrenar una ControlNet: un esquelet de postura (OpenPose / DWPose), un mapa de profunditat (a prop = blanc), línies (Canny, Lineart)… Cada mapa conserva una cosa diferent: la postura només on són els braços i les cames, la profunditat els volums i la disposició, les línies els contorns.', 'Una ControlNet no lee fotos: lee <b>mapas</b>. Un <b>preprocesador</b> convierte una foto en el mapa con el que se entrenó una ControlNet: un esqueleto de postura (OpenPose / DWPose), un mapa de profundidad (cerca = blanco), líneas (Canny, Lineart)… Cada mapa conserva algo distinto: la postura solo dónde están los brazos y las piernas, la profundidad los volúmenes y la disposición, las líneas los contornos.'),
        how: [L('From the IMAGE of Load Image, search <b>DWPose Estimator</b> and connect a Preview Image to it.', 'Des de la IMAGE de Load Image, cerca <b>DWPose Estimator</b> i connecta-hi un Preview Image.', 'Desde la IMAGE de Load Image, busca <b>DWPose Estimator</b> y conéctale un Preview Image.'), L('Do the same with <b>Depth Anything V2 - Relative</b>.', 'Fes el mateix amb <b>Depth Anything V2 - Relative</b>.', 'Haz lo mismo con <b>Depth Anything V2 - Relative</b>.'), L('Run and compare the two maps.', 'Executa i compara els dos mapes.', 'Ejecuta y compara los dos mapas.')],
        note: L('Preprocessors come in the custom node pack comfyui_controlnet_aux (ComfyUI Manager). The first run of each downloads its model.', 'Els preprocessadors venen al paquet de custom nodes comfyui_controlnet_aux (ComfyUI Manager). La primera execució de cadascun en descarrega el model.', 'Los preprocesadores vienen en el paquete de custom nodes comfyui_controlnet_aux (ComfyUI Manager). La primera ejecución de cada uno descarga su modelo.'),
        starter: G.mapsStart, solution: G.maps,
        goals: [goal(L('A pose map', 'Un mapa de postura', 'Un mapa de postura'), (g, c) => c.history.some(h => h.kind === 'pose')), goal(L('A depth map', 'Un mapa de profunditat', 'Un mapa de profundidad'), (g, c) => c.history.some(h => h.kind === 'depth'))],
      },
      {
        title: L('The right model for the map', 'El model bo per al mapa', 'El modelo bueno para el mapa'),
        task: L('This graph feeds a depth map to the OpenPose ControlNet. Run it, then give it the pose map it expects.', 'Aquest graf dona un mapa de profunditat a la ControlNet OpenPose. Executa’l i després dona-li el mapa de postura que espera.', 'Este grafo da un mapa de profundidad a la ControlNet OpenPose. Ejecútalo y luego dale el mapa de postura que espera.'),
        concept: L('Each ControlNet model understands <b>one kind of map</b>: openpose ↔ pose skeletons, depth ↔ depth maps, canny ↔ edges (lineart is close enough). Give it another map and it barely reacts, without any error: the picture simply ignores the control. When a ControlNet “does nothing”, check first that the map and the model match, and that the preprocessor found something (a pose map of a photo without people is black).', 'Cada model de ControlNet entén <b>un tipus de mapa</b>: openpose ↔ esquelets de postura, depth ↔ mapes de profunditat, canny ↔ vores (lineart s’hi assembla prou). Si li dones un altre mapa gairebé no reacciona, sense cap error: la imatge simplement ignora el control. Quan una ControlNet “no fa res”, mira primer que el mapa i el model encaixin, i que el preprocessador hagi trobat alguna cosa (un mapa de postura d’una foto sense persones és negre).', 'Cada modelo de ControlNet entiende <b>un tipo de mapa</b>: openpose ↔ esqueletos de postura, depth ↔ mapas de profundidad, canny ↔ bordes (lineart se parece bastante). Si le das otro mapa casi no reacciona, sin ningún error: la imagen simplemente ignora el control. Cuando una ControlNet “no hace nada”, mira primero que el mapa y el modelo encajen, y que el preprocesador haya encontrado algo (un mapa de postura de una foto sin personas es negro).'),
        how: [L('Run: the woman ignores the pose.', 'Executa: la dona ignora la postura.', 'Ejecuta: la mujer ignora la postura.'), L('Replace Depth Anything with <b>DWPose Estimator</b> (or set the loader to the depth model).', 'Substitueix Depth Anything per <b>DWPose Estimator</b> (o posa el loader al model depth).', 'Sustituye Depth Anything por <b>DWPose Estimator</b> (o pon el loader en el modelo depth).'), L('Run again: the jump pose.', 'Torna a executar: la postura del salt.', 'Vuelve a ejecutar: la postura del salto.')],
        note: L('Union ControlNets (one model, many map types) exist for SDXL and Flux; there you tell it the type with a node.', 'Hi ha ControlNets union (un model, molts tipus de mapa) per a SDXL i Flux; allà li dius el tipus amb un node.', 'Hay ControlNets union (un modelo, muchos tipos de mapa) para SDXL y Flux; allí le dices el tipo con un nodo.'),
        starter: () => G.cn({ map: 'depth', net: NET.pose }), solution: () => G.cn(),
        goals: [goal(L('Saw a mismatched map do (almost) nothing', 'Has vist com un mapa que no encaixa (gairebé) no fa res', 'Has visto cómo un mapa que no encaja (casi) no hace nada'), (g, c) => ran(c, h => h.controls.some(x => x.match > 0 && x.match < .5))), goal(L('Map and model match', 'El mapa i el model encaixen', 'El mapa y el modelo encajan'), (g, c) => ran(c, h => h.controls.some(x => x.match === 1))), goal(L('A person in the pose of the photo', 'Una persona amb la postura de la foto', 'Una persona con la postura de la foto'), (g, c) => ran(c, h => h.posed))],
      },
      {
        title: L('Two ControlNets at once', 'Dues ControlNets alhora', 'Dos ControlNets a la vez'),
        task: L('A pose and a depth map are stacked, both at strength 1: run and look. Then balance them (sum ≤ 1.6) so the picture comes back.', 'Hi ha una postura i un mapa de profunditat apilats, tots dos amb força 1: executa i mira. Després equilibra’ls (suma ≤ 1.6) perquè la imatge torni.', 'Hay una postura y un mapa de profundidad apilados, los dos con fuerza 1: ejecuta y mira. Luego equilíbralos (suma ≤ 1.6) para que la imagen vuelva.'),
        concept: L('ControlNets <b>chain</b>: the conditioning goes through one Apply ControlNet and then the next. Each one controls something: here the pose places the woman, the depth of another photo places a lighthouse. Their pushes <b>add up</b>: two at full strength overcook the picture (hard edges, posterised colours). Lower them (0.5–0.8 each) or end them early (end_percent 0.6–0.8) so the model has freedom for the details.', 'Les ControlNets <b>s’encadenen</b>: el conditioning passa per un Apply ControlNet i després pel següent. Cadascuna controla una cosa: aquí la postura col·loca la dona, i la profunditat d’una altra foto col·loca un far. Les seves empentes <b>se sumen</b>: dues a força màxima cremen la imatge (vores dures, colors posteritzats). Abaixa-les (0.5–0.8 cadascuna) o fes-les acabar abans (end_percent 0.6–0.8) perquè el model tingui llibertat per als detalls.', 'Los ControlNets <b>se encadenan</b>: el conditioning pasa por un Apply ControlNet y luego por el siguiente. Cada uno controla algo: aquí la postura coloca a la mujer, y la profundidad de otra foto coloca un faro. Sus empujes <b>se suman</b>: dos a fuerza máxima queman la imagen (bordes duros, colores posterizados). Bájalos (0.5–0.8 cada uno) o haz que acaben antes (end_percent 0.6–0.8) para que el modelo tenga libertad para los detalles.'),
        how: [L('Run as it is (1 + 1).', 'Executa tal com està (1 + 1).', 'Ejecuta tal cual (1 + 1).'), L('Pose ControlNet <b>0.75</b>, depth ControlNet <b>0.6</b>.', 'ControlNet de postura <b>0.75</b>, ControlNet de profunditat <b>0.6</b>.', 'ControlNet de postura <b>0.75</b>, ControlNet de profundidad <b>0.6</b>.'), L('Run again.', 'Torna a executar.', 'Vuelve a ejecutar.')],
        note: L('Order does not matter much, but strength does: the one that matters most gets the higher value.', 'L’ordre no importa gaire, però la força sí: la que més importa porta el valor més alt.', 'El orden no importa mucho, pero la fuerza sí: la que más importa lleva el valor más alto.'),
        starter: () => G.multi(1, 1), solution: () => G.multi(),
        goals: [goal(L('Saw two full ControlNets overcook', 'Has vist dues ControlNets a tope cremar la imatge', 'Has visto dos ControlNets a tope quemar la imagen'), (g, c) => ran(c, h => h.overcooked)), goal(L('Two matched ControlNets, sum ≤ 1.6', 'Dues ControlNets que encaixen, suma ≤ 1.6', 'Dos ControlNets que encajan, suma ≤ 1.6'), (g, c) => ran(c, h => h.controls.filter(x => x.match === 1 && x.amount > .3).length >= 2 && h.strengthSum <= 1.6 && !h.overcooked)), goal(L('Pose and lighthouse both in place', 'La postura i el far al seu lloc', 'La postura y el faro en su sitio'), (g, c) => ran(c, h => h.posed && !h.overcooked && h.controls.length >= 2))],
      },
    ],
  },
  {
    id: 'regions', name: L('Regions', 'Regions', 'Regiones'), sub: L('Area · mask', 'Àrea · màscara', 'Área · máscara'),
    steps: [
      {
        title: L('Each colour in its place', 'Cada color al seu lloc', 'Cada color en su sitio'),
        task: L('“a red cat and a blue robot” mixes the colours. Split it: global prompt for the landscape, the cat on the left half, the robot on the right half.', '“a red cat and a blue robot” barreja els colors. Separa-ho: prompt global per al paisatge, el gat a la meitat esquerra, el robot a la dreta.', '“a red cat and a blue robot” mezcla los colores. Sepáralo: prompt global para el paisaje, el gato en la mitad izquierda, el robot en la derecha.'),
        concept: L('With CLIP models, one prompt with two objects mixes their colours and features. <b>Regional prompting</b> gives each part of the picture its own prompt: <b>Conditioning (Set Area)</b> limits a prompt to a rectangle, and <b>Conditioning (Combine)</b> joins them. Keep a global prompt (the background, the light, the style) combined with the regional ones, so the parts belong to the same picture.', 'Amb els models CLIP, un prompt amb dos objectes en barreja els colors i les característiques. El <b>prompting regional</b> dona a cada part de la imatge el seu prompt: <b>Conditioning (Set Area)</b> limita un prompt a un rectangle, i <b>Conditioning (Combine)</b> els uneix. Mantén un prompt global (el fons, la llum, l’estil) combinat amb els regionals, perquè les parts siguin de la mateixa imatge.', 'Con los modelos CLIP, un prompt con dos objetos mezcla sus colores y características. El <b>prompting regional</b> da a cada parte de la imagen su prompt: <b>Conditioning (Set Area)</b> limita un prompt a un rectángulo, y <b>Conditioning (Combine)</b> los une. Mantén un prompt global (el fondo, la luz, el estilo) combinado con los regionales, para que las partes sean de la misma imagen.'),
        how: [L('Run: one mixed object.', 'Executa: un sol objecte barrejat.', 'Ejecuta: un solo objeto mezclado.'), L('Two new CLIP Text Encode (“a red cat”, “a blue robot”), each into <b>Conditioning (Set Area with Percentage)</b>: width 0.5, x 0 and x 0.5.', 'Dos CLIP Text Encode nous (“a red cat”, “a blue robot”), cadascun a un <b>Conditioning (Set Area with Percentage)</b>: width 0.5, x 0 i x 0.5.', 'Dos CLIP Text Encode nuevos (“a red cat”, “a blue robot”), cada uno a un <b>Conditioning (Set Area with Percentage)</b>: width 0.5, x 0 y x 0.5.'), L('Combine both, then combine with the global prompt (“a landscape”) → positive. Run.', 'Combina’ls, i després combina-ho amb el prompt global (“a landscape”) → positive. Executa.', 'Combínalos, y luego combínalo con el prompt global (“a landscape”) → positive. Ejecuta.')],
        note: L('Flux, with T5, already keeps colours apart in one sentence; regions are still the way to decide exactly where things go.', 'Flux, amb T5, ja separa els colors en una sola frase; les regions continuen sent la manera de decidir exactament on va cada cosa.', 'Flux, con T5, ya separa los colores en una sola frase; las regiones siguen siendo la forma de decidir exactamente dónde va cada cosa.'),
        starter: () => G.base('a red cat and a blue robot in a landscape, detailed'), solution: G.regions,
        goals: [goal(L('Saw the colours mix', 'Has vist barrejar-se els colors', 'Has visto mezclarse los colores'), (g, c) => ran(c, h => h.bleed)), goal(L('Two areas with their own prompts', 'Dues àrees amb el seu prompt', 'Dos áreas con su prompt'), (g, c) => ran(c, h => h.regionSubjects.length >= 2 && new Set(h.regionSubjects.map(s => s.col)).size >= 2)), goal(L('Cat on the left, robot on the right', 'El gat a l’esquerra, el robot a la dreta', 'El gato a la izquierda, el robot a la derecha'), (g, c) => ran(c, h => { const cat = h.regionSubjects.find(s => s.kind === 'cat'), rob = h.regionSubjects.find(s => s.kind === 'robot'); return cat && rob && cat.cx < .5 && rob.cx > .5; }))],
      },
      {
        title: L('A region from a mask', 'Una regió a partir d’una màscara', 'Una región a partir de una máscara'),
        task: L('Put the lighthouse exactly where the mask is painted, with Conditioning (Set Mask).', 'Posa el far exactament on hi ha pintada la màscara, amb Conditioning (Set Mask).', 'Pon el faro exactamente donde está pintada la máscara, con Conditioning (Set Mask).'),
        concept: L('Rectangles are not always enough. <b>Conditioning (Set Mask)</b> limits a prompt to any shape you paint: a tall strip for a lighthouse, a corner for the moon. The mask comes from the Mask Editor (Load Image) or any mask node. With <b>mask bounds</b>, the region is sampled at more resolution, which helps small things.', 'Els rectangles no sempre n’hi ha prou. <b>Conditioning (Set Mask)</b> limita un prompt a qualsevol forma que pintis: una franja alta per a un far, una cantonada per a la lluna. La màscara ve del Mask Editor (Load Image) o de qualsevol node de màscara. Amb <b>mask bounds</b>, la regió es mostreja amb més resolució, cosa que ajuda les coses petites.', 'Los rectángulos no siempre bastan. <b>Conditioning (Set Mask)</b> limita un prompt a cualquier forma que pintes: una franja alta para un faro, una esquina para la luna. La máscara viene del Mask Editor (Load Image) o de cualquier nodo de máscara. Con <b>mask bounds</b>, la región se muestrea con más resolución, lo que ayuda a las cosas pequeñas.'),
        how: [L('Change the global prompt to <b>a beach, sunset</b>. A new CLIP Text Encode: <b>a white lighthouse</b>.', 'Canvia el prompt global a <b>a beach, sunset</b>. Un CLIP Text Encode nou: <b>a white lighthouse</b>.', 'Cambia el prompt global a <b>a beach, sunset</b>. Un CLIP Text Encode nuevo: <b>a white lighthouse</b>.'), L('Into <b>Conditioning (Set Mask)</b>, mask = MASK of the Load Image (already painted on the right).', 'A <b>Conditioning (Set Mask)</b>, mask = MASK del Load Image (ja pintada a la dreta).', 'A <b>Conditioning (Set Mask)</b>, mask = MASK del Load Image (ya pintada a la derecha).'), L('Combine with the global prompt → positive. Run.', 'Combina amb el prompt global → positive. Executa.', 'Combina con el prompt global → positive. Ejecuta.')],
        note: L('Repaint the mask in the Mask Editor and run again: the lighthouse follows it.', 'Torna a pintar la màscara al Mask Editor i executa: el far la segueix.', 'Vuelve a pintar la máscara en el Mask Editor y ejecuta: el faro la sigue.'),
        starter: G.maskStart, solution: G.maskRegion,
        goals: [goal(L('Set Mask gets a mask', 'Set Mask rep una màscara', 'Set Mask recibe una máscara'), g => N(g, 'ConditioningSetMask').some(n => into(g, n.id, 'mask'))), goal(L('The lighthouse inside the mask', 'El far dins la màscara', 'El faro dentro de la máscara'), (g, c) => ran(c, h => h.regionSubjects.some(s => s.kind === 'lighthouse' && s.cx > .65)))],
      },
    ],
  },
  {
    id: 'ipadapter', name: L('IPAdapter', 'IPAdapter', 'IPAdapter'), sub: L('Style · content · layout', 'Estil · contingut · composició', 'Estilo · contenido · composición'),
    steps: [
      {
        title: L('A picture as a prompt', 'Una imatge com a prompt', 'Una imagen como prompt'),
        task: L('Run with the watercolor reference at weight_type linear: what else came in? Then use style transfer.', 'Executa amb la referència d’aquarel·la amb weight_type linear: què més ha entrat? Després fes servir style transfer.', 'Ejecuta con la referencia de acuarela con weight_type linear: ¿qué más ha entrado? Luego usa style transfer.'),
        concept: L('<b>IPAdapter</b> turns a reference picture into something like a prompt and injects it into the <b>MODEL</b>: you can say “like this” with a picture instead of words. With <b>linear</b> it takes everything: the style <i>and</i> the content (here a lighthouse appears that nobody asked for). <b>style transfer</b> only takes the look (palette, brushwork, light); <b>composition</b> only the layout. Choosing the weight type is choosing what to inject.', '<b>IPAdapter</b> converteix una imatge de referència en una mena de prompt i la injecta al <b>MODEL</b>: pots dir “així” amb una imatge en lloc de paraules. Amb <b>linear</b> ho agafa tot: l’estil <i>i</i> el contingut (aquí apareix un far que ningú no ha demanat). <b>style transfer</b> només agafa l’aspecte (paleta, pinzellada, llum); <b>composition</b> només la composició. Triar el weight type és triar què injectes.', '<b>IPAdapter</b> convierte una imagen de referencia en una especie de prompt y la inyecta en el <b>MODEL</b>: puedes decir “así” con una imagen en lugar de palabras. Con <b>linear</b> lo toma todo: el estilo <i>y</i> el contenido (aquí aparece un faro que nadie ha pedido). <b>style transfer</b> solo toma el aspecto (paleta, pincelada, luz); <b>composition</b> solo la composición. Elegir el weight type es elegir qué inyectas.'),
        how: [L('Run: watercolour, and a lighthouse.', 'Executa: aquarel·la, i un far.', 'Ejecuta: acuarela, y un faro.'), L('IPAdapter Advanced › weight_type <b>style transfer</b>.', 'IPAdapter Advanced › weight_type <b>style transfer</b>.', 'IPAdapter Advanced › weight_type <b>style transfer</b>.'), L('Run: the style without the lighthouse.', 'Executa: l’estil sense el far.', 'Ejecuta: el estilo sin el faro.')],
        note: L('IPAdapter goes on the MODEL path (like a LoRA), between the loader and the KSampler. For SDXL, style transfer is especially clean.', 'IPAdapter va pel camí del MODEL (com una LoRA), entre el loader i el KSampler. Amb SDXL, style transfer és especialment net.', 'IPAdapter va por el camino del MODEL (como una LoRA), entre el loader y el KSampler. Con SDXL, style transfer es especialmente limpio.'),
        starter: () => G.ipa(), solution: () => G.ipa({ type: 'style transfer' }),
        goals: [goal(L('IPAdapter feeds the KSampler’s model', 'IPAdapter alimenta el model del KSampler', 'IPAdapter alimenta el modelo del KSampler'), g => N(g, 'KSampler').some(s => from(g, s.id, 'model')?.type?.startsWith('IPAdapter'))), goal(L('Saw content leak with linear', 'Has vist entrar contingut amb linear', 'Has visto entrar contenido con linear'), (g, c) => ran(c, h => h.leak)), goal(L('Style without the content', 'L’estil sense el contingut', 'El estilo sin el contenido'), (g, c) => ran(c, h => h.style && h.style.amount >= .5 && !h.leak))],
      },
      {
        title: L('Layout and weight', 'Composició i pes', 'Composición y peso'),
        task: L('Use the neon reference with weight_type composition: your cat takes the place of its robot. Then try a weight of 1.3 with strong style transfer, and settle between 0.5 and 0.9.', 'Fes servir la referència de neó amb weight_type composition: el teu gat ocupa el lloc del seu robot. Després prova un pes d’1.3 amb strong style transfer, i queda’t entre 0.5 i 0.9.', 'Usa la referencia de neón con weight_type composition: tu gato ocupa el lugar de su robot. Luego prueba un peso de 1.3 con strong style transfer, y quédate entre 0.5 y 0.9.'),
        concept: L('<b>composition</b> takes where things are and how big, not how they look: a quick way to copy a framing. And <b>weight</b> is the balance between the picture and your prompt: above ~1 the reference takes over (its content comes back even with style transfer); below 0.4 it barely shows. Most good results live between 0.5 and 0.9.', '<b>composition</b> agafa on són les coses i com són de grans, no com es veuen: una manera ràpida de copiar un enquadrament. I el <b>weight</b> és l’equilibri entre la imatge i el teu prompt: per sobre de ~1 la referència mana (el seu contingut torna fins i tot amb style transfer); per sota de 0.4 gairebé no es nota. La majoria de bons resultats són entre 0.5 i 0.9.', '<b>composition</b> toma dónde están las cosas y lo grandes que son, no cómo se ven: una forma rápida de copiar un encuadre. Y el <b>weight</b> es el equilibrio entre la imagen y tu prompt: por encima de ~1 la referencia manda (su contenido vuelve incluso con style transfer); por debajo de 0.4 casi no se nota. La mayoría de buenos resultados están entre 0.5 y 0.9.'),
        how: [L('Load Image › <b>ref_neon.png</b>; weight_type <b>composition</b>. Run.', 'Load Image › <b>ref_neon.png</b>; weight_type <b>composition</b>. Executa.', 'Load Image › <b>ref_neon.png</b>; weight_type <b>composition</b>. Ejecuta.'), L('weight_type <b>strong style transfer</b>, weight <b>1.3</b>. Run.', 'weight_type <b>strong style transfer</b>, weight <b>1.3</b>. Executa.', 'weight_type <b>strong style transfer</b>, weight <b>1.3</b>. Ejecuta.'), L('weight <b>0.7</b>, style transfer. Run.', 'weight <b>0.7</b>, style transfer. Executa.', 'weight <b>0.7</b>, style transfer. Ejecuta.')],
        note: L('start_at / end_at work like in ControlNet: ending at 0.6 leaves the last steps to your prompt.', 'start_at / end_at funcionen com a la ControlNet: acabar a 0.6 deixa els últims steps al teu prompt.', 'start_at / end_at funcionan como en la ControlNet: acabar en 0.6 deja los últimos steps a tu prompt.'),
        starter: () => G.ipa({ type: 'style transfer' }), solution: () => G.ipa({ type: 'style transfer', weight: .7, ref: 'ref_neon.png' }),
        goals: [goal(L('Layout copied with composition', 'Composició copiada amb composition', 'Composición copiada con composition'), (g, c) => ran(c, h => h.composition && !h.style)), goal(L('Weight too high: the reference takes over', 'Pes massa alt: la referència mana', 'Peso demasiado alto: la referencia manda'), (g, c) => ran(c, h => h.style && h.style.amount > 1 && h.leak)), goal(L('Balanced style, no leak', 'Estil equilibrat, sense contingut colat', 'Estilo equilibrado, sin contenido colado'), (g, c) => ran(c, h => h.style && h.style.amount >= .45 && h.style.amount <= 1 && !h.leak && !h.composition))],
      },
    ],
  },
  {
    id: 'identity', name: L('Identity', 'Identitat', 'Identidad'), sub: L('FaceID · weight', 'FaceID · pes', 'FaceID · peso'),
    steps: [
      {
        title: L('A face from a photo', 'Una cara a partir d’una foto', 'Una cara a partir de una foto'),
        task: L('A plain IPAdapter with a portrait gives only a vague likeness. Replace it with the FaceID loader and IPAdapter FaceID.', 'Un IPAdapter normal amb un retrat només dona una semblança vaga. Substitueix-lo pel loader FaceID i IPAdapter FaceID.', 'Un IPAdapter normal con un retrato solo da un parecido vago. Sustitúyelo por el loader FaceID e IPAdapter FaceID.'),
        concept: L('A normal IPAdapter sees a portrait as a picture: colours, light, framing. <b>FaceID</b> reads the face with a <b>face recognition</b> network (InsightFace), the kind that tells people apart, and injects <i>who</i> the person is. So the same face appears in any scene and pose the prompt describes. Other identity tools work with the same idea (InstantID, PuLID).', 'Un IPAdapter normal veu un retrat com una imatge: colors, llum, enquadrament. <b>FaceID</b> llegeix la cara amb una xarxa de <b>reconeixement facial</b> (InsightFace), de les que distingeixen persones, i injecta <i>qui</i> és. Així la mateixa cara apareix en qualsevol escena i postura que descrigui el prompt. Altres eines d’identitat funcionen amb la mateixa idea (InstantID, PuLID).', 'Un IPAdapter normal ve un retrato como una imagen: colores, luz, encuadre. <b>FaceID</b> lee la cara con una red de <b>reconocimiento facial</b> (InsightFace), de las que distinguen personas, e inyecta <i>quién</i> es. Así la misma cara aparece en cualquier escena y postura que describa el prompt. Otras herramientas de identidad funcionan con la misma idea (InstantID, PuLID).'),
        how: [L('Run: the face only looks a bit like Anna.', 'Executa: la cara només s’assembla una mica a l’Anna.', 'Ejecuta: la cara solo se parece un poco a Anna.'), L('Add <b>IPAdapter Unified Loader FaceID</b> (FACEID PLUS V2) and <b>IPAdapter FaceID</b> with the portrait; its MODEL → KSampler.', 'Afegeix <b>IPAdapter Unified Loader FaceID</b> (FACEID PLUS V2) i <b>IPAdapter FaceID</b> amb el retrat; el seu MODEL → KSampler.', 'Añade <b>IPAdapter Unified Loader FaceID</b> (FACEID PLUS V2) e <b>IPAdapter FaceID</b> con el retrato; su MODEL → KSampler.'), L('Run.', 'Executa.', 'Ejecuta.')],
        note: L('FaceID needs the insightface package in ComfyUI’s Python. Use identity tools with permission: with your own face or with people who agree.', 'FaceID necessita el paquet insightface al Python de ComfyUI. Fes servir les eines d’identitat amb permís: amb la teva cara o amb persones que hi estiguin d’acord.', 'FaceID necesita el paquete insightface en el Python de ComfyUI. Usa las herramientas de identidad con permiso: con tu cara o con personas que estén de acuerdo.'),
        starter: () => G.faceid({ plain: true }), solution: () => G.faceid(),
        goals: [goal(L('Plain IPAdapter: a vague likeness', 'IPAdapter normal: una semblança vaga', 'IPAdapter normal: un parecido vago'), (g, c) => ran(c, h => h.persons.some(p => p.ref && p.score < .6))), goal(L('IPAdapter FaceID feeds the model', 'IPAdapter FaceID alimenta el model', 'IPAdapter FaceID alimenta el modelo'), g => N(g, 'IPAdapterFaceID').some(n => from(g, n.id, 'ipadapter')?.type === 'IPAdapterUnifiedLoaderFaceID')), goal(L('Anna on the beach', 'L’Anna a la platja', 'Anna en la playa'), (g, c) => ran(c, h => h.persons.some(p => p.ref === 'portrait_anna.png' && p.score >= .75) && h.sceneKept))],
      },
      {
        title: L('Identity against the prompt', 'Identitat contra el prompt', 'Identidad contra el prompt'),
        task: L('Try weight 1.5, then 0.3, and find the balance (0.7–1).', 'Prova un pes d’1.5, després 0.3, i troba l’equilibri (0.7–1).', 'Prueba un peso de 1.5, luego 0.3, y encuentra el equilibrio (0.7–1).'),
        concept: L('Too much identity weight and the model stops listening to the prompt: it <b>copies the reference photo</b> (same framing, same background) instead of putting the person in your scene. Too little and the face drifts to a generic one. The useful range keeps both: the person of the photo, in the picture of the prompt.', 'Massa pes d’identitat i el model deixa d’escoltar el prompt: <b>copia la foto de referència</b> (mateix enquadrament, mateix fons) en lloc de posar la persona a la teva escena. Massa poc i la cara es torna genèrica. El rang útil conserva les dues coses: la persona de la foto, a la imatge del prompt.', 'Demasiado peso de identidad y el modelo deja de escuchar el prompt: <b>copia la foto de referencia</b> (mismo encuadre, mismo fondo) en lugar de poner a la persona en tu escena. Demasiado poco y la cara se vuelve genérica. El rango útil conserva las dos cosas: la persona de la foto, en la imagen del prompt.'),
        how: [L('IPAdapter FaceID › weight <b>1.5</b>. Run.', 'IPAdapter FaceID › weight <b>1.5</b>. Executa.', 'IPAdapter FaceID › weight <b>1.5</b>. Ejecuta.'), L('weight <b>0.3</b>. Run.', 'weight <b>0.3</b>. Executa.', 'weight <b>0.3</b>. Ejecuta.'), L('weight <b>0.85</b>. Run.', 'weight <b>0.85</b>. Executa.', 'weight <b>0.85</b>. Ejecuta.')],
        note: L('weight_faceidv2 strengthens the identity without copying the photo as much: raise it before raising weight.', 'weight_faceidv2 reforça la identitat sense copiar tant la foto: puja’l abans de pujar el weight.', 'weight_faceidv2 refuerza la identidad sin copiar tanto la foto: súbelo antes de subir el weight.'),
        starter: () => G.faceid(), solution: () => G.faceid({ weight: .85 }),
        goals: [goal(L('Weight too high: the photo is copied', 'Pes massa alt: es copia la foto', 'Peso demasiado alto: se copia la foto'), (g, c) => ran(c, h => h.copy)), goal(L('Weight too low: identity lost', 'Pes massa baix: es perd la identitat', 'Peso demasiado bajo: se pierde la identidad'), (g, c) => ran(c, h => h.adapters > 0 && h.persons.some(p => p.ref && p.score < .45) && !h.copy)), goal(L('The balance: Anna, in your scene', 'L’equilibri: l’Anna, a la teva escena', 'El equilibrio: Anna, en tu escena'), (g, c) => ran(c, h => !h.copy && h.persons.some(p => p.ref === 'portrait_anna.png' && p.score >= .75)))],
      },
    ],
  },
  {
    id: 'masked', name: L('Masked injection', 'Injecció amb màscara', 'Inyección con máscara'), sub: L('Two faces · all together', 'Dues cares · tot junt', 'Dos caras · todo junto'),
    steps: [
      {
        title: L('Two people, two faces', 'Dues persones, dues cares', 'Dos personas, dos caras'),
        task: L('A woman on the left and a man on the right (regions are ready). Give her Anna’s face and him Leo’s, each IPAdapter FaceID with its own attn_mask.', 'Una dona a l’esquerra i un home a la dreta (les regions ja hi són). Dona-li a ella la cara de l’Anna i a ell la del Leo, cada IPAdapter FaceID amb la seva attn_mask.', 'Una mujer a la izquierda y un hombre a la derecha (las regiones ya están). Dale a ella la cara de Anna y a él la de Leo, cada IPAdapter FaceID con su attn_mask.'),
        concept: L('An IPAdapter affects the whole picture: two faces in the same model blend into one person. The <b>attn_mask</b> input limits each adapter to a part of the picture: Anna’s adapter only sees the left, Leo’s only the right. The masks are just masks: paint one half and use <b>InvertMask</b> for the other. Regions place the people; masked adapters give them their faces.', 'Un IPAdapter afecta tota la imatge: dues cares al mateix model es barregen en una sola persona. L’entrada <b>attn_mask</b> limita cada adaptador a una part de la imatge: el de l’Anna només veu l’esquerra, el del Leo només la dreta. Les màscares són màscares normals: pinta’n una meitat i fes servir <b>InvertMask</b> per a l’altra. Les regions col·loquen les persones; els adaptadors amb màscara els donen la cara.', 'Un IPAdapter afecta a toda la imagen: dos caras en el mismo modelo se mezclan en una sola persona. La entrada <b>attn_mask</b> limita cada adaptador a una parte de la imagen: el de Anna solo ve la izquierda, el de Leo solo la derecha. Las máscaras son máscaras normales: pinta una mitad y usa <b>InvertMask</b> para la otra. Las regiones colocan a las personas; los adaptadores con máscara les dan la cara.'),
        how: [L('Add the FaceID loader and two <b>IPAdapter FaceID</b> in a chain (Anna, then Leo).', 'Afegeix el loader FaceID i dos <b>IPAdapter FaceID</b> en cadena (Anna, després Leo).', 'Añade el loader FaceID y dos <b>IPAdapter FaceID</b> en cadena (Anna, luego Leo).'), L('A Load Image with the left half painted → attn_mask of Anna; through <b>InvertMask</b> → attn_mask of Leo.', 'Un Load Image amb la meitat esquerra pintada → attn_mask de l’Anna; a través d’<b>InvertMask</b> → attn_mask del Leo.', 'Un Load Image con la mitad izquierda pintada → attn_mask de Anna; a través de <b>InvertMask</b> → attn_mask de Leo.'), L('Run.', 'Executa.', 'Ejecuta.')],
        note: L('The same works for styles: a watercolour background and a realistic person, with two masked IPAdapters.', 'El mateix funciona per als estils: un fons d’aquarel·la i una persona realista, amb dos IPAdapters amb màscara.', 'Lo mismo funciona para los estilos: un fondo de acuarela y una persona realista, con dos IPAdapters con máscara.'),
        starter: G.twoStart, solution: G.two,
        goals: [goal(L('Two adapters with attention masks', 'Dos adaptadors amb màscares d’atenció', 'Dos adaptadores con máscaras de atención'), (g, c) => ran(c, h => h.maskedAdapters >= 2)), goal(L('Anna on the left, Leo on the right', 'L’Anna a l’esquerra, el Leo a la dreta', 'Anna a la izquierda, Leo a la derecha'), (g, c) => ran(c, h => h.persons.some(p => p.x < .5 && p.ref === 'portrait_anna.png' && p.score >= .7) && h.persons.some(p => p.x > .5 && p.ref === 'portrait_leo.png' && p.score >= .7)))],
      },
      {
        title: L('All together', 'Tot junt', 'Todo junto'),
        task: L('The pose is already controlled. Add Anna’s face (FaceID) and the watercolour style (IPAdapter, style transfer) and get the final picture.', 'La postura ja està controlada. Afegeix la cara de l’Anna (FaceID) i l’estil d’aquarel·la (IPAdapter, style transfer) i aconsegueix la imatge final.', 'La postura ya está controlada. Añade la cara de Anna (FaceID) y el estilo de acuarela (IPAdapter, style transfer) y consigue la imagen final.'),
        concept: L('Each tool does one job, and they stack: <b>ControlNet</b> (conditioning) decides the shape, <b>FaceID</b> (model) who it is, <b>IPAdapter style transfer</b> (model) how it looks, and the <b>prompt</b> the rest. Two adapters on the model path chain one after the other, each with its own loader. With all of them at moderate weights, nobody fights.', 'Cada eina fa una feina, i s’apilen: la <b>ControlNet</b> (conditioning) decideix la forma, <b>FaceID</b> (model) qui és, <b>IPAdapter style transfer</b> (model) com es veu, i el <b>prompt</b> la resta. Dos adaptadors al camí del model s’encadenen l’un darrere l’altre, cadascun amb el seu loader. Amb tots a pesos moderats, ningú no es baralla.', 'Cada herramienta hace un trabajo, y se apilan: la <b>ControlNet</b> (conditioning) decide la forma, <b>FaceID</b> (model) quién es, <b>IPAdapter style transfer</b> (model) cómo se ve, y el <b>prompt</b> el resto. Dos adaptadores en el camino del modelo se encadenan uno detrás de otro, cada uno con su loader. Con todos a pesos moderados, nadie se pelea.'),
        how: [L('Load Checkpoint → FaceID loader → IPAdapter FaceID (portrait_anna, 0.85).', 'Load Checkpoint → loader FaceID → IPAdapter FaceID (portrait_anna, 0.85).', 'Load Checkpoint → loader FaceID → IPAdapter FaceID (portrait_anna, 0.85).'), L('→ IPAdapter Unified Loader → IPAdapter Advanced (ref_watercolor, style transfer, 0.8) → KSampler.', '→ IPAdapter Unified Loader → IPAdapter Advanced (ref_watercolor, style transfer, 0.8) → KSampler.', '→ IPAdapter Unified Loader → IPAdapter Advanced (ref_watercolor, style transfer, 0.8) → KSampler.'), L('Run, and save the workflow (<kbd>Ctrl S</kbd>).', 'Executa, i desa el workflow (<kbd>Ctrl S</kbd>).', 'Ejecuta, y guarda el workflow (<kbd>Ctrl S</kbd>).')],
        note: L('With Flux the same ideas exist with other nodes (ControlNet union, Redux for images, PuLID for faces).', 'Amb Flux les mateixes idees existeixen amb altres nodes (ControlNet union, Redux per a imatges, PuLID per a cares).', 'Con Flux las mismas ideas existen con otros nodos (ControlNet union, Redux para imágenes, PuLID para caras).'),
        starter: G.finalStart, solution: G.final,
        goals: [goal(L('The pose from the ControlNet', 'La postura de la ControlNet', 'La postura de la ControlNet'), (g, c) => ran(c, h => h.posed)), goal(L('Anna’s face', 'La cara de l’Anna', 'La cara de Anna'), (g, c) => ran(c, h => h.posed && h.persons.some(p => p.ref === 'portrait_anna.png' && p.score >= .75) && !h.copy)), goal(L('Watercolour style, no leaked content', 'Estil d’aquarel·la, sense contingut colat', 'Estilo de acuarela, sin contenido colado'), (g, c) => ran(c, h => h.posed && h.style?.style === 'watercolor' && h.style.amount >= .5 && !h.leak && h.persons.some(p => p.score >= .75))), goal(L('Saved the workflow', 'Has desat el workflow', 'Has guardado el workflow'), (g, c) => c.flags.saved, true)],
      },
    ],
  },
];

export const TEMPLATES = [
  { id: 'pose', name: L('ControlNet (pose)', 'ControlNet (postura)', 'ControlNet (postura)'), make: () => G.cn() },
  { id: 'multi', name: L('Two ControlNets', 'Dues ControlNets', 'Dos ControlNets'), make: () => G.multi() },
  { id: 'regions', name: L('Regional prompts', 'Prompts regionals', 'Prompts regionales'), make: G.regions },
  { id: 'style', name: L('IPAdapter style transfer', 'IPAdapter style transfer', 'IPAdapter style transfer'), make: () => G.ipa({ type: 'style transfer' }) },
  { id: 'faceid', name: L('FaceID', 'FaceID', 'FaceID'), make: () => G.faceid() },
  { id: 'two-faces', name: L('Two faces (masked)', 'Dues cares (amb màscara)', 'Dos caras (con máscara)'), make: G.two },
];
export { G as GRAPHS };
