// Carrot Revolt Labs · Flux Lab · stages, steps and live checklists.
// It runs on the ComfyUI Lab interface (../comfyui/app.js) and adds the Flux nodes and simulator (./nodes.js).
import { defaultGraph, makeNode, makeLink, connect } from '../comfyui/engine.js';
import { historyExtra as hx, VRAM, KONTEXT_PHOTO } from './nodes.js';
export const L = (en, ca, es) => ({ en, ca, es });

export const META = { key: 'carrot-revolt-comfy-flux:', title: 'Flux Lab', label: 'GENERATIVE IMAGE / COMFYUI · 04' };
export const historyExtra = hx;

/* ── Graph helpers ── */
const N = (g, type) => g.nodes.filter(n => n.type === type && n.mode === 0);
const into = (g, id, input) => g.links.find(l => l.to === id && l.input === input);
const from = (g, id, input) => { const l = into(g, id, input); return l ? g.nodes.find(n => n.id === l.from) : null; };
// Follow a conditioning wire back towards the prompt and list the node types it goes through.
const condPath = (g, id, input) => { const out = []; let n = from(g, id, input); for (let i = 0; n && i < 12; i++) { out.push(n); const next = ['conditioning', 'positive'].map(k => from(g, n.id, k)).find(Boolean); n = next; } return out; };
const goal = (text, test, optional = false) => ({ text, test, optional });
const add = (g, ...nodes) => { g.nodes.push(...nodes); return g; };
const wire = (g, list) => { for (const l of list) connect(g, makeLink(...l)); return g; };
const set = (g, id, k, v) => { g.nodes.find(n => n.id === id).widgets[k] = v; return g; };
const move = (g, id, x, y) => { const n = g.nodes.find(n => n.id === id); n.x = x; n.y = y; return g; };
const drop = (g, id) => { g.nodes = g.nodes.filter(n => n.id !== id); g.links = g.links.filter(l => l.from !== id && l.to !== id); return g; };
const runs = c => c.history.filter(h => h.family);
const ran = (c, f) => runs(c).some(f);
const flux = h => h.family === 'flux';
const PROMPT = 'a cat sitting in a sunny landscape, golden light, detailed';
const CAT_MASK = [.49, .58, .67, .76, .84].map(y => ({ p: [[.35, y], [.68, y]], r: .06 }));

/* ── Starters and solutions ── */
const G = {
  sd: (text = PROMPT, ckpt = 'dreamshaper_8.safetensors', size = 512) => { const g = defaultGraph(); set(g, 'pos', 'text', text); set(g, 'neg', 'text', 'blurry, text, watermark'); set(g, 'sampler', 'control_after_generate', 'fixed'); set(g, 'ckpt', 'ckpt_name', ckpt); set(g, 'latent', 'width', size); set(g, 'latent', 'height', size); return g; },
  flux: ({ unet = 'flux1-dev.safetensors', dtype = 'fp8_e4m3fn', gguf = null, type = 'flux', vae = 'ae.safetensors', cfg = 1, steps = 20, text = PROMPT, neg = '', fg = true, guidance = 3.5, w = 1024, h = 1024 } = {}) => {
    const g = drop(drop(defaultGraph(), 'ckpt'), 'latent');
    add(g, gguf ? makeNode('UnetLoaderGGUF', 26, 120, { unet_name: gguf }, 'unet') : makeNode('UNETLoader', 26, 120, { unet_name: unet, weight_dtype: dtype }, 'unet'), makeNode('DualCLIPLoader', 26, 300, { type }, 'clip'), makeNode('VAELoader', 26, 540, { vae_name: vae }, 'vae'), makeNode('EmptySD3LatentImage', 473, 609, { width: w, height: h }, 'latent'));
    set(g, 'pos', 'text', text); set(g, 'neg', 'text', neg);
    for (const [k, v] of Object.entries({ cfg, steps, sampler_name: 'euler', scheduler: 'simple', control_after_generate: 'fixed' })) set(g, 'sampler', k, v);
    wire(g, [['unet', 0, 'sampler', 'model'], ['clip', 0, 'pos', 'clip'], ['clip', 0, 'neg', 'clip'], ['vae', 0, 'decode', 'vae'], ['latent', 0, 'sampler', 'latent_image']]);
    if (fg) { add(g, makeNode('FluxGuidance', 863, 30, { guidance }, 'fg')); wire(g, [['pos', 0, 'fg', 'conditioning'], ['fg', 0, 'sampler', 'positive']]); }
    return g;
  },
  fill: (unet = 'flux1-fill-dev.safetensors', guidance = 30) => {
    const g = drop(G.flux({ unet, guidance, text: 'a blue robot in a landscape, detailed' }), 'latent');
    add(g, makeNode('LoadImage', 26, 760, { image: 'garden_cat.png', mask: CAT_MASK }, 'img'), makeNode('InpaintModelConditioning', 470, 640, {}, 'imc'));
    move(g, 'sampler', 1240, 186); move(g, 'decode', 1600, 188); move(g, 'save', 1850, 189); move(g, 'fg', 900, 30);
    return wire(g, [['fg', 0, 'imc', 'positive'], ['neg', 0, 'imc', 'negative'], ['vae', 0, 'imc', 'vae'], ['img', 0, 'imc', 'pixels'], ['img', 1, 'imc', 'mask'], ['imc', 0, 'sampler', 'positive'], ['imc', 1, 'sampler', 'negative'], ['imc', 2, 'sampler', 'latent_image']]);
  },
  kontext: (ref = true, text = 'make the cat black and turn the scene into night') => {
    const g = G.flux({ unet: 'flux1-kontext-dev.safetensors', guidance: 2.5, text });
    add(g, makeNode('LoadImage', 26, 760, { image: KONTEXT_PHOTO.name }, 'kimg'), makeNode('FluxKontextImageScale', 400, 860, {}, 'kscale'), makeNode('VAEEncode', 680, 860, {}, 'kenc'));
    wire(g, [['kimg', 0, 'kscale', 'image'], ['kscale', 0, 'kenc', 'pixels'], ['vae', 0, 'kenc', 'vae']]);
    if (ref) { add(g, makeNode('ReferenceLatent', 863, -90, {}, 'ref')); wire(g, [['pos', 0, 'ref', 'conditioning'], ['kenc', 0, 'ref', 'latent'], ['ref', 0, 'fg', 'conditioning']]); }
    return g;
  },
  lora: (name = 'watercolor_sd15.safetensors', text = PROMPT) => { const g = G.flux({ text }); add(g, makeNode('LoraLoaderModelOnly', 400, 20, { lora_name: name }, 'lora')); return wire(g, [['unet', 0, 'lora', 'model'], ['lora', 0, 'sampler', 'model']]); },
};

export const UI = {
  headline: L('Three files, <span>one model.</span>', 'Tres fitxers, <span>un model.</span>', 'Tres archivos, <span>un modelo.</span>'),
  lead: L('Modern models work differently: Flux comes in parts (diffusion model, text encoders, VAE), samples at CFG 1 with its own guidance, ignores the negative prompt, reads whole sentences and writes text in the picture. Learn to load it, to fit it in memory, to sample and prompt it, and its tools: Fill to inpaint and Kontext to edit with words.', 'Els models moderns funcionen diferent: Flux ve per parts (model de difusió, text encoders, VAE), mostreja amb CFG 1 i la seva pròpia guidance, ignora el prompt negatiu, llegeix frases senceres i escriu text a la imatge. Aprèn a carregar-lo, a fer-lo cabre a la memòria, a mostrejar-lo i a fer-li prompts, i les seves eines: Fill per a l’inpainting i Kontext per editar amb paraules.', 'Los modelos modernos funcionan distinto: Flux viene por partes (modelo de difusión, text encoders, VAE), muestrea con CFG 1 y su propia guidance, ignora el prompt negativo, lee frases enteras y escribe texto en la imagen. Aprende a cargarlo, a hacerlo caber en la memoria, a muestrearlo y a hacerle prompts, y sus herramientas: Fill para el inpainting y Kontext para editar con palabras.'),
  loraVsCn: L('SD or Flux?', 'SD o Flux?', '¿SD o Flux?'),
};
const T3 = (h, rows, foot) => `<table class="c-cmp"><tr><th></th><th>${h[0]}</th><th>${h[1]}</th></tr>${rows.map(r => `<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</table><p>${foot}</p>`;
UI.loraVsCnBody = L(
  T3(['SD 1.5 / SDXL', 'Flux dev'], [['Files', 'one checkpoint', 'model + text encoders + VAE'], ['CFG', '5–8', '1 (+ Flux Guidance 3.5)'], ['Negative', 'yes', 'ignored at CFG 1'], ['Prompt', 'tags, (weights)', 'sentences, text in quotes'], ['Size', '512 / 1024', '0.5–2 MP, ×16']], 'Newer families (Flux.2, Qwen-Image…) follow the same pattern: separate files, natural language, low CFG.'),
  T3(['SD 1.5 / SDXL', 'Flux dev'], [['Fitxers', 'un checkpoint', 'model + text encoders + VAE'], ['CFG', '5–8', '1 (+ Flux Guidance 3.5)'], ['Negatiu', 'sí', 'ignorat amb CFG 1'], ['Prompt', 'etiquetes, (pesos)', 'frases, text entre cometes'], ['Mida', '512 / 1024', '0.5–2 MP, ×16']], 'Les famílies noves (Flux.2, Qwen-Image…) segueixen el mateix patró: fitxers separats, llenguatge natural, CFG baix.'),
  T3(['SD 1.5 / SDXL', 'Flux dev'], [['Archivos', 'un checkpoint', 'modelo + text encoders + VAE'], ['CFG', '5–8', '1 (+ Flux Guidance 3.5)'], ['Negativo', 'sí', 'ignorado con CFG 1'], ['Prompt', 'etiquetas, (pesos)', 'frases, texto entre comillas'], ['Tamaño', '512 / 1024', '0.5–2 MP, ×16']], 'Las familias nuevas (Flux.2, Qwen-Image…) siguen el mismo patrón: archivos separados, lenguaje natural, CFG bajo.'));

export const DOCS = {
  UNETLoader: { short: L('Loads only the diffusion model.', 'Carrega només el model de difusió.', 'Carga solo el modelo de difusión.'), long: L('Modern models ship the diffusion model alone (models/diffusion_models). weight_dtype fp8 loads it at half the memory with almost the same quality.', 'Els models moderns es distribueixen amb el model de difusió sol (models/diffusion_models). weight_dtype fp8 el carrega amb la meitat de memòria i gairebé la mateixa qualitat.', 'Los modelos modernos se distribuyen con el modelo de difusión solo (models/diffusion_models). weight_dtype fp8 lo carga con la mitad de memoria y casi la misma calidad.'), widgets: { unet_name: L('dev, schnell, fill, kontext…', 'dev, schnell, fill, kontext…', 'dev, schnell, fill, kontext…'), weight_dtype: L('default = full precision; fp8 = half the memory', 'default = precisió completa; fp8 = la meitat de memòria', 'default = precisión completa; fp8 = la mitad de memoria') } },
  UnetLoaderGGUF: { short: L('Loads a quantized (GGUF) diffusion model.', 'Carrega un model de difusió quantitzat (GGUF).', 'Carga un modelo de difusión cuantizado (GGUF).'), long: L('Custom node (ComfyUI-GGUF). Q8 is practically identical to the original; Q4 fits small cards with a small loss of detail.', 'Custom node (ComfyUI-GGUF). Q8 és pràcticament idèntic a l’original; Q4 cap a targetes petites amb una petita pèrdua de detall.', 'Custom node (ComfyUI-GGUF). Q8 es prácticamente idéntico al original; Q4 cabe en tarjetas pequeñas con una pequeña pérdida de detalle.') },
  DualCLIPLoader: { short: L('Loads two text encoders.', 'Carrega dos text encoders.', 'Carga dos text encoders.'), long: L('Flux reads the prompt with CLIP-L and T5-XXL (models/text_encoders). type must say which model they are for. T5 in fp8 saves RAM with no visible change.', 'Flux llegeix el prompt amb CLIP-L i T5-XXL (models/text_encoders). type ha de dir per a quin model són. T5 en fp8 estalvia RAM sense cap canvi visible.', 'Flux lee el prompt con CLIP-L y T5-XXL (models/text_encoders). type debe decir para qué modelo son. T5 en fp8 ahorra RAM sin cambio visible.'), widgets: { type: L('flux for Flux, sdxl for SDXL…', 'flux per a Flux, sdxl per a SDXL…', 'flux para Flux, sdxl para SDXL…') } },
  VAELoader: { short: L('Loads a VAE.', 'Carrega un VAE.', 'Carga un VAE.'), long: L('Flux uses its own VAE (ae.safetensors, 16 channels). A VAE of another family cannot read its latents.', 'Flux fa servir el seu VAE (ae.safetensors, 16 canals). Un VAE d’una altra família no pot llegir els seus latents.', 'Flux usa su VAE (ae.safetensors, 16 canales). Un VAE de otra familia no puede leer sus latentes.') },
  EmptySD3LatentImage: { short: L('Empty latent for modern models (16 channels).', 'Latent buit per a models moderns (16 canals).', 'Latente vacío para modelos modernos (16 canales).'), long: L('The empty latent the Flux and SD3 templates use. Sizes in steps of 16.', 'El latent buit que fan servir les plantilles de Flux i SD3. Mides de 16 en 16.', 'El latente vacío que usan las plantillas de Flux y SD3. Tamaños de 16 en 16.') },
  FluxGuidance: { short: L('Sets Flux’s guidance (instead of CFG).', 'Fixa la guidance de Flux (en lloc del CFG).', 'Fija la guidance de Flux (en lugar del CFG).'), long: L('Flux dev learned the effect of CFG inside the model: you get it with this value and keep the KSampler at CFG 1. 3.5 is the default; 2–3 looks more natural, 5+ more contrasted and plastic. Fill wants about 30, Kontext about 2.5.', 'Flux dev va aprendre l’efecte del CFG dins el model: l’obtens amb aquest valor i deixes el KSampler a CFG 1. 3.5 és el valor per defecte; 2–3 es veu més natural, 5+ més contrastat i de plàstic. Fill vol uns 30, Kontext uns 2.5.', 'Flux dev aprendió el efecto del CFG dentro del modelo: lo obtienes con este valor y dejas el KSampler a CFG 1. 3.5 es el valor por defecto; 2–3 se ve más natural, 5+ más contrastado y plástico. Fill quiere unos 30, Kontext unos 2.5.') },
  CLIPTextEncodeFlux: { short: L('A Flux prompt with separate CLIP-L and T5 texts.', 'Un prompt de Flux amb textos separats per a CLIP-L i T5.', 'Un prompt de Flux con textos separados para CLIP-L y T5.'), long: L('Lets you give short tags to CLIP-L and the full description to T5, with the guidance included.', 'Permet donar etiquetes curtes a CLIP-L i la descripció completa a T5, amb la guidance inclosa.', 'Permite dar etiquetas cortas a CLIP-L y la descripción completa a T5, con la guidance incluida.') },
  ModelSamplingFlux: { short: L('Adjusts Flux’s noise schedule to the size.', 'Ajusta el calendari de soroll de Flux a la mida.', 'Ajusta el calendario de ruido de Flux al tamaño.'), long: L('Bigger pictures need more “shift”. Its width and height must match the latent, or the result gets soft.', 'Les imatges més grans necessiten més “shift”. La seva amplada i alçada han de coincidir amb el latent, o el resultat queda tou.', 'Las imágenes más grandes necesitan más “shift”. Su ancho y alto deben coincidir con el latente, o el resultado queda blando.') },
  LoraLoaderModelOnly: { short: L('Applies a LoRA to the MODEL only.', 'Aplica una LoRA només al MODEL.', 'Aplica una LoRA solo al MODEL.'), long: L('Most Flux LoRAs only train the diffusion model, so they go between the loader and the KSampler. A LoRA must match the family: an SD 1.5 LoRA on Flux does nothing (“lora key not loaded”).', 'La majoria de LoRAs de Flux només entrenen el model de difusió, i van entre el loader i el KSampler. Una LoRA ha de coincidir amb la família: una LoRA de SD 1.5 a Flux no fa res (“lora key not loaded”).', 'La mayoría de LoRAs de Flux solo entrenan el modelo de difusión, y van entre el loader y el KSampler. Una LoRA debe coincidir con la familia: una LoRA de SD 1.5 en Flux no hace nada (“lora key not loaded”).') },
  ReferenceLatent: { short: L('Attaches a reference picture to the conditioning.', 'Afegeix una imatge de referència al conditioning.', 'Añade una imagen de referencia al conditioning.'), long: L('For edit models like Kontext: the model sees the encoded picture and the instruction, and changes only what you ask.', 'Per a models d’edició com Kontext: el model veu la imatge codificada i la instrucció, i només canvia el que demanes.', 'Para modelos de edición como Kontext: el modelo ve la imagen codificada y la instrucción, y solo cambia lo que pides.') },
  FluxKontextImageScale: { short: L('Scales a picture to a size Kontext likes.', 'Escala una imatge a una mida que agrada a Kontext.', 'Escala una imagen a un tamaño que le gusta a Kontext.'), long: L('Keeps the aspect ratio and picks the closest of the resolutions Kontext was trained on (about 1 megapixel).', 'Manté la proporció i tria la resolució més propera de les que es va entrenar Kontext (prop d’1 megapíxel).', 'Mantiene la proporción y elige la resolución más cercana de las que se entrenó Kontext (cerca de 1 megapíxel).') },
};

export const STAGES = [
  {
    id: 'parts', name: L('Models in parts', 'Models per parts', 'Modelos por partes'), sub: L('Load · mistakes · memory', 'Carrega · errors · memòria', 'Carga · errores · memoria'),
    steps: [
      {
        title: L('Load Flux in three parts', 'Carrega Flux en tres parts', 'Carga Flux en tres partes'),
        task: L('Replace Load Checkpoint with Load Diffusion Model, DualCLIPLoader and Load VAE, and generate with Flux.', 'Substitueix Load Checkpoint per Load Diffusion Model, DualCLIPLoader i Load VAE, i genera amb Flux.', 'Sustituye Load Checkpoint por Load Diffusion Model, DualCLIPLoader y Load VAE, y genera con Flux.'),
        concept: L('A checkpoint is three models in one file. Modern models come <b>in parts</b>: the <b>diffusion model</b> (models/diffusion_models), the <b>text encoders</b> (models/text_encoders: Flux uses CLIP-L and T5-XXL, a big language encoder that reads whole sentences) and the <b>VAE</b> (models/vae). You load each with its own node and wire them where Load Checkpoint’s MODEL, CLIP and VAE used to go.', 'Un checkpoint són tres models en un fitxer. Els models moderns venen <b>per parts</b>: el <b>model de difusió</b> (models/diffusion_models), els <b>text encoders</b> (models/text_encoders: Flux fa servir CLIP-L i T5-XXL, un encoder de llenguatge gran que llegeix frases senceres) i el <b>VAE</b> (models/vae). Cadascun es carrega amb el seu node i es connecta on anaven el MODEL, el CLIP i el VAE de Load Checkpoint.', 'Un checkpoint son tres modelos en un archivo. Los modelos modernos vienen <b>por partes</b>: el <b>modelo de difusión</b> (models/diffusion_models), los <b>text encoders</b> (models/text_encoders: Flux usa CLIP-L y T5-XXL, un encoder de lenguaje grande que lee frases enteras) y el <b>VAE</b> (models/vae). Cada uno se carga con su nodo y se conecta donde iban el MODEL, el CLIP y el VAE de Load Checkpoint.'),
        how: [L('Add <b>Load Diffusion Model</b> (flux1-dev, weight_dtype fp8_e4m3fn) → model of the KSampler.', 'Afegeix <b>Load Diffusion Model</b> (flux1-dev, weight_dtype fp8_e4m3fn) → model del KSampler.', 'Añade <b>Load Diffusion Model</b> (flux1-dev, weight_dtype fp8_e4m3fn) → model del KSampler.'), L('<b>DualCLIPLoader</b> (clip_l + t5xxl, type <b>flux</b>) → clip of both prompts. <b>Load VAE</b> (ae) → VAE Decode.', '<b>DualCLIPLoader</b> (clip_l + t5xxl, type <b>flux</b>) → clip dels dos prompts. <b>Load VAE</b> (ae) → VAE Decode.', '<b>DualCLIPLoader</b> (clip_l + t5xxl, type <b>flux</b>) → clip de los dos prompts. <b>Load VAE</b> (ae) → VAE Decode.'), L('Delete Load Checkpoint, set the latent to 1024 × 1024 and the KSampler to cfg <b>1</b>, scheduler simple. Run.', 'Esborra Load Checkpoint, posa el latent a 1024 × 1024 i el KSampler a cfg <b>1</b>, scheduler simple. Executa.', 'Borra Load Checkpoint, pon el latente a 1024 × 1024 y el KSampler a cfg <b>1</b>, scheduler simple. Ejecuta.')],
        note: L('Why CFG 1 is explained in stage 2. There are also “all in one” Flux checkpoints (flux1-dev-fp8) that load with Load Checkpoint.', 'Per què CFG 1 s’explica a l’etapa 2. També hi ha checkpoints de Flux “tot en un” (flux1-dev-fp8) que es carreguen amb Load Checkpoint.', 'Por qué CFG 1 se explica en la etapa 2. También hay checkpoints de Flux “todo en uno” (flux1-dev-fp8) que se cargan con Load Checkpoint.'),
        starter: () => G.sd(), solution: () => G.flux({ fg: false }),
        goals: [goal(L('Load Diffusion Model feeds the KSampler', 'Load Diffusion Model alimenta el KSampler', 'Load Diffusion Model alimenta el KSampler'), g => N(g, 'KSampler').some(s => ['UNETLoader', 'UnetLoaderGGUF'].includes(from(g, s.id, 'model')?.type))), goal(L('DualCLIPLoader (type flux) feeds the prompts', 'DualCLIPLoader (type flux) alimenta els prompts', 'DualCLIPLoader (type flux) alimenta los prompts'), g => N(g, 'CLIPTextEncode').length >= 2 && N(g, 'CLIPTextEncode').every(c => from(g, c.id, 'clip')?.type === 'DualCLIPLoader' && from(g, c.id, 'clip').widgets.type === 'flux')), goal(L('Load VAE (ae) feeds VAE Decode', 'Load VAE (ae) alimenta VAE Decode', 'Load VAE (ae) alimenta VAE Decode'), g => N(g, 'VAEDecode').some(v => from(g, v.id, 'vae')?.widgets?.vae_name === 'ae.safetensors')), goal(L('A Flux picture', 'Una imatge de Flux', 'Una imagen de Flux'), (g, c) => ran(c, h => flux(h) && !h.burned))],
      },
      {
        title: L('Two classic mistakes', 'Dos errors clàssics', 'Dos errores clásicos'),
        task: L('This graph has two wrong settings. Run it, read each error and fix it until it generates.', 'Aquest graf té dos paràmetres malament. Executa’l, llegeix cada error i arregla’l fins que generi.', 'Este grafo tiene dos parámetros mal. Ejecútalo, lee cada error y arréglalo hasta que genere.'),
        concept: L('With models in parts, each part must belong to the same family. A <b>DualCLIPLoader with the wrong type</b> builds conditioning of the wrong shape: the KSampler fails with “mat1 and mat2 shapes cannot be multiplied”. A <b>VAE of another family</b> cannot read the latent: Flux latents have 16 channels, SD ones 4 (“expected input to have 4 channels, but got 16”). Learn to read these messages: they tell you which piece does not fit.', 'Amb els models per parts, cada part ha de ser de la mateixa família. Un <b>DualCLIPLoader amb el type equivocat</b> fa un conditioning amb una forma equivocada: el KSampler falla amb “mat1 and mat2 shapes cannot be multiplied”. Un <b>VAE d’una altra família</b> no pot llegir el latent: els latents de Flux tenen 16 canals i els de SD 4 (“expected input to have 4 channels, but got 16”). Aprèn a llegir aquests missatges: et diuen quina peça no encaixa.', 'Con los modelos por partes, cada parte debe ser de la misma familia. Un <b>DualCLIPLoader con el type equivocado</b> hace un conditioning con una forma equivocada: el KSampler falla con “mat1 and mat2 shapes cannot be multiplied”. Un <b>VAE de otra familia</b> no puede leer el latente: los latentes de Flux tienen 16 canales y los de SD 4 (“expected input to have 4 channels, but got 16”). Aprende a leer estos mensajes: te dicen qué pieza no encaja.'),
        how: [L('Run: the KSampler fails. DualCLIPLoader › type <b>flux</b>.', 'Executa: falla el KSampler. DualCLIPLoader › type <b>flux</b>.', 'Ejecuta: falla el KSampler. DualCLIPLoader › type <b>flux</b>.'), L('Run: now VAE Decode fails. Load VAE › <b>ae.safetensors</b>.', 'Executa: ara falla VAE Decode. Load VAE › <b>ae.safetensors</b>.', 'Ejecuta: ahora falla VAE Decode. Load VAE › <b>ae.safetensors</b>.'), L('Run again.', 'Torna a executar.', 'Vuelve a ejecutar.')],
        note: L('The node with the red outline is where it failed, not always where the mistake is: the wrong piece is usually upstream.', 'El node amb el contorn vermell és on ha fallat, no sempre on hi ha l’error: la peça equivocada sol ser més amunt.', 'El nodo con el contorno rojo es donde ha fallado, no siempre donde está el error: la pieza equivocada suele estar más arriba.'),
        starter: () => G.flux({ type: 'sdxl', vae: 'sdxl_vae.safetensors', fg: false }), solution: () => G.flux({ fg: false }),
        goals: [goal(L('Read the shape error (text encoders)', 'Has llegit l’error de forma (text encoders)', 'Has leído el error de forma (text encoders)'), (g, c) => c.flags.rt_shape), goal(L('Read the VAE channels error', 'Has llegit l’error de canals del VAE', 'Has leído el error de canales del VAE'), (g, c) => c.flags.rt_vae), goal(L('Generated after fixing both', 'Has generat després d’arreglar-los', 'Has generado después de arreglarlos'), (g, c) => ran(c, h => flux(h)))],
      },
      {
        title: L('Memory and precision', 'Memòria i precisió', 'Memoria y precisión'),
        task: L('Run Flux at full precision on the simulated 16 GB card, then make it fit: weight_dtype fp8 or a GGUF model.', 'Executa Flux a precisió completa a la targeta simulada de 16 GB i després fes-lo cabre: weight_dtype fp8 o un model GGUF.', 'Ejecuta Flux a precisión completa en la tarjeta simulada de 16 GB y luego hazlo caber: weight_dtype fp8 o un modelo GGUF.'),
        concept: L('Flux dev has 12 billion parameters: <b>23.8 GB</b> at full precision (fp16). If it does not fit, ComfyUI loads it partially and keeps moving pieces from RAM, many times slower. Two ways to make it smaller: <b>fp8</b> (weight_dtype, 11.9 GB, almost identical) and <b>GGUF</b> quantization (custom node ComfyUI-GGUF: Q8 12.7 GB, practically identical; Q4 6.8 GB for 8 GB cards, slightly softer).', 'Flux dev té 12.000 milions de paràmetres: <b>23.8 GB</b> a precisió completa (fp16). Si no hi cap, ComfyUI el carrega parcialment i va movent trossos des de la RAM, moltes vegades més lent. Dues maneres de fer-lo més petit: <b>fp8</b> (weight_dtype, 11.9 GB, gairebé idèntic) i la quantització <b>GGUF</b> (custom node ComfyUI-GGUF: Q8 12.7 GB, pràcticament idèntic; Q4 6.8 GB per a targetes de 8 GB, una mica més tou).', 'Flux dev tiene 12.000 millones de parámetros: <b>23.8 GB</b> a precisión completa (fp16). Si no cabe, ComfyUI lo carga parcialmente y va moviendo trozos desde la RAM, muchas veces más lento. Dos formas de hacerlo más pequeño: <b>fp8</b> (weight_dtype, 11.9 GB, casi idéntico) y la cuantización <b>GGUF</b> (custom node ComfyUI-GGUF: Q8 12.7 GB, prácticamente idéntico; Q4 6.8 GB para tarjetas de 8 GB, un poco más blando).'),
        how: [L('Run: the log says “loaded partially … offloaded” (slow).', 'Executa: el log diu “loaded partially … offloaded” (lent).', 'Ejecuta: el log dice “loaded partially … offloaded” (lento).'), L('Load Diffusion Model › weight_dtype <b>fp8_e4m3fn</b>, run.', 'Load Diffusion Model › weight_dtype <b>fp8_e4m3fn</b>, executa.', 'Load Diffusion Model › weight_dtype <b>fp8_e4m3fn</b>, ejecuta.'), L('Optional: replace it with <b>Unet Loader (GGUF)</b> Q4_K_S and compare.', 'Opcional: substitueix-lo per <b>Unet Loader (GGUF)</b> Q4_K_S i compara.', 'Opcional: sustitúyelo por <b>Unet Loader (GGUF)</b> Q4_K_S y compara.')],
        note: L('The T5 text encoder is also big (9.8 GB in fp16): t5xxl_fp8 halves it. ComfyUI unloads it after encoding the prompt, so it costs RAM more than VRAM.', 'El text encoder T5 també és gros (9.8 GB en fp16): t5xxl_fp8 el redueix a la meitat. ComfyUI el descarrega després de codificar el prompt, i costa més RAM que VRAM.', 'El text encoder T5 también es grande (9.8 GB en fp16): t5xxl_fp8 lo reduce a la mitad. ComfyUI lo descarga después de codificar el prompt, y cuesta más RAM que VRAM.'),
        starter: () => G.flux({ dtype: 'default', fg: false }), solution: () => G.flux({ fg: false }),
        goals: [goal(L('Saw a partial load', 'Has vist una càrrega parcial', 'Has visto una carga parcial'), (g, c) => ran(c, h => flux(h) && h.partial)), goal(L(`A run that fits in ${VRAM.gb} GB`, `Una execució que cap a ${VRAM.gb} GB`, `Una ejecución que cabe en ${VRAM.gb} GB`), (g, c) => ran(c, h => flux(h) && !h.partial)), goal(L('Tried a Q4 GGUF', 'Has provat un GGUF Q4', 'Has probado un GGUF Q4'), (g, c) => ran(c, h => flux(h) && h.quant === 'Q4_K_S'), true)],
      },
    ],
  },
  {
    id: 'sampling', name: L('Sampling Flux', 'Mostrejar Flux', 'Muestrear Flux'), sub: L('CFG 1 · guidance · negative · schnell', 'CFG 1 · guidance · negatiu · schnell', 'CFG 1 · guidance · negativo · schnell'),
    steps: [
      {
        title: L('CFG 1 and Flux Guidance', 'CFG 1 i Flux Guidance', 'CFG 1 y Flux Guidance'),
        task: L('Run with cfg 8 (the SD habit) and see what happens. Then cfg 1, and a FluxGuidance node on the positive prompt.', 'Executa amb cfg 8 (l’hàbit de SD) i mira què passa. Després cfg 1, i un node FluxGuidance al prompt positiu.', 'Ejecuta con cfg 8 (el hábito de SD) y mira qué pasa. Luego cfg 1, y un nodo FluxGuidance en el prompt positivo.'),
        concept: L('CFG runs the model twice per step (with and without the prompt) and pushes the difference. Flux dev was <b>distilled</b>: it learned that push inside the model, controlled by a number, the <b>guidance</b>. So the KSampler stays at <b>CFG 1</b> (one pass per step, twice as fast) and the strength goes in <b>FluxGuidance</b> (3.5 by default). CFG 8 on Flux burns the picture and doubles the time.', 'El CFG executa el model dues vegades per step (amb i sense el prompt) i empeny la diferència. Flux dev està <b>destil·lat</b>: va aprendre aquesta empenta dins el model, controlada per un número, la <b>guidance</b>. Per això el KSampler es queda a <b>CFG 1</b> (una passada per step, el doble de ràpid) i la força va a <b>FluxGuidance</b> (3.5 per defecte). CFG 8 a Flux crema la imatge i dobla el temps.', 'El CFG ejecuta el modelo dos veces por step (con y sin el prompt) y empuja la diferencia. Flux dev está <b>destilado</b>: aprendió ese empuje dentro del modelo, controlado por un número, la <b>guidance</b>. Por eso el KSampler se queda a <b>CFG 1</b> (una pasada por step, el doble de rápido) y la fuerza va a <b>FluxGuidance</b> (3.5 por defecto). CFG 8 en Flux quema la imagen y dobla el tiempo.'),
        how: [L('Run as it is (cfg 8): burned, oversaturated.', 'Executa tal com està (cfg 8): cremat, sobresaturat.', 'Ejecuta tal cual (cfg 8): quemado, sobresaturado.'), L('KSampler › cfg <b>1</b>.', 'KSampler › cfg <b>1</b>.', 'KSampler › cfg <b>1</b>.'), L('Add <b>FluxGuidance</b> between the positive CLIP Text Encode and the KSampler (3.5). Run.', 'Afegeix <b>FluxGuidance</b> entre el CLIP Text Encode positiu i el KSampler (3.5). Executa.', 'Añade <b>FluxGuidance</b> entre el CLIP Text Encode positivo y el KSampler (3.5). Ejecuta.')],
        note: L('Without a FluxGuidance node, Flux dev uses 3.5 anyway: the node is there to change it.', 'Sense node FluxGuidance, Flux dev fa servir 3.5 igualment: el node hi és per canviar-lo.', 'Sin nodo FluxGuidance, Flux dev usa 3.5 igualmente: el nodo está para cambiarlo.'),
        starter: () => G.flux({ cfg: 8, fg: false }), solution: () => G.flux(),
        goals: [goal(L('Saw what CFG 8 does to Flux', 'Has vist què fa CFG 8 a Flux', 'Has visto qué hace CFG 8 a Flux'), (g, c) => ran(c, h => flux(h) && h.burned)), goal(L('FluxGuidance on the positive prompt', 'FluxGuidance al prompt positiu', 'FluxGuidance en el prompt positivo'), g => N(g, 'KSampler').some(s => condPath(g, s.id, 'positive').some(n => n.type === 'FluxGuidance'))), goal(L('CFG 1 with guidance 2.5–4.5', 'CFG 1 amb guidance 2.5–4.5', 'CFG 1 con guidance 2.5–4.5'), (g, c) => ran(c, h => flux(h) && h.cfg <= 1.05 && h.guidance >= 2.5 && h.guidance <= 4.5 && !h.burned))],
      },
      {
        title: L('The guidance range', 'El rang de la guidance', 'El rango de la guidance'),
        task: L('Run with guidance 1.5, then 7, then back to 3–4. Compare.', 'Executa amb guidance 1.5, després 7, i torna a 3–4. Compara.', 'Ejecuta con guidance 1.5, luego 7, y vuelve a 3–4. Compara.'),
        concept: L('Guidance decides how hard the prompt is pushed. <b>Low (1.5–2.5)</b>: softer, more natural light, less contrast, sometimes washed out; many people use 2–2.5 for photographic looks. <b>3–4</b>: the balanced default. <b>High (5+)</b>: saturated, contrasted, “plastic” skin and too-perfect pictures. It does not need to be high for the prompt to be followed: Flux follows the prompt anyway.', 'La guidance decideix amb quina força s’empeny el prompt. <b>Baixa (1.5–2.5)</b>: més suau, llum més natural, menys contrast, de vegades apagat; molta gent fa servir 2–2.5 per a un aspecte fotogràfic. <b>3–4</b>: l’equilibri per defecte. <b>Alta (5+)</b>: saturat, contrastat, pell “de plàstic” i imatges massa perfectes. No cal que sigui alta perquè se segueixi el prompt: Flux el segueix igualment.', 'La guidance decide con qué fuerza se empuja el prompt. <b>Baja (1.5–2.5)</b>: más suave, luz más natural, menos contraste, a veces apagado; mucha gente usa 2–2.5 para un aspecto fotográfico. <b>3–4</b>: el equilibrio por defecto. <b>Alta (5+)</b>: saturado, contrastado, piel “de plástico” e imágenes demasiado perfectas. No hace falta que sea alta para que se siga el prompt: Flux lo sigue igualmente.'),
        how: [L('FluxGuidance › <b>1.5</b>, run.', 'FluxGuidance › <b>1.5</b>, executa.', 'FluxGuidance › <b>1.5</b>, ejecuta.'), L('<b>7</b>, run.', '<b>7</b>, executa.', '<b>7</b>, ejecuta.'), L('Back to <b>3.5</b>.', 'Torna a <b>3.5</b>.', 'Vuelve a <b>3.5</b>.')],
        note: L('Keep the seed fixed to compare: with control_after_generate on fixed you only change one thing at a time.', 'Mantén el seed fix per comparar: amb control_after_generate a fixed només canvies una cosa cada vegada.', 'Mantén el seed fijo para comparar: con control_after_generate en fixed solo cambias una cosa cada vez.'),
        starter: () => G.flux(), solution: () => G.flux({ guidance: 3.5 }),
        goals: [goal(L('Low guidance (≤ 2): soft and washed', 'Guidance baixa (≤ 2): tou i apagat', 'Guidance baja (≤ 2): blando y apagado'), (g, c) => ran(c, h => flux(h) && h.guidance !== null && h.guidance <= 2 && h.cfg <= 1.05)), goal(L('High guidance (≥ 6): plastic', 'Guidance alta (≥ 6): de plàstic', 'Guidance alta (≥ 6): de plástico'), (g, c) => ran(c, h => flux(h) && h.guidance >= 6 && h.cfg <= 1.05)), goal(L('Back in the balanced range', 'Tornes a l’equilibri', 'Vuelves al equilibrio'), (g, c) => ran(c, h => flux(h) && h.guidance >= 2.5 && h.guidance <= 4.5 && h.cfg <= 1.05 && !h.burned && !h.soft))],
      },
      {
        title: L('No negative prompt', 'Sense prompt negatiu', 'Sin prompt negativo'),
        task: L('Try to remove the trees with “forest” in the negative prompt. Then remove them the Flux way: describe a scene without trees.', 'Intenta treure els arbres amb “forest” al prompt negatiu. Després treu-los a la manera de Flux: descriu una escena sense arbres.', 'Intenta quitar los árboles con “forest” en el prompt negativo. Luego quítalos a la manera de Flux: describe una escena sin árboles.'),
        concept: L('The negative prompt only works through CFG: it is the “without” half of the double pass. At <b>CFG 1</b> there is no second pass, so the negative prompt is <b>ignored</b>, whatever you write. To avoid something, <b>describe what you want instead</b> (“an open snowy field” rather than “no trees”), and never write “no X” in the positive: the word X is still there. Some people raise CFG to 1.5–2 to get a bit of negative back, at twice the time.', 'El prompt negatiu només funciona a través del CFG: és la meitat “sense” de la doble passada. Amb <b>CFG 1</b> no hi ha segona passada, i el prompt negatiu s’<b>ignora</b>, escriguis el que escriguis. Per evitar una cosa, <b>descriu el que vols en lloc d’això</b> (“an open snowy field” en lloc de “no trees”), i no escriguis mai “no X” al positiu: la paraula X hi continua sent. Hi ha qui puja el CFG a 1.5–2 per recuperar una mica de negatiu, al doble de temps.', 'El prompt negativo solo funciona a través del CFG: es la mitad “sin” de la doble pasada. Con <b>CFG 1</b> no hay segunda pasada, y el prompt negativo se <b>ignora</b>, escribas lo que escribas. Para evitar algo, <b>describe lo que quieres en su lugar</b> (“an open snowy field” en lugar de “no trees”), y no escribas nunca “no X” en el positivo: la palabra X sigue ahí. Hay quien sube el CFG a 1.5–2 para recuperar algo de negativo, al doble de tiempo.'),
        how: [L('Run: the negative prompt says “forest”, and the forest is still there.', 'Executa: el prompt negatiu diu “forest”, i el bosc hi continua sent.', 'Ejecuta: el prompt negativo dice “forest”, y el bosque sigue ahí.'), L('Positive: <b>a cat sitting in the snow, open field, detailed</b>. Empty the negative.', 'Positiu: <b>a cat sitting in the snow, open field, detailed</b>. Buida el negatiu.', 'Positivo: <b>a cat sitting in the snow, open field, detailed</b>. Vacía el negativo.'), L('Run.', 'Executa.', 'Ejecuta.')],
        note: L('Schnell and Kontext work the same way: CFG 1, no negative.', 'Schnell i Kontext funcionen igual: CFG 1, sense negatiu.', 'Schnell y Kontext funcionan igual: CFG 1, sin negativo.'),
        starter: () => G.flux({ text: 'a cat sitting in a forest, detailed', neg: 'forest, trees' }), solution: () => G.flux({ text: 'a cat sitting in the snow, open field, detailed' }),
        goals: [goal(L('The negative was ignored at CFG 1', 'S’ha ignorat el negatiu amb CFG 1', 'Se ha ignorado el negativo con CFG 1'), (g, c) => ran(c, h => flux(h) && h.negIgnored && h.setting === 'forest')), goal(L('A scene without trees, written in the positive', 'Una escena sense arbres, escrita al positiu', 'Una escena sin árboles, escrita en el positivo'), (g, c) => ran(c, h => flux(h) && h.setting && h.setting !== 'forest' && !/\bno\b/.test(h.posText)))],
      },
      {
        title: L('Dev and schnell', 'Dev i schnell', 'Dev y schnell'),
        task: L('Run dev with only 4 steps. Then load flux1-schnell and run it at 4 steps. Then dev at 20 or more.', 'Executa dev amb només 4 steps. Després carrega flux1-schnell i executa’l a 4 steps. Després dev a 20 o més.', 'Ejecuta dev con solo 4 steps. Luego carga flux1-schnell y ejecútalo a 4 steps. Luego dev a 20 o más.'),
        concept: L('<b>Flux schnell</b> (“fast”) is distilled further to finish in <b>1–4 steps</b>: great for exploring ideas quickly. It does not use guidance and its licence (Apache 2.0) allows commercial use. <b>Flux dev</b> needs <b>20–30 steps</b> and gives more detail and better prompt following; its licence is non-commercial for the weights. Dev at 4 steps is an unfinished picture.', '<b>Flux schnell</b> (“ràpid”) està destil·lat encara més per acabar en <b>1–4 steps</b>: ideal per explorar idees de pressa. No fa servir guidance i la seva llicència (Apache 2.0) permet l’ús comercial. <b>Flux dev</b> necessita <b>20–30 steps</b> i dona més detall i segueix millor el prompt; la llicència dels pesos és no comercial. Dev a 4 steps és una imatge a mig fer.', '<b>Flux schnell</b> (“rápido”) está destilado aún más para acabar en <b>1–4 steps</b>: ideal para explorar ideas deprisa. No usa guidance y su licencia (Apache 2.0) permite el uso comercial. <b>Flux dev</b> necesita <b>20–30 steps</b> y da más detalle y sigue mejor el prompt; la licencia de los pesos es no comercial. Dev a 4 steps es una imagen a medio hacer.'),
        how: [L('KSampler › steps <b>4</b>, run (dev).', 'KSampler › steps <b>4</b>, executa (dev).', 'KSampler › steps <b>4</b>, ejecuta (dev).'), L('Load Diffusion Model › <b>flux1-schnell</b>, run.', 'Load Diffusion Model › <b>flux1-schnell</b>, executa.', 'Load Diffusion Model › <b>flux1-schnell</b>, ejecuta.'), L('Back to flux1-dev, steps <b>20</b>.', 'Torna a flux1-dev, steps <b>20</b>.', 'Vuelve a flux1-dev, steps <b>20</b>.')],
        note: L('Licences change: check the model card of each file before using it in paid work.', 'Les llicències canvien: mira la fitxa de cada model abans de fer-lo servir en feina pagada.', 'Las licencias cambian: mira la ficha de cada modelo antes de usarlo en trabajo pagado.'),
        starter: () => G.flux({ steps: 4 }), solution: () => G.flux({ steps: 20 }),
        goals: [goal(L('Dev at ≤ 8 steps: unfinished', 'Dev a ≤ 8 steps: a mig fer', 'Dev a ≤ 8 steps: a medio hacer'), (g, c) => ran(c, h => flux(h) && h.variant === 'dev' && !h.finished)), goal(L('Schnell at 4 steps: finished', 'Schnell a 4 steps: acabat', 'Schnell a 4 steps: acabado'), (g, c) => ran(c, h => flux(h) && h.variant === 'schnell' && h.steps <= 4 && h.finished)), goal(L('Dev at 20+ steps', 'Dev a 20+ steps', 'Dev a 20+ steps'), (g, c) => ran(c, h => flux(h) && h.variant === 'dev' && h.steps >= 20 && h.finished))],
      },
    ],
  },
  {
    id: 'prompting', name: L('Prompting', 'Prompts', 'Prompts'), sub: L('Sentences · text · size', 'Frases · text · mida', 'Frases · texto · tamaño'),
    steps: [
      {
        title: L('Sentences, not tags', 'Frases, no etiquetes', 'Frases, no etiquetas'),
        task: L('Run “a red cat next to a blue robot” with SD 1.5, then with Flux, and compare the colours.', 'Executa “a red cat next to a blue robot” amb SD 1.5, després amb Flux, i compara els colors.', 'Ejecuta “a red cat next to a blue robot” con SD 1.5, luego con Flux, y compara los colores.'),
        concept: L('CLIP, the text encoder of SD 1.5 and SDXL, reads a prompt almost as a <b>bag of words</b>: “red”, “cat”, “blue”, “robot”. Which colour goes on which object gets mixed up (<b>attribute bleeding</b>). <b>T5</b>, Flux’s encoder, is a language model: it understands sentences, relations (“next to”, “on top of”) and who has which colour. So with Flux you write like you would describe the picture to a person, and the long tag lists (“masterpiece, best quality, 8k”) are useless.', 'CLIP, el text encoder de SD 1.5 i SDXL, llegeix un prompt gairebé com una <b>bossa de paraules</b>: “red”, “cat”, “blue”, “robot”. Quin color va a quin objecte es barreja (<b>attribute bleeding</b>). <b>T5</b>, l’encoder de Flux, és un model de llenguatge: entén frases, relacions (“next to”, “on top of”) i qui té quin color. Per això amb Flux escrius com si descrivissis la imatge a una persona, i les llistes llargues d’etiquetes (“masterpiece, best quality, 8k”) no serveixen.', 'CLIP, el text encoder de SD 1.5 y SDXL, lee un prompt casi como una <b>bolsa de palabras</b>: “red”, “cat”, “blue”, “robot”. Qué color va con qué objeto se mezcla (<b>attribute bleeding</b>). <b>T5</b>, el encoder de Flux, es un modelo de lenguaje: entiende frases, relaciones (“next to”, “on top of”) y quién tiene qué color. Por eso con Flux escribes como si describieras la imagen a una persona, y las listas largas de etiquetas (“masterpiece, best quality, 8k”) no sirven.'),
        how: [L('Run the SD 1.5 graph as it is.', 'Executa el graf de SD 1.5 tal com està.', 'Ejecuta el grafo de SD 1.5 tal cual.'), L('Templates › <b>Flux dev</b> (or build it), and use the same prompt.', 'Templates › <b>Flux dev</b> (o construeix-lo), i fes servir el mateix prompt.', 'Templates › <b>Flux dev</b> (o constrúyelo), y usa el mismo prompt.'), L('Try “a red cat sitting on top of a blue robot”.', 'Prova “a red cat sitting on top of a blue robot”.', 'Prueba “a red cat sitting on top of a blue robot”.')],
        note: L('Weights like (word:1.3) do much less with T5: say it with words (“a very large…”, “mostly…”).', 'Els pesos com (paraula:1.3) fan molt menys amb T5: digues-ho amb paraules (“a very large…”, “mostly…”).', 'Los pesos como (palabra:1.3) hacen mucho menos con T5: dilo con palabras (“a very large…”, “mostly…”).'),
        starter: () => G.sd('a red cat next to a blue robot, in a landscape'), solution: () => G.flux({ text: 'a red cat next to a blue robot, in a landscape' }),
        goals: [goal(L('SD 1.5 mixed the colours', 'SD 1.5 ha barrejat els colors', 'SD 1.5 ha mezclado los colores'), (g, c) => ran(c, h => !flux(h) && h.pairs >= 2 && !h.bound)), goal(L('Flux put each colour on its object', 'Flux ha posat cada color al seu objecte', 'Flux ha puesto cada color en su objeto'), (g, c) => ran(c, h => flux(h) && h.pairs >= 2 && h.bound))],
      },
      {
        title: L('Text in the picture', 'Text a la imatge', 'Texto en la imagen'),
        task: L('Write a sign with a word on it: a wooden sign that says "OPEN". Compare SD 1.5 and Flux.', 'Escriu un cartell amb una paraula: a wooden sign that says "OPEN". Compara SD 1.5 i Flux.', 'Escribe un cartel con una palabra: a wooden sign that says "OPEN". Compara SD 1.5 y Flux.'),
        concept: L('Text was the classic weakness of image models: SD 1.5 draws letter-like shapes, SDXL gets some letters right. Flux spells short texts correctly. The trick is to put the exact text <b>in quotes</b> and say where it is (“a sign that says…”, “a t-shirt with the word…”). Short texts work best; long sentences start to fail.', 'El text era el punt feble clàssic dels models d’imatge: SD 1.5 dibuixa formes que semblen lletres, SDXL n’encerta algunes. Flux escriu correctament els textos curts. El truc és posar el text exacte <b>entre cometes</b> i dir on és (“a sign that says…”, “a t-shirt with the word…”). Els textos curts funcionen millor; les frases llargues comencen a fallar.', 'El texto era el punto débil clásico de los modelos de imagen: SD 1.5 dibuja formas que parecen letras, SDXL acierta algunas. Flux escribe correctamente los textos cortos. El truco es poner el texto exacto <b>entre comillas</b> y decir dónde está (“a sign that says…”, “a t-shirt with the word…”). Los textos cortos funcionan mejor; las frases largas empiezan a fallar.'),
        how: [L('Flux prompt: <b>a cat next to a wooden sign that says "OPEN", landscape</b>. Run.', 'Prompt de Flux: <b>a cat next to a wooden sign that says "OPEN", landscape</b>. Executa.', 'Prompt de Flux: <b>a cat next to a wooden sign that says "OPEN", landscape</b>. Ejecuta.'), L('Try a long text (more than 22 letters) and see where it breaks.', 'Prova un text llarg (més de 22 lletres) i mira on es trenca.', 'Prueba un texto largo (más de 22 letras) y mira dónde se rompe.'), L('Optional: the same prompt with SD 1.5.', 'Opcional: el mateix prompt amb SD 1.5.', 'Opcional: el mismo prompt con SD 1.5.')],
        note: L('For a logo or exact typography, generate the scene and add the text later in a design program.', 'Per a un logotip o una tipografia exacta, genera l’escena i afegeix el text després en un programa de disseny.', 'Para un logotipo o una tipografía exacta, genera la escena y añade el texto después en un programa de diseño.'),
        starter: () => G.flux(), solution: () => G.flux({ text: 'a cat next to a wooden sign that says "OPEN", landscape' }),
        goals: [goal(L('Flux wrote the text right', 'Flux ha escrit bé el text', 'Flux ha escrito bien el texto'), (g, c) => ran(c, h => flux(h) && h.quoted && h.textOk)), goal(L('Found the limit with a long text', 'Has trobat el límit amb un text llarg', 'Has encontrado el límite con un texto largo'), (g, c) => ran(c, h => flux(h) && h.quoted && h.quoted.length > 22), true), goal(L('Compared with SD 1.5', 'Comparat amb SD 1.5', 'Comparado con SD 1.5'), (g, c) => ran(c, h => !flux(h) && h.quoted && !h.textOk), true)],
      },
      {
        title: L('Size and shape', 'Mida i forma', 'Tamaño y forma'),
        task: L('Generate a 16:9 picture (1344 × 768 or 1920 × 1088). Then try 2048 × 2048 and look for repeats.', 'Genera una imatge 16:9 (1344 × 768 o 1920 × 1088). Després prova 2048 × 2048 i busca repeticions.', 'Genera una imagen 16:9 (1344 × 768 o 1920 × 1088). Luego prueba 2048 × 2048 y busca repeticiones.'),
        concept: L('SD 1.5 lives at 512 and SDXL at about 1 megapixel with a few fixed shapes. Flux is happier with any shape between about <b>0.5 and 2 megapixels</b>, in steps of <b>16</b> pixels: 1344 × 768 for 16:9, 1920 × 1088 for Full HD. Above 2 MP the composition starts to repeat, like SD above its size: go bigger with the upscale methods of the previous lab.', 'SD 1.5 viu a 512 i SDXL a prop d’1 megapíxel amb unes quantes formes fixes. Flux treballa bé amb qualsevol forma entre uns <b>0.5 i 2 megapíxels</b>, de <b>16</b> en 16 píxels: 1344 × 768 per a 16:9, 1920 × 1088 per a Full HD. Per sobre de 2 MP la composició es comença a repetir, com SD per sobre de la seva mida: per anar més enllà, fes servir els mètodes d’upscale del lab anterior.', 'SD 1.5 vive a 512 y SDXL cerca de 1 megapíxel con unas pocas formas fijas. Flux trabaja bien con cualquier forma entre unos <b>0.5 y 2 megapíxeles</b>, de <b>16</b> en 16 píxeles: 1344 × 768 para 16:9, 1920 × 1088 para Full HD. Por encima de 2 MP la composición se empieza a repetir, como SD por encima de su tamaño: para ir más allá, usa los métodos de upscale del lab anterior.'),
        how: [L('EmptySD3LatentImage › <b>1344 × 768</b>. Run.', 'EmptySD3LatentImage › <b>1344 × 768</b>. Executa.', 'EmptySD3LatentImage › <b>1344 × 768</b>. Ejecuta.'), L('<b>2048 × 2048</b> (4 MP), run: count the cats.', '<b>2048 × 2048</b> (4 MP), executa: compta els gats.', '<b>2048 × 2048</b> (4 MP), ejecuta: cuenta los gatos.')],
        note: L('If you add ModelSamplingFlux, give it the same width and height as the latent.', 'Si afegeixes ModelSamplingFlux, dona-li la mateixa amplada i alçada que el latent.', 'Si añades ModelSamplingFlux, dale el mismo ancho y alto que el latente.'),
        starter: () => G.flux(), solution: () => G.flux({ w: 1344, h: 768 }),
        goals: [goal(L('A wide picture (16:9) under 2 MP', 'Una imatge apaïsada (16:9) de menys de 2 MP', 'Una imagen apaisada (16:9) de menos de 2 MP'), (g, c) => ran(c, h => flux(h) && h.w / h.h >= 1.6 && h.area <= 2.2e6 && h.w % 16 === 0 && h.h % 16 === 0)), goal(L('Tried 4 MP', 'Has provat 4 MP', 'Has probado 4 MP'), (g, c) => ran(c, h => flux(h) && h.area > 3e6), true)],
      },
    ],
  },
  {
    id: 'tools', name: L('Flux tools', 'Eines de Flux', 'Herramientas de Flux'), sub: L('Fill · Kontext · LoRA', 'Fill · Kontext · LoRA', 'Fill · Kontext · LoRA'),
    steps: [
      {
        title: L('Flux Fill', 'Flux Fill', 'Flux Fill'),
        task: L('Inpaint the cat with flux1-dev, then switch to flux1-fill-dev, and then raise FluxGuidance to 30.', 'Fes l’inpaint del gat amb flux1-dev, després canvia a flux1-fill-dev i puja FluxGuidance a 30.', 'Haz el inpaint del gato con flux1-dev, luego cambia a flux1-fill-dev y sube FluxGuidance a 30.'),
        concept: L('<b>Flux Fill</b> is Flux’s inpainting model, the equivalent of an inpainting checkpoint: the same graph you learned (InpaintModelConditioning, a mask, denoise 1) with this model. Two things to remember: it needs a very high guidance, <b>about 30</b> (with 3.5 the filled area comes out weak), and it also does outpainting with Pad Image for Outpainting.', '<b>Flux Fill</b> és el model d’inpainting de Flux, l’equivalent d’un checkpoint d’inpainting: el mateix graf que ja coneixes (InpaintModelConditioning, una màscara, denoise 1) amb aquest model. Dues coses a recordar: necessita una guidance molt alta, <b>uns 30</b> (amb 3.5 la zona omplerta surt fluixa), i també fa outpainting amb Pad Image for Outpainting.', '<b>Flux Fill</b> es el modelo de inpainting de Flux, el equivalente de un checkpoint de inpainting: el mismo grafo que ya conoces (InpaintModelConditioning, una máscara, denoise 1) con este modelo. Dos cosas a recordar: necesita una guidance muy alta, <b>unos 30</b> (con 3.5 la zona rellenada sale floja), y también hace outpainting con Pad Image for Outpainting.'),
        how: [L('Run with flux1-dev: the border shows.', 'Executa amb flux1-dev: es veu la vora.', 'Ejecuta con flux1-dev: se ve el borde.'), L('Load Diffusion Model › <b>flux1-fill-dev</b>, run: guidance 3.5 is too low.', 'Load Diffusion Model › <b>flux1-fill-dev</b>, executa: guidance 3.5 és massa baixa.', 'Load Diffusion Model › <b>flux1-fill-dev</b>, ejecuta: guidance 3.5 es demasiado baja.'), L('FluxGuidance › <b>30</b>. Run.', 'FluxGuidance › <b>30</b>. Executa.', 'FluxGuidance › <b>30</b>. Ejecuta.')],
        note: L('Differential Diffusion and the composite over the original work exactly as in the Inpainting Lab.', 'Differential Diffusion i la composició sobre l’original funcionen exactament com a l’Inpainting Lab.', 'Differential Diffusion y la composición sobre el original funcionan exactamente como en el Inpainting Lab.'),
        starter: () => G.fill('flux1-dev.safetensors', 3.5), solution: () => G.fill(),
        goals: [goal(L('Tried a normal model', 'Has provat un model normal', 'Has probado un modelo normal'), (g, c) => ran(c, h => flux(h) && h.inpaint && h.variant === 'dev'), true), goal(L('flux1-fill-dev in the graph', 'flux1-fill-dev al graf', 'flux1-fill-dev en el grafo'), g => N(g, 'UNETLoader').some(n => n.widgets.unet_name === 'flux1-fill-dev.safetensors')), goal(L('Filled with guidance ≥ 20', 'Omplert amb guidance ≥ 20', 'Rellenado con guidance ≥ 20'), (g, c) => ran(c, h => h.fill && h.guidance >= 20))],
      },
      {
        title: L('Kontext: edit with words', 'Kontext: edita amb paraules', 'Kontext: edita con palabras'),
        task: L('Run this Kontext graph: it ignores the photo. Add a ReferenceLatent with the encoded photo, and edit it with an instruction.', 'Executa aquest graf de Kontext: ignora la foto. Afegeix un ReferenceLatent amb la foto codificada, i edita-la amb una instrucció.', 'Ejecuta este grafo de Kontext: ignora la foto. Añade un ReferenceLatent con la foto codificada, y edítala con una instrucción.'),
        concept: L('<b>Flux Kontext</b> is an <b>editing</b> model: you give it a picture and an instruction (“make the cat black”, “turn it into night”, “remove the cat”) and it changes only that, keeping the rest and the identity. The picture enters through <b>ReferenceLatent</b>: the photo is scaled (FluxKontextImageScale), encoded with the VAE and attached to the conditioning. Without it, Kontext is just a text-to-image model. Write instructions, not descriptions, and say what to keep.', '<b>Flux Kontext</b> és un model d’<b>edició</b>: li dones una imatge i una instrucció (“make the cat black”, “turn it into night”, “remove the cat”) i canvia només això, conservant la resta i la identitat. La imatge entra per <b>ReferenceLatent</b>: la foto s’escala (FluxKontextImageScale), es codifica amb el VAE i s’afegeix al conditioning. Sense això, Kontext és només un model de text a imatge. Escriu instruccions, no descripcions, i digues què cal conservar.', '<b>Flux Kontext</b> es un modelo de <b>edición</b>: le das una imagen y una instrucción (“make the cat black”, “turn it into night”, “remove the cat”) y cambia solo eso, conservando el resto y la identidad. La imagen entra por <b>ReferenceLatent</b>: la foto se escala (FluxKontextImageScale), se codifica con el VAE y se añade al conditioning. Sin eso, Kontext es solo un modelo de texto a imagen. Escribe instrucciones, no descripciones, y di qué hay que conservar.'),
        how: [L('Run: a random picture, not your photo.', 'Executa: una imatge qualsevol, no la teva foto.', 'Ejecuta: una imagen cualquiera, no tu foto.'), L('Add <b>ReferenceLatent</b>: conditioning from the positive CLIP Text Encode, latent from VAE Encode; its output → FluxGuidance (2.5).', 'Afegeix <b>ReferenceLatent</b>: conditioning del CLIP Text Encode positiu, latent de VAE Encode; la seva sortida → FluxGuidance (2.5).', 'Añade <b>ReferenceLatent</b>: conditioning del CLIP Text Encode positivo, latent de VAE Encode; su salida → FluxGuidance (2.5).'), L('Run. Then try another instruction: “make it snowy”, “remove the cat”, “watercolor style”.', 'Executa. Després prova una altra instrucció: “make it snowy”, “remove the cat”, “watercolor style”.', 'Ejecuta. Luego prueba otra instrucción: “make it snowy”, “remove the cat”, “watercolor style”.')],
        note: L('Chain edits by feeding the result back as the next input, one change at a time: big multi-change instructions are less reliable.', 'Encadena edicions tornant a fer servir el resultat com a entrada, un canvi cada vegada: les instruccions amb molts canvis són menys fiables.', 'Encadena ediciones volviendo a usar el resultado como entrada, un cambio cada vez: las instrucciones con muchos cambios son menos fiables.'),
        starter: () => G.kontext(false), solution: () => G.kontext(true),
        goals: [goal(L('Kontext without a reference', 'Kontext sense referència', 'Kontext sin referencia'), (g, c) => ran(c, h => h.kontext && !h.kontext.reference), true), goal(L('ReferenceLatent on the positive path', 'ReferenceLatent al camí positiu', 'ReferenceLatent en el camino positivo'), g => N(g, 'KSampler').some(s => condPath(g, s.id, 'positive').some(n => n.type === 'ReferenceLatent' && from(g, n.id, 'latent')))), goal(L('An edit that keeps the cat', 'Una edició que conserva el gat', 'Una edición que conserva el gato'), (g, c) => ran(c, h => h.kontext?.reference && (h.kontext.col || h.kontext.setting || h.kontext.style) && !h.kontext.remove)), goal(L('A second, different instruction', 'Una segona instrucció diferent', 'Una segunda instrucción diferente'), (g, c) => new Set(runs(c).filter(h => h.kontext?.reference).map(h => h.posText)).size >= 2, true)],
      },
      {
        title: L('LoRAs for Flux', 'LoRAs per a Flux', 'LoRAs para Flux'),
        task: L('This LoraLoaderModelOnly has an SD 1.5 LoRA: run it and read the log. Then pick a Flux LoRA and use its trigger word.', 'Aquest LoraLoaderModelOnly té una LoRA de SD 1.5: executa i llegeix el log. Després tria una LoRA de Flux i fes servir la seva paraula clau.', 'Este LoraLoaderModelOnly tiene una LoRA de SD 1.5: ejecuta y lee el log. Luego elige una LoRA de Flux y usa su palabra clave.'),
        concept: L('LoRAs belong to a family: an SD 1.5 or SDXL LoRA on Flux loads nothing (“lora key not loaded”) and changes nothing, without an error. Most Flux LoRAs are trained on the diffusion model only, so they use <b>LoraLoaderModelOnly</b> between the loader and the KSampler. Typical strengths are 0.7–1, and many have a trigger word you must write in the prompt.', 'Les LoRAs pertanyen a una família: una LoRA de SD 1.5 o SDXL a Flux no carrega res (“lora key not loaded”) i no canvia res, sense cap error. La majoria de LoRAs de Flux s’entrenen només sobre el model de difusió, i fan servir <b>LoraLoaderModelOnly</b> entre el loader i el KSampler. Les forces habituals són 0.7–1, i moltes tenen una paraula clau que has d’escriure al prompt.', 'Las LoRAs pertenecen a una familia: una LoRA de SD 1.5 o SDXL en Flux no carga nada (“lora key not loaded”) y no cambia nada, sin ningún error. La mayoría de LoRAs de Flux se entrenan solo sobre el modelo de difusión, y usan <b>LoraLoaderModelOnly</b> entre el loader y el KSampler. Las fuerzas habituales son 0.7–1, y muchas tienen una palabra clave que debes escribir en el prompt.'),
        how: [L('Run and open the log (bottom panel): “lora key not loaded”.', 'Executa i mira el log (panell inferior): “lora key not loaded”.', 'Ejecuta y mira el log (panel inferior): “lora key not loaded”.'), L('lora_name › <b>flux_watercolor_v2</b>.', 'lora_name › <b>flux_watercolor_v2</b>.', 'lora_name › <b>flux_watercolor_v2</b>.'), L('Add the trigger <b>wtrcolor</b> to the prompt. Run.', 'Afegeix la paraula clau <b>wtrcolor</b> al prompt. Executa.', 'Añade la palabra clave <b>wtrcolor</b> al prompt. Ejecuta.')],
        note: L('Look for the base model on the LoRA’s page: “Flux.1 D”, “SDXL 1.0”, “SD 1.5”. It decides where it works.', 'Mira el model base a la pàgina de la LoRA: “Flux.1 D”, “SDXL 1.0”, “SD 1.5”. Això decideix on funciona.', 'Mira el modelo base en la página de la LoRA: “Flux.1 D”, “SDXL 1.0”, “SD 1.5”. Eso decide dónde funciona.'),
        starter: () => G.lora(), solution: () => G.lora('flux_watercolor_v2.safetensors', `wtrcolor, ${PROMPT}`),
        goals: [goal(L('Saw an SD LoRA do nothing on Flux', 'Has vist una LoRA de SD que no fa res a Flux', 'Has visto una LoRA de SD que no hace nada en Flux'), (g, c) => ran(c, h => flux(h) && h.loraOff)), goal(L('A Flux LoRA with its trigger word', 'Una LoRA de Flux amb la seva paraula clau', 'Una LoRA de Flux con su palabra clave'), (g, c) => ran(c, h => flux(h) && h.fluxLora))],
      },
    ],
  },
];

export const TEMPLATES = [
  { id: 'flux-dev', name: L('Flux dev', 'Flux dev', 'Flux dev'), make: () => G.flux() },
  { id: 'flux-schnell', name: L('Flux schnell', 'Flux schnell', 'Flux schnell'), make: () => G.flux({ unet: 'flux1-schnell.safetensors', steps: 4, fg: false }) },
  { id: 'flux-gguf', name: L('Flux dev (GGUF Q8)', 'Flux dev (GGUF Q8)', 'Flux dev (GGUF Q8)'), make: () => G.flux({ gguf: 'flux1-dev-Q8_0.gguf' }) },
  { id: 'flux-fill', name: L('Flux Fill', 'Flux Fill', 'Flux Fill'), make: () => G.fill() },
  { id: 'flux-kontext', name: L('Flux Kontext', 'Flux Kontext', 'Flux Kontext'), make: () => G.kontext(true) },
  { id: 'sd15', name: L('SD 1.5 (default)', 'SD 1.5 (per defecte)', 'SD 1.5 (por defecto)'), make: () => G.sd() },
];
export { G as GRAPHS };
