// Carrot Revolt Labs · LoRA Lab · stages, steps and live checklists.
// It runs on the ComfyUI Lab interface (../comfyui/app.js) and adds its own nodes and simulator (./nodes.js).
import { defaultGraph, makeNode, makeLink, connect } from '../comfyui/engine.js';
import { historyExtra as hx, TRIGGER } from './nodes.js';
export const L = (en, ca, es) => ({ en, ca, es });

export const META = { key: 'carrot-revolt-comfy-lora:', title: 'LoRA Lab', label: 'GENERATIVE IMAGE / COMFYUI · 07' };
export const historyExtra = hx;

/* ── Graph helpers ── */
const N = (g, type) => g.nodes.filter(n => n.type === type && n.mode === 0);
const from = (g, id, input) => { const l = g.links.find(x => x.to === id && x.input === input); return l ? g.nodes.find(n => n.id === l.from) : null; };
const goal = (text, test, optional = false) => ({ text, test, optional });
const add = (g, ...nodes) => { g.nodes.push(...nodes); return g; };
const wire = (g, list) => { for (const l of list) connect(g, makeLink(...l)); return g; };
const set = (g, id, k, v) => { g.nodes.find(n => n.id === id).widgets[k] = v; return g; };
const move = (g, id, x, y) => { const n = g.nodes.find(n => n.id === id); n.x = x; n.y = y; return g; };
const runs = c => c.history.filter(h => h.pip);
const ran = (c, f) => runs(c).some(f);
const PIP = `${TRIGGER} sitting in a landscape, detailed`, SNOW = `${TRIGGER} standing in the snow, detailed`;

/* ── Starters and solutions ── */
const G = {
  base: (text = PIP) => { const g = defaultGraph(); set(g, 'pos', 'text', text); set(g, 'neg', 'text', 'blurry, text, watermark'); set(g, 'sampler', 'control_after_generate', 'fixed'); return g; },
  use: ({ name = 'pip_character.safetensors', sm = 1, sc = 1, text = PIP } = {}) => {
    const g = G.base(text); add(g, makeNode('LoraLoader', 30, 200, { lora_name: name, strength_model: sm, strength_clip: sc }, 'lora')); move(g, 'ckpt', 26, 520);
    return wire(g, [['ckpt', 0, 'lora', 'model'], ['ckpt', 1, 'lora', 'clip'], ['lora', 0, 'sampler', 'model'], ['lora', 1, 'pos', 'clip'], ['lora', 1, 'neg', 'clip']]);
  },
  stack: (s1 = .85, s2 = .6) => {
    const g = G.use({ sm: s1, sc: s1, text: `${TRIGGER}, wtrcolor, sitting in a landscape, detailed` }); add(g, makeNode('LoraLoader', 30, -120, { lora_name: 'watercolor_sd15.safetensors', strength_model: s2, strength_clip: s2 }, 'lora2'));
    return wire(g, [['lora', 0, 'lora2', 'model'], ['lora', 1, 'lora2', 'clip'], ['lora2', 0, 'sampler', 'model'], ['lora2', 1, 'pos', 'clip'], ['lora2', 1, 'neg', 'clip']]);
  },
  dataset: (folder = 'pip_6_same_background') => { const g = { nodes: [makeNode('CheckpointLoaderSimple', 26, 260, {}, 'ckpt'), makeNode('LoadImageTextSetFromFolderNode', 420, 200, { folder }, 'ds'), makeNode('PreviewImage', 820, 200, {}, 'pv')], links: [], groups: [] }; return wire(g, [['ckpt', 1, 'ds', 'clip'], ['ds', 0, 'pv', 'images']]); },
  trainStart: (folder = 'pip_6_same_background') => { const g = G.base(SNOW); add(g, makeNode('LoadImageTextSetFromFolderNode', 26, 760, { folder }, 'ds'), makeNode('VAEEncode', 440, 820, {}, 'enc')); return wire(g, [['ckpt', 1, 'ds', 'clip'], ['ds', 0, 'enc', 'pixels'], ['ckpt', 2, 'enc', 'vae']]); },
  train: ({ folder = 'pip_20_varied', steps = 600, lr = .0001, rank = 16 } = {}) => {
    const g = G.trainStart(folder);
    add(g, makeNode('TrainLoraNode', 420, -420, { steps, learning_rate: lr, rank }, 'train'), makeNode('LoraModelLoader', 863, 20, {}, 'lml'), makeNode('SaveLoRANode', 1240, -320, {}, 'slora'), makeNode('LossGraphNode', 1240, 520, {}, 'loss'));
    move(g, 'sampler', 863, 186);
    return wire(g, [['ckpt', 0, 'train', 'model'], ['enc', 0, 'train', 'latents'], ['ds', 1, 'train', 'positive'], ['ckpt', 0, 'lml', 'model'], ['train', 1, 'lml', 'lora'], ['lml', 0, 'sampler', 'model'], ['train', 1, 'slora', 'lora'], ['train', 2, 'loss', 'loss']]);
  },
};

export const UI = {
  headline: L('Teach the model <span>something new.</span>', 'Ensenya al model <span>una cosa nova.</span>', 'Enseña al modelo <span>algo nuevo.</span>'),
  lead: L('A LoRA is a small add-on that teaches a model a character, a style or an object. Learn to use them well (model and clip strength, trigger words, stacking) and to make your own: a dataset with variety, captions that say the right things, training settings that stop before the model learns too much, and how to test and pick the best file. With Pip, our own mascot.', 'Una LoRA és un complement petit que ensenya a un model un personatge, un estil o un objecte. Aprèn a fer-les servir bé (força del model i del clip, paraules clau, apilar-les) i a fer-ne de teves: un dataset variat, captions que diguin el que cal, uns paràmetres d’entrenament que s’aturin abans que el model aprengui massa, i com provar i triar el millor fitxer. Amb la Pip, la nostra mascota.', 'Una LoRA es un complemento pequeño que enseña a un modelo un personaje, un estilo o un objeto. Aprende a usarlas bien (fuerza del modelo y del clip, palabras clave, apilarlas) y a hacer las tuyas: un dataset variado, captions que digan lo que toca, unos parámetros de entrenamiento que paren antes de que el modelo aprenda demasiado, y cómo probar y elegir el mejor archivo. Con Pip, nuestra mascota.'),
  loraVsCn: L('Training at a glance', 'L’entrenament d’un cop d’ull', 'El entrenamiento de un vistazo'),
  type_LORA_MODEL: L('a LoRA being trained (in memory)', 'una LoRA que s’està entrenant (a la memòria)', 'una LoRA que se está entrenando (en memoria)'),
  type_LOSS_MAP: L('the loss of each training step', 'la pèrdua de cada step d’entrenament', 'la pérdida de cada step de entrenamiento'),
};
const T3 = (h, rows, foot) => `<table class="c-cmp"><tr><th></th><th>${h[0]}</th><th>${h[1]}</th></tr>${rows.map(r => `<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</table><p>${foot}</p>`;
UI.loraVsCnBody = L(
  T3(['Too little', 'Too much'], [['<b>Steps / epochs</b>', 'weak likeness', 'frozen poses, baked background'], ['<b>Learning rate</b>', 'learns slowly', 'fried colours, unstable'], ['<b>Rank</b>', 'not enough detail', 'big file, overfits sooner'], ['<b>Images</b>', '< 10: copies them', '15–40 varied is plenty']], 'Caption what should stay changeable; let the trigger word carry what defines the subject.'),
  T3(['Massa poc', 'Massa'], [['<b>Steps / epochs</b>', 'semblança fluixa', 'postures congelades, fons enganxat'], ['<b>Learning rate</b>', 'aprèn a poc a poc', 'colors cremats, inestable'], ['<b>Rank</b>', 'poc detall', 'fitxer gran, sobreentrena abans'], ['<b>Imatges</b>', '< 10: les copia', '15–40 variades n’hi ha prou']], 'Escriu als captions el que ha de poder canviar; deixa que la paraula clau porti el que defineix el subjecte.'),
  T3(['Massa poc', 'Demasiado'], [['<b>Steps / epochs</b>', 'parecido flojo', 'posturas congeladas, fondo pegado'], ['<b>Learning rate</b>', 'aprende despacio', 'colores quemados, inestable'], ['<b>Rank</b>', 'poco detalle', 'archivo grande, sobreentrena antes'], ['<b>Imágenes</b>', '< 10: las copia', '15–40 variadas bastan']], 'Escribe en los captions lo que debe poder cambiar; deja que la palabra clave lleve lo que define al sujeto.'));

export const DOCS = {
  LoadImageTextSetFromFolderNode: { short: L('Loads a training set: pictures and their captions.', 'Carrega un conjunt d’entrenament: imatges i els seus captions.', 'Carga un conjunto de entrenamiento: imágenes y sus captions.'), long: L('A folder in input/ with pictures and a .txt caption next to each one (same name). The captions are encoded with the CLIP you connect.', 'Una carpeta a input/ amb imatges i un .txt de caption al costat de cadascuna (mateix nom). Els captions es codifiquen amb el CLIP que hi connectis.', 'Una carpeta en input/ con imágenes y un .txt de caption junto a cada una (mismo nombre). Los captions se codifican con el CLIP que conectes.') },
  TrainLoraNode: { short: L('Trains a LoRA on a dataset.', 'Entrena una LoRA amb un dataset.', 'Entrena una LoRA con un dataset.'), long: L('Part of ComfyUI’s training nodes (still young; dedicated trainers like kohya_ss, AI Toolkit or OneTrainer expose the same settings). steps × batch is how many pictures it sees; learning_rate how big each correction is; rank how much the LoRA can store.', 'Forma part dels nodes d’entrenament de ComfyUI (encara joves; entrenadors dedicats com kohya_ss, AI Toolkit o OneTrainer tenen els mateixos paràmetres). steps × batch és quantes imatges veu; learning_rate com de gran és cada correcció; rank quant pot guardar la LoRA.', 'Forma parte de los nodos de entrenamiento de ComfyUI (aún jóvenes; entrenadores dedicados como kohya_ss, AI Toolkit u OneTrainer tienen los mismos parámetros). steps × batch es cuántas imágenes ve; learning_rate lo grande que es cada corrección; rank cuánto puede guardar la LoRA.'), widgets: { steps: L('training steps', 'steps d’entrenament', 'steps de entrenamiento'), learning_rate: L('1e-4 is a safe start for SD 1.5', '1e-4 és un inici segur per a SD 1.5', '1e-4 es un inicio seguro para SD 1.5'), rank: L('8–32 for a character', '8–32 per a un personatge', '8–32 para un personaje') } },
  LoraModelLoader: { short: L('Applies a LoRA that is in memory.', 'Aplica una LoRA que és a la memòria.', 'Aplica una LoRA que está en memoria.'), long: L('To test the LoRA right after training, without saving and reloading it.', 'Per provar la LoRA just després d’entrenar-la, sense desar-la i tornar-la a carregar.', 'Para probar la LoRA justo después de entrenarla, sin guardarla y volver a cargarla.') },
  SaveLoRANode: { short: L('Saves the trained LoRA to models/loras.', 'Desa la LoRA entrenada a models/loras.', 'Guarda la LoRA entrenada en models/loras.'), long: L('After saving, it appears in Load LoRA like any other.', 'Un cop desada, apareix a Load LoRA com qualsevol altra.', 'Una vez guardada, aparece en Load LoRA como cualquier otra.') },
  LossGraphNode: { short: L('Draws the loss curve of the training.', 'Dibuixa la corba de pèrdua de l’entrenament.', 'Dibuja la curva de pérdida del entrenamiento.'), long: L('The loss should go down and flatten. It does not tell you when the LoRA is good: only test pictures do.', 'La pèrdua ha de baixar i aplanar-se. No et diu quan la LoRA és bona: només ho diuen les imatges de prova.', 'La pérdida debe bajar y aplanarse. No te dice cuándo la LoRA es buena: solo lo dicen las imágenes de prueba.') },
};

export const STAGES = [
  {
    id: 'use', name: L('Using LoRAs', 'Fer servir LoRAs', 'Usar LoRAs'), sub: L('Model · clip · trigger · stack', 'Model · clip · paraula clau · apilar', 'Modelo · clip · palabra clave · apilar'),
    steps: [
      {
        title: L('Model, clip and the trigger word', 'Model, clip i la paraula clau', 'Modelo, clip y la palabra clave'),
        task: L('Run Pip as it is. Then set strength_clip to 0. Then put clip back to 1 and remove “pip robot” from the prompt.', 'Executa la Pip tal com està. Després posa strength_clip a 0. Després torna el clip a 1 i treu “pip robot” del prompt.', 'Ejecuta a Pip tal cual. Luego pon strength_clip a 0. Luego vuelve el clip a 1 y quita “pip robot” del prompt.'),
        concept: L('A LoRA changes two models. <b>strength_model</b> changes the diffusion model (what Pip looks like); <b>strength_clip</b> changes the text encoder (how it understands the words that call Pip). A character LoRA is trained with a <b>trigger word</b> (here “pip robot”): without it, or without the clip part, the model does not really know you are asking for Pip. The trigger words are on the LoRA’s page (and in its metadata).', 'Una LoRA canvia dos models. <b>strength_model</b> canvia el model de difusió (com és la Pip); <b>strength_clip</b> canvia el text encoder (com entén les paraules que criden la Pip). Una LoRA de personatge s’entrena amb una <b>paraula clau</b> (aquí “pip robot”): sense ella, o sense la part del clip, el model no sap del tot que demanes la Pip. Les paraules clau són a la pàgina de la LoRA (i a les seves metadades).', 'Una LoRA cambia dos modelos. <b>strength_model</b> cambia el modelo de difusión (cómo es Pip); <b>strength_clip</b> cambia el text encoder (cómo entiende las palabras que llaman a Pip). Una LoRA de personaje se entrena con una <b>palabra clave</b> (aquí “pip robot”): sin ella, o sin la parte del clip, el modelo no sabe del todo que pides a Pip. Las palabras clave están en la página de la LoRA (y en sus metadatos).'),
        how: [L('Run: Pip, orange, green scarf, star on the antenna.', 'Executa: la Pip, taronja, bufanda verda, estrella a l’antena.', 'Ejecuta: Pip, naranja, bufanda verde, estrella en la antena.'), L('Load LoRA › strength_clip <b>0</b>. Run.', 'Load LoRA › strength_clip <b>0</b>. Executa.', 'Load LoRA › strength_clip <b>0</b>. Ejecuta.'), L('strength_clip <b>1</b>, and remove “pip robot” from the prompt. Run.', 'strength_clip <b>1</b>, i treu “pip robot” del prompt. Executa.', 'strength_clip <b>1</b>, y quita “pip robot” del prompt. Ejecuta.')],
        note: L('Pip is our own invented character: a LoRA trained on 20 pictures of her.', 'La Pip és un personatge inventat nostre: una LoRA entrenada amb 20 imatges seves.', 'Pip es un personaje inventado nuestro: una LoRA entrenada con 20 imágenes suyas.'),
        starter: () => G.use(), solution: () => G.use({ text: 'a robot sitting in a landscape, detailed' }),
        goals: [goal(L('Pip with both strengths at 1', 'La Pip amb les dues forces a 1', 'Pip con las dos fuerzas a 1'), (g, c) => ran(c, h => h.pip.likeness >= .75 && h.pip.trigger)), goal(L('Clip at 0: weaker', 'Clip a 0: més fluixa', 'Clip a 0: más floja'), (g, c) => ran(c, h => h.loraFiles.some(l => l.concept && l.strength > 0 && l.clip === 0) && h.pip.likeness < .75)), goal(L('Without the trigger word: barely Pip', 'Sense la paraula clau: amb prou feines la Pip', 'Sin la palabra clave: apenas Pip'), (g, c) => ran(c, h => h.loraFiles.some(l => l.concept) && !h.pip.trigger && h.pip.likeness < .5))],
      },
      {
        title: L('Not too strong', 'No massa fort', 'No demasiado fuerte'),
        task: L('This LoRA is at 1.6. Run it, then find a strength between 0.6 and 1.2 that keeps Pip without frying the picture.', 'Aquesta LoRA és a 1.6. Executa-la i després troba una força entre 0.6 i 1.2 que mantingui la Pip sense cremar la imatge.', 'Esta LoRA está a 1.6. Ejecútala y luego encuentra una fuerza entre 0.6 y 1.2 que mantenga a Pip sin quemar la imagen.'),
        concept: L('A LoRA is a correction to the model’s weights; its strength multiplies it. Around 1 it does what it was trained for. Above ~1.3 the correction is exaggerated: saturated, burned colours and broken shapes (“fried”). Below 0.5 it fades. Negative strengths push the other way (useful with “slider” LoRAs). If a LoRA needs 1.5 to show, it is usually undertrained or does not match your model.', 'Una LoRA és una correcció dels pesos del model; la força la multiplica. Al voltant d’1 fa el que va aprendre. Per sobre d’~1.3 la correcció s’exagera: colors saturats, cremats i formes trencades (“fregida”). Per sota de 0.5 s’esvaeix. Les forces negatives empenyen cap a l’altra banda (útil amb LoRAs “slider”). Si una LoRA necessita 1.5 per notar-se, normalment està poc entrenada o no coincideix amb el teu model.', 'Una LoRA es una corrección de los pesos del modelo; la fuerza la multiplica. Alrededor de 1 hace lo que aprendió. Por encima de ~1.3 la corrección se exagera: colores saturados, quemados y formas rotas (“frita”). Por debajo de 0.5 se desvanece. Las fuerzas negativas empujan hacia el otro lado (útil con LoRAs “slider”). Si una LoRA necesita 1.5 para notarse, normalmente está poco entrenada o no coincide con tu modelo.'),
        how: [L('Run at 1.6.', 'Executa a 1.6.', 'Ejecuta a 1.6.'), L('strength_model and strength_clip to <b>0.9</b>. Run.', 'strength_model i strength_clip a <b>0.9</b>. Executa.', 'strength_model y strength_clip a <b>0.9</b>. Ejecuta.')],
        note: L('Drag on a number widget to change it fast; click it to type the value.', 'Arrossega sobre un widget numèric per canviar-lo de pressa; clica-hi per escriure el valor.', 'Arrastra sobre un widget numérico para cambiarlo deprisa; haz clic para escribir el valor.'),
        starter: () => G.use({ sm: 1.6, sc: 1.6 }), solution: () => G.use({ sm: .9, sc: .9 }),
        goals: [goal(L('Saw a LoRA fry the picture', 'Has vist una LoRA cremar la imatge', 'Has visto una LoRA quemar la imagen'), (g, c) => ran(c, h => h.pip.fried)), goal(L('Pip at a sane strength', 'La Pip amb una força raonable', 'Pip con una fuerza razonable'), (g, c) => ran(c, h => !h.pip.fried && h.pip.likeness >= .65 && h.loraFiles.some(l => l.concept && l.strength >= .6 && l.strength <= 1.2)))],
      },
      {
        title: L('Two LoRAs together', 'Dues LoRAs juntes', 'Dos LoRAs juntas'),
        task: L('Pip and a watercolour LoRA, both at 1: run it. Then lower them (about 0.85 and 0.6) so both show and nothing burns.', 'La Pip i una LoRA d’aquarel·la, totes dues a 1: executa. Després abaixa-les (uns 0.85 i 0.6) perquè es notin totes dues i res no es cremi.', 'Pip y una LoRA de acuarela, las dos a 1: ejecuta. Luego bájalas (unos 0.85 y 0.6) para que se noten las dos y nada se queme.'),
        concept: L('LoRAs chain: each Load LoRA takes MODEL and CLIP from the previous one. Their corrections <b>add up</b>, so two at full strength often fry, and they can fight (a style LoRA repainting the character). Give the one that matters most the higher value, lower the other, and keep the total under about 1.8. Each needs its own trigger word in the prompt.', 'Les LoRAs s’encadenen: cada Load LoRA agafa el MODEL i el CLIP de l’anterior. Les seves correccions <b>se sumen</b>, i dues a força màxima sovint cremen, i es poden barallar (una LoRA d’estil repintant el personatge). Dona el valor més alt a la que més importa, abaixa l’altra, i mantén el total per sota d’uns 1.8. Cadascuna necessita la seva paraula clau al prompt.', 'Las LoRAs se encadenan: cada Load LoRA toma el MODEL y el CLIP de la anterior. Sus correcciones <b>se suman</b>, y dos a fuerza máxima a menudo queman, y se pueden pelear (una LoRA de estilo repintando el personaje). Da el valor más alto a la que más importa, baja la otra, y mantén el total por debajo de unos 1.8. Cada una necesita su palabra clave en el prompt.'),
        how: [L('Run as it is (1 + 1).', 'Executa tal com està (1 + 1).', 'Ejecuta tal cual (1 + 1).'), L('Pip <b>0.85</b>, watercolour <b>0.6</b> (model and clip).', 'Pip <b>0.85</b>, aquarel·la <b>0.6</b> (model i clip).', 'Pip <b>0.85</b>, acuarela <b>0.6</b> (modelo y clip).'), L('Run.', 'Executa.', 'Ejecuta.')],
        note: L('Many LoRAs at low strength (0.3–0.5) are a common way to mix looks.', 'Moltes LoRAs a força baixa (0.3–0.5) són una manera habitual de barrejar estils.', 'Muchas LoRAs a fuerza baja (0.3–0.5) son una forma habitual de mezclar estilos.'),
        starter: () => G.stack(1, 1), solution: () => G.stack(),
        goals: [goal(L('Two at full strength: too much', 'Dues a tota força: massa', 'Dos a toda fuerza: demasiado'), (g, c) => ran(c, h => h.loraFiles.length >= 2 && h.pip.fried)), goal(L('Pip and watercolour, balanced', 'La Pip i l’aquarel·la, equilibrades', 'Pip y acuarela, equilibradas'), (g, c) => ran(c, h => h.loraFiles.length >= 2 && !h.pip.fried && h.pip.likeness >= .6 && h.styleOn.includes('watercolor')))],
      },
    ],
  },
  {
    id: 'dataset', name: L('Dataset', 'Dataset', 'Dataset'), sub: L('Variety · captions', 'Varietat · captions', 'Variedad · captions'),
    steps: [
      {
        title: L('Variety beats quantity', 'Varietat millor que quantitat', 'Variedad mejor que cantidad'),
        task: L('Preview the 6-picture dataset, then the 20 varied pictures.', 'Previsualitza el dataset de 6 imatges, i després el de 20 imatges variades.', 'Previsualiza el dataset de 6 imágenes, y luego el de 20 imágenes variadas.'),
        concept: L('A LoRA learns <b>everything that repeats</b> in its pictures. Six pictures of Pip, all centred on the same grey background, teach “Pip” and also “grey background, centred, this size”: the LoRA will paint that background everywhere. 15–40 pictures with different backgrounds, poses, distances and light teach only what is always the same: Pip. Use clean, sharp pictures; a few good ones are better than many bad ones.', 'Una LoRA aprèn <b>tot el que es repeteix</b> a les seves imatges. Sis imatges de la Pip, totes centrades sobre el mateix fons gris, ensenyen “Pip” i també “fons gris, centrada, aquesta mida”: la LoRA pintarà aquell fons a tot arreu. 15–40 imatges amb fons, postures, distàncies i llums diferents ensenyen només el que sempre és igual: la Pip. Fes servir imatges netes i nítides; poques de bones és millor que moltes de dolentes.', 'Una LoRA aprende <b>todo lo que se repite</b> en sus imágenes. Seis imágenes de Pip, todas centradas sobre el mismo fondo gris, enseñan “Pip” y también “fondo gris, centrada, este tamaño”: la LoRA pintará ese fondo en todas partes. 15–40 imágenes con fondos, posturas, distancias y luces diferentes enseñan solo lo que siempre es igual: Pip. Usa imágenes limpias y nítidas; pocas buenas es mejor que muchas malas.'),
        how: [L('Run: the 6 pictures in Preview Image.', 'Executa: les 6 imatges a Preview Image.', 'Ejecuta: las 6 imágenes en Preview Image.'), L('folder › <b>pip_20_varied</b>. Run.', 'folder › <b>pip_20_varied</b>. Executa.', 'folder › <b>pip_20_varied</b>. Ejecuta.'), L('Compare: what is the same in all of them?', 'Compara: què és igual a totes?', 'Compara: ¿qué es igual en todas?')],
        note: L('A training folder holds the pictures and, next to each, a .txt with its caption (same file name).', 'Una carpeta d’entrenament conté les imatges i, al costat de cadascuna, un .txt amb el seu caption (mateix nom de fitxer).', 'Una carpeta de entrenamiento contiene las imágenes y, junto a cada una, un .txt con su caption (mismo nombre de archivo).'),
        starter: () => G.dataset(), solution: () => G.dataset('pip_20_varied'),
        goals: [goal(L('Previewed the small dataset', 'Has previsualitzat el dataset petit', 'Has previsualizado el dataset pequeño'), (g, c) => c.history.some(h => h.kind === 'dataset' && h.graph?.nodes.some(n => n.widgets?.folder === 'pip_6_same_background'))), goal(L('Previewed a varied one with 20 pictures', 'Has previsualitzat un de variat amb 20 imatges', 'Has previsualizado uno variado con 20 imágenes'), (g, c) => c.history.some(h => h.kind === 'dataset' && h.graph?.nodes.some(n => n.widgets?.folder?.startsWith('pip_20'))))],
      },
      {
        title: L('Captions', 'Captions', 'Captions'),
        task: L('Look at the three captioned versions of the 20 pictures and choose the one with the trigger word plus only what changes.', 'Mira les tres versions amb captions de les 20 imatges i tria la que té la paraula clau i només el que canvia.', 'Mira las tres versiones con captions de las 20 imágenes y elige la que tiene la palabra clave y solo lo que cambia.'),
        concept: L('Captions tell the trainer what each picture contains. The rule: <b>describe what should stay changeable</b> (pose, background, light, clothes you want to change) and <b>let the trigger word carry what defines the subject</b> (orange body, scarf, star). If you describe the scarf in every caption, the LoRA learns that “scarf” is a separate word and Pip comes out without it unless you ask. With no captions at all, everything gets glued to the LoRA, and Pip appears even when you do not ask for her.', 'Els captions diuen a l’entrenador què conté cada imatge. La regla: <b>descriu el que ha de poder canviar</b> (postura, fons, llum, roba que vulguis canviar) i <b>deixa que la paraula clau porti el que defineix el subjecte</b> (cos taronja, bufanda, estrella). Si descrius la bufanda a tots els captions, la LoRA aprèn que “scarf” és una paraula a part i la Pip surt sense bufanda si no la demanes. Sense cap caption, tot queda enganxat a la LoRA, i la Pip apareix fins i tot quan no la demanes.', 'Los captions dicen al entrenador qué contiene cada imagen. La regla: <b>describe lo que debe poder cambiar</b> (postura, fondo, luz, ropa que quieras cambiar) y <b>deja que la palabra clave lleve lo que define al sujeto</b> (cuerpo naranja, bufanda, estrella). Si describes la bufanda en todos los captions, la LoRA aprende que “scarf” es una palabra aparte y Pip sale sin bufanda si no la pides. Sin ningún caption, todo queda pegado a la LoRA, y Pip aparece incluso cuando no la pides.'),
        how: [L('Run the version without captions.', 'Executa la versió sense captions.', 'Ejecuta la versión sin captions.'), L('Try <b>pip_20_varied_captions_everything</b>, then <b>pip_20_varied</b>.', 'Prova <b>pip_20_varied_captions_everything</b> i després <b>pip_20_varied</b>.', 'Prueba <b>pip_20_varied_captions_everything</b> y luego <b>pip_20_varied</b>.'), L('Read the captions under each picture.', 'Llegeix els captions de sota cada imatge.', 'Lee los captions bajo cada imagen.')],
        note: L('Vision models (Florence-2, JoyCaption…) write captions automatically; always read and fix them.', 'Els models de visió (Florence-2, JoyCaption…) escriuen captions automàticament; llegeix-los i corregeix-los sempre.', 'Los modelos de visión (Florence-2, JoyCaption…) escriben captions automáticamente; léelos y corrígelos siempre.'),
        starter: () => G.dataset('pip_20_varied_no_captions'), solution: () => G.dataset('pip_20_varied'),
        goals: [goal(L('Looked at the “describe everything” captions', 'Has mirat els captions que “ho descriuen tot”', 'Has mirado los captions que “lo describen todo”'), (g, c) => c.history.some(h => h.kind === 'dataset' && h.graph?.nodes.some(n => n.widgets?.folder === 'pip_20_varied_captions_everything')), true), goal(L('Chose trigger + what changes', 'Has triat paraula clau + el que canvia', 'Has elegido palabra clave + lo que cambia'), (g, c) => c.history.some(h => h.kind === 'dataset' && h.graph?.nodes.some(n => n.widgets?.folder === 'pip_20_varied')))],
      },
    ],
  },
  {
    id: 'train', name: L('Training', 'Entrenament', 'Entrenamiento'), sub: L('Train · steps · rate and rank', 'Entrena · steps · rate i rank', 'Entrena · steps · rate y rank'),
    steps: [
      {
        title: L('Train a LoRA', 'Entrena una LoRA', 'Entrena una LoRA'),
        task: L('Build the training graph: dataset (pip_20_varied) → VAE Encode → Train LoRA (600 steps, 0.0001, rank 16) → Load LoRA Model → KSampler, plus Save LoRA Weights and Plot Loss Graph.', 'Construeix el graf d’entrenament: dataset (pip_20_varied) → VAE Encode → Train LoRA (600 steps, 0.0001, rank 16) → Load LoRA Model → KSampler, més Save LoRA Weights i Plot Loss Graph.', 'Construye el grafo de entrenamiento: dataset (pip_20_varied) → VAE Encode → Train LoRA (600 steps, 0.0001, rank 16) → Load LoRA Model → KSampler, más Save LoRA Weights y Plot Loss Graph.'),
        concept: L('Training shows the model your pictures (as latents) with their captions (as conditioning) many times, and adjusts a small set of extra weights, the LoRA, until it reproduces them. In ComfyUI the training nodes take the model, the <b>latents</b> of the dataset and its <b>conditioning</b>; the LoRA comes out in memory, ready to test with Load LoRA Model and to save. The loss curve should go down and level off.', 'Entrenar és ensenyar al model les teves imatges (com a latents) amb els seus captions (com a conditioning) moltes vegades, i ajustar un petit conjunt de pesos extra, la LoRA, fins que les reprodueix. A ComfyUI els nodes d’entrenament reben el model, els <b>latents</b> del dataset i el seu <b>conditioning</b>; la LoRA en surt a la memòria, a punt per provar-la amb Load LoRA Model i per desar-la. La corba de pèrdua ha de baixar i estabilitzar-se.', 'Entrenar es enseñar al modelo tus imágenes (como latentes) con sus captions (como conditioning) muchas veces, y ajustar un pequeño conjunto de pesos extra, la LoRA, hasta que las reproduce. En ComfyUI los nodos de entrenamiento reciben el modelo, los <b>latentes</b> del dataset y su <b>conditioning</b>; la LoRA sale en memoria, lista para probarla con Load LoRA Model y para guardarla. La curva de pérdida debe bajar y estabilizarse.'),
        how: [L('Dataset folder › <b>pip_20_varied</b>. Add <b>Train LoRA</b>: model ← Load Checkpoint, latents ← VAE Encode, positive ← the dataset’s CONDITIONING. steps 600, learning_rate 0.0001, rank 16.', 'Carpeta del dataset › <b>pip_20_varied</b>. Afegeix <b>Train LoRA</b>: model ← Load Checkpoint, latents ← VAE Encode, positive ← el CONDITIONING del dataset. steps 600, learning_rate 0.0001, rank 16.', 'Carpeta del dataset › <b>pip_20_varied</b>. Añade <b>Train LoRA</b>: model ← Load Checkpoint, latents ← VAE Encode, positive ← el CONDITIONING del dataset. steps 600, learning_rate 0.0001, rank 16.'), L('<b>Load LoRA Model</b> (model from the checkpoint, lora from Train LoRA) → model of the KSampler.', '<b>Load LoRA Model</b> (model del checkpoint, lora de Train LoRA) → model del KSampler.', '<b>Load LoRA Model</b> (modelo del checkpoint, lora de Train LoRA) → model del KSampler.'), L('Add <b>Save LoRA Weights</b> and <b>Plot Loss Graph</b>. Run.', 'Afegeix <b>Save LoRA Weights</b> i <b>Plot Loss Graph</b>. Executa.', 'Añade <b>Save LoRA Weights</b> y <b>Plot Loss Graph</b>. Ejecuta.')],
        note: L('Real training takes minutes to hours and a lot of VRAM; here it is instant. The settings and their effects are the real ones.', 'Un entrenament real dura de minuts a hores i fa servir molta VRAM; aquí és instantani. Els paràmetres i els seus efectes són els reals.', 'Un entrenamiento real dura de minutos a horas y usa mucha VRAM; aquí es instantáneo. Los parámetros y sus efectos son los reales.'),
        starter: () => G.trainStart(), solution: () => G.train(),
        goals: [goal(L('Train LoRA gets latents and conditioning', 'Train LoRA rep latents i conditioning', 'Train LoRA recibe latentes y conditioning'), g => N(g, 'TrainLoraNode').some(n => from(g, n.id, 'latents')?.type === 'VAEEncode' && from(g, n.id, 'positive')?.type === 'LoadImageTextSetFromFolderNode')), goal(L('The KSampler tests the trained LoRA', 'El KSampler prova la LoRA entrenada', 'El KSampler prueba la LoRA entrenada'), g => N(g, 'KSampler').some(s => from(g, s.id, 'model')?.type === 'LoraModelLoader')), goal(L('A good Pip from your LoRA', 'Una bona Pip de la teva LoRA', 'Una buena Pip de tu LoRA'), (g, c) => ran(c, h => h.trained && h.pip.likeness >= .7 && !h.pip.fried && !h.pip.baked))],
      },
      {
        title: L('Too little, too much', 'Massa poc, massa', 'Demasiado poco, demasiado'),
        task: L('Train with 100 steps, then with 3000, and look at both. Then find the window again.', 'Entrena amb 100 steps, després amb 3000, i mira-ho. Després torna a trobar la finestra.', 'Entrena con 100 steps, luego con 3000, y míralo. Luego vuelve a encontrar la ventana.'),
        concept: L('<b>Underfit</b>: too few steps and the LoRA has barely learned: a generic robot with a hint of orange. <b>Overfit</b>: too many and it learns the pictures, not the idea: the same pose, the same size, the backgrounds of the dataset, burned colours, and the prompt stops working. The good LoRA is in between, and it is usually earlier than you think. That is why trainers save a file every few hundred steps.', '<b>Infraentrenada</b>: massa pocs steps i la LoRA amb prou feines ha après: un robot genèric amb un toc de taronja. <b>Sobreentrenada</b>: massa i aprèn les imatges, no la idea: la mateixa postura, la mateixa mida, els fons del dataset, colors cremats, i el prompt deixa de funcionar. La LoRA bona és al mig, i normalment abans del que et penses. Per això els entrenadors desen un fitxer cada uns quants centenars de steps.', '<b>Infraentrenada</b>: demasiado pocos steps y la LoRA apenas ha aprendido: un robot genérico con un toque de naranja. <b>Sobreentrenada</b>: demasiados y aprende las imágenes, no la idea: la misma postura, el mismo tamaño, los fondos del dataset, colores quemados, y el prompt deja de funcionar. La LoRA buena está en medio, y normalmente antes de lo que crees. Por eso los entrenadores guardan un archivo cada pocos cientos de steps.'),
        how: [L('Train LoRA › steps <b>100</b>. Run.', 'Train LoRA › steps <b>100</b>. Executa.', 'Train LoRA › steps <b>100</b>. Ejecuta.'), L('steps <b>3000</b>. Run.', 'steps <b>3000</b>. Executa.', 'steps <b>3000</b>. Ejecuta.'), L('Back to 500–1000.', 'Torna a 500–1000.', 'Vuelve a 500–1000.')],
        note: L('Rule of thumb for SD 1.5: about 30–50 views of each picture (steps × batch ÷ number of pictures).', 'Regla pràctica per a SD 1.5: unes 30–50 vegades cada imatge (steps × batch ÷ nombre d’imatges).', 'Regla práctica para SD 1.5: unas 30–50 veces cada imagen (steps × batch ÷ número de imágenes).'),
        starter: () => G.train(), solution: () => G.train({ steps: 800 }),
        goals: [goal(L('Underfit: barely Pip', 'Infraentrenada: amb prou feines la Pip', 'Infraentrenada: apenas Pip'), (g, c) => ran(c, h => h.trained && h.pip.likeness < .5)), goal(L('Overfit: frozen and baked', 'Sobreentrenada: congelada i enganxada', 'Sobreentrenada: congelada y pegada'), (g, c) => ran(c, h => h.trained && (h.pip.frozen || h.pip.baked))), goal(L('Back in the window', 'Tornes a la finestra', 'Vuelves a la ventana'), (g, c) => ran(c, h => h.trained && h.pip.likeness >= .7 && !h.pip.frozen && !h.pip.baked && !h.pip.fried))],
      },
      {
        title: L('Learning rate and rank', 'Learning rate i rank', 'Learning rate y rank'),
        task: L('Try a learning rate of 0.001 (ten times more). Then go back to 0.0001 and try rank 4 and rank 32.', 'Prova un learning rate de 0.001 (deu vegades més). Després torna a 0.0001 i prova rank 4 i rank 32.', 'Prueba un learning rate de 0.001 (diez veces más). Luego vuelve a 0.0001 y prueba rank 4 y rank 32.'),
        concept: L('<b>Learning rate</b> is the size of each correction: too high and training becomes unstable, colours burn and the LoRA overfits in a few steps; too low and it takes forever. 1e-4 is a safe start for SD 1.5 (other models and optimizers use other values). <b>Rank</b> is how much the LoRA can store: 4 may not hold all of Pip’s details, 16–32 is plenty for a character, 128 is a big file that memorises faster.', 'El <b>learning rate</b> és la mida de cada correcció: massa alt i l’entrenament es torna inestable, els colors es cremen i la LoRA sobreentrena en pocs steps; massa baix i no s’acaba mai. 1e-4 és un inici segur per a SD 1.5 (altres models i optimitzadors fan servir altres valors). El <b>rank</b> és quant pot guardar la LoRA: amb 4 potser no hi caben tots els detalls de la Pip, 16–32 n’hi ha prou per a un personatge, 128 és un fitxer gran que memoritza més de pressa.', 'El <b>learning rate</b> es el tamaño de cada corrección: demasiado alto y el entrenamiento se vuelve inestable, los colores se queman y la LoRA sobreentrena en pocos steps; demasiado bajo y no se acaba nunca. 1e-4 es un inicio seguro para SD 1.5 (otros modelos y optimizadores usan otros valores). El <b>rank</b> es cuánto puede guardar la LoRA: con 4 quizá no caben todos los detalles de Pip, 16–32 basta para un personaje, 128 es un archivo grande que memoriza más deprisa.'),
        how: [L('learning_rate <b>0.001</b>. Run.', 'learning_rate <b>0.001</b>. Executa.', 'learning_rate <b>0.001</b>. Ejecuta.'), L('Back to <b>0.0001</b>; rank <b>4</b>, run; rank <b>32</b>, run.', 'Torna a <b>0.0001</b>; rank <b>4</b>, executa; rank <b>32</b>, executa.', 'Vuelve a <b>0.0001</b>; rank <b>4</b>, ejecuta; rank <b>32</b>, ejecuta.'), L('Compare likeness and file size (Save LoRA Weights).', 'Compara la semblança i la mida del fitxer (Save LoRA Weights).', 'Compara el parecido y el tamaño del archivo (Save LoRA Weights).')],
        note: L('Change one setting at a time and keep notes: training is an experiment.', 'Canvia un paràmetre cada vegada i pren notes: entrenar és un experiment.', 'Cambia un parámetro cada vez y toma notas: entrenar es un experimento.'),
        starter: () => G.train(), solution: () => G.train({ rank: 32 }),
        goals: [goal(L('Learning rate too high: fried', 'Learning rate massa alt: cremada', 'Learning rate demasiado alto: quemada'), (g, c) => ran(c, h => h.trained && h.trained.lr >= .0008 && h.pip.fried)), goal(L('Rank 4: less detail', 'Rank 4: menys detall', 'Rank 4: menos detalle'), (g, c) => ran(c, h => h.trained && h.trained.rank <= 4 && h.pip.likeness < .85), true), goal(L('A good LoRA: safe rate, rank 8–32', 'Una bona LoRA: rate segur, rank 8–32', 'Una buena LoRA: rate seguro, rank 8–32'), (g, c) => ran(c, h => h.trained && h.trained.lr <= .0005 && h.trained.rank >= 8 && h.trained.rank <= 32 && h.pip.likeness >= .7 && !h.pip.fried && !h.pip.frozen))],
      },
    ],
  },
  {
    id: 'evaluate', name: L('Evaluate', 'Avaluar', 'Evaluar'), sub: L('Flexibility · pick the file', 'Flexibilitat · tria el fitxer', 'Flexibilidad · elige el archivo'),
    steps: [
      {
        title: L('Is it flexible?', 'És flexible?', '¿Es flexible?'),
        task: L('Test your LoRA in new situations: Pip in the snow, at night… and a picture of a cat without the trigger word.', 'Prova la teva LoRA en situacions noves: la Pip a la neu, de nit… i una imatge d’un gat sense la paraula clau.', 'Prueba tu LoRA en situaciones nuevas: Pip en la nieve, de noche… y una imagen de un gato sin la palabra clave.'),
        concept: L('A good LoRA does two things: it draws Pip whenever you call her, <b>in whatever scene the prompt describes</b>, and it <b>stays quiet</b> when you do not call her. Test both: prompts with places, light and styles that are not in the dataset, and a prompt without the trigger. If the backgrounds of the dataset come back, or Pip sneaks into every picture, the LoRA (or its captions) needs work.', 'Una bona LoRA fa dues coses: dibuixa la Pip sempre que la crides, <b>en l’escena que descrigui el prompt</b>, i <b>no apareix</b> quan no la crides. Prova les dues: prompts amb llocs, llums i estils que no són al dataset, i un prompt sense la paraula clau. Si tornen els fons del dataset, o la Pip es cola a totes les imatges, la LoRA (o els seus captions) s’ha de millorar.', 'Una buena LoRA hace dos cosas: dibuja a Pip siempre que la llamas, <b>en la escena que describa el prompt</b>, y <b>no aparece</b> cuando no la llamas. Prueba las dos: prompts con lugares, luces y estilos que no están en el dataset, y un prompt sin la palabra clave. Si vuelven los fondos del dataset, o Pip se cuela en todas las imágenes, la LoRA (o sus captions) hay que mejorarla.'),
        how: [L('Prompt: <b>pip robot standing in the snow</b>. Run.', 'Prompt: <b>pip robot standing in the snow</b>. Executa.', 'Prompt: <b>pip robot standing in the snow</b>. Ejecuta.'), L('<b>pip robot at night, stars</b>. Run.', '<b>pip robot at night, stars</b>. Executa.', '<b>pip robot at night, stars</b>. Ejecuta.'), L('<b>a cat sitting in a landscape</b> (no trigger). Run.', '<b>a cat sitting in a landscape</b> (sense paraula clau). Executa.', '<b>a cat sitting in a landscape</b> (sin palabra clave). Ejecuta.')],
        note: L('Train once with the “no captions” dataset and repeat the cat test: Pip appears anyway.', 'Entrena una vegada amb el dataset “sense captions” i repeteix la prova del gat: la Pip apareix igualment.', 'Entrena una vez con el dataset “sin captions” y repite la prueba del gato: Pip aparece igualmente.'),
        starter: () => G.train({ steps: 800 }), solution: () => { const g = G.train({ steps: 800 }); set(g, 'pos', 'text', 'pip robot at night, stars, detailed'); return g; },
        goals: [goal(L('Pip in two different scenes', 'La Pip en dues escenes diferents', 'Pip en dos escenas distintas'), (g, c) => new Set(runs(c).filter(h => h.trained && h.pip.likeness >= .7 && !h.pip.baked).map(h => h.setting)).size >= 2), goal(L('No trigger, no Pip', 'Sense paraula clau, sense Pip', 'Sin palabra clave, sin Pip'), (g, c) => ran(c, h => h.trained && !h.pip.trigger && !h.pip.shown && h.subject === 'cat'))],
      },
      {
        title: L('Pick the best file', 'Tria el millor fitxer', 'Elige el mejor archivo'),
        task: L('One training run saved pip_v1 at 250, 750, 1500 and 2500 steps. Load each with Load LoRA (same seed, a snowy prompt) and keep the best.', 'Un entrenament va desar pip_v1 a 250, 750, 1500 i 2500 steps. Carrega’ls amb Load LoRA (mateix seed, un prompt amb neu) i queda’t el millor.', 'Un entrenamiento guardó pip_v1 a 250, 750, 1500 y 2500 steps. Cárgalos con Load LoRA (mismo seed, un prompt con nieve) y quédate el mejor.'),
        concept: L('Trainers save a checkpoint every N steps because the last one is rarely the best. Compare them with the <b>same seed and prompt</b>, in a scene the dataset did not have: the early ones are weak, the late ones rigid. Pick the earliest one that looks right, and keep the trigger word, the base model and the recommended strength next to the file: that is what anyone (you, in six months) needs to use it.', 'Els entrenadors desen un checkpoint cada N steps perquè l’últim poques vegades és el millor. Compara’ls amb el <b>mateix seed i prompt</b>, en una escena que el dataset no tenia: els primers són fluixos, els últims rígids. Tria el primer que es vegi bé, i guarda la paraula clau, el model base i la força recomanada al costat del fitxer: és el que necessita qualsevol (tu, d’aquí sis mesos) per fer-lo servir.', 'Los entrenadores guardan un checkpoint cada N steps porque el último pocas veces es el mejor. Compáralos con el <b>mismo seed y prompt</b>, en una escena que el dataset no tenía: los primeros son flojos, los últimos rígidos. Elige el primero que se vea bien, y guarda la palabra clave, el modelo base y la fuerza recomendada junto al archivo: es lo que necesita cualquiera (tú, dentro de seis meses) para usarlo.'),
        how: [L('Load LoRA › <b>pip_v1-000250</b>. Run.', 'Load LoRA › <b>pip_v1-000250</b>. Executa.', 'Load LoRA › <b>pip_v1-000250</b>. Ejecuta.'), L('The same with 000750, 001500 and 002500.', 'El mateix amb 000750, 001500 i 002500.', 'Lo mismo con 000750, 001500 y 002500.'), L('Leave the best one loaded and run it.', 'Deixa carregat el millor i executa’l.', 'Deja cargado el mejor y ejecútalo.')],
        note: L('With control_after_generate on fixed every file gets the same starting noise: a fair comparison.', 'Amb control_after_generate a fixed cada fitxer rep el mateix soroll inicial: una comparació justa.', 'Con control_after_generate en fixed cada archivo recibe el mismo ruido inicial: una comparación justa.'),
        starter: () => G.use({ name: 'pip_v1-000250.safetensors', text: SNOW }), solution: () => G.use({ name: 'pip_v1-000750.safetensors', text: SNOW }),
        goals: [goal(L('Compared three or more files', 'Has comparat tres fitxers o més', 'Has comparado tres archivos o más'), (g, c) => new Set(runs(c).flatMap(h => h.loraFiles.filter(l => l.name?.startsWith('pip_v1')).map(l => l.name))).size >= 3), goal(L('The best: an early, flexible one', 'El millor: un dels primers, flexible', 'El mejor: uno de los primeros, flexible'), (g, c) => ran(c, h => h.loraFiles.some(l => ['pip_v1-000750.safetensors', 'pip_v1-001500.safetensors'].includes(l.name)) && h.pip.likeness >= .75 && !h.pip.frozen && !h.pip.baked && h.setting === 'snow'))],
      },
    ],
  },
];

export const TEMPLATES = [
  { id: 'use', name: L('Load LoRA (Pip)', 'Load LoRA (Pip)', 'Load LoRA (Pip)'), make: () => G.use() },
  { id: 'stack', name: L('Two LoRAs', 'Dues LoRAs', 'Dos LoRAs'), make: () => G.stack() },
  { id: 'train', name: L('Train a LoRA', 'Entrena una LoRA', 'Entrena una LoRA'), make: () => G.train({ steps: 800 }) },
];
export { G as GRAPHS };
