// Carrot Revolt Labs · ComfyUI Lab · stages, steps, explanations and live checklists.
import { defaultGraph, makeNode, makeLink, connect, validate, NODES } from './engine.js';
export const L = (en, ca, es) => ({ en, ca, es });

/* ── Graph helpers ── */
const N = (g, type) => g.nodes.filter(n => n.type === type && n.mode === 0);
const link = (g, from, out, to, input) => g.links.find(l => l.from === from && l.out === out && l.to === to && l.input === input);
const into = (g, id, input) => g.links.find(l => l.to === id && l.input === input);
const srcType = (g, id, input) => { const l = into(g, id, input); return l ? g.nodes.find(n => n.id === l.from)?.type : null; };
const sampler = g => N(g, 'KSampler')[0];
const runs = c => c.history;
const same = (a, b) => a.seed === b.seed;
const goal = (text, test, optional = false) => ({ text, test, optional });
const add = (g, ...nodes) => { g.nodes.push(...nodes); return g; };
const wire = (g, list) => { for (const l of list) connect(g, makeLink(...l)); return g; };
const set = (g, id, k, v) => { g.nodes.find(n => n.id === id).widgets[k] = v; return g; };
const fixed = g => set(g, 'sampler', 'control_after_generate', 'fixed');

/* ── Starters and solutions ── */
const G = {
  base: () => defaultGraph(),
  empty: () => defaultGraph({ links: false }),
  broken: () => { const g = defaultGraph(); g.links = g.links.filter(l => !(l.to === 'decode' && l.input === 'vae') && !(l.to === 'sampler' && l.input === 'negative')); return g; },
  preview: () => wire(add(defaultGraph(), makeNode('PreviewImage', 1460, 520, {}, 'preview')), [['decode', 0, 'preview', 'images']]),
  prompts: () => set(set(defaultGraph(), 'pos', 'text', 'a (red:1.2) robot in a snowy forest, watercolor, detailed'), 'neg', 'text', 'blurry, text, watermark, tree'),
  fixedSeed: () => fixed(G.prompts()),
  sdxl: () => set(set(set(fixed(G.prompts()), 'ckpt', 'ckpt_name', 'sd_xl_base_1.0.safetensors'), 'latent', 'width', 1024), 'latent', 'height', 1024),
  img2img: () => { const g = set(set(fixed(G.base()), 'pos', 'text', 'watercolor lighthouse at sunset, beach'), 'sampler', 'denoise', .55); add(g, makeNode('LoadImage', 40, 820, { image: 'lighthouse.png' }, 'img'), makeNode('VAEEncode', 470, 820, {}, 'enc')); g.nodes = g.nodes.filter(n => n.id !== 'latent'); g.links = g.links.filter(l => l.from !== 'latent'); return wire(g, [['img', 0, 'enc', 'pixels'], ['ckpt', 2, 'enc', 'vae'], ['enc', 0, 'sampler', 'latent_image']]); },
  lora: (name = 'pixel_art_sd15.safetensors', text = 'pixelart, a house in a forest, sunset') => {
    const g = set(fixed(G.base()), 'pos', 'text', text); add(g, makeNode('LoraLoader', 30, 200, { lora_name: name }, 'lora'));
    g.nodes.find(n => n.id === 'ckpt').y = 520; return wire(g, [['ckpt', 0, 'lora', 'model'], ['ckpt', 1, 'lora', 'clip'], ['lora', 0, 'sampler', 'model'], ['lora', 1, 'pos', 'clip'], ['lora', 1, 'neg', 'clip']]);
  },
  twoLoras: () => { const g = G.lora('pixel_art_sd15.safetensors', 'pixelart, wtrcolor, a cat on the beach'); add(g, makeNode('LoraLoader', 30, -120, { lora_name: 'watercolor_sd15.safetensors', strength_model: .7, strength_clip: .7 }, 'lora2')); return wire(g, [['lora', 0, 'lora2', 'model'], ['lora', 1, 'lora2', 'clip'], ['lora2', 0, 'sampler', 'model'], ['lora2', 1, 'pos', 'clip'], ['lora2', 1, 'neg', 'clip']]); },
  canny: () => wire(add(fixed(G.base()), makeNode('LoadImage', 40, 900, { image: 'pose_jump.png' }, 'img'), makeNode('Canny', 420, 900, {}, 'canny'), makeNode('PreviewImage', 800, 900, {}, 'cpreview')), [['img', 0, 'canny', 'image'], ['canny', 0, 'cpreview', 'images']]),
  control: (strength = 1) => {
    const g = set(G.canny(), 'pos', 'text', 'a blue robot in the desert, detailed');
    add(g, makeNode('ControlNetLoader', 420, 1180, {}, 'cnl'), makeNode('ControlNetApplyAdvanced', 860, 620, { strength }, 'apply'));
    g.nodes.find(n => n.id === 'sampler').x = 1240; g.nodes.find(n => n.id === 'decode').x = 1600; g.nodes.find(n => n.id === 'save').x = 1850;
    return wire(g, [['pos', 0, 'apply', 'positive'], ['neg', 0, 'apply', 'negative'], ['cnl', 0, 'apply', 'control_net'], ['canny', 0, 'apply', 'image'], ['apply', 0, 'sampler', 'positive'], ['apply', 1, 'sampler', 'negative']]);
  },
};
const fullDefault = g => validate(g).ok && ['CheckpointLoaderSimple', 'CLIPTextEncode', 'EmptyLatentImage', 'KSampler', 'VAEDecode'].every(t => N(g, t).length);
const loraFeeds = g => { const ls = N(g, 'LoraLoader'); const s = sampler(g); if (!ls.length || !s) return false; const m = into(g, s.id, 'model'); const clips = N(g, 'CLIPTextEncode').map(c => into(g, c.id, 'clip')); return m && ls.some(l => l.id === m.from) && clips.length >= 2 && clips.every(c => c && ls.some(l => l.id === c.from)); };

export const STAGES = [
  {
    id: 'interface', name: L('Interface', 'Interfície', 'Interfaz'), sub: L('Canvas · search · Run', 'Llenç · cerca · Run', 'Lienzo · búsqueda · Run'),
    steps: [
      {
        title: L('Move around the canvas', 'Mou-te pel llenç', 'Muévete por el lienzo'),
        task: L('This is ComfyUI’s default workflow. Pan the canvas, zoom in and out, and frame everything again.', 'Aquest és el workflow per defecte de ComfyUI. Desplaça el llenç, fes zoom i torna a enquadrar-ho tot.', 'Este es el workflow por defecto de ComfyUI. Desplaza el lienzo, haz zoom y vuelve a encuadrarlo todo.'),
        concept: L('A ComfyUI workflow is a graph: boxes (<b>nodes</b>) joined by wires (<b>links</b>). Each node does one job and passes its result to the right. The canvas is endless, so you will move a lot: learn the gestures first and everything else is faster.', 'Un workflow de ComfyUI és un graf: caixes (<b>nodes</b>) unides per cables (<b>links</b>). Cada node fa una feina i passa el resultat cap a la dreta. El llenç és infinit, i et mouràs molt: aprèn els gestos primer i tota la resta anirà més ràpid.', 'Un workflow de ComfyUI es un grafo: cajas (<b>nodos</b>) unidas por cables (<b>links</b>). Cada nodo hace un trabajo y pasa su resultado hacia la derecha. El lienzo es infinito, y te moverás mucho: aprende los gestos primero y todo lo demás irá más rápido.'),
        how: [L('Drag on an empty area of the canvas (or hold <kbd>Space</kbd> and move the mouse) to pan.', 'Arrossega en una zona buida del llenç (o mantén <kbd>Space</kbd> i mou el ratolí) per desplaçar-te.', 'Arrastra en una zona vacía del lienzo (o mantén <kbd>Space</kbd> y mueve el ratón) para desplazarte.'), L('Mouse wheel to zoom where the pointer is.', 'Roda del ratolí per fer zoom on hi ha el punter.', 'Rueda del ratón para hacer zoom donde está el puntero.'), L('Press <kbd>.</kbd> to fit the view to all nodes (or the ⛶ button, bottom right).', 'Prem <kbd>.</kbd> per encaixar la vista a tots els nodes (o el botó ⛶, a baix a la dreta).', 'Pulsa <kbd>.</kbd> para encajar la vista a todos los nodos (o el botón ⛶, abajo a la derecha).')],
        note: L('Newer versions have a “Standard” navigation mode where the wheel pans; this lab uses the classic mode, the one most tutorials show.', 'Les versions noves tenen un mode de navegació “Standard” on la roda desplaça; aquest lab fa servir el clàssic, el de la majoria de tutorials.', 'Las versiones nuevas tienen un modo de navegación “Standard” donde la rueda desplaza; este lab usa el clásico, el de la mayoría de tutoriales.'),
        starter: G.base, solution: G.base,
        goals: [goal(L('Panned the canvas', 'Has desplaçat el llenç', 'Has desplazado el lienzo'), (g, c) => c.flags.panned), goal(L('Zoomed in and out', 'Has fet zoom', 'Has hecho zoom'), (g, c) => c.flags.zoomed), goal(L('Framed all with <kbd>.</kbd>', 'Has enquadrat amb <kbd>.</kbd>', 'Has encuadrado con <kbd>.</kbd>'), (g, c) => c.flags.fitted)],
      },
      {
        title: L('Add a node with search', 'Afegeix un node amb la cerca', 'Añade un nodo con la búsqueda'),
        task: L('Add a Preview Image node and connect it to the IMAGE output of VAE Decode.', 'Afegeix un node Preview Image i connecta’l a la sortida IMAGE de VAE Decode.', 'Añade un nodo Preview Image y conéctalo a la salida IMAGE de VAE Decode.'),
        concept: L('<b>Double-click</b> on the empty canvas opens the node search: the fastest way to add anything. Wires only join sockets of the same <b>type</b>, and each type has a colour: IMAGE is blue. An output can feed many inputs; an input takes only one wire. Preview Image shows the result without saving a file; Save Image writes it to the output folder.', 'Fer <b>doble clic</b> al llenç buit obre la cerca de nodes: la manera més ràpida d’afegir qualsevol cosa. Els cables només uneixen sockets del mateix <b>tipus</b>, i cada tipus té un color: IMAGE és blau. Una sortida pot alimentar moltes entrades; una entrada només accepta un cable. Preview Image mostra el resultat sense desar cap fitxer; Save Image l’escriu a la carpeta output.', 'Hacer <b>doble clic</b> en el lienzo vacío abre la búsqueda de nodos: la forma más rápida de añadir cualquier cosa. Los cables solo unen sockets del mismo <b>tipo</b>, y cada tipo tiene un color: IMAGE es azul. Una salida puede alimentar muchas entradas; una entrada solo acepta un cable. Preview Image muestra el resultado sin guardar ningún archivo; Save Image lo escribe en la carpeta output.'),
        how: [L('Double-click an empty area, type <b>preview</b> and press <kbd>Enter</kbd>.', 'Fes doble clic en una zona buida, escriu <b>preview</b> i prem <kbd>Enter</kbd>.', 'Haz doble clic en una zona vacía, escribe <b>preview</b> y pulsa <kbd>Enter</kbd>.'), L('Drag from the blue <b>IMAGE</b> dot of VAE Decode to the <b>images</b> dot of Preview Image.', 'Arrossega des del punt blau <b>IMAGE</b> de VAE Decode fins al punt <b>images</b> de Preview Image.', 'Arrastra desde el punto azul <b>IMAGE</b> de VAE Decode hasta el punto <b>images</b> de Preview Image.'), L('Shortcut: drag a wire from IMAGE and drop it on the empty canvas: the search opens already filtered and connects the new node.', 'Drecera: arrossega un cable des d’IMAGE i deixa’l anar al llenç buit: s’obre la cerca ja filtrada i connecta el node nou.', 'Atajo: arrastra un cable desde IMAGE y suéltalo en el lienzo vacío: se abre la búsqueda ya filtrada y conecta el nodo nuevo.')],
        note: L('Right-click the canvas › Add Node shows the same nodes by category. <kbd>N</kbd> opens the Node Library panel.', 'Clic dret al llenç › Add Node mostra els mateixos nodes per categories. <kbd>N</kbd> obre el panell Node Library.', 'Clic derecho en el lienzo › Add Node muestra los mismos nodos por categorías. <kbd>N</kbd> abre el panel Node Library.'),
        starter: G.base, solution: G.preview,
        goals: [goal(L('A Preview Image node exists', 'Hi ha un node Preview Image', 'Hay un nodo Preview Image'), g => N(g, 'PreviewImage').length > 0), goal(L('It gets the IMAGE of VAE Decode', 'Rep la IMAGE de VAE Decode', 'Recibe la IMAGE de VAE Decode'), g => N(g, 'PreviewImage').some(p => srcType(g, p.id, 'images') === 'VAEDecode'))],
      },
      {
        title: L('Run it and watch it work', 'Executa-ho i mira com treballa', 'Ejecútalo y mira cómo trabaja'),
        task: L('Queue the workflow with Ctrl Enter, watch the nodes run, then open the Queue panel.', 'Posa el workflow a la cua amb Ctrl Enter, mira com s’executen els nodes i obre el panell Queue.', 'Pon el workflow en la cola con Ctrl Enter, mira cómo se ejecutan los nodos y abre el panel Queue.'),
        concept: L('<b>Run</b> (Queue Prompt) sends the whole graph to the server. ComfyUI starts from the output nodes and runs only what they need, in order: the green outline shows the running node, the KSampler shows its steps. Run again without changing anything: almost nothing runs, because unchanged nodes are taken from the <b>cache</b>. And look at the seed: “control after generate: randomize” gives a new one after every run.', '<b>Run</b> (Queue Prompt) envia tot el graf al servidor. ComfyUI comença pels nodes de sortida i executa només el que necessiten, en ordre: el contorn verd marca el node que treballa, i el KSampler mostra els seus passos. Torna a executar sense canviar res: gairebé no s’executa res, perquè els nodes que no han canviat surten de la <b>memòria cau</b> (cache). I mira el seed: “control after generate: randomize” en posa un de nou després de cada execució.', '<b>Run</b> (Queue Prompt) envía todo el grafo al servidor. ComfyUI empieza por los nodos de salida y ejecuta solo lo que necesitan, en orden: el contorno verde marca el nodo que trabaja, y el KSampler muestra sus pasos. Vuelve a ejecutar sin cambiar nada: casi no se ejecuta nada, porque los nodos que no han cambiado salen de la <b>caché</b>. Y mira el seed: “control after generate: randomize” pone uno nuevo después de cada ejecución.'),
        how: [L('Press <kbd>Ctrl Enter</kbd> (or the blue <b>Run</b> button, top right).', 'Prem <kbd>Ctrl Enter</kbd> (o el botó blau <b>Run</b>, a dalt a la dreta).', 'Pulsa <kbd>Ctrl Enter</kbd> (o el botón azul <b>Run</b>, arriba a la derecha).'), L('Follow the green outline from Load Checkpoint to Save Image.', 'Segueix el contorn verd des de Load Checkpoint fins a Save Image.', 'Sigue el contorno verde desde Load Checkpoint hasta Save Image.'), L('Press <kbd>Q</kbd> to open the Queue panel with your results.', 'Prem <kbd>Q</kbd> per obrir el panell Queue amb els resultats.', 'Pulsa <kbd>Q</kbd> para abrir el panel Queue con los resultados.')],
        note: L('This lab does not run an AI model: the pictures are drawn by a simulator that follows the same rules, so every setting has a visible effect.', 'Aquest lab no executa cap model d’IA: les imatges les dibuixa un simulador que segueix les mateixes regles, perquè cada paràmetre tingui un efecte visible.', 'Este lab no ejecuta ningún modelo de IA: las imágenes las dibuja un simulador que sigue las mismas reglas, para que cada parámetro tenga un efecto visible.'),
        starter: G.preview, solution: G.preview,
        goals: [goal(L('Queued with <kbd>Ctrl Enter</kbd>', 'Executat amb <kbd>Ctrl Enter</kbd>', 'Ejecutado con <kbd>Ctrl Enter</kbd>'), (g, c) => c.flags.runHotkey), goal(L('An image was generated', 'S’ha generat una imatge', 'Se ha generado una imagen'), (g, c) => runs(c).length > 0), goal(L('Opened the Queue panel', 'Has obert el panell Queue', 'Has abierto el panel Queue'), (g, c) => c.flags.queueOpen)],
      },
    ],
  },
  {
    id: 'txt2img', name: L('Text to image', 'Text a imatge', 'Texto a imagen'), sub: L('The 7 basic nodes', 'Els 7 nodes bàsics', 'Los 7 nodos básicos'),
    steps: [
      {
        title: L('Build the basic workflow', 'Construeix el workflow bàsic', 'Construye el workflow básico'),
        task: L('All nodes are there, but no wire. Make the nine connections of text-to-image and run it.', 'Hi ha tots els nodes, però cap cable. Fes les nou connexions del text a imatge i executa-ho.', 'Están todos los nodos, pero ningún cable. Haz las nueve conexiones del texto a imagen y ejecútalo.'),
        concept: L('<b>Load Checkpoint</b> opens a model file with three parts: <b>MODEL</b> (the network that removes noise), <b>CLIP</b> (turns words into numbers) and <b>VAE</b> (translates between pixels and latent space). <b>CLIP Text Encode</b> turns the prompts into CONDITIONING: one positive (what you want) and one negative (what to avoid). <b>Empty Latent Image</b> is the blank canvas, in latent space: 8 times smaller than the picture. <b>KSampler</b> starts from noise and removes it step by step, guided by the conditioning. <b>VAE Decode</b> turns the latent into pixels, and <b>Save Image</b> saves them.', '<b>Load Checkpoint</b> obre un fitxer de model amb tres parts: <b>MODEL</b> (la xarxa que treu el soroll), <b>CLIP</b> (converteix les paraules en números) i <b>VAE</b> (tradueix entre píxels i espai latent). <b>CLIP Text Encode</b> converteix els prompts en CONDITIONING: un de positiu (el que vols) i un de negatiu (el que vols evitar). <b>Empty Latent Image</b> és el llenç en blanc, en espai latent: 8 vegades més petit que la imatge. <b>KSampler</b> parteix de soroll i el treu pas a pas, guiat pel conditioning. <b>VAE Decode</b> converteix el latent en píxels, i <b>Save Image</b> els desa.', '<b>Load Checkpoint</b> abre un archivo de modelo con tres partes: <b>MODEL</b> (la red que quita el ruido), <b>CLIP</b> (convierte las palabras en números) y <b>VAE</b> (traduce entre píxeles y espacio latente). <b>CLIP Text Encode</b> convierte los prompts en CONDITIONING: uno positivo (lo que quieres) y uno negativo (lo que quieres evitar). <b>Empty Latent Image</b> es el lienzo en blanco, en espacio latente: 8 veces más pequeño que la imagen. <b>KSampler</b> parte de ruido y lo quita paso a paso, guiado por el conditioning. <b>VAE Decode</b> convierte el latente en píxeles, y <b>Save Image</b> los guarda.'),
        how: [L('Follow the colours: MODEL (violet) → KSampler · model; CLIP (yellow) → both CLIP Text Encode; VAE (red) → VAE Decode.', 'Segueix els colors: MODEL (violeta) → KSampler · model; CLIP (groc) → els dos CLIP Text Encode; VAE (vermell) → VAE Decode.', 'Sigue los colores: MODEL (violeta) → KSampler · model; CLIP (amarillo) → los dos CLIP Text Encode; VAE (rojo) → VAE Decode.'), L('CONDITIONING (orange): the top prompt → positive, the bottom one → negative. LATENT (pink): Empty Latent → latent_image, KSampler → VAE Decode · samples.', 'CONDITIONING (taronja): el prompt de dalt → positive, el de sota → negative. LATENT (rosa): Empty Latent → latent_image, KSampler → VAE Decode · samples.', 'CONDITIONING (naranja): el prompt de arriba → positive, el de abajo → negative. LATENT (rosa): Empty Latent → latent_image, KSampler → VAE Decode · samples.'), L('IMAGE (blue) → Save Image. Then <kbd>Ctrl Enter</kbd>.', 'IMAGE (blau) → Save Image. Després <kbd>Ctrl Enter</kbd>.', 'IMAGE (azul) → Save Image. Después <kbd>Ctrl Enter</kbd>.')],
        note: L('Select a node and click <b>ⓘ</b> in the small toolbar above it to read what it does.', 'Selecciona un node i clica <b>ⓘ</b> a la barra petita de sobre per llegir què fa.', 'Selecciona un nodo y haz clic en <b>ⓘ</b> en la barra pequeña de encima para leer qué hace.'),
        starter: G.empty, solution: G.base,
        goals: [goal(L('Every required input is connected', 'Totes les entrades obligatòries estan connectades', 'Todas las entradas obligatorias están conectadas'), g => fullDefault(g)), goal(L('Positive and negative are not swapped', 'Positive i negative no estan intercanviats', 'Positive y negative no están intercambiados'), g => { const s = sampler(g); const p = s && into(g, s.id, 'positive'); return p && /bottle|robot|cat|house|light|tree|person|scenery/i.test(g.nodes.find(n => n.id === p.from)?.widgets.text || ''); }), goal(L('Run it', 'Executa-ho', 'Ejecútalo'), (g, c) => runs(c).length > 0)],
      },
      {
        title: L('Read the red error', 'Llegeix l’error vermell', 'Lee el error rojo'),
        task: L('Run this workflow, read the error and fix the two missing connections.', 'Executa aquest workflow, llegeix l’error i arregla les dues connexions que falten.', 'Ejecuta este workflow, lee el error y arregla las dos conexiones que faltan.'),
        concept: L('Before running anything, ComfyUI checks the graph. A required input with no wire stops everything: “Prompt outputs failed validation · Required input is missing”. The node with the problem gets a <b>red outline</b>. Optional inputs (shown faded) can stay empty.', 'Abans d’executar res, ComfyUI revisa el graf. Una entrada obligatòria sense cable ho atura tot: “Prompt outputs failed validation · Required input is missing”. El node amb el problema queda amb un <b>contorn vermell</b>. Les entrades opcionals (més apagades) poden quedar buides.', 'Antes de ejecutar nada, ComfyUI revisa el grafo. Una entrada obligatoria sin cable lo detiene todo: “Prompt outputs failed validation · Required input is missing”. El nodo con el problema queda con un <b>contorno rojo</b>. Las entradas opcionales (más apagadas) pueden quedar vacías.'),
        how: [L('Press <kbd>Ctrl Enter</kbd> and read the dialog: which node, which input.', 'Prem <kbd>Ctrl Enter</kbd> i llegeix el diàleg: quin node, quina entrada.', 'Pulsa <kbd>Ctrl Enter</kbd> y lee el diálogo: qué nodo, qué entrada.'), L('Connect them and run again.', 'Connecta-les i torna a executar.', 'Conéctalas y vuelve a ejecutar.')],
        note: L('In the real ComfyUI a missing <b>custom node</b> also turns red when you open a workflow: the Manager can install it.', 'Al ComfyUI real un <b>custom node</b> que no tens també surt en vermell quan obres un workflow: el Manager el pot instal·lar.', 'En el ComfyUI real un <b>custom node</b> que no tienes también sale en rojo al abrir un workflow: el Manager puede instalarlo.'),
        starter: G.broken, solution: G.base,
        goals: [goal(L('You saw the validation error', 'Has vist l’error de validació', 'Has visto el error de validación'), (g, c) => c.flags.errorSeen), goal(L('The graph is valid again', 'El graf torna a ser vàlid', 'El grafo vuelve a ser válido'), g => validate(g).ok), goal(L('It runs and saves an image', 'S’executa i desa una imatge', 'Se ejecuta y guarda una imagen'), (g, c) => runs(c).length > 0)],
      },
      {
        title: L('Write the prompts', 'Escriu els prompts', 'Escribe los prompts'),
        task: L('Write your own positive prompt (a subject, a place and a style) and use the negative to remove something.', 'Escriu el teu prompt positiu (un subjecte, un lloc i un estil) i fes servir el negatiu per treure alguna cosa.', 'Escribe tu prompt positivo (un sujeto, un lugar y un estilo) y usa el negativo para quitar algo.'),
        concept: L('The text encoder reads words, not sentences: order and keywords matter more than grammar. Emphasis changes the weight of a word: <b>(red:1.3)</b> = 30 % more, <b>(red)</b> = 10 % more. The negative prompt pushes the picture away from what it describes. This simulator understands a small vocabulary: subjects (robot, cat, house, lighthouse, bottle, tree, person), places (forest, beach, snow, desert, sunset, night, galaxy), colours and styles (watercolor, pixel art, neon, sketch, oil painting).', 'L’encoder de text llegeix paraules, no frases: l’ordre i les paraules clau importen més que la gramàtica. L’èmfasi canvia el pes d’una paraula: <b>(red:1.3)</b> = un 30 % més, <b>(red)</b> = un 10 % més. El prompt negatiu allunya la imatge del que descriu. Aquest simulador entén un vocabulari petit: subjectes (robot, cat, house, lighthouse, bottle, tree, person), llocs (forest, beach, snow, desert, sunset, night, galaxy), colors i estils (watercolor, pixel art, neon, sketch, oil painting).', 'El encoder de texto lee palabras, no frases: el orden y las palabras clave importan más que la gramática. El énfasis cambia el peso de una palabra: <b>(red:1.3)</b> = un 30 % más, <b>(red)</b> = un 10 % más. El prompt negativo aleja la imagen de lo que describe. Este simulador entiende un vocabulario pequeño: sujetos (robot, cat, house, lighthouse, bottle, tree, person), lugares (forest, beach, snow, desert, sunset, night, galaxy), colores y estilos (watercolor, pixel art, neon, sketch, oil painting).'),
        how: [L('Click the top text box (positive) and write, for example: <i>a (red:1.2) robot in a snowy forest, watercolor</i>.', 'Clica la caixa de text de dalt (positiu) i escriu, per exemple: <i>a (red:1.2) robot in a snowy forest, watercolor</i>.', 'Haz clic en la caja de texto de arriba (positivo) y escribe, por ejemplo: <i>a (red:1.2) robot in a snowy forest, watercolor</i>.'), L('In the negative add something you see and do not want, like <i>tree</i>.', 'Al negatiu afegeix una cosa que veus i no vols, com <i>tree</i>.', 'En el negativo añade algo que ves y no quieres, como <i>tree</i>.'), L('Run and compare in the Queue panel.', 'Executa i compara al panell Queue.', 'Ejecuta y compara en el panel Queue.')],
        note: L('<kbd>Ctrl ↑</kbd> / <kbd>Ctrl ↓</kbd> with words selected in a prompt change their weight, as in ComfyUI.', '<kbd>Ctrl ↑</kbd> / <kbd>Ctrl ↓</kbd> amb paraules seleccionades en un prompt en canvien el pes, com a ComfyUI.', '<kbd>Ctrl ↑</kbd> / <kbd>Ctrl ↓</kbd> con palabras seleccionadas en un prompt cambian su peso, como en ComfyUI.'),
        starter: G.base, solution: G.prompts,
        goals: [goal(L('The positive has a subject and a place or style', 'El positiu té un subjecte i un lloc o estil', 'El positivo tiene un sujeto y un lugar o estilo'), (g, c) => runs(c).some(r => r.pos.subjects.length && (r.pos.settings.length || r.pos.styles.length) && !/glass bottle landscape/.test(r.pos.text))), goal(L('The negative removes something it knows', 'El negatiu treu alguna cosa que coneix', 'El negativo quita algo que conoce'), (g, c) => runs(c).some(r => r.neg.subjects.length || r.neg.colors.length || r.neg.settings.length)), goal(L('Used emphasis like (word:1.3)', 'Has fet servir èmfasi com (paraula:1.3)', 'Has usado énfasis como (palabra:1.3)'), (g, c) => runs(c).some(r => Object.keys(r.pos.weights).length), true)],
      },
    ],
  },
  {
    id: 'ksampler', name: L('KSampler', 'KSampler', 'KSampler'), sub: L('seed · steps · cfg · sampler', 'seed · steps · cfg · sampler', 'seed · steps · cfg · sampler'),
    steps: [
      {
        title: L('The seed', 'El seed', 'El seed'),
        task: L('Set control after generate to fixed, run twice and get the same picture. Then change the seed by hand.', 'Posa control after generate a fixed, executa dues vegades i obtén la mateixa imatge. Després canvia el seed a mà.', 'Pon control after generate en fixed, ejecuta dos veces y obtén la misma imagen. Después cambia el seed a mano.'),
        concept: L('The KSampler does not start from nothing: it starts from <b>noise</b>, and the <b>seed</b> decides that noise. Same seed + same settings = the same picture, always. That is how you reproduce a result and change only one thing at a time. With <i>randomize</i> the seed changes after each run, so you never see the same image twice.', 'El KSampler no parteix de res: parteix de <b>soroll</b>, i el <b>seed</b> decideix quin soroll. Mateix seed + mateixos paràmetres = la mateixa imatge, sempre. Així reprodueixes un resultat i canvies una sola cosa cada vegada. Amb <i>randomize</i> el seed canvia després de cada execució, i mai veus dues vegades la mateixa imatge.', 'El KSampler no parte de nada: parte de <b>ruido</b>, y el <b>seed</b> decide qué ruido. Mismo seed + mismos parámetros = la misma imagen, siempre. Así reproduces un resultado y cambias una sola cosa cada vez. Con <i>randomize</i> el seed cambia después de cada ejecución, y nunca ves dos veces la misma imagen.'),
        how: [L('Click the value of <b>control_after_generate</b> and choose <b>fixed</b>.', 'Clica el valor de <b>control_after_generate</b> i tria <b>fixed</b>.', 'Haz clic en el valor de <b>control_after_generate</b> y elige <b>fixed</b>.'), L('Run twice: the two thumbnails in Queue are identical.', 'Executa dues vegades: les dues miniatures de Queue són idèntiques.', 'Ejecuta dos veces: las dos miniaturas de Queue son idénticas.'), L('Click the arrows of <b>seed</b> (or drag it) and run again.', 'Clica les fletxes del <b>seed</b> (o arrossega’l) i torna a executar.', 'Haz clic en las flechas del <b>seed</b> (o arrástralo) y vuelve a ejecutar.')],
        note: L('Found a good image? Its seed is in the Queue panel: load that workflow and keep working on it.', 'Has trobat una bona imatge? El seed és al panell Queue: carrega aquell workflow i continua treballant-hi.', '¿Has encontrado una buena imagen? Su seed está en el panel Queue: carga ese workflow y sigue trabajando en él.'),
        starter: G.prompts, solution: G.fixedSeed,
        goals: [goal(L('control_after_generate is fixed', 'control_after_generate és fixed', 'control_after_generate es fixed'), g => sampler(g)?.widgets.control_after_generate === 'fixed'), goal(L('Two runs with the same seed and settings', 'Dues execucions amb el mateix seed i paràmetres', 'Dos ejecuciones con el mismo seed y parámetros'), (g, c) => runs(c).some((a, i) => runs(c).some((b, j) => j > i && a.key === b.key))), goal(L('A run with another seed', 'Una execució amb un altre seed', 'Una ejecución con otro seed'), (g, c) => new Set(runs(c).map(r => r.seed)).size >= 2)],
      },
      {
        title: L('Steps: how finished', 'Steps: com d’acabada', 'Steps: cómo de acabada'),
        task: L('With the same seed, run with 4 steps or fewer and with 20 or more.', 'Amb el mateix seed, executa amb 4 steps o menys i amb 20 o més.', 'Con el mismo seed, ejecuta con 4 steps o menos y con 20 o más.'),
        concept: L('Each <b>step</b> removes part of the noise. Too few and the picture stays noisy and blurred; after a point (20–30 with euler) more steps cost time and change almost nothing. Watch the KSampler preview: the picture appears out of the noise.', 'Cada <b>step</b> treu una part del soroll. Massa pocs i la imatge queda sorollosa i borrosa; a partir d’un punt (20–30 amb euler) més steps costen temps i gairebé no canvien res. Mira la vista prèvia del KSampler: la imatge apareix del soroll.', 'Cada <b>step</b> quita una parte del ruido. Demasiado pocos y la imagen queda ruidosa y borrosa; a partir de un punto (20–30 con euler) más steps cuestan tiempo y casi no cambian nada. Mira la vista previa del KSampler: la imagen aparece del ruido.'),
        how: [L('Keep the seed fixed. Steps <b>4</b> › run.', 'Mantén el seed fix. Steps <b>4</b> › executa.', 'Mantén el seed fijo. Steps <b>4</b> › ejecuta.'), L('Steps <b>25</b> › run. Compare both in Queue (click a thumbnail to enlarge).', 'Steps <b>25</b> › executa. Compara-les a Queue (clica una miniatura per ampliar-la).', 'Steps <b>25</b> › ejecuta. Compáralas en Queue (haz clic en una miniatura para ampliarla).')],
        note: L('Some models (LCM, Turbo, Lightning) are trained to finish in 4–8 steps; with them, more steps can make it worse.', 'Alguns models (LCM, Turbo, Lightning) estan entrenats per acabar en 4–8 steps; amb aquests, més steps ho poden empitjorar.', 'Algunos modelos (LCM, Turbo, Lightning) están entrenados para terminar en 4–8 steps; con ellos, más steps pueden empeorarlo.'),
        starter: G.fixedSeed, solution: G.fixedSeed,
        goals: [goal(L('A run with ≤ 4 steps', 'Una execució amb ≤ 4 steps', 'Una ejecución con ≤ 4 steps'), (g, c) => runs(c).some(r => r.steps <= 4)), goal(L('A run with ≥ 20 steps and the same seed', 'Una execució amb ≥ 20 steps i el mateix seed', 'Una ejecución con ≥ 20 steps y el mismo seed'), (g, c) => runs(c).some(a => a.steps <= 4 && runs(c).some(b => b.steps >= 20 && same(a, b))))],
      },
      {
        title: L('CFG: how much it obeys', 'CFG: com d’obedient', 'CFG: cuánto obedece'),
        task: L('With the same seed, compare cfg 1.5, a middle value (6–8) and 15 or more.', 'Amb el mateix seed, compara cfg 1,5, un valor mitjà (6–8) i 15 o més.', 'Con el mismo seed, compara cfg 1,5, un valor medio (6–8) y 15 o más.'),
        concept: L('<b>CFG</b> (classifier-free guidance) is how strongly the sampler follows the prompt. Low: pale, vague, the prompt is half ignored. Medium (5–8 for SD 1.5): balanced. High: saturated, contrasty, “burned” colours. It is a compromise, not a “quality” slider.', 'El <b>CFG</b> (classifier-free guidance) és la força amb què el sampler segueix el prompt. Baix: pàl·lid, vague, el prompt mig ignorat. Mitjà (5–8 per a SD 1.5): equilibrat. Alt: saturat, contrastat, colors “cremats”. És un compromís, no un control de “qualitat”.', 'El <b>CFG</b> (classifier-free guidance) es la fuerza con la que el sampler sigue el prompt. Bajo: pálido, vago, el prompt medio ignorado. Medio (5–8 para SD 1.5): equilibrado. Alto: saturado, contrastado, colores “quemados”. Es un compromiso, no un control de “calidad”.'),
        how: [L('cfg <b>1.5</b> › run · cfg <b>7</b> › run · cfg <b>16</b> › run.', 'cfg <b>1,5</b> › executa · cfg <b>7</b> › executa · cfg <b>16</b> › executa.', 'cfg <b>1,5</b> › ejecuta · cfg <b>7</b> › ejecuta · cfg <b>16</b> › ejecuta.'), L('Compare the three in the Queue panel.', 'Compara les tres al panell Queue.', 'Compara las tres en el panel Queue.')],
        note: L('Flux and some distilled models use cfg 1 and a separate “guidance” value: always check the model page.', 'Flux i alguns models destil·lats fan servir cfg 1 i un valor de “guidance” a part: mira sempre la pàgina del model.', 'Flux y algunos modelos destilados usan cfg 1 y un valor de “guidance” aparte: mira siempre la página del modelo.'),
        starter: G.fixedSeed, solution: G.fixedSeed,
        goals: [goal(L('A run with cfg ≤ 2', 'Una execució amb cfg ≤ 2', 'Una ejecución con cfg ≤ 2'), (g, c) => runs(c).some(r => r.cfg <= 2)), goal(L('A run with cfg between 5 and 9', 'Una execució amb cfg entre 5 i 9', 'Una ejecución con cfg entre 5 y 9'), (g, c) => runs(c).some(r => r.cfg >= 5 && r.cfg <= 9)), goal(L('A run with cfg ≥ 15', 'Una execució amb cfg ≥ 15', 'Una ejecución con cfg ≥ 15'), (g, c) => runs(c).some(r => r.cfg >= 15))],
      },
      {
        title: L('Sampler and scheduler', 'Sampler i scheduler', 'Sampler y scheduler'),
        task: L('Try dpmpp_2m with karras, then an ancestral sampler at two different step counts.', 'Prova dpmpp_2m amb karras, i després un sampler ancestral amb dos nombres de steps diferents.', 'Prueba dpmpp_2m con karras, y después un sampler ancestral con dos números de steps distintos.'),
        concept: L('The <b>sampler</b> is the method for removing noise; the <b>scheduler</b> decides how much noise is removed at each step. dpmpp_2m + karras finishes in fewer steps than euler + normal. <b>Ancestral</b> samplers (with “a” or “sde”) add a little new noise at every step: the picture never settles, so changing the steps also changes the composition.', 'El <b>sampler</b> és el mètode per treure soroll; el <b>scheduler</b> decideix quant soroll se’n treu a cada step. dpmpp_2m + karras acaba en menys steps que euler + normal. Els samplers <b>ancestrals</b> (amb “a” o “sde”) afegeixen una mica de soroll nou a cada step: la imatge no s’estabilitza mai, i canviar els steps també canvia la composició.', 'El <b>sampler</b> es el método para quitar ruido; el <b>scheduler</b> decide cuánto ruido se quita en cada step. dpmpp_2m + karras termina en menos steps que euler + normal. Los samplers <b>ancestrales</b> (con “a” o “sde”) añaden un poco de ruido nuevo en cada step: la imagen nunca se estabiliza, y cambiar los steps también cambia la composición.'),
        how: [L('sampler_name <b>dpmpp_2m</b>, scheduler <b>karras</b>, steps 12 › run.', 'sampler_name <b>dpmpp_2m</b>, scheduler <b>karras</b>, steps 12 › executa.', 'sampler_name <b>dpmpp_2m</b>, scheduler <b>karras</b>, steps 12 › ejecuta.'), L('sampler_name <b>euler_ancestral</b>: run with 20 and with 30 steps and compare.', 'sampler_name <b>euler_ancestral</b>: executa amb 20 i amb 30 steps i compara.', 'sampler_name <b>euler_ancestral</b>: ejecuta con 20 y con 30 steps y compara.')],
        note: L('A safe start for SD 1.5 and SDXL: dpmpp_2m · karras · 20–30 steps · cfg 5–7.', 'Un bon punt de partida per a SD 1.5 i SDXL: dpmpp_2m · karras · 20–30 steps · cfg 5–7.', 'Un buen punto de partida para SD 1.5 y SDXL: dpmpp_2m · karras · 20–30 steps · cfg 5–7.'),
        starter: G.fixedSeed, solution: G.fixedSeed,
        goals: [goal(L('A run with dpmpp_2m and karras', 'Una execució amb dpmpp_2m i karras', 'Una ejecución con dpmpp_2m y karras'), (g, c) => runs(c).some(r => r.sampler === 'dpmpp_2m' && r.scheduler === 'karras')), goal(L('An ancestral sampler with two step counts', 'Un sampler ancestral amb dos nombres de steps', 'Un sampler ancestral con dos números de steps'), (g, c) => { const a = runs(c).filter(r => /ancestral|sde/.test(r.sampler)); return new Set(a.map(r => r.steps)).size >= 2; })],
      },
    ],
  },
  {
    id: 'size', name: L('Size & img2img', 'Mida i img2img', 'Tamaño e img2img'), sub: L('resolution · denoise', 'resolució · denoise', 'resolución · denoise'),
    steps: [
      {
        title: L('The model’s own size', 'La mida del model', 'El tamaño del modelo'),
        task: L('Run SD 1.5 at 1024 × 1024 and look at the subject. Then switch to the SDXL checkpoint at 1024 × 1024.', 'Executa SD 1.5 a 1024 × 1024 i mira el subjecte. Després canvia al checkpoint SDXL a 1024 × 1024.', 'Ejecuta SD 1.5 a 1024 × 1024 y mira el sujeto. Después cambia al checkpoint SDXL a 1024 × 1024.'),
        concept: L('Every model was trained at one resolution: SD 1.5 at <b>512</b>, SDXL at <b>1024</b>. Far above it the model “fills” the extra space by repeating things: two subjects, double heads, stretched bodies. Far below it the picture loses detail. Make the picture at the native size, then upscale.', 'Cada model es va entrenar a una resolució: SD 1.5 a <b>512</b>, SDXL a <b>1024</b>. Molt per sobre, el model “omple” l’espai que sobra repetint coses: dos subjectes, caps dobles, cossos estirats. Molt per sota, la imatge perd detall. Fes la imatge a la mida nativa i després amplia-la.', 'Cada modelo se entrenó a una resolución: SD 1.5 a <b>512</b>, SDXL a <b>1024</b>. Muy por encima, el modelo “rellena” el espacio sobrante repitiendo cosas: dos sujetos, cabezas dobles, cuerpos estirados. Muy por debajo, la imagen pierde detalle. Haz la imagen al tamaño nativo y después amplíala.'),
        how: [L('Empty Latent Image: width and height <b>1024</b> › run with <b>dreamshaper_8</b> (SD 1.5).', 'Empty Latent Image: width i height <b>1024</b> › executa amb <b>dreamshaper_8</b> (SD 1.5).', 'Empty Latent Image: width y height <b>1024</b> › ejecuta con <b>dreamshaper_8</b> (SD 1.5).'), L('Load Checkpoint › <b>sd_xl_base_1.0</b> › run again.', 'Load Checkpoint › <b>sd_xl_base_1.0</b> › torna a executar.', 'Load Checkpoint › <b>sd_xl_base_1.0</b> › vuelve a ejecutar.')],
        note: L('Sizes must be multiples of 8 (the latent is 8 times smaller). Common SDXL sizes: 1024 × 1024, 1152 × 896, 1216 × 832.', 'Les mides han de ser múltiples de 8 (el latent és 8 vegades més petit). Mides SDXL habituals: 1024 × 1024, 1152 × 896, 1216 × 832.', 'Los tamaños deben ser múltiplos de 8 (el latente es 8 veces más pequeño). Tamaños SDXL habituales: 1024 × 1024, 1152 × 896, 1216 × 832.'),
        starter: G.fixedSeed, solution: G.sdxl,
        goals: [goal(L('SD 1.5 at 1024: duplicated subject', 'SD 1.5 a 1024: subjecte repetit', 'SD 1.5 a 1024: sujeto repetido'), (g, c) => runs(c).some(r => r.arch === 'SD1.5' && Math.max(r.w, r.h) >= 1024)), goal(L('SDXL at 1024: one subject', 'SDXL a 1024: un sol subjecte', 'SDXL a 1024: un solo sujeto'), (g, c) => runs(c).some(r => r.arch === 'SDXL' && Math.max(r.w, r.h) >= 1000 && Math.max(r.w, r.h) <= 1400))],
      },
      {
        title: L('Image to image: denoise', 'Imatge a imatge: denoise', 'Imagen a imagen: denoise'),
        task: L('Start from lighthouse.png instead of an empty latent: Load Image › VAE Encode › KSampler. Run with denoise 0.3 and 0.8.', 'Parteix de lighthouse.png en lloc d’un latent buit: Load Image › VAE Encode › KSampler. Executa amb denoise 0,3 i 0,8.', 'Parte de lighthouse.png en lugar de un latente vacío: Load Image › VAE Encode › KSampler. Ejecuta con denoise 0,3 y 0,8.'),
        concept: L('<b>VAE Encode</b> turns a picture into latent space. The KSampler then adds only part of the noise and removes it again: <b>denoise</b> decides how much. 0.3 keeps the photo and changes the surface; 0.6 keeps the composition and redraws it; 1.0 ignores it completely. With an <i>empty</i> latent, denoise below 1 just gives grey mush: denoise is for img2img.', '<b>VAE Encode</b> converteix una imatge en espai latent. Llavors el KSampler només hi afegeix una part del soroll i el torna a treure: el <b>denoise</b> decideix quanta. 0,3 conserva la foto i en canvia la superfície; 0,6 manté la composició i la redibuixa; 1,0 la ignora del tot. Amb un latent <i>buit</i>, un denoise per sota d’1 només dona una pasta grisa: el denoise és per a img2img.', '<b>VAE Encode</b> convierte una imagen en espacio latente. Entonces el KSampler solo añade una parte del ruido y lo vuelve a quitar: el <b>denoise</b> decide cuánta. 0,3 conserva la foto y cambia la superficie; 0,6 mantiene la composición y la redibuja; 1,0 la ignora del todo. Con un latente <i>vacío</i>, un denoise por debajo de 1 solo da una pasta gris: el denoise es para img2img.'),
        how: [L('Add <b>Load Image</b> (image: lighthouse.png) and <b>VAE Encode</b>; its vae comes from Load Checkpoint.', 'Afegeix <b>Load Image</b> (image: lighthouse.png) i <b>VAE Encode</b>; la seva vae surt de Load Checkpoint.', 'Añade <b>Load Image</b> (image: lighthouse.png) y <b>VAE Encode</b>; su vae sale de Load Checkpoint.'), L('VAE Encode › LATENT › KSampler · latent_image (it replaces Empty Latent).', 'VAE Encode › LATENT › KSampler · latent_image (substitueix l’Empty Latent).', 'VAE Encode › LATENT › KSampler · latent_image (sustituye al Empty Latent).'), L('denoise <b>0.3</b> › run · denoise <b>0.8</b> › run.', 'denoise <b>0,3</b> › executa · denoise <b>0,8</b> › executa.', 'denoise <b>0,3</b> › ejecuta · denoise <b>0,8</b> › ejecuta.')],
        note: L('Templates (left sidebar) has an Image to Image workflow ready to load.', 'Templates (barra de l’esquerra) té un workflow Image to Image a punt de carregar.', 'Templates (barra de la izquierda) tiene un workflow Image to Image listo para cargar.'),
        starter: G.fixedSeed, solution: G.img2img,
        goals: [goal(L('VAE Encode feeds latent_image', 'VAE Encode alimenta latent_image', 'VAE Encode alimenta latent_image'), g => { const s = sampler(g); return s && srcType(g, s.id, 'latent_image') === 'VAEEncode'; }), goal(L('A run with denoise ≤ 0.4 from the image', 'Una execució amb denoise ≤ 0,4 des de la imatge', 'Una ejecución con denoise ≤ 0,4 desde la imagen'), (g, c) => runs(c).some(r => r.img2img && r.denoise <= .4)), goal(L('A run with denoise ≥ 0.75 from the image', 'Una execució amb denoise ≥ 0,75 des de la imatge', 'Una ejecución con denoise ≥ 0,75 desde la imagen'), (g, c) => runs(c).some(r => r.img2img && r.denoise >= .75))],
      },
    ],
  },
  {
    id: 'lora', name: L('LoRA', 'LoRA', 'LoRA'), sub: L('style · trigger · strength', 'estil · trigger · força', 'estilo · trigger · fuerza'),
    steps: [
      {
        title: L('Insert a LoRA', 'Insereix una LoRA', 'Inserta una LoRA'),
        task: L('Put a Load LoRA node between Load Checkpoint and the rest: MODEL and CLIP go through it.', 'Posa un node Load LoRA entre Load Checkpoint i la resta: MODEL i CLIP hi passen per dins.', 'Pon un nodo Load LoRA entre Load Checkpoint y el resto: MODEL y CLIP pasan por dentro.'),
        concept: L('A <b>LoRA</b> (Low-Rank Adaptation) is a small file (10–200 MB) with <i>corrections</i> for a big model: a style, a character, an object. It is not a filter on the image: it changes the model before it draws. That is why it sits on the MODEL wire (how it draws) and on the CLIP wire (how it reads the words). It only works with the model family it was trained for.', 'Una <b>LoRA</b> (Low-Rank Adaptation) és un fitxer petit (10–200 MB) amb <i>correccions</i> per a un model gran: un estil, un personatge, un objecte. No és un filtre sobre la imatge: canvia el model abans que dibuixi. Per això va al cable MODEL (com dibuixa) i al cable CLIP (com llegeix les paraules). Només funciona amb la família de models per a la qual es va entrenar.', 'Una <b>LoRA</b> (Low-Rank Adaptation) es un archivo pequeño (10–200 MB) con <i>correcciones</i> para un modelo grande: un estilo, un personaje, un objeto. No es un filtro sobre la imagen: cambia el modelo antes de que dibuje. Por eso va en el cable MODEL (cómo dibuja) y en el cable CLIP (cómo lee las palabras). Solo funciona con la familia de modelos para la que se entrenó.'),
        how: [L('Add <b>Load LoRA</b> (search “lora”, or Model Library <kbd>M</kbd> › loras).', 'Afegeix <b>Load LoRA</b> (cerca “lora”, o Model Library <kbd>M</kbd> › loras).', 'Añade <b>Load LoRA</b> (busca “lora”, o Model Library <kbd>M</kbd> › loras).'), L('Load Checkpoint MODEL → LoRA model, CLIP → LoRA clip.', 'Load Checkpoint MODEL → model de la LoRA, CLIP → clip de la LoRA.', 'Load Checkpoint MODEL → model de la LoRA, CLIP → clip de la LoRA.'), L('LoRA MODEL → KSampler model; LoRA CLIP → both CLIP Text Encode. Run.', 'MODEL de la LoRA → model del KSampler; CLIP de la LoRA → els dos CLIP Text Encode. Executa.', 'MODEL de la LoRA → model del KSampler; CLIP de la LoRA → los dos CLIP Text Encode. Ejecuta.')],
        note: L('Each new wire into an input replaces the old one, so you only need to connect; nothing to delete.', 'Cada cable nou a una entrada substitueix l’anterior: només cal connectar, no cal esborrar res.', 'Cada cable nuevo en una entrada sustituye al anterior: solo hay que conectar, no hay que borrar nada.'),
        starter: G.fixedSeed, solution: () => G.lora(),
        goals: [goal(L('The KSampler gets MODEL from the LoRA', 'El KSampler rep el MODEL de la LoRA', 'El KSampler recibe el MODEL de la LoRA'), g => { const s = sampler(g); return s && srcType(g, s.id, 'model') === 'LoraLoader'; }), goal(L('Both prompts get CLIP from the LoRA', 'Els dos prompts reben el CLIP de la LoRA', 'Los dos prompts reciben el CLIP de la LoRA'), g => loraFeeds(g)), goal(L('Run it', 'Executa-ho', 'Ejecútalo'), (g, c) => runs(c).some(r => r.loras.length))],
      },
      {
        title: L('Trigger word and strength', 'Paraula clau i força', 'Palabra clave y fuerza'),
        task: L('Use pixel_art_sd15 with its trigger word “pixelart” in the prompt. Compare strength_model 0 and 1 with the same seed, and try 2.', 'Fes servir pixel_art_sd15 amb la paraula clau “pixelart” al prompt. Compara strength_model 0 i 1 amb el mateix seed, i prova 2.', 'Usa pixel_art_sd15 con su palabra clave “pixelart” en el prompt. Compara strength_model 0 y 1 con el mismo seed, y prueba 2.'),
        concept: L('Many LoRAs were trained with a <b>trigger word</b>: without it in the prompt they barely work (it is written on the LoRA’s download page). <b>strength_model</b> is how much the LoRA changes the drawing; <b>strength_clip</b> how much it changes the reading of the prompt (and so the trigger). 0 = off, 1 = as trained, above 1.3 or so it breaks the picture.', 'Moltes LoRA es van entrenar amb una <b>paraula clau</b> (trigger): si no és al prompt gairebé no fan res (surt a la pàgina de descàrrega de la LoRA). <b>strength_model</b> és quant canvia la LoRA el dibuix; <b>strength_clip</b> quant canvia la lectura del prompt (i per tant el trigger). 0 = apagada, 1 = com es va entrenar, per sobre d’1,3 aproximadament trenca la imatge.', 'Muchas LoRA se entrenaron con una <b>palabra clave</b> (trigger): si no está en el prompt casi no hacen nada (sale en la página de descarga de la LoRA). <b>strength_model</b> es cuánto cambia la LoRA el dibujo; <b>strength_clip</b> cuánto cambia la lectura del prompt (y por tanto el trigger). 0 = apagada, 1 = como se entrenó, por encima de 1,3 aproximadamente rompe la imagen.'),
        how: [L('lora_name <b>pixel_art_sd15</b>; prompt starts with <b>pixelart,</b>; seed fixed.', 'lora_name <b>pixel_art_sd15</b>; el prompt comença amb <b>pixelart,</b>; seed fix.', 'lora_name <b>pixel_art_sd15</b>; el prompt empieza con <b>pixelart,</b>; seed fijo.'), L('strength_model <b>0</b> › run · <b>1</b> › run · <b>2</b> › run.', 'strength_model <b>0</b> › executa · <b>1</b> › executa · <b>2</b> › executa.', 'strength_model <b>0</b> › ejecuta · <b>1</b> › ejecuta · <b>2</b> › ejecuta.'), L('Remove “pixelart” from the prompt and run at 1: much weaker.', 'Treu “pixelart” del prompt i executa a 1: molt més fluix.', 'Quita “pixelart” del prompt y ejecuta a 1: mucho más flojo.')],
        note: L('watercolor_sd15 uses “wtrcolor”; ink_sketch_sd15 needs no trigger.', 'watercolor_sd15 fa servir “wtrcolor”; ink_sketch_sd15 no en necessita.', 'watercolor_sd15 usa “wtrcolor”; ink_sketch_sd15 no necesita ninguno.'),
        starter: () => G.lora('pixel_art_sd15.safetensors', 'a house in a forest, sunset'), solution: () => G.lora(),
        goals: [goal(L('A run with the trigger word', 'Una execució amb la paraula clau', 'Una ejecución con la palabra clave'), (g, c) => runs(c).some(r => r.loras.some(l => l.trigger && r.pos.triggers.includes(l.trigger) && l.strength > .5))), goal(L('strength 0 and 1 with the same seed', 'Força 0 i 1 amb el mateix seed', 'Fuerza 0 y 1 con el mismo seed'), (g, c) => runs(c).some(a => a.loras.some(l => l.strength === 0) && runs(c).some(b => same(a, b) && b.loras.some(l => l.strength >= .9 && l.strength <= 1.1)))), goal(L('Too much: strength ≥ 1.8', 'Massa: força ≥ 1,8', 'Demasiado: fuerza ≥ 1,8'), (g, c) => runs(c).some(r => r.loras.some(l => l.strength >= 1.8)), true)],
      },
      {
        title: L('Compatibility and stacking', 'Compatibilitat i combinació', 'Compatibilidad y combinación'),
        task: L('Switch the checkpoint to SDXL and read the warning. Back on SD 1.5, chain a second LoRA after the first one.', 'Canvia el checkpoint a SDXL i llegeix l’avís. Torna a SD 1.5 i encadena una segona LoRA després de la primera.', 'Cambia el checkpoint a SDXL y lee el aviso. Vuelve a SD 1.5 y encadena una segunda LoRA después de la primera.'),
        concept: L('An SD 1.5 LoRA does not fit an SDXL model: ComfyUI loads it but prints “lora key not loaded” and nothing changes. Check the base model on the download page. LoRAs <b>stack</b> by chaining Load LoRA nodes; their effects add up, so lower each strength (0.6–0.8) when you combine them.', 'Una LoRA de SD 1.5 no encaixa en un model SDXL: ComfyUI la carrega però escriu “lora key not loaded” i no canvia res. Mira el model base a la pàgina de descàrrega. Les LoRA es <b>combinen</b> encadenant nodes Load LoRA; els efectes se sumen, així que baixa cada força (0,6–0,8) quan en combinis.', 'Una LoRA de SD 1.5 no encaja en un modelo SDXL: ComfyUI la carga pero escribe “lora key not loaded” y no cambia nada. Mira el modelo base en la página de descarga. Las LoRA se <b>combinan</b> encadenando nodos Load LoRA; los efectos se suman, así que baja cada fuerza (0,6–0,8) cuando combines.'),
        how: [L('Load Checkpoint › sd_xl_base_1.0 › run: read the log at the bottom.', 'Load Checkpoint › sd_xl_base_1.0 › executa: llegeix el registre de sota.', 'Load Checkpoint › sd_xl_base_1.0 › ejecuta: lee el registro de abajo.'), L('Back to dreamshaper_8. Select Load LoRA, <kbd>Ctrl C</kbd> <kbd>Ctrl V</kbd>, choose watercolor_sd15.', 'Torna a dreamshaper_8. Selecciona Load LoRA, <kbd>Ctrl C</kbd> <kbd>Ctrl V</kbd>, tria watercolor_sd15.', 'Vuelve a dreamshaper_8. Selecciona Load LoRA, <kbd>Ctrl C</kbd> <kbd>Ctrl V</kbd>, elige watercolor_sd15.'), L('First LoRA → second LoRA (model and clip) → KSampler and the prompts. Add “wtrcolor” and run.', 'Primera LoRA → segona LoRA (model i clip) → KSampler i els prompts. Afegeix “wtrcolor” i executa.', 'Primera LoRA → segunda LoRA (model y clip) → KSampler y los prompts. Añade “wtrcolor” y ejecuta.')],
        note: L('Too many LoRAs at strength 1 fight each other: muddy colours and broken shapes.', 'Massa LoRA a força 1 es barallen: colors bruts i formes trencades.', 'Demasiadas LoRA a fuerza 1 se pelean: colores sucios y formas rotas.'),
        starter: () => G.lora(), solution: G.twoLoras,
        goals: [goal(L('You saw “lora key not loaded”', 'Has vist “lora key not loaded”', 'Has visto “lora key not loaded”'), (g, c) => c.flags.loraWarn), goal(L('Two LoRAs chained, feeding the KSampler', 'Dues LoRA encadenades que alimenten el KSampler', 'Dos LoRA encadenadas que alimentan el KSampler'), (g, c) => runs(c).some(r => r.arch === 'SD1.5' && r.loras.filter(l => l.strength > 0).length >= 2))],
      },
    ],
  },
  {
    id: 'controlnet', name: L('ControlNet', 'ControlNet', 'ControlNet'), sub: L('Canny · strength · timing', 'Canny · força · temps', 'Canny · fuerza · tiempo'),
    steps: [
      {
        title: L('Prepare the control image', 'Prepara la imatge de control', 'Prepara la imagen de control'),
        task: L('Load pose_jump.png, pass it through Canny and look at the edges with Preview Image.', 'Carrega pose_jump.png, passa-la per Canny i mira les vores amb Preview Image.', 'Carga pose_jump.png, pásala por Canny y mira los bordes con Preview Image.'),
        concept: L('A LoRA changes the <i>style</i>; a <b>ControlNet</b> controls the <i>composition</i>: shapes, pose, perspective. It does not read a normal photo: it reads a <b>control map</b>. A <b>preprocessor</b> makes it: Canny draws the edges, Depth makes a depth map, OpenPose draws a skeleton. Each ControlNet model needs its own kind of map.', 'Una LoRA canvia l’<i>estil</i>; una <b>ControlNet</b> controla la <i>composició</i>: formes, postura, perspectiva. No llegeix una foto normal: llegeix un <b>mapa de control</b>. El fa un <b>preprocessador</b>: Canny dibuixa les vores, Depth fa un mapa de profunditat, OpenPose dibuixa un esquelet. Cada model de ControlNet necessita el seu tipus de mapa.', 'Una LoRA cambia el <i>estilo</i>; una <b>ControlNet</b> controla la <i>composición</i>: formas, postura, perspectiva. No lee una foto normal: lee un <b>mapa de control</b>. Lo hace un <b>preprocesador</b>: Canny dibuja los bordes, Depth hace un mapa de profundidad, OpenPose dibuja un esqueleto. Cada modelo de ControlNet necesita su tipo de mapa.'),
        how: [L('Add <b>Load Image</b> › image: pose_jump.png.', 'Afegeix <b>Load Image</b> › image: pose_jump.png.', 'Añade <b>Load Image</b> › image: pose_jump.png.'), L('Add <b>Canny</b> and <b>Preview Image</b>: Load Image → Canny → Preview Image.', 'Afegeix <b>Canny</b> i <b>Preview Image</b>: Load Image → Canny → Preview Image.', 'Añade <b>Canny</b> y <b>Preview Image</b>: Load Image → Canny → Preview Image.'), L('Run. Lower low_threshold for more edges, raise it for fewer.', 'Executa. Baixa low_threshold per tenir més vores, puja’l per tenir-ne menys.', 'Ejecuta. Baja low_threshold para tener más bordes, súbelo para tener menos.')],
        note: L('Canny is a core node. Depth and OpenPose preprocessors come from the custom node pack <i>comfyui_controlnet_aux</i>.', 'Canny és un node del nucli. Els preprocessadors Depth i OpenPose són del paquet de custom nodes <i>comfyui_controlnet_aux</i>.', 'Canny es un nodo del núcleo. Los preprocesadores Depth y OpenPose son del paquete de custom nodes <i>comfyui_controlnet_aux</i>.'),
        starter: G.fixedSeed, solution: G.canny,
        goals: [goal(L('Load Image → Canny', 'Load Image → Canny', 'Load Image → Canny'), g => N(g, 'Canny').some(c => srcType(g, c.id, 'image') === 'LoadImage')), goal(L('You ran it and saw the edges', 'L’has executat i has vist les vores', 'Lo has ejecutado y has visto los bordes'), (g, c) => c.flags.cannySeen)],
      },
      {
        title: L('Apply the ControlNet', 'Aplica la ControlNet', 'Aplica la ControlNet'),
        task: L('Add Load ControlNet Model (canny) and Apply ControlNet between the prompts and the KSampler, with the Canny map as image.', 'Afegeix Load ControlNet Model (canny) i Apply ControlNet entre els prompts i el KSampler, amb el mapa Canny com a image.', 'Añade Load ControlNet Model (canny) y Apply ControlNet entre los prompts y el KSampler, con el mapa Canny como image.'),
        concept: L('Apply ControlNet works on the <b>conditioning</b>: it takes the positive and negative, adds the control map, and gives them back. So it sits on the orange wires, between CLIP Text Encode and the KSampler. The prompt still decides <i>what</i> (a blue robot, a desert); the map decides <i>where and with which shape</i>.', 'Apply ControlNet treballa sobre el <b>conditioning</b>: agafa el positiu i el negatiu, hi afegeix el mapa de control i els torna. Per això va als cables taronja, entre CLIP Text Encode i el KSampler. El prompt continua decidint <i>què</i> (un robot blau, un desert); el mapa decideix <i>on i amb quina forma</i>.', 'Apply ControlNet trabaja sobre el <b>conditioning</b>: coge el positivo y el negativo, les añade el mapa de control y los devuelve. Por eso va en los cables naranja, entre CLIP Text Encode y el KSampler. El prompt sigue decidiendo <i>qué</i> (un robot azul, un desierto); el mapa decide <i>dónde y con qué forma</i>.'),
        how: [L('Add <b>Load ControlNet Model</b> (control_v11p_sd15_canny) and <b>Apply ControlNet</b>.', 'Afegeix <b>Load ControlNet Model</b> (control_v11p_sd15_canny) i <b>Apply ControlNet</b>.', 'Añade <b>Load ControlNet Model</b> (control_v11p_sd15_canny) y <b>Apply ControlNet</b>.'), L('Positive and negative prompts → Apply ControlNet; its positive and negative → KSampler.', 'Prompts positiu i negatiu → Apply ControlNet; el seu positive i negative → KSampler.', 'Prompts positivo y negativo → Apply ControlNet; su positive y negative → KSampler.'), L('control_net from the loader, image from Canny. Write a prompt (e.g. <i>a blue robot in the desert</i>) and run.', 'control_net des del loader, image des de Canny. Escriu un prompt (p. ex. <i>a blue robot in the desert</i>) i executa.', 'control_net desde el loader, image desde Canny. Escribe un prompt (p. ej. <i>a blue robot in the desert</i>) y ejecuta.')],
        note: L('The vae input of Apply ControlNet is optional: some newer ControlNets need it.', 'L’entrada vae d’Apply ControlNet és opcional: algunes ControlNet noves la necessiten.', 'La entrada vae de Apply ControlNet es opcional: algunas ControlNet nuevas la necesitan.'),
        starter: G.canny, solution: () => G.control(),
        goals: [goal(L('The KSampler gets its conditioning from Apply ControlNet', 'El KSampler rep el conditioning d’Apply ControlNet', 'El KSampler recibe el conditioning de Apply ControlNet'), g => { const s = sampler(g); return s && srcType(g, s.id, 'positive') === 'ControlNetApplyAdvanced' && srcType(g, s.id, 'negative') === 'ControlNetApplyAdvanced'; }), goal(L('The image comes from Canny', 'La image ve de Canny', 'La image viene de Canny'), g => N(g, 'ControlNetApplyAdvanced').some(a => srcType(g, a.id, 'image') === 'Canny')), goal(L('The result follows the pose', 'El resultat segueix la postura', 'El resultado sigue la postura'), (g, c) => runs(c).some(r => r.control >= .6))],
      },
      {
        title: L('Strength, timing and the right map', 'Força, temps i el mapa adequat', 'Fuerza, tiempo y el mapa adecuado'),
        task: L('With the same seed, compare strength 0.3 and 1, run once with end_percent 0.4, and once with the depth model on the Canny map.', 'Amb el mateix seed, compara strength 0,3 i 1, executa una vegada amb end_percent 0,4 i una amb el model depth sobre el mapa Canny.', 'Con el mismo seed, compara strength 0,3 y 1, ejecuta una vez con end_percent 0,4 y una con el modelo depth sobre el mapa Canny.'),
        concept: L('<b>strength</b>: how strictly the shape is followed. <b>start_percent / end_percent</b>: during which part of the sampling the ControlNet acts. The composition is decided in the first steps, so ending at 0.4 keeps the pose but leaves the details free. A canny map in a depth model is the <b>wrong map</b>: the result barely follows it.', '<b>strength</b>: com d’estrictament se segueix la forma. <b>start_percent / end_percent</b>: durant quina part del mostreig actua la ControlNet. La composició es decideix als primers steps: acabar a 0,4 manté la postura però deixa els detalls lliures. Un mapa canny en un model depth és el <b>mapa equivocat</b>: el resultat gairebé no el segueix.', '<b>strength</b>: con qué rigor se sigue la forma. <b>start_percent / end_percent</b>: durante qué parte del muestreo actúa la ControlNet. La composición se decide en los primeros steps: terminar en 0,4 mantiene la postura pero deja los detalles libres. Un mapa canny en un modelo depth es el <b>mapa equivocado</b>: el resultado casi no lo sigue.'),
        how: [L('strength <b>0.3</b> › run · <b>1</b> › run.', 'strength <b>0,3</b> › executa · <b>1</b> › executa.', 'strength <b>0,3</b> › ejecuta · <b>1</b> › ejecuta.'), L('strength 1, end_percent <b>0.4</b> › run.', 'strength 1, end_percent <b>0,4</b> › executa.', 'strength 1, end_percent <b>0,4</b> › ejecuta.'), L('control_net_name <b>control_v11f1p_sd15_depth</b> › run, then back to canny.', 'control_net_name <b>control_v11f1p_sd15_depth</b> › executa, i torna a canny.', 'control_net_name <b>control_v11f1p_sd15_depth</b> › ejecuta, y vuelve a canny.')],
        note: L('An SD 1.5 ControlNet on SDXL stops with “mat1 and mat2 shapes cannot be multiplied”: the classic sign of mixed model families.', 'Una ControlNet de SD 1.5 sobre SDXL s’atura amb “mat1 and mat2 shapes cannot be multiplied”: el senyal clàssic de famílies de models barrejades.', 'Una ControlNet de SD 1.5 sobre SDXL se detiene con “mat1 and mat2 shapes cannot be multiplied”: la señal clásica de familias de modelos mezcladas.'),
        starter: () => G.control(), solution: () => G.control(),
        goals: [goal(L('strength ≤ 0.4 and 1 with the same seed', 'strength ≤ 0,4 i 1 amb el mateix seed', 'strength ≤ 0,4 y 1 con el mismo seed'), (g, c) => runs(c).some(a => a.ctlStrength != null && a.ctlStrength <= .4 && runs(c).some(b => same(a, b) && b.ctlStrength >= .95))), goal(L('A run with end_percent ≤ 0.5', 'Una execució amb end_percent ≤ 0,5', 'Una ejecución con end_percent ≤ 0,5'), (g, c) => runs(c).some(r => r.ctlEnd != null && r.ctlEnd <= .5)), goal(L('A run with the depth model on a canny map', 'Una execució amb el model depth sobre un mapa canny', 'Una ejecución con el modelo depth sobre un mapa canny'), (g, c) => runs(c).some(r => r.ctlKind === 'depth'))],
      },
    ],
  },
  {
    id: 'habits', name: L('Workflow habits', 'Hàbits de treball', 'Hábitos de trabajo'), sub: L('bypass · groups · save', 'bypass · grups · desar', 'bypass · grupos · guardar'),
    steps: [
      {
        title: L('Bypass and mute', 'Bypass i mute', 'Bypass y mute'),
        task: L('Bypass the LoRA with Ctrl B and run. Then mute the Preview Image with Ctrl M and run again.', 'Fes bypass de la LoRA amb Ctrl B i executa. Després silencia el Preview Image amb Ctrl M i torna a executar.', 'Haz bypass de la LoRA con Ctrl B y ejecuta. Después silencia el Preview Image con Ctrl M y vuelve a ejecutar.'),
        concept: L('<b>Bypass</b> (<kbd>Ctrl B</kbd>, purple) lets the data pass through a node as if it were not there: perfect to compare with and without a LoRA. <b>Mute</b> (<kbd>Ctrl M</kbd>, faded) removes the node from the run: whatever depends on it does not run either. Nothing is deleted, and you switch it back with the same keys.', 'El <b>bypass</b> (<kbd>Ctrl B</kbd>, lila) deixa passar les dades a través d’un node com si no hi fos: perfecte per comparar amb i sense una LoRA. El <b>mute</b> (<kbd>Ctrl M</kbd>, apagat) treu el node de l’execució: el que en depèn tampoc s’executa. No s’esborra res, i es torna a activar amb les mateixes tecles.', 'El <b>bypass</b> (<kbd>Ctrl B</kbd>, lila) deja pasar los datos a través de un nodo como si no estuviera: perfecto para comparar con y sin una LoRA. El <b>mute</b> (<kbd>Ctrl M</kbd>, apagado) quita el nodo de la ejecución: lo que depende de él tampoco se ejecuta. No se borra nada, y se vuelve a activar con las mismas teclas.'),
        how: [L('Click Load LoRA, press <kbd>Ctrl B</kbd>, run: the image has no pixel art.', 'Clica Load LoRA, prem <kbd>Ctrl B</kbd>, executa: la imatge ja no té pixel art.', 'Haz clic en Load LoRA, pulsa <kbd>Ctrl B</kbd>, ejecuta: la imagen ya no tiene pixel art.'), L('<kbd>Ctrl B</kbd> again to bring it back.', '<kbd>Ctrl B</kbd> una altra vegada per tornar-la a activar.', '<kbd>Ctrl B</kbd> otra vez para volver a activarla.'), L('Click Preview Image, <kbd>Ctrl M</kbd>, run.', 'Clica Preview Image, <kbd>Ctrl M</kbd>, executa.', 'Haz clic en Preview Image, <kbd>Ctrl M</kbd>, ejecuta.')],
        note: L('The selection toolbar above a node has the same bypass button, and a colour picker to organise big workflows.', 'La barra de selecció de sobre d’un node té el mateix botó de bypass, i un selector de color per organitzar workflows grans.', 'La barra de selección de encima de un nodo tiene el mismo botón de bypass, y un selector de color para organizar workflows grandes.'),
        starter: () => wire(add(G.lora(), makeNode('PreviewImage', 1460, 560, {}, 'preview')), [['decode', 0, 'preview', 'images']]), solution: () => { const g = wire(add(G.lora(), makeNode('PreviewImage', 1460, 560, {}, 'preview')), [['decode', 0, 'preview', 'images']]); g.nodes.find(n => n.id === 'lora').mode = 4; g.nodes.find(n => n.id === 'preview').mode = 2; return g; },
        goals: [goal(L('Ran with a bypassed LoRA', 'Executat amb una LoRA en bypass', 'Ejecutado con una LoRA en bypass'), (g, c) => c.flags.ranBypass), goal(L('Ran with a muted node', 'Executat amb un node silenciat', 'Ejecutado con un nodo silenciado'), (g, c) => c.flags.ranMute)],
      },
      {
        title: L('Groups and saving', 'Grups i desar', 'Grupos y guardar'),
        task: L('Select the three loaders and prompts, group them with Ctrl G, rename the group, and save the workflow with Ctrl S.', 'Selecciona els carregadors i els prompts, agrupa’ls amb Ctrl G, canvia el nom del grup i desa el workflow amb Ctrl S.', 'Selecciona los cargadores y los prompts, agrúpalos con Ctrl G, cambia el nombre del grupo y guarda el workflow con Ctrl S.'),
        concept: L('Big workflows need order: <b>groups</b> are coloured frames that move their nodes together. A workflow is a <b>.json</b> file; saving it keeps your graph, your values and your prompts. The Workflows panel (<kbd>W</kbd>) lists the saved ones.', 'Els workflows grans necessiten ordre: els <b>grups</b> són marcs de color que mouen els seus nodes junts. Un workflow és un fitxer <b>.json</b>; desar-lo guarda el graf, els valors i els prompts. El panell Workflows (<kbd>W</kbd>) mostra els desats.', 'Los workflows grandes necesitan orden: los <b>grupos</b> son marcos de color que mueven sus nodos juntos. Un workflow es un archivo <b>.json</b>; guardarlo conserva el grafo, los valores y los prompts. El panel Workflows (<kbd>W</kbd>) muestra los guardados.'),
        how: [L('<kbd>Ctrl</kbd> + drag on the empty canvas to box-select (or <kbd>Ctrl</kbd>/<kbd>Shift</kbd> + click each node).', '<kbd>Ctrl</kbd> + arrossegar al llenç buit per seleccionar amb un rectangle (o <kbd>Ctrl</kbd>/<kbd>Shift</kbd> + clic a cada node).', '<kbd>Ctrl</kbd> + arrastrar en el lienzo vacío para seleccionar con un rectángulo (o <kbd>Ctrl</kbd>/<kbd>Shift</kbd> + clic en cada nodo).'), L('<kbd>Ctrl G</kbd> makes the group; double-click its title to rename it.', '<kbd>Ctrl G</kbd> crea el grup; fes doble clic al títol per canviar-li el nom.', '<kbd>Ctrl G</kbd> crea el grupo; haz doble clic en su título para cambiarle el nombre.'), L('<kbd>Ctrl S</kbd> and give it a name.', '<kbd>Ctrl S</kbd> i posa-li un nom.', '<kbd>Ctrl S</kbd> y ponle un nombre.')],
        note: L('Drag a group by its title bar and every node inside moves with it.', 'Arrossega un grup per la barra del títol i tots els nodes de dins el segueixen.', 'Arrastra un grupo por su barra de título y todos los nodos de dentro lo siguen.'),
        starter: () => G.lora(), solution: () => { const g = G.lora(); g.groups = [{ title: 'Models', x: 0, y: 150, w: 900, h: 600, color: '#3f789e' }]; return g; },
        goals: [goal(L('There is a group', 'Hi ha un grup', 'Hay un grupo'), g => (g.groups || []).length > 0), goal(L('The group has its own name', 'El grup té un nom propi', 'El grupo tiene un nombre propio'), g => (g.groups || []).some(x => x.title && x.title !== 'Group')), goal(L('Saved with <kbd>Ctrl S</kbd>', 'Desat amb <kbd>Ctrl S</kbd>', 'Guardado con <kbd>Ctrl S</kbd>'), (g, c) => c.flags.saved)],
      },
      {
        title: L('The workflow lives in the image', 'El workflow viu dins la imatge', 'El workflow vive dentro de la imagen'),
        task: L('Load the workflow of one of your earlier images from the Queue panel.', 'Carrega el workflow d’una de les teves imatges anteriors des del panell Queue.', 'Carga el workflow de una de tus imágenes anteriores desde el panel Queue.'),
        concept: L('Every PNG that ComfyUI saves carries the whole workflow inside it, as metadata. Drag a ComfyUI image onto the canvas and you get the exact graph, prompts and seed that made it. It is how people share workflows, and how you go back to an image you liked.', 'Cada PNG que desa ComfyUI porta tot el workflow a dins, com a metadades. Arrossega una imatge de ComfyUI al llenç i tindràs exactament el graf, els prompts i el seed que la van fer. És com es comparteixen workflows, i com tornes a una imatge que t’havia agradat.', 'Cada PNG que guarda ComfyUI lleva dentro todo el workflow, como metadatos. Arrastra una imagen de ComfyUI al lienzo y tendrás exactamente el grafo, los prompts y el seed que la hicieron. Es como se comparten workflows, y como vuelves a una imagen que te gustó.'),
        how: [L('<kbd>Q</kbd> to open Queue. Click an earlier thumbnail.', '<kbd>Q</kbd> per obrir Queue. Clica una miniatura anterior.', '<kbd>Q</kbd> para abrir Queue. Haz clic en una miniatura anterior.'), L('<b>Load Workflow</b>: the graph comes back, with its seed.', '<b>Load Workflow</b>: el graf torna, amb el seu seed.', '<b>Load Workflow</b>: el grafo vuelve, con su seed.')],
        note: L('Images shared on social networks usually lose these metadata: keep the original PNG.', 'Les imatges compartides a les xarxes socials normalment perden aquestes metadades: guarda el PNG original.', 'Las imágenes compartidas en redes sociales normalmente pierden estos metadatos: guarda el PNG original.'),
        starter: () => G.lora(), solution: () => G.lora(),
        goals: [goal(L('A workflow loaded from an image', 'Un workflow carregat des d’una imatge', 'Un workflow cargado desde una imagen'), (g, c) => c.flags.loadedFromImage)],
      },
    ],
  },
];
export const TEMPLATES = [
  { id: 'default', name: L('Text to Image (default)', 'Text a imatge (per defecte)', 'Texto a imagen (por defecto)'), make: G.base },
  { id: 'img2img', name: L('Image to Image', 'Imatge a imatge', 'Imagen a imagen'), make: G.img2img },
  { id: 'lora', name: L('LoRA', 'LoRA', 'LoRA'), make: () => G.lora() },
  { id: 'controlnet', name: L('ControlNet (Canny)', 'ControlNet (Canny)', 'ControlNet (Canny)'), make: () => G.control() },
];
export { G as GRAPHS };
