// Carrot Revolt Labs · Video & 3D Lab · stages, steps and live checklists.
// It runs on the ComfyUI Lab interface (../comfyui/app.js) and adds its own nodes and simulator (./nodes.js).
import { defaultGraph, makeNode, makeLink, connect } from '../comfyui/engine.js';
import { outputExtra as ox, findRecipe as fr, historyExtra as hx } from './nodes.js';
export const L = (en, ca, es) => ({ en, ca, es });

export const META = { key: 'carrot-revolt-comfy-video:', title: 'Video & 3D Lab', label: 'GENERATIVE IMAGE / COMFYUI · 08' };
export const outputExtra = ox, findRecipe = fr, historyExtra = hx;
export function resultExtra(h) {
  if (!h.sprite) return '';
  const v = h.video, dur = v ? Math.max(.4, v.seconds) : h.spriteN / 6;
  const cap = v ? `${v.frames} frames · ${v.fps} fps · ${v.seconds} s · ${v.w}×${v.h}` : `turntable · octree ${h.mesh.octree} · threshold ${h.mesh.threshold}`;
  return `<div class="vid" style="--n:${h.spriteN};--dur:${dur}s;--ar:${h.ar || '16/9'};background-image:url(${h.sprite})"></div><p class="vid-cap">${cap}</p>`;
}

/* ── Graph helpers ── */
const N = (g, type) => g.nodes.filter(n => n.type === type && n.mode === 0);
const from = (g, id, input) => { const l = g.links.find(x => x.to === id && x.input === input); return l ? g.nodes.find(n => n.id === l.from) : null; };
const goal = (text, test, optional = false) => ({ text, test, optional });
const add = (g, ...nodes) => { g.nodes.push(...nodes); return g; };
const wire = (g, list) => { for (const l of list) connect(g, makeLink(...l)); return g; };
const set = (g, id, k, v) => { g.nodes.find(n => n.id === id).widgets[k] = v; return g; };
const move = (g, id, x, y) => { const n = g.nodes.find(n => n.id === id); n.x = x; n.y = y; return g; };
const drop = (g, id) => { g.nodes = g.nodes.filter(n => n.id !== id); g.links = g.links.filter(l => l.from !== id && l.to !== id); return g; };
const vids = c => c.history.filter(h => h.video), meshes = c => c.history.filter(h => h.mesh);
const ran = (c, f) => vids(c).some(f);
const T2V = 'wan2.1_t2v_1.3B_fp16.safetensors', T2V14 = 'wan2.1_t2v_14B_fp8_e4m3fn.safetensors', I2V = 'wan2.1_i2v_480p_14B_fp8_e4m3fn.safetensors', FLF = 'wan2.1_flf2v_720p_14B_fp8_e4m3fn.safetensors';
const HIGH = 'wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors', LOW = 'wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors';
const PROMPT = 'a cat walking in the snow, camera slowly zooms in, detailed';
const NEG = 'static, still picture, blurry, low quality, distorted';

/* ── Starters and solutions ── */
const G = {
  t2v: ({ unet = T2V, w = 832, h = 480, len = 33, text = PROMPT, steps = 30, fps = 16, still = false } = {}) => {
    const g = drop(drop(drop(defaultGraph(), 'ckpt'), 'latent'), 'save');
    set(g, 'pos', 'text', text); set(g, 'neg', 'text', NEG);
    for (const [k, v] of Object.entries({ steps, cfg: 6, sampler_name: 'uni_pc', scheduler: 'simple', control_after_generate: 'fixed' })) set(g, 'sampler', k, v);
    add(g, makeNode('UNETLoader', 26, 100, { unet_name: unet }, 'unet'), makeNode('ModelSamplingSD3', 430, 30, { shift: 8 }, 'ms'), makeNode('CLIPLoader', 26, 300, {}, 'clip'), makeNode('VAELoader', 26, 520, {}, 'vae'),
      still ? makeNode('EmptyLatentImage', 473, 609, { width: w, height: h }, 'latent') : makeNode('EmptyHunyuanLatentVideo', 473, 609, { width: w, height: h, length: len }, 'latent'), makeNode('SaveAnimatedWEBP', 1451, 189, { fps }, 'save'));
    return wire(g, [['unet', 0, 'ms', 'model'], ['ms', 0, 'sampler', 'model'], ['clip', 0, 'pos', 'clip'], ['clip', 0, 'neg', 'clip'], ['vae', 0, 'decode', 'vae'], ['latent', 0, 'sampler', 'latent_image'], ['decode', 0, 'save', 'images']]);
  },
  i2v: ({ unet = I2V, vision = true, text = 'the cat walks to the right, detailed' } = {}) => {
    const g = drop(G.t2v({ unet, text, len: 81 }), 'latent'); move(g, 'sampler', 1240, 186); move(g, 'decode', 1600, 188); move(g, 'save', 1850, 189);
    add(g, makeNode('LoadImage', 26, 760, { image: 'i2v_cat.png' }, 'img'), makeNode('WanImageToVideo', 860, 560, { length: 81 }, 'wan'));
    wire(g, [['pos', 0, 'wan', 'positive'], ['neg', 0, 'wan', 'negative'], ['vae', 0, 'wan', 'vae'], ['img', 0, 'wan', 'start_image'], ['wan', 0, 'sampler', 'positive'], ['wan', 1, 'sampler', 'negative'], ['wan', 2, 'sampler', 'latent_image']]);
    if (vision) { add(g, makeNode('CLIPVisionLoader', 420, 800, {}, 'cvl'), makeNode('CLIPVisionEncode', 420, 960, {}, 'cve')); wire(g, [['cvl', 0, 'cve', 'clip_vision'], ['img', 0, 'cve', 'image'], ['cve', 0, 'wan', 'clip_vision_output']]); }
    return g;
  },
  flf: () => {
    const g = drop(G.t2v({ unet: FLF, text: 'the cat walks from left to right, smooth motion, detailed', len: 81 }), 'latent'); move(g, 'sampler', 1240, 186); move(g, 'decode', 1600, 188); move(g, 'save', 1850, 189);
    add(g, makeNode('LoadImage', 26, 760, { image: 'i2v_cat.png' }, 'img'), makeNode('LoadImage', 26, 1180, { image: 'i2v_cat_end.png' }, 'img2'), makeNode('CLIPVisionLoader', 420, 800, {}, 'cvl'), makeNode('CLIPVisionEncode', 420, 960, {}, 'cve'), makeNode('WanFirstLastFrameToVideo', 860, 560, { length: 81 }, 'wan'));
    return wire(g, [['pos', 0, 'wan', 'positive'], ['neg', 0, 'wan', 'negative'], ['vae', 0, 'wan', 'vae'], ['img', 0, 'wan', 'start_image'], ['img2', 0, 'wan', 'end_image'], ['cvl', 0, 'cve', 'clip_vision'], ['img', 0, 'cve', 'image'], ['cve', 0, 'wan', 'clip_vision_start_image'], ['wan', 0, 'sampler', 'positive'], ['wan', 1, 'sampler', 'negative'], ['wan', 2, 'sampler', 'latent_image']]);
  },
  wan22: (first = HIGH, second = LOW) => {
    const g = drop(drop(G.t2v({ unet: first, len: 81 }), 'sampler'), 'ms'); drop(g, 'unet'); move(g, 'decode', 1620, 188); move(g, 'save', 1860, 189);
    const common = { noise_seed: 156680208700286, steps: 20, cfg: 3.5, sampler_name: 'euler', scheduler: 'simple' };
    add(g, makeNode('UNETLoader', 26, -60, { unet_name: first }, 'unetA'), makeNode('UNETLoader', 26, 120, { unet_name: second }, 'unetB'), makeNode('ModelSamplingSD3', 430, -120, { shift: 8 }, 'msA'), makeNode('ModelSamplingSD3', 430, 40, { shift: 8 }, 'msB'),
      makeNode('KSamplerAdvanced', 863, 186, { ...common, end_at_step: 10, return_with_leftover_noise: 'enable' }, 'a1'), makeNode('KSamplerAdvanced', 1240, 186, { ...common, add_noise: 'disable', start_at_step: 10 }, 'a2'));
    return wire(g, [['unetA', 0, 'msA', 'model'], ['unetB', 0, 'msB', 'model'], ['msA', 0, 'a1', 'model'], ['pos', 0, 'a1', 'positive'], ['neg', 0, 'a1', 'negative'], ['latent', 0, 'a1', 'latent_image'], ['msB', 0, 'a2', 'model'], ['pos', 0, 'a2', 'positive'], ['neg', 0, 'a2', 'negative'], ['a1', 0, 'a2', 'latent_image'], ['a2', 0, 'decode', 'samples']]);
  },
  h3dStart: () => { const g = { nodes: [makeNode('LoadImage', 26, 160, { image: 'toy_robot.png' }, 'img'), makeNode('PreviewImage', 420, 160, {}, 'pv')], links: [], groups: [] }; return wire(g, [['img', 0, 'pv', 'images']]); },
  h3d: ({ image = 'toy_robot.png', octree = 256, threshold = .6, rembg = false } = {}) => {
    const g = { nodes: [], links: [], groups: [] };
    add(g, makeNode('ImageOnlyCheckpointLoader', 26, 40, {}, 'ckpt'), makeNode('LoadImage', 26, 300, { image }, 'img'), makeNode('CLIPVisionEncode', 820, 320, {}, 'cve'), makeNode('Hunyuan3Dv2Conditioning', 820, 460, {}, 'cond'), makeNode('EmptyLatentHunyuan3Dv2', 820, 600, {}, 'latent'),
      makeNode('KSampler', 1180, 120, { steps: 30, cfg: 5, sampler_name: 'euler', scheduler: 'normal', control_after_generate: 'fixed' }, 'sampler'), makeNode('VAEDecodeHunyuan3D', 1540, 120, { octree_resolution: octree }, 'vdec'), makeNode('VoxelToMesh', 1540, 300, { threshold }, 'v2m'), makeNode('SaveGLB', 1860, 120, {}, 'glb'));
    let src = 'img'; if (rembg) { add(g, makeNode('ImageRemoveBackground', 420, 360, {}, 'rb')); wire(g, [['img', 0, 'rb', 'image']]); src = 'rb'; }
    return wire(g, [['ckpt', 1, 'cve', 'clip_vision'], [src, 0, 'cve', 'image'], ['cve', 0, 'cond', 'clip_vision_output'], ['ckpt', 0, 'sampler', 'model'], ['cond', 0, 'sampler', 'positive'], ['cond', 1, 'sampler', 'negative'], ['latent', 0, 'sampler', 'latent_image'], ['sampler', 0, 'vdec', 'samples'], ['ckpt', 2, 'vdec', 'vae'], ['vdec', 0, 'v2m', 'voxel'], ['v2m', 0, 'glb', 'mesh']]);
  },
};

export const UI = {
  headline: L('Pictures that move, <span>pictures with a back.</span>', 'Imatges que es mouen, <span>imatges amb esquena.</span>', 'Imágenes que se mueven, <span>imágenes con espalda.</span>'),
  lead: L('The same graph thinking, two more dimensions. Video with Wan: latents with frames, frame rate and duration, prompts that describe motion and camera, image to video, first and last frame, memory and length limits, and the two experts of Wan 2.2. Then 3D: from one picture to a mesh, with a clean input and the right resolution.', 'La mateixa manera de pensar en grafs, dues dimensions més. Vídeo amb Wan: latents amb frames, fps i durada, prompts que descriuen moviment i càmera, imatge a vídeo, primer i últim frame, límits de memòria i de llargada, i els dos experts de Wan 2.2. Després 3D: d’una imatge a una malla, amb una entrada neta i la resolució bona.', 'La misma forma de pensar en grafos, dos dimensiones más. Vídeo con Wan: latentes con frames, fps y duración, prompts que describen movimiento y cámara, imagen a vídeo, primer y último frame, límites de memoria y de duración, y los dos expertos de Wan 2.2. Luego 3D: de una imagen a una malla, con una entrada limpia y la resolución buena.'),
  loraVsCn: L('Video numbers', 'Números del vídeo', 'Números del vídeo'),
  type_CLIP_VISION: L('an image encoder', 'un encoder d’imatges', 'un encoder de imágenes'), type_CLIP_VISION_OUTPUT: L('a picture, encoded', 'una imatge, codificada', 'una imagen, codificada'), type_VOXEL: L('a 3D grid of occupancy', 'una graella 3D d’ocupació', 'una rejilla 3D de ocupación'), type_MESH: L('triangles you can export', 'triangles que pots exportar', 'triángulos que puedes exportar'),
};
const T3 = (h, rows, foot) => `<table class="c-cmp"><tr><th></th><th>${h[0]}</th><th>${h[1]}</th></tr>${rows.map(r => `<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</table><p>${foot}</p>`;
UI.loraVsCnBody = L(
  T3(['Wan 2.1', 'Note'], [['<b>Frames</b>', '81 (4n + 1)', 'more and it loops or drifts'], ['<b>fps</b>', '16', 'saving at 30 plays it fast'], ['<b>Size</b>', '832 × 480 / 1280 × 720', '1.3B: only 480p'], ['<b>Memory</b>', 'pixels × frames', 'smaller model, fewer frames']], 'Duration = frames ÷ fps. 81 frames at 16 fps = 5 seconds.'),
  T3(['Wan 2.1', 'Nota'], [['<b>Frames</b>', '81 (4n + 1)', 'més i es repeteix o es deforma'], ['<b>fps</b>', '16', 'desar a 30 el fa anar de pressa'], ['<b>Mida</b>', '832 × 480 / 1280 × 720', '1.3B: només 480p'], ['<b>Memòria</b>', 'píxels × frames', 'model més petit, menys frames']], 'Durada = frames ÷ fps. 81 frames a 16 fps = 5 segons.'),
  T3(['Wan 2.1', 'Nota'], [['<b>Frames</b>', '81 (4n + 1)', 'más y se repite o se deforma'], ['<b>fps</b>', '16', 'guardar a 30 lo acelera'], ['<b>Tamaño</b>', '832 × 480 / 1280 × 720', '1.3B: solo 480p'], ['<b>Memoria</b>', 'píxeles × frames', 'modelo más pequeño, menos frames']], 'Duración = frames ÷ fps. 81 frames a 16 fps = 5 segundos.'));

export const DOCS = {
  EmptyHunyuanLatentVideo: { short: L('An empty video latent: width, height and frames.', 'Un latent de vídeo buit: amplada, alçada i frames.', 'Un latente de vídeo vacío: ancho, alto y frames.'), long: L('Used for text-to-video with Wan and Hunyuan Video. length is the number of frames, in steps of 4 plus 1 (33, 49, 81…).', 'Es fa servir per al text a vídeo amb Wan i Hunyuan Video. length és el nombre de frames, de 4 en 4 més 1 (33, 49, 81…).', 'Se usa para el texto a vídeo con Wan y Hunyuan Video. length es el número de frames, de 4 en 4 más 1 (33, 49, 81…).') },
  SaveAnimatedWEBP: { short: L('Saves the frames as an animation.', 'Desa els frames com una animació.', 'Guarda los frames como una animación.'), long: L('fps decides the playback speed: it should match the model (16 for Wan 2.1). For MP4, use Create Video + Save Video.', 'fps decideix la velocitat de reproducció: ha de coincidir amb el model (16 per a Wan 2.1). Per a MP4, fes servir Create Video + Save Video.', 'fps decide la velocidad de reproducción: debe coincidir con el modelo (16 para Wan 2.1). Para MP4, usa Create Video + Save Video.') },
  WanImageToVideo: { short: L('Starts a Wan video from a picture.', 'Comença un vídeo de Wan a partir d’una imatge.', 'Empieza un vídeo de Wan a partir de una imagen.'), long: L('Adds the start image (and its CLIP Vision encoding) to the conditioning and returns the video latent. Needs an image-to-video model (i2v).', 'Afegeix la imatge inicial (i la seva codificació CLIP Vision) al conditioning i torna el latent de vídeo. Necessita un model d’imatge a vídeo (i2v).', 'Añade la imagen inicial (y su codificación CLIP Vision) al conditioning y devuelve el latente de vídeo. Necesita un modelo de imagen a vídeo (i2v).') },
  WanFirstLastFrameToVideo: { short: L('A video between a first and a last picture.', 'Un vídeo entre una primera i una última imatge.', 'Un vídeo entre una primera y una última imagen.'), long: L('With the flf2v model, the video starts at one picture and ends at the other: a controlled transition.', 'Amb el model flf2v, el vídeo comença en una imatge i acaba en l’altra: una transició controlada.', 'Con el modelo flf2v, el vídeo empieza en una imagen y acaba en la otra: una transición controlada.') },
  ModelSamplingSD3: { short: L('Sets the noise shift of the model.', 'Fixa el shift del soroll del model.', 'Fija el shift del ruido del modelo.'), long: L('Wan workflows use a shift of about 8: more steps are spent on the big shapes and the motion.', 'Els workflows de Wan fan servir un shift d’uns 8: es dediquen més steps a les formes grans i al moviment.', 'Los workflows de Wan usan un shift de unos 8: se dedican más steps a las formas grandes y al movimiento.') },
  VAEDecodeHunyuan3D: { short: L('Turns a 3D latent into a voxel grid.', 'Converteix un latent 3D en una graella de vòxels.', 'Convierte un latente 3D en una rejilla de vóxeles.'), long: L('octree_resolution is the detail of the grid: 256 is a good default, 384–512 for small details (slower, more memory).', 'octree_resolution és el detall de la graella: 256 és un bon valor per defecte, 384–512 per a detalls petits (més lent, més memòria).', 'octree_resolution es el detalle de la rejilla: 256 es un buen valor por defecto, 384–512 para detalles pequeños (más lento, más memoria).') },
  VoxelToMesh: { short: L('Builds triangles from the voxels.', 'Construeix triangles a partir dels vòxels.', 'Construye triángulos a partir de los vóxeles.'), long: L('threshold decides where the surface is: lower makes the object fatter and blobby, higher thinner, with holes.', 'threshold decideix on és la superfície: més baix fa l’objecte més gros i tou, més alt més prim, amb forats.', 'threshold decide dónde está la superficie: más bajo hace el objeto más gordo y blando, más alto más delgado, con agujeros.') },
  SaveGLB: { short: L('Saves the mesh as a .glb file.', 'Desa la malla com a fitxer .glb.', 'Guarda la malla como archivo .glb.'), long: L('GLB opens in Blender, game engines and web viewers. The mesh comes without UVs or a clean topology: plan to retopologise.', 'El GLB s’obre a Blender, motors de joc i visors web. La malla no té UVs ni una topologia neta: compta a fer-ne la retopologia.', 'El GLB se abre en Blender, motores de juego y visores web. La malla no tiene UVs ni una topología limpia: cuenta con hacer la retopología.') },
  ImageRemoveBackground: { short: L('Cuts the subject out of its background.', 'Retalla el subjecte del fons.', 'Recorta el sujeto del fondo.'), long: L('Custom node (rembg). Image-to-3D models build everything they see: remove the background first.', 'Custom node (rembg). Els models d’imatge a 3D construeixen tot el que veuen: treu el fons primer.', 'Custom node (rembg). Los modelos de imagen a 3D construyen todo lo que ven: quita el fondo primero.') },
};

export const STAGES = [
  {
    id: 't2v', name: L('Text to video', 'Text a vídeo', 'Texto a vídeo'), sub: L('Frames · fps · motion', 'Frames · fps · moviment', 'Frames · fps · movimiento'),
    steps: [
      {
        title: L('A latent with time', 'Un latent amb temps', 'Un latente con tiempo'),
        task: L('This Wan graph uses an image latent: it makes one frame. Replace Empty Latent Image with EmptyHunyuanLatentVideo (832 × 480, length 33) and run.', 'Aquest graf de Wan fa servir un latent d’imatge: fa un sol frame. Substitueix Empty Latent Image per EmptyHunyuanLatentVideo (832 × 480, length 33) i executa.', 'Este grafo de Wan usa un latente de imagen: hace un solo frame. Sustituye Empty Latent Image por EmptyHunyuanLatentVideo (832 × 480, length 33) y ejecuta.'),
        concept: L('A video model is an image model with one more dimension: <b>time</b>. Its latent has width, height and <b>frames</b>, and the model denoises all of them together, so the frames agree with each other. Wan comes in parts like Flux: the diffusion model, the umt5 text encoder (Load CLIP, type wan), its VAE, and a <b>ModelSamplingSD3</b> with shift 8. VAE Decode returns a batch of frames, and a video saver turns them into an animation.', 'Un model de vídeo és un model d’imatge amb una dimensió més: el <b>temps</b>. El seu latent té amplada, alçada i <b>frames</b>, i el model els treu el soroll a tots alhora, de manera que els frames lliguen entre ells. Wan ve per parts com Flux: el model de difusió, el text encoder umt5 (Load CLIP, type wan), el seu VAE, i un <b>ModelSamplingSD3</b> amb shift 8. VAE Decode torna una tanda de frames, i un node de desar vídeo els converteix en una animació.', 'Un modelo de vídeo es un modelo de imagen con una dimensión más: el <b>tiempo</b>. Su latente tiene ancho, alto y <b>frames</b>, y el modelo les quita el ruido a todos a la vez, de modo que los frames encajan entre sí. Wan viene por partes como Flux: el modelo de difusión, el text encoder umt5 (Load CLIP, type wan), su VAE, y un <b>ModelSamplingSD3</b> con shift 8. VAE Decode devuelve una tanda de frames, y un nodo de guardar vídeo los convierte en una animación.'),
        how: [L('Run: one frame.', 'Executa: un sol frame.', 'Ejecuta: un solo frame.'), L('Search <b>EmptyHunyuanLatentVideo</b>: 832 × 480, length <b>33</b>. Its LATENT → latent_image of the KSampler.', 'Cerca <b>EmptyHunyuanLatentVideo</b>: 832 × 480, length <b>33</b>. El seu LATENT → latent_image del KSampler.', 'Busca <b>EmptyHunyuanLatentVideo</b>: 832 × 480, length <b>33</b>. Su LATENT → latent_image del KSampler.'), L('Run, and open the result in the Queue: it plays.', 'Executa, i obre el resultat a la Queue: es reprodueix.', 'Ejecuta, y abre el resultado en la Queue: se reproduce.')],
        note: L('The 1.3B Wan model runs on 8 GB cards; the 14B ones need 16 GB or more (or GGUF versions).', 'El model Wan 1.3B funciona en targetes de 8 GB; els de 14B necessiten 16 GB o més (o versions GGUF).', 'El modelo Wan 1.3B funciona en tarjetas de 8 GB; los de 14B necesitan 16 GB o más (o versiones GGUF).'),
        starter: () => G.t2v({ still: true }), solution: () => G.t2v(),
        goals: [goal(L('A video latent feeds the KSampler', 'Un latent de vídeo alimenta el KSampler', 'Un latente de vídeo alimenta el KSampler'), g => N(g, 'KSampler').some(s => from(g, s.id, 'latent_image')?.type === 'EmptyHunyuanLatentVideo')), goal(L('A video with more than one frame', 'Un vídeo de més d’un frame', 'Un vídeo de más de un frame'), (g, c) => ran(c, h => h.video.frames > 1))],
      },
      {
        title: L('Frames, fps and seconds', 'Frames, fps i segons', 'Frames, fps y segundos'),
        task: L('Make a 5-second video: length 81 and save at 16 fps. Then try saving at 30 fps and compare the speed.', 'Fes un vídeo de 5 segons: length 81 i desa a 16 fps. Després prova de desar a 30 fps i compara la velocitat.', 'Haz un vídeo de 5 segundos: length 81 y guarda a 16 fps. Luego prueba a guardar a 30 fps y compara la velocidad.'),
        concept: L('<b>Duration = frames ÷ fps.</b> Wan 2.1 was trained on clips of <b>81 frames at 16 fps</b>: 5 seconds. The length goes in steps of 4 plus one (33, 49, 65, 81) because the video latent packs 4 frames in each step of time. The fps of the saver does not change the frames, only how fast they play: the same 81 frames at 30 fps last 2.7 seconds and everything moves too fast.', '<b>Durada = frames ÷ fps.</b> Wan 2.1 es va entrenar amb clips de <b>81 frames a 16 fps</b>: 5 segons. La llargada va de 4 en 4 més un (33, 49, 65, 81) perquè el latent de vídeo empaqueta 4 frames a cada pas de temps. Els fps del node de desar no canvien els frames, només com de ràpid es reprodueixen: els mateixos 81 frames a 30 fps duren 2.7 segons i tot es mou massa de pressa.', '<b>Duración = frames ÷ fps.</b> Wan 2.1 se entrenó con clips de <b>81 frames a 16 fps</b>: 5 segundos. La longitud va de 4 en 4 más uno (33, 49, 65, 81) porque el latente de vídeo empaqueta 4 frames en cada paso de tiempo. Los fps del nodo de guardar no cambian los frames, solo lo rápido que se reproducen: los mismos 81 frames a 30 fps duran 2.7 segundos y todo se mueve demasiado deprisa.'),
        how: [L('EmptyHunyuanLatentVideo › length <b>81</b>. SaveAnimatedWEBP › fps <b>16</b>. Run.', 'EmptyHunyuanLatentVideo › length <b>81</b>. SaveAnimatedWEBP › fps <b>16</b>. Executa.', 'EmptyHunyuanLatentVideo › length <b>81</b>. SaveAnimatedWEBP › fps <b>16</b>. Ejecuta.'), L('fps <b>30</b>, run: the same video, faster.', 'fps <b>30</b>, executa: el mateix vídeo, més ràpid.', 'fps <b>30</b>, ejecuta: el mismo vídeo, más rápido.'), L('Open both in the Queue.', 'Obre’ls tots dos a la Queue.', 'Ábrelos los dos en la Queue.')],
        note: L('To get smooth 30 fps from a 16 fps video, interpolate frames (custom nodes like RIFE / FILM) instead of changing the fps.', 'Per tenir 30 fps suaus a partir d’un vídeo de 16 fps, interpola frames (custom nodes com RIFE / FILM) en lloc de canviar els fps.', 'Para tener 30 fps suaves a partir de un vídeo de 16 fps, interpola frames (custom nodes como RIFE / FILM) en lugar de cambiar los fps.'),
        starter: () => G.t2v(), solution: () => G.t2v({ len: 81 }),
        goals: [goal(L('81 frames', '81 frames', '81 frames'), (g, c) => ran(c, h => h.video.frames === 81)), goal(L('Saved at 16 fps: 5 seconds', 'Desat a 16 fps: 5 segons', 'Guardado a 16 fps: 5 segundos'), (g, c) => ran(c, h => h.video.frames === 81 && h.video.fps === 16)), goal(L('Saw what 30 fps does', 'Has vist què fan 30 fps', 'Has visto qué hacen 30 fps'), (g, c) => ran(c, h => h.video.fps >= 24), true)],
      },
      {
        title: L('Describe the motion', 'Descriu el moviment', 'Describe el movimiento'),
        task: L('Run a prompt without motion. Then describe what moves (the cat walks) and what the camera does (slowly zooms in).', 'Executa un prompt sense moviment. Després descriu què es mou (el gat camina) i què fa la càmera (fa un zoom lent).', 'Ejecuta un prompt sin movimiento. Luego describe qué se mueve (el gato camina) y qué hace la cámara (hace un zoom lento).'),
        concept: L('A video prompt needs <b>verbs</b>. Describe the subject’s action (walks, runs, turns, jumps), how it moves (slowly, towards the camera) and the <b>camera</b> (zooms in, pans left, tracking shot). Without them you get a moving photograph. Put “static, still picture” in the negative prompt to push for motion. One clear action per clip works better than a story.', 'Un prompt de vídeo necessita <b>verbs</b>. Descriu l’acció del subjecte (camina, corre, gira, salta), com es mou (a poc a poc, cap a la càmera) i la <b>càmera</b> (fa zoom, panoràmica a l’esquerra, travelling). Sense això tens una fotografia que es mou. Posa “static, still picture” al prompt negatiu per empènyer el moviment. Una acció clara per clip funciona millor que una història.', 'Un prompt de vídeo necesita <b>verbos</b>. Describe la acción del sujeto (camina, corre, gira, salta), cómo se mueve (despacio, hacia la cámara) y la <b>cámara</b> (hace zoom, panorámica a la izquierda, travelling). Sin eso tienes una fotografía que se mueve. Pon “static, still picture” en el prompt negativo para empujar el movimiento. Una acción clara por clip funciona mejor que una historia.'),
        how: [L('Prompt: <b>a cat in the snow, detailed</b>. Run.', 'Prompt: <b>a cat in the snow, detailed</b>. Executa.', 'Prompt: <b>a cat in the snow, detailed</b>. Ejecuta.'), L('<b>a cat walking in the snow</b>. Run.', '<b>a cat walking in the snow</b>. Executa.', '<b>a cat walking in the snow</b>. Ejecuta.'), L('Add <b>camera slowly zooms in</b> (or pans left). Run.', 'Afegeix <b>camera slowly zooms in</b> (o pans left). Executa.', 'Añade <b>camera slowly zooms in</b> (o pans left). Ejecuta.')],
        note: L('Wan understands English and Chinese best; long, precise descriptions help.', 'Wan entén millor l’anglès i el xinès; les descripcions llargues i precises ajuden.', 'Wan entiende mejor el inglés y el chino; las descripciones largas y precisas ayudan.'),
        starter: () => G.t2v({ text: 'a cat in the snow, detailed' }), solution: () => G.t2v({ text: PROMPT }),
        goals: [goal(L('The subject moves', 'El subjecte es mou', 'El sujeto se mueve'), (g, c) => ran(c, h => h.video.motion)), goal(L('The camera moves', 'La càmera es mou', 'La cámara se mueve'), (g, c) => ran(c, h => h.video.camera))],
      },
    ],
  },
  {
    id: 'i2v', name: L('Image to video', 'Imatge a vídeo', 'Imagen a vídeo'), sub: L('Start frame · first and last', 'Frame inicial · primer i últim', 'Frame inicial · primero y último'),
    steps: [
      {
        title: L('Animate a picture', 'Anima una imatge', 'Anima una imagen'),
        task: L('This graph gives a start image to the text-to-video model: run it and read the error. Then use the i2v model and add CLIP Vision.', 'Aquest graf dona una imatge inicial al model de text a vídeo: executa’l i llegeix l’error. Després fes servir el model i2v i afegeix CLIP Vision.', 'Este grafo da una imagen inicial al modelo de texto a vídeo: ejecútalo y lee el error. Luego usa el modelo i2v y añade CLIP Vision.'),
        concept: L('Image to video starts from <b>your picture</b> as the first frame: you control the look, the model adds the motion. <b>WanImageToVideo</b> puts the start image into the conditioning and the latent; it needs an <b>i2v model</b>, trained to read that extra input (36 channels instead of 16, hence the error). With Wan 2.1, a <b>CLIP Vision</b> encoding of the picture helps keep it faithful for the whole clip.', 'Imatge a vídeo comença a partir de <b>la teva imatge</b> com a primer frame: tu controles l’aspecte, el model hi posa el moviment. <b>WanImageToVideo</b> posa la imatge inicial al conditioning i al latent; necessita un <b>model i2v</b>, entrenat per llegir aquesta entrada extra (36 canals en lloc de 16, d’aquí l’error). Amb Wan 2.1, una codificació <b>CLIP Vision</b> de la imatge ajuda a mantenir-la fidel tot el clip.', 'Imagen a vídeo empieza a partir de <b>tu imagen</b> como primer frame: tú controlas el aspecto, el modelo pone el movimiento. <b>WanImageToVideo</b> pone la imagen inicial en el conditioning y en el latente; necesita un <b>modelo i2v</b>, entrenado para leer esa entrada extra (36 canales en lugar de 16, de ahí el error). Con Wan 2.1, una codificación <b>CLIP Vision</b> de la imagen ayuda a mantenerla fiel todo el clip.'),
        how: [L('Run: “expected input to have 16 channels, but got 36”.', 'Executa: “expected input to have 16 channels, but got 36”.', 'Ejecuta: “expected input to have 16 channels, but got 36”.'), L('Load Diffusion Model › <b>wan2.1_i2v_480p_14B</b>.', 'Load Diffusion Model › <b>wan2.1_i2v_480p_14B</b>.', 'Load Diffusion Model › <b>wan2.1_i2v_480p_14B</b>.'), L('<b>Load CLIP Vision</b> (clip_vision_h) → <b>CLIP Vision Encode</b> (image from Load Image) → clip_vision_output of WanImageToVideo. Run.', '<b>Load CLIP Vision</b> (clip_vision_h) → <b>CLIP Vision Encode</b> (image de Load Image) → clip_vision_output de WanImageToVideo. Executa.', '<b>Load CLIP Vision</b> (clip_vision_h) → <b>CLIP Vision Encode</b> (image de Load Image) → clip_vision_output de WanImageToVideo. Ejecuta.')],
        note: L('Make the start image in ComfyUI first (with everything from the other labs) and animate it: that is the usual pipeline.', 'Fes primer la imatge inicial a ComfyUI (amb tot el dels altres labs) i anima-la: és el pipeline habitual.', 'Haz primero la imagen inicial en ComfyUI (con todo lo de los otros labs) y anímala: es el pipeline habitual.'),
        starter: () => G.i2v({ unet: T2V, vision: false }), solution: () => G.i2v(),
        goals: [goal(L('Read the channels error', 'Has llegit l’error de canals', 'Has leído el error de canales'), (g, c) => c.flags.rt_shape), goal(L('The video starts from your picture', 'El vídeo comença a partir de la teva imatge', 'El vídeo empieza a partir de tu imagen'), (g, c) => ran(c, h => h.video.keepsStart)), goal(L('With CLIP Vision: faithful all along', 'Amb CLIP Vision: fidel tota l’estona', 'Con CLIP Vision: fiel todo el rato'), (g, c) => ran(c, h => h.video.keepsStart && h.video.identity >= 1))],
      },
      {
        title: L('First and last frame', 'Primer i últim frame', 'Primer y último frame'),
        task: L('Give the video a start and an end: the cat on the left, then on the right. Use the flf2v model and WanFirstLastFrameToVideo.', 'Dona al vídeo un inici i un final: el gat a l’esquerra, després a la dreta. Fes servir el model flf2v i WanFirstLastFrameToVideo.', 'Da al vídeo un inicio y un final: el gato a la izquierda, luego a la derecha. Usa el modelo flf2v y WanFirstLastFrameToVideo.'),
        concept: L('With only a start image, the model decides where the clip ends. <b>First-last frame</b> models take both ends and fill the motion in between: transitions, transformations, a character crossing the frame exactly as planned. They are also the way to <b>chain clips</b>: the last frame of one clip becomes the first of the next.', 'Amb només una imatge inicial, el model decideix on acaba el clip. Els models de <b>primer i últim frame</b> reben els dos extrems i omplen el moviment del mig: transicions, transformacions, un personatge que travessa el pla exactament com l’has planificat. També són la manera d’<b>encadenar clips</b>: l’últim frame d’un clip és el primer del següent.', 'Con solo una imagen inicial, el modelo decide dónde acaba el clip. Los modelos de <b>primer y último frame</b> reciben los dos extremos y rellenan el movimiento de en medio: transiciones, transformaciones, un personaje que cruza el plano exactamente como lo has planificado. También son la forma de <b>encadenar clips</b>: el último frame de un clip es el primero del siguiente.'),
        how: [L('Load Diffusion Model › <b>wan2.1_flf2v_720p_14B</b>.', 'Load Diffusion Model › <b>wan2.1_flf2v_720p_14B</b>.', 'Load Diffusion Model › <b>wan2.1_flf2v_720p_14B</b>.'), L('Replace WanImageToVideo with <b>WanFirstLastFrameToVideo</b>: start_image = i2v_cat, end_image = i2v_cat_end.', 'Substitueix WanImageToVideo per <b>WanFirstLastFrameToVideo</b>: start_image = i2v_cat, end_image = i2v_cat_end.', 'Sustituye WanImageToVideo por <b>WanFirstLastFrameToVideo</b>: start_image = i2v_cat, end_image = i2v_cat_end.'), L('Run.', 'Executa.', 'Ejecuta.')],
        note: L('Wan 2.2 does first-last frame with its normal image-to-video models.', 'Wan 2.2 fa primer i últim frame amb els seus models normals d’imatge a vídeo.', 'Wan 2.2 hace primer y último frame con sus modelos normales de imagen a vídeo.'),
        starter: () => G.i2v(), solution: G.flf,
        goals: [goal(L('WanFirstLastFrameToVideo with both pictures', 'WanFirstLastFrameToVideo amb les dues imatges', 'WanFirstLastFrameToVideo con las dos imágenes'), g => N(g, 'WanFirstLastFrameToVideo').some(n => from(g, n.id, 'start_image') && from(g, n.id, 'end_image'))), goal(L('A clip that ends where you said', 'Un clip que acaba on has dit', 'Un clip que acaba donde has dicho'), (g, c) => ran(c, h => h.video.reachesEnd))],
      },
    ],
  },
  {
    id: 'limits', name: L('Limits', 'Límits', 'Límites'), sub: L('Memory · length · Wan 2.2', 'Memòria · llargada · Wan 2.2', 'Memoria · duración · Wan 2.2'),
    steps: [
      {
        title: L('Video memory', 'La memòria del vídeo', 'La memoria del vídeo'),
        task: L('1280 × 720 × 121 frames with the 14B model: run it. Then make it fit: 832 × 480 and 81 frames.', '1280 × 720 × 121 frames amb el model de 14B: executa. Després fes-ho cabre: 832 × 480 i 81 frames.', '1280 × 720 × 121 frames con el modelo de 14B: ejecuta. Luego hazlo caber: 832 × 480 y 81 frames.'),
        concept: L('A video latent holds <b>every frame at once</b>: memory grows with width × height × frames. Five seconds of 720p is like sampling eighty pictures together. The levers, in order: lower the resolution (generate at 480p and upscale the video later), fewer frames, a smaller or quantized model (1.3B, 5B, fp8, GGUF). On a 16 GB card, 832 × 480 × 81 with the 14B fp8 model is the comfortable spot.', 'Un latent de vídeo conté <b>tots els frames alhora</b>: la memòria creix amb amplada × alçada × frames. Cinc segons de 720p és com mostrejar vuitanta imatges juntes. Les palanques, per ordre: baixar la resolució (generar a 480p i fer upscale del vídeo després), menys frames, un model més petit o quantitzat (1.3B, 5B, fp8, GGUF). En una targeta de 16 GB, 832 × 480 × 81 amb el model 14B fp8 és el punt còmode.', 'Un latente de vídeo contiene <b>todos los frames a la vez</b>: la memoria crece con ancho × alto × frames. Cinco segundos de 720p es como muestrear ochenta imágenes juntas. Las palancas, por orden: bajar la resolución (generar a 480p y hacer upscale del vídeo después), menos frames, un modelo más pequeño o cuantizado (1.3B, 5B, fp8, GGUF). En una tarjeta de 16 GB, 832 × 480 × 81 con el modelo 14B fp8 es el punto cómodo.'),
        how: [L('Run: torch.OutOfMemoryError.', 'Executa: torch.OutOfMemoryError.', 'Ejecuta: torch.OutOfMemoryError.'), L('EmptyHunyuanLatentVideo › <b>832 × 480</b>, length <b>81</b>.', 'EmptyHunyuanLatentVideo › <b>832 × 480</b>, length <b>81</b>.', 'EmptyHunyuanLatentVideo › <b>832 × 480</b>, length <b>81</b>.'), L('Run.', 'Executa.', 'Ejecuta.')],
        note: L('The 1.3B model at 720p does not crash, but it was trained at 480p: the picture breaks (try it).', 'El model 1.3B a 720p no peta, però es va entrenar a 480p: la imatge es trenca (prova-ho).', 'El modelo 1.3B a 720p no peta, pero se entrenó a 480p: la imagen se rompe (pruébalo).'),
        starter: () => G.t2v({ unet: T2V14, w: 1280, h: 720, len: 121 }), solution: () => G.t2v({ unet: T2V14, len: 81 }),
        goals: [goal(L('Saw the video run out of memory', 'Has vist el vídeo quedar-se sense memòria', 'Has visto el vídeo quedarse sin memoria'), (g, c) => c.flags.rt_oom), goal(L('81 frames with the 14B model', '81 frames amb el model de 14B', '81 frames con el modelo de 14B'), (g, c) => ran(c, h => h.video.frames === 81 && /14B/.test(h.video.model)))],
      },
      {
        title: L('Longer is not better', 'Més llarg no és millor', 'Más largo no es mejor'),
        task: L('Run 129 frames and watch the end of the clip. Then go back to 81.', 'Executa 129 frames i mira el final del clip. Després torna a 81.', 'Ejecuta 129 frames y mira el final del clip. Luego vuelve a 81.'),
        concept: L('The model learned clips of a certain length. Ask for more and the end of the video <b>drifts</b>: the motion loops back, shapes morph, colours shift. For longer videos, <b>chain clips</b>: take the last frame of one clip as the start image (or first frame) of the next, and keep the prompt consistent.', 'El model va aprendre clips d’una certa llargada. Si en demanes més, el final del vídeo <b>es desvia</b>: el moviment torna enrere, les formes es deformen, els colors canvien. Per a vídeos més llargs, <b>encadena clips</b>: agafa l’últim frame d’un clip com a imatge inicial (o primer frame) del següent, i mantén el prompt coherent.', 'El modelo aprendió clips de una cierta longitud. Si pides más, el final del vídeo <b>se desvía</b>: el movimiento vuelve atrás, las formas se deforman, los colores cambian. Para vídeos más largos, <b>encadena clips</b>: toma el último frame de un clip como imagen inicial (o primer frame) del siguiente, y mantén el prompt coherente.'),
        how: [L('length <b>129</b>. Run and open it: look at the last second.', 'length <b>129</b>. Executa i obre’l: mira l’últim segon.', 'length <b>129</b>. Ejecuta y ábrelo: mira el último segundo.'), L('Back to <b>81</b>.', 'Torna a <b>81</b>.', 'Vuelve a <b>81</b>.')],
        note: L('Some custom node packs offer “context windows” to make long videos in overlapping chunks.', 'Alguns paquets de custom nodes ofereixen “context windows” per fer vídeos llargs a trossos que se solapen.', 'Algunos paquetes de custom nodes ofrecen “context windows” para hacer vídeos largos en trozos que se solapan.'),
        starter: () => G.t2v({ len: 129 }), solution: () => G.t2v({ len: 81 }),
        goals: [goal(L('Saw a long clip drift', 'Has vist desviar-se un clip llarg', 'Has visto desviarse un clip largo'), (g, c) => ran(c, h => h.video.drift)), goal(L('Back to a clean 81-frame clip', 'Tornes a un clip net de 81 frames', 'Vuelves a un clip limpio de 81 frames'), (g, c) => ran(c, h => h.video.frames <= 81 && h.video.frames > 1 && !h.video.drift && !h.video.flicker))],
      },
      {
        title: L('Wan 2.2: two experts', 'Wan 2.2: dos experts', 'Wan 2.2: dos expertos'),
        task: L('Wan 2.2 uses a high-noise model for the first steps and a low-noise model for the last. This graph has them in the wrong order: fix it.', 'Wan 2.2 fa servir un model d’alt soroll per als primers steps i un de baix soroll per als últims. Aquest graf els té a l’inrevés: arregla-ho.', 'Wan 2.2 usa un modelo de alto ruido para los primeros steps y uno de bajo ruido para los últimos. Este grafo los tiene al revés: arréglalo.'),
        concept: L('Wan 2.2 14B is two models: the <b>high-noise expert</b> decides layout and motion in the noisy first half of the steps, the <b>low-noise expert</b> adds the detail in the second half. It is the two-sampler hand-over of the Sampling Lab: two KSampler (Advanced), the first with leftover noise up to step 10 of 20, the second without adding noise from step 10. Swap them and the low-noise model has to invent the motion: soft, unstable results.', 'Wan 2.2 14B són dos models: l’<b>expert d’alt soroll</b> decideix la composició i el moviment a la primera meitat dels steps, amb molt soroll, i l’<b>expert de baix soroll</b> hi posa el detall a la segona meitat. És el relleu de dos samplers del Sampling Lab: dos KSampler (Advanced), el primer amb soroll sobrant fins al step 10 de 20, el segon sense afegir soroll des del step 10. Si els intercanvies, el model de baix soroll s’ha d’inventar el moviment: resultats tous i inestables.', 'Wan 2.2 14B son dos modelos: el <b>experto de alto ruido</b> decide la composición y el movimiento en la primera mitad de los steps, con mucho ruido, y el <b>experto de bajo ruido</b> pone el detalle en la segunda mitad. Es el relevo de dos samplers del Sampling Lab: dos KSampler (Advanced), el primero con ruido sobrante hasta el step 10 de 20, el segundo sin añadir ruido desde el step 10. Si los intercambias, el modelo de bajo ruido tiene que inventarse el movimiento: resultados blandos e inestables.'),
        how: [L('Run as it is.', 'Executa tal com està.', 'Ejecuta tal cual.'), L('First Load Diffusion Model › <b>high_noise</b>; second › <b>low_noise</b>.', 'Primer Load Diffusion Model › <b>high_noise</b>; segon › <b>low_noise</b>.', 'Primer Load Diffusion Model › <b>high_noise</b>; segundo › <b>low_noise</b>.'), L('Run.', 'Executa.', 'Ejecuta.')],
        note: L('Wan 2.2 also has a 5B model (text and image to video, 24 fps) that runs in one pass on smaller cards.', 'Wan 2.2 també té un model de 5B (text i imatge a vídeo, 24 fps) que funciona en una sola passada en targetes més petites.', 'Wan 2.2 también tiene un modelo de 5B (texto e imagen a vídeo, 24 fps) que funciona en una sola pasada en tarjetas más pequeñas.'),
        starter: () => G.wan22(LOW, HIGH), solution: () => G.wan22(),
        goals: [goal(L('Saw the experts swapped', 'Has vist els experts intercanviats', 'Has visto los expertos intercambiados'), (g, c) => ran(c, h => h.video.experts === 'reversed')), goal(L('High noise first, low noise second', 'Primer alt soroll, després baix soroll', 'Primero alto ruido, luego bajo ruido'), (g, c) => ran(c, h => h.video.experts === 'ok' && !h.video.flicker))],
      },
    ],
  },
  {
    id: '3d', name: L('Image to 3D', 'Imatge a 3D', 'Imagen a 3D'), sub: L('Mesh · clean input · resolution', 'Malla · entrada neta · resolució', 'Malla · entrada limpia · resolución'),
    steps: [
      {
        title: L('From a picture to a mesh', 'D’una imatge a una malla', 'De una imagen a una malla'),
        task: L('Build the image-to-3D graph: checkpoint, CLIP Vision Encode of the photo, Hunyuan3Dv2Conditioning, EmptyLatentHunyuan3Dv2, KSampler, VAEDecodeHunyuan3D, VoxelToMesh and Save 3D Model.', 'Construeix el graf d’imatge a 3D: checkpoint, CLIP Vision Encode de la foto, Hunyuan3Dv2Conditioning, EmptyLatentHunyuan3Dv2, KSampler, VAEDecodeHunyuan3D, VoxelToMesh i Save 3D Model.', 'Construye el grafo de imagen a 3D: checkpoint, CLIP Vision Encode de la foto, Hunyuan3Dv2Conditioning, EmptyLatentHunyuan3Dv2, KSampler, VAEDecodeHunyuan3D, VoxelToMesh y Save 3D Model.'),
        concept: L('Image-to-3D models generate a <b>shape</b> the same way image models generate pictures: a latent, denoised by a KSampler, guided by a conditioning (here, the picture encoded with CLIP Vision). The VAE decodes it into a <b>voxel</b> grid (which cells are inside the object), and <b>VoxelToMesh</b> turns that into triangles you can save as GLB. The front is reliable; the back is the model’s best guess.', 'Els models d’imatge a 3D generen una <b>forma</b> igual que els models d’imatge generen imatges: un latent, al qual un KSampler treu el soroll, guiat per un conditioning (aquí, la imatge codificada amb CLIP Vision). El VAE el descodifica en una graella de <b>vòxels</b> (quines cel·les són dins l’objecte), i <b>VoxelToMesh</b> la converteix en triangles que pots desar com a GLB. La part de davant és fiable; la de darrere és la millor suposició del model.', 'Los modelos de imagen a 3D generan una <b>forma</b> igual que los modelos de imagen generan imágenes: un latente, al que un KSampler quita el ruido, guiado por un conditioning (aquí, la imagen codificada con CLIP Vision). El VAE lo decodifica en una rejilla de <b>vóxeles</b> (qué celdas están dentro del objeto), y <b>VoxelToMesh</b> la convierte en triángulos que puedes guardar como GLB. La parte de delante es fiable; la de detrás es la mejor suposición del modelo.'),
        how: [L('<b>Image Only Checkpoint Loader</b> (hunyuan3d-dit-v2). Its CLIP_VISION + the photo → <b>CLIP Vision Encode</b> → <b>Hunyuan3Dv2Conditioning</b>.', '<b>Image Only Checkpoint Loader</b> (hunyuan3d-dit-v2). El seu CLIP_VISION + la foto → <b>CLIP Vision Encode</b> → <b>Hunyuan3Dv2Conditioning</b>.', '<b>Image Only Checkpoint Loader</b> (hunyuan3d-dit-v2). Su CLIP_VISION + la foto → <b>CLIP Vision Encode</b> → <b>Hunyuan3Dv2Conditioning</b>.'), L('<b>KSampler</b> (model, positive, negative, <b>EmptyLatentHunyuan3Dv2</b>) → <b>VAEDecodeHunyuan3D</b> (vae from the loader) → <b>VoxelToMesh</b> → <b>Save 3D Model</b>.', '<b>KSampler</b> (model, positive, negative, <b>EmptyLatentHunyuan3Dv2</b>) → <b>VAEDecodeHunyuan3D</b> (vae del loader) → <b>VoxelToMesh</b> → <b>Save 3D Model</b>.', '<b>KSampler</b> (model, positive, negative, <b>EmptyLatentHunyuan3Dv2</b>) → <b>VAEDecodeHunyuan3D</b> (vae del loader) → <b>VoxelToMesh</b> → <b>Save 3D Model</b>.'), L('Run, and open the result: it turns.', 'Executa, i obre el resultat: gira.', 'Ejecuta, y abre el resultado: gira.')],
        note: L('Texturing the mesh is a separate step (custom node packs or a 3D program). Expect to clean the topology in Blender.', 'Texturitzar la malla és un pas a part (paquets de custom nodes o un programa 3D). Compta a netejar la topologia a Blender.', 'Texturizar la malla es un paso aparte (paquetes de custom nodes o un programa 3D). Cuenta con limpiar la topología en Blender.'),
        starter: G.h3dStart, solution: () => G.h3d(),
        goals: [goal(L('Save 3D Model gets a mesh from VoxelToMesh', 'Save 3D Model rep una malla de VoxelToMesh', 'Save 3D Model recibe una malla de VoxelToMesh'), g => N(g, 'SaveGLB').some(n => from(g, n.id, 'mesh')?.type === 'VoxelToMesh')), goal(L('A mesh saved', 'Una malla desada', 'Una malla guardada'), (g, c) => meshes(c).some(h => h.mesh.ok))],
      },
      {
        title: L('Clean input, right resolution', 'Entrada neta, resolució bona', 'Entrada limpia, resolución buena'),
        task: L('This photo has a room behind the toy and a low octree resolution. Remove the background, set octree_resolution to 256 or more and keep threshold between 0.5 and 0.7.', 'Aquesta foto té una habitació darrere la joguina i una octree resolution baixa. Treu el fons, posa octree_resolution a 256 o més i mantén threshold entre 0.5 i 0.7.', 'Esta foto tiene una habitación detrás del juguete y una octree resolution baja. Quita el fondo, pon octree_resolution a 256 o más y mantén threshold entre 0.5 y 0.7.'),
        concept: L('The model builds <b>everything it sees</b>: a background becomes a slab glued to the object. Start from a clean picture: the object alone, on white or transparent, well lit, from a slightly raised three-quarter view. <b>octree_resolution</b> is the voxel detail: 64 is blocky, 256 is the usual, 384–512 for small details. <b>threshold</b> places the surface: too low and the object swells and blurs, too high and it gets holes.', 'El model construeix <b>tot el que veu</b>: un fons es converteix en una placa enganxada a l’objecte. Comença amb una imatge neta: l’objecte sol, sobre blanc o transparent, ben il·luminat, amb una vista de tres quarts una mica elevada. <b>octree_resolution</b> és el detall dels vòxels: 64 fa blocs, 256 és l’habitual, 384–512 per a detalls petits. <b>threshold</b> situa la superfície: massa baix i l’objecte s’infla i es desdibuixa, massa alt i té forats.', 'El modelo construye <b>todo lo que ve</b>: un fondo se convierte en una placa pegada al objeto. Empieza con una imagen limpia: el objeto solo, sobre blanco o transparente, bien iluminado, con una vista de tres cuartos un poco elevada. <b>octree_resolution</b> es el detalle de los vóxeles: 64 hace bloques, 256 es lo habitual, 384–512 para detalles pequeños. <b>threshold</b> sitúa la superficie: demasiado bajo y el objeto se hincha y se desdibuja, demasiado alto y tiene agujeros.'),
        how: [L('Run: a slab and blocks.', 'Executa: una placa i blocs.', 'Ejecuta: una placa y bloques.'), L('Add <b>Image Remove Background (rembg)</b> between Load Image and CLIP Vision Encode.', 'Afegeix <b>Image Remove Background (rembg)</b> entre Load Image i CLIP Vision Encode.', 'Añade <b>Image Remove Background (rembg)</b> entre Load Image y CLIP Vision Encode.'), L('VAEDecodeHunyuan3D › octree_resolution <b>256</b>. Run.', 'VAEDecodeHunyuan3D › octree_resolution <b>256</b>. Executa.', 'VAEDecodeHunyuan3D › octree_resolution <b>256</b>. Ejecuta.')],
        note: L('For a better back, use the multi-view model with Hunyuan3Dv2ConditioningMultiView and pictures from the front, side and back.', 'Per a una part de darrere millor, fes servir el model multivista amb Hunyuan3Dv2ConditioningMultiView i imatges de davant, del costat i de darrere.', 'Para una parte de detrás mejor, usa el modelo multivista con Hunyuan3Dv2ConditioningMultiView e imágenes de delante, del lado y de detrás.'),
        starter: () => G.h3d({ image: 'toy_robot_room.png', octree: 64 }), solution: () => G.h3d({ image: 'toy_robot_room.png', rembg: true }),
        goals: [goal(L('Saw the background become a slab', 'Has vist el fons convertit en una placa', 'Has visto el fondo convertido en una placa'), (g, c) => meshes(c).some(h => h.mesh.slab)), goal(L('Background removed', 'Fons tret', 'Fondo quitado'), (g, c) => meshes(c).some(h => h.mesh.cut && !h.mesh.slab)), goal(L('A clean mesh: 256+, threshold 0.5–0.7', 'Una malla neta: 256+, threshold 0.5–0.7', 'Una malla limpia: 256+, threshold 0.5–0.7'), (g, c) => meshes(c).some(h => h.mesh.ok && !h.mesh.slab && h.mesh.octree >= 256 && h.mesh.threshold >= .5 && h.mesh.threshold <= .7 && !h.mesh.blocky && !h.mesh.holes && !h.mesh.bloated))],
      },
    ],
  },
];

export const TEMPLATES = [
  { id: 't2v', name: L('Wan 2.1 text to video', 'Wan 2.1 text a vídeo', 'Wan 2.1 texto a vídeo'), make: () => G.t2v({ len: 81 }) },
  { id: 'i2v', name: L('Wan 2.1 image to video', 'Wan 2.1 imatge a vídeo', 'Wan 2.1 imagen a vídeo'), make: () => G.i2v() },
  { id: 'flf', name: L('Wan first-last frame', 'Wan primer i últim frame', 'Wan primer y último frame'), make: G.flf },
  { id: 'wan22', name: L('Wan 2.2 (two experts)', 'Wan 2.2 (dos experts)', 'Wan 2.2 (dos expertos)'), make: () => G.wan22() },
  { id: 'h3d', name: L('Image to 3D', 'Imatge a 3D', 'Imagen a 3D'), make: () => G.h3d({ rembg: true }) },
];
export { G as GRAPHS };
